### ISSUE TITLE
оновлення даних в ukr_med_registries

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1015]
Необхідно оновити таблицю з закладами по автоверифікації
Лінк приватно кидаю на @warehousman  і @lymychp

**Comment by AlekzandrV** [comment]
Є декілька питань
1) Багато дублів з різнми назвами - схоже на те, що це відділення (Divisions). Хочу в Укр Мед реєстрі ми очікуємо Юр. особи (Legal_Entities)
Приеріть будь-ласка дублікати

EDRPOU | COUNT
-------| -----
11111111 | 1376
******** | 15
******** | 13
******** | 11
******** | 10
******** | 10
******** | 6
******** | 5
******** | 4
******** | 4
******** | 3
******** | 3
******** | 3
******** | 3
******** | 3
******** | 3
******** | 3
******** | 3
******** | 3
******** | 2
******** | 2
******** | 2
******** | 2
******** | 2
******** | 2
******** | 2
******** | 2
00000000 | 2
******** | 2

2) Є окрема секція у файлі РЕСП. Що це і навіщо вона там?

**Comment by kmakarenko** [comment]
[ЛПЗ+РЕСП_14092017.xlsx](https://github.com/edenlabllc/ehealth.api/files/1306287/_14092017.xlsx)

**Comment by IrynaShevch** [comment]
залили сюда https://docs.google.com/spreadsheets/d/1OLmxkwu1ufdkrRh6rxAj5xL7lj4oQ4t_C8EQw2fK22Q/edit#gid=221637580

убрали такие дубликаты от С. Верного:
01993575        15
01993581        13
01993546        11
33271905        10
01993405        10
01994132        6
01993374        5
01993658        4
26191575        4
01993440        3
36338715        3
20765006        3
01998226        3
01993457        3
33578224        3
22398210        3
01997297        3
01993368        3
25064231        2
02004829        2
01998803        2
02010801        2
40170117        2
01993351        2
01993612        2
37467665        2
01996326        2

**Comment by AlekzandrV** [comment]
Реєстр залито на всі середовища
