### ISSUE TITLE
Rename ehealth to Архімед

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1034]
Нове ім'я системи: Електронна система охорони здоров'я Архімед
Скорочено - система Архімед
Англійською: Arhimed eHealth System
Домен, на якому буде портал - arhimed.org.ua

Як і домовлялись, надсилаємо вам оновлені тексти листів, смс та посилання на лого з [коментарями](https://docs.google.com/document/d/1lA0-dyDy784u3Bwf56i7pNqhtJW-BpWeChbXv5fwDo4/edit#) до наявних скринів:

**Comment by lymychp** [comment]
@kmakarenko FYI

**Comment by kmakarenko** [comment]
please stop all tasks related to renaming to eHealth
