### ISSUE TITLE
NHS portal final fixes

### ISSUE THREAD

**Issue by SmartBBC** [edenlabllc/ehealth.api#1042]
Обрати МІС
- [x] меняем вид страницы
по примеру сайта eHealth
https://www.ehealth-ukraine.org/reyestraciya

- [x] лого МИС - ccылка на страницу МИСа

Header
- [x] ссылка на соц сети в header
twitter facebook
- [x] Національна електронна система охорони здоров’я

Мапа:
- [x] убрать аптеки
- [x] уменьшить футер на 30 px
- [x] заменить "Клініки" на "Заклади охорони здоров’я"

Документи:
- [x] перенести с сайта ehealth
https://www.ehealth-ukraine.org/pro-ehealth/dokumenti
_______________

Пояснення:
- [x] убрать аптеки

Контакты
- [x] убрать телефон/адрес

Зворотній зв’язок
 добавить поля:
- [x] тема
- [x] email

**Comment by lymychp** [comment]
rename label `лікаря` на `декларацій`
<img width="514" alt="screen shot 2017-09-14 at 2 02 57 pm" src="https://user-images.githubusercontent.com/5257001/30426647-75c0b262-9955-11e7-9f3a-69290ece305e.png">

**Comment by ivchenkodima** [comment]
done
