### ISSUE TITLE
WS: Get Medication Dispenses

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1045]
Create WS `Get Medication Dispenses` according to [spec](http://docs.uaehealthapi.apiary.io/#reference/public.-reimbursement/medication-dispense/get-medication-dispenses-list) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/27852963/Get+Medication+Dispenses)

- [x] Create WS spec
- [x] Create WS logic
- [x] Implement
- [x] Deploy
- [x] Create test scenarios

**Comment by danakonovalenko** [comment]
@AlexKovalevych  add field "dispensed_at" to filter
