### ISSUE TITLE
EP: Get List INNMs

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1054]
Get List INNMs WS

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/27754627/Get+INNM+List)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by svetavedmed** [comment]
tests are done in Postman "eHealth Reimbursement Medications"
