### ISSUE TITLE
EP: Get Medication by ID

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1055]
Get Medication by ID WS

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/x/iYCoAQ)
- [x]  Implement
- [x]  Deploy
- [ ]  Improve test scenarios

**Comment by danakonovalenko** [comment]
The medications with status is_active=false also must be shown. Currently for response it is received 404 error.

**Comment by PavelVesnin** [comment]
@danakonovalenko fixed
