### ISSUE TITLE
Update NHS Admin portal

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#1058]
- [x] remove Nebo15 logo
- [x] fix documentation link
- [x] Employees Tax ID don't shown
- [x] handle legal_entities without mandatory/optional fields in respose. For example, edrpou= 40888750, `medical_service_provider.licenses.order_no` is missing. 
- [x] add units to global configuration

**Comment by lymychp** [comment]
[proper documentation link](http://docs.uaehealthapi.apiary.io/#)
