### ISSUE TITLE
NHS Portal PO feedback

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1064]
На вихідних Іра подивилась, надсилаю перелік необхідних правок:

# КРОКИ
- [x]  ЛІкар первинки
Крок 5: додати «,» після слова «повідомленні»- Вказати код, що пацієнт отримав у СМС-повідомленні,

- [x] Пацієнт 
Крок 3: підказка не вміщається, можемо її якось прописати у 2 рядки

- [x] Працівник реєстратури:
Крок 4: прописати у формулювання, як у решти ролей: «Вказати код, що пацієнт отримав у СМС-повідомленні, або прикріпити фото/скан копії його документів пацієнта»

- [x]  ВИБІР МІС
Треба сьогодні для кожної МІС «Функції в системі eHealth»

- [x] Два тексти мають назву «Чому система має відкритий код?» - Ось за цим посиланням має бути назва Процедура підключення МІС  до системи eHealth http://portal.demo.ehealth.world/clarifications/2017-09-15-open/
- [x] ДОКУМЕНТИ 
Перейменувати Регламент функціонування пілотного проекту електронної системи охорони здоров’я  - на Регламент функціонування системи у тестовому режимі
- [x] Не в усіх текстах є Назва+Початок тексту, часто написана тільки Назва (http://portal.demo.ehealth.world/clarifications.html) или ...
 
- [x] title: Як розробникам підключитись до системи eHealth? *нумерация*
Як розробникам підключитись до системи eHealth?  - наприкінці продовжується нумерація в Етапі 3 - потрібно, щоб почалась наново 1. Ознайомитись з Регламентом 2. Подати заявку

- [x] документи поки що не працюють. target _blank, blue color

- [x] ЗВОРОТНІЙ ЗВ’ЯЗОК
зараз в тему листа підтягується «Зворотній зв’язок від..», а не тема повідомлення «запит від ЗМІ»/«консультування лікарів»/«організаційні питання»
- [x] title: Процедура підключення МІС  до системи eHealth *нумерация*

- [x] ПОЯСНЕННЯ 
В мене чомусь не переключається фільтр між «Всім-Розробникам-Заклдам- і тД»
Safari
 

- [ ] Интеграция (http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/)

**Comment by IrynaShevch** [comment]
Привіт, маю останні правки від Юри і мене: 

КРОКИ
Працівник реєстратури
Пункт 5
**Є:** За потреби **поздрукувати** заповнену Декларацію у двох примірниках: один – пацієнту, один – лікарю.
**Треба:** За потреби роздрукувати заповнену Декларацію у двох примірниках: один – пацієнту, один – лікарю.

ПОЯСНЕННЯ
1. **Назва:** Як закладу підключити своїх працівників до системи eHealth?
**Є:** Перелік медичних інформаційних систем, які вже приєдналися до системи eHealth наведений на сайті системи.
**Треба:** Перелік медичних інформаційних систем, які вже приєдналися до системи eHealth, наведений на сайті системи.

2. **Назва:** Чому система має відкритий код?
**Замінити назву:** Чому не створюється єдиний державний інтерфейс?

СТАТИСТИКА
**замінити:**
М.київ - м. Київ
М.севастополь - м. Севастополь
Автономна республіка крим - Автономна Республіка Крим


ПРО НАС
https://portal.ehealth-ukraine.org/about.html
Назва тексту: Що таке система eHealth?
1. **Є:** Центральний компонент буде контролювати Національна служба здоров’я України, яка створюється при Міністерстві охорони здоров’я. Вона вимагатиме від розробників МІС строго дотримуватися вимог до надійності, безпеки та конфіденційності даних, якими їхні системи обмінюватимуться з центральним компонентом. Система також пройде сертифікацію Державної служби спеціального зв'язку та захисту інформації України.
**Треба:** Центральний компонент буде контролювати держава. За експлуатацію системи eHealth буде відповідати створене з цією метою державне підприємство. Разом вони вимагатимуть від розробників МІС строго дотримуватися вимог до надійності, безпеки та конфіденційності даних, якими їхні системи обмінюватимуться з центральним компонентом. Система також пройде сертифікацію Державної служби спеціального зв'язку та захисту інформації України.

**Є:** В Україні система складатиметься з центрального компонента – він відповідатиме за централізоване зберігання та обробку інформації – та медичних інформаційних систем (МІС), які лікарні та поліклініки можуть обирати на ринку і встановлювати в себе.
**Треба:** В Україні система складатиметься з центрального компонента – він відповідатиме за централізоване зберігання та обробку інформації – та медичних інформаційних систем (МІС), які лікарні та поліклініки можуть обирати на ринку і встановлювати в себе.

**Є (останнє речення у тексті):** За експлуатацію e системи eHealth буде відповідати створене з цією метою державне підприємство.
**Треба:** _прибрати це речення наприкінці тексту_

2. З їх допомогою було створено систему eHealth:
  -  Логотип Canada поставити між EDGE та USAID
  -  Логотип Lifecell - поставити наприкінці окремо з надписом “Всі СМС у системі відправлено з допомогою: _(лого Lifecell)_”

**Comment by IrynaShevch** [comment]
ОБРАТИ МЕДИЧНУ ІНФОРМАЦІЙНУ СИСТЕМУ 
http://portal.demo.ehealth.world/providers.html

1. У профілі MEDSTAR прибрати відео взагалі.
2. У профілі MEDICS у розділі **Про МІС** замінити у тексті "Поліклініка без черг" на "MEDICS"

**Comment by IrynaShevch** [comment]
@ivchenkodima  если интеграция с мейлчимпом не выходит, все ок, просто убираем про рассылку
