### ISSUE TITLE
Review and create db indexes

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#1089]
Since we launched prod, need to review and create missed db indexes to avoid slow queries (e.g.: reports)

**Comment by lymychp** [comment]
- [ ] add unique indexes only first

**Comment by AlexKovalevych** [comment]
### Mithril
1. client_types:
- name
2. roles:
- name

### Il
1. declaration_requests
- declaration_id is not null

### Mpi
1. persons:
- first_name, last_name, second_name, tax_id, birth_date

### Ops
1. declarations
- person_id, status = 'active'
- declaration_request_id
2. medication_dispenses
- medication_request_id, status = 'PROCESSED'
3. medication_requests
- request_number
- medication_request_requests_id

### Prm

1. black_list_users
- tax_id, is_active = true
2. employees
- legal_entity_id, is_active = true, employee_type = 'OWNER'
3. global_parameters
- parameter
4. innms
- sctid, is_active = true
5. parties
- first_name, last_name, second_name, tax_id, birth_date
- drop index by tax_id, birth_date

### Uaddresses
1. districts
- name, region_id
2. settlements
- district_id, region_id, name
3. streets
- settlement_id, name, type

### Verification
1. verifications
- phone_number, active = true

**Comment by AlekzandrV** [comment]
1. Remove the following UNIQUE indexes:

> ## Uaddresses
> 2. settlements
> * district_id, region_id, name
> 3. streets
> * settlement_id, name, type

There are duplicated settlements in one district

2. Do not replace parties_tax_id_birth_date_index - it makes no sense

**Comment by lymychp** [comment]
> 4. innms
sctid not null, is_active = true

how about name?

**Comment by AlekzandrV** [comment]
> > 4. innms
> sctid not null, is_active = true
> 
> how about name?

Our implementation allows us to create two records with the same name
