### ISSUE TITLE
Support request - Оновити опис lifecell на порталі

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1112]
На порталі необхідно змінити фразу про lifecell на сторінці https://portal.ehealth-ukraine.org/about.html

Поточний напис:

Всі смс у системі відправлено з допомогою «лайфселл»  <logo>

Очікуваний надпис

Технологічний партнер  - ТОВ «лайфселл» <logo>

P.S. Будь ласка, для оперативності повідомте мене в слак або у мейлі про оновлення, коли воно буде зроблено, щоб я могла комунікувати це з партнером.

**Comment by lymychp** [comment]
deployed to prod
