### ISSUE TITLE
Response codes - 500 on prod

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1121]
# env - prod

```sql
select * from requests r where r.status_code = '500'
and r.inserted_at >= current_date - interval '5 day'
order by inserted_at desc;
```
To investigate the reasons of 500
- [x] {"id": "93b3fce5-c697-40ea-bf1a-ba980b210059", "name": "Declaration requests"
- [x] {"id": "ef37e661-d528-4e39-83bb-22057478c8e9", "name": "Get employee request by ID"
- [x] {"id": "07cb9a23-919e-4726-a362-42d1ce9a1d15", "name": "Employees",
- [x] {"id": "5d6d9b0a-7a0a-4927-8601-07ac12e92fcf", "name": "Legal entities"
- [x] {"id": "c7a0c9bd-7511-4f54-a544-30801dff4469", "name": "Divisions"

**Comment by Troush** [comment]
```93b3fce5-c697-40ea-bf1a-ba980b210059```
Investigated. Ticket #1169 

All other one looks like 500 during pod restarts. Can't reproduce them.
