### ISSUE TITLE
Adjust behavior when user without roles is trying to login

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1129]
## preconditions
existing user that has no roles - `pavel.zhuk@gmail.com`

## reprosteps
enter login/pass

## actual result
UI is freezed, nothing happen

## expected result

show proper error message that access is restricted for this user

**Comment by ivchenkodima** [comment]
@lymychp I need user email and password  for specifying the api response for this case. And than I add new error message.
