### ISSUE TITLE
Support request - [All pages] Change the page title name to correct

### ISSUE THREAD

**Issue by NicuPhX** [edenlabllc/ehealth.api#1146]
**Summary:** [All pages] Title of the site is not correct
**Issue type:** Bug
**Severity:** Trivial
**Assignee:** @kmakarenko 
**Reporter:** A.Khilko
**Environment:** Google Chrome Версія 61.0.3163.100 (Розробка) (32-розрядна версія)

**Description:**
**Steps to reproduce:**
1. Open page http://portal.demo.ehealth.world/
2. Observe the site title
**Actual result:**
Національна служба здоров'я
**Expected result:**
Офіційний сайт електронної системи охорони здоров'я E-Health
**Attachment:**
![bug9](https://user-images.githubusercontent.com/24367361/30940184-d252decc-a3e8-11e7-8d72-55bb14f83f1b.png)

**Comment by kmakarenko** [comment]
Please change expected result to "Офіційний сайт електронної системи охорони здоров’я eHealth"

**Comment by NicuPhX** [comment]
Verified
