### ISSUE TITLE
wrong db migration for il.declaration_requests field :printout_content

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1148]
:printout_content is string here
https://github.com/edenlabllc/ehealth.api/blob/d97cfb005add289b0822fb9304a68648124418f8/lib/ehealth/declaration_request/schema.ex#L35

but jsonb in migration here:
https://github.com/edenlabllc/ehealth.api/blob/2266142985fab231e8298c212bfab281527b5321/priv/repo/migrations/20170613133040_add_columns_to_declaration_request.exs

**Comment by ybod** [comment]
Fixed in https://github.com/edenlabllc/ehealth.api/pull/1363

**Comment by AlekzandrV** [comment]
Tested
