### ISSUE TITLE
Receive 403 while getting legal entity by ID

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1151]
Log in as Pharmacy_owner

## GET
{{host}}/api/legal_entities/af04b24a-6d45-44fe-a55e-b67f2e38796b

in prm.legal_entities

id|name|type|edrpou
--|--|--|--|
af04b24a-6d45-44fe-a55e-b67f2e38796b | Аптека №13 | PHARMACY | 38782323

expect 201

receive:
### Responce
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/legal_entities/af04b24a-6d45-44fe-a55e-b67f2e38796b",
        "type": "object",
        "request_id": "qt4cf8pb2msajf8rfbtp2j7uej5bgdv5",
        "code": 403
    },
    "error": {
        "type": "forbidden"
    }
}
```

**Comment by AlexKovalevych** [comment]
Need to add `PHARMACY` to environment variable `TOKENS_TYPES_PERSONAL`
