### ISSUE TITLE
db migration for a single OWNER constraint

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1152]
Apparently, there are multiple options allowed in prod PRM. 
Since there would be a single owner constraint in latest releases -we have to have a db migration disabling previous OWNERs

**Comment by lymychp** [comment]
updated on prod. Below select returns no records:
```
select e.legal_entity_id, count(1) from employees e
  where e.employee_type = 'OWNER'
  and e.is_active = TRUE
group by e.legal_entity_id
having count(1) >1;
```
