### ISSUE TITLE
All the existing ACSK activation 

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1191]
As a NHS admin
I want all the ACSK to be registered in the eHealth
So that any certificate holder can work with eHealth

**Comment by pzhuk** [comment]
list of entities to be activated
https://czo.gov.ua/ca-registry

BR, Pavel V. Zhuk


2017-10-04 11:06 GMT+03:00 lymychp <notifications@github.com>:

**Comment by pzhuk** [comment]
status?

**Comment by svetavedmed** [comment]
10 entities were not activatited, as we do not have all tree types of sertificates - root, tsp, ocsp. If you provide as all certificates, we will import them as well.

Here is a list of not imported sertificates:
- [Акредитований центр сертифікації ключів Державної казначейської служби України](https://czo.gov.ua/ca-registry-details?type=0&id=100)
- [Акредитований центр сертифікації ключів державного підприємства "Головний інформаційно-обчислювальний центр Державної адміністрації залізничного транспорту України"](https://czo.gov.ua/ca-registry-details?type=0&id=89)
- [Акредитований центр сертифікації ключів Державного підприємства "Український інститут інтелектуальної власності"](https://czo.gov.ua/ca-registry-details?type=0&id=115)
- [Засвідчувальний центр Національного банку України](https://czo.gov.ua/ca-registry-details?type=0&id=82)
- [Акредитований центр сертифікації ключів ПрАТ "Науково-дослідний інститут прикладних інформаційних технологій"](https://czo.gov.ua/ca-registry-details?type=0&id=87)
- [Акредитований центр сертифікації ключів АТ "Ощадбанк"](https://czo.gov.ua/ca-registry-details?type=0&id=123)
- [Акредитований центр сертифікації ключів публічного акціонерного товариства "Національний депозитарій України"](https://czo.gov.ua/ca-registry-details?type=0&id=86)
- [Акредитований центр сертифікації ключів ТОВ "Інтер-Метл"](https://czo.gov.ua/ca-registry-details?type=0&id=92)
- [Акредитований центр сертифікації ключів товариства з обмеженою відповідальністю "Універсальний дата центр"](https://czo.gov.ua/ca-registry-details?type=0&id=90)
- [Акредитований центр сертифікації ключів "UPG PKI" товариства з обмеженою відповідальністю "Юкрейн Проперті Групп"](https://czo.gov.ua/ca-registry-details?type=0&id=94)

and list of imported:
- Акредитований центр сертифікації ключів Державної прикордонної служби України
- Акредитований центр сертифікації ключів Збройних Сил
- Акредитований центр сертифікації ключів ринку електричної енергії
- Акредитований центр сертифікації ключів державного підприємства "Українські спеціальні системи"
- Акредитований центр сертифікації ключів Міністерства внутрішніх справ України
- Акредитований центр сертифікації ключів Національного банку України
- Акредитований центр сертифікації ключів ПУБЛІЧНОГО АКЦІОНЕРНОГО ТОВАРИСТВА КОМЕРЦІЙНИЙ БАНК "ПРИВАТБАНК"
- Акредитований центр сертифікації ключів публічного акціонерного товариства "УкрСиббанк"
- Акредитований центр сертифікації ключів "eSign" ТОВ "Алтерсайн"
- Акредитований центр сертифікації ключів "Masterkey" ТОВ "Арт-мастер"
- Акредитований центр сертифікації ключів товариства з обмеженою відповідальністю "КЛЮЧОВІ СИСТЕМИ"
- Акредитований центр сертифікації ключів товариства з обмеженою відповідальністю "Центр сертифікації ключів "Україна"
- Акредитований центр сертифікації ключів органів юстиції України
- Акредитований центр сертифікації ключів Інформаційно-довідкового департаменту ДФС

**Comment by pzhuk** [comment]
Щойно потестував  "КЛЮЧОВІ СИСТЕМИ" на dev- працює :) Дякую

По тим, де сертифікатів невистачає - спробую звернутись напряму.
Прошу додати в найближчий реліз, всі, які вже було імпортовано на сьогодні

Дякую
