### ISSUE TITLE
provide endpoint which will return role-scopes model

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1205]
We have to have an endpoint which returns role scopes model from mithril.
I suspect it should be just a GET method, however, list of roles returned for this endpoint should be configurable. Also, access to this endpoint should be provided to MIS user only

**Comment by AlekzandrV** [comment]
Done on Dev and Demo

Scopes model document updated
Apiary specification updated

Added proper scope to all valid mis users (tokens)
