### ISSUE TITLE
parties replica 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1212]
As for now it's not clear whether it's allowed to replicate "parties" 
    - fist_name
    - last_name 
    - second_name
It was replicated on dev as those field is used for Reimbursement Report, but can't be replicated to demo etc. Before this it must be decided whether we delete fields from Report or can add personal information to report db.

**Comment by danakonovalenko** [comment]
@AlexKovalevych It was allowed to add fields from parties to existing table with id
```
             - fist_name
             - last_name 
             - second_name
```

**Comment by lymychp** [comment]
done
