### ISSUE TITLE
Medications Deactivation

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1222]
- [x] When deactivate not active medication response 200 must be shown. For now an error 404 is received in response. 
Same rule must be applied for 
- medical program deactivation
- innm_dosage deactivation

- [x] After update program_medication.is_active=false, medication_requests_allowed can't be updated, until program_medication.is_active=true
      program_medication.is_active=false - > program_medication.medication_requests_allowed=false

**Comment by PavelVesnin** [comment]
done
