### ISSUE TITLE
(NHS Admin portal) Design & implement button "Reset ..." on page "Declaration detail"

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1236]
As a NHS Admin.   
I want reset MPI authorization method   
So that - On page "Declaration detail" create button "Reset authorization method".

**Requirements:**
- on page "Declaration detail", on section "Person/Людина" add button "Reset authorization method"
- on click button (after confirmation in dialog) - invoke WS ([spec](http://docs.uaehealthapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/persons/reset-authentication-method))

**Additional:**
- on page "Declaration detail" add attribute "Status" (declaration status)
- on page "Declaration list" add column "Status" (declaration status)
 
------------------------------
- [x] Implement
- [ ]  Deploy
- [x]  Tests

**Comment by kiurchv** [comment]
In current implementation, `status` attribute is missing in declaration instance from the declarations list​
