### ISSUE TITLE
[portal]: division description on the map should contain legal entity name

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1242]
Currently, when checking divisions on the map - only division name is displayed, which is not informative.
We should show a MSP name + division name
Screenshot attached

cc: @lymychp @kmakarenko 

![screenshot from 2017-10-12 13-39-05](https://user-images.githubusercontent.com/10362976/31492206-bf433a82-af52-11e7-911e-895eb64406eb.png)

**Comment by svetavedmed** [comment]
done on prod - division_name(Legal_entity_name)
![image](https://user-images.githubusercontent.com/30794602/43251604-063f0d14-90c9-11e8-93f8-2468f7d5b480.png)
