### ISSUE TITLE
Block/Unblock fraud User

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1246]
After user fraud was detected there is a necessity to block and in case the suspicious wasn't correct unblock him. In order to have the possibility to do that next steps must be done:

- [x] Describe the logic of blocking/unblocking users [confluence](https://edenlab.atlassian.net/wiki/x/nICPAw)
- [x] Implement
- [x] Improve test scenarios

**Comment by danakonovalenko** [comment]
When creating new employee_request there is must be additional verification. If party.tax_id=black_list_users.tax_id and is_active=true show 422 error (New employee with this tax_id can't be created).

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed

**Comment by danakonovalenko** [comment]
We need to expire all tokens for blocked users from mithril.tokens:
tax_id -> party_id(s) -> user_id(s) -> update expires_at= now()

**Comment by PavelVesnin** [comment]
@danakonovalenko maybe let's delete tokens by user_ids?

**Comment by PavelVesnin** [comment]
@danakonovalenko implemented and deployed
