### ISSUE TITLE
change eHealth portal logo (ASAP)

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1278]
Steps: 
1. Open Facebook messenger 
2. Paste portal link in a message to someone https://portal.ehealth-ukraine.org/providers.html
Current label: helsi logo in attached link
![screen shot 2017-10-18 at 13 10 52](https://user-images.githubusercontent.com/32056656/31716454-8e45b4c4-b410-11e7-9b6c-ff4d36e3031d.png)

Expected label: ehealth logo in attached link

**Comment by pzhuk** [comment]
can we please adjust meta tags
og:image should always point to main eHealth logo

https://developers.facebook.com/docs/sharing/webmasters/

**Comment by pzhuk** [comment]
@warehousman can we prioritize this pls? Really bad PR for us :(

**Comment by warehousman** [comment]
@pzhuk OK

**Comment by warehousman** [comment]
@pzhuk assigned and in progress

**Comment by pzhuk** [comment]
thanks a lot

**Comment by warehousman** [comment]
@pzhuk - Done
