### ISSUE TITLE
Change WS specs: rename `dispense_details` -> `details`

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1294]
Rename JSON object `dispense_details` -> `details` in all [Dispense WS](http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/medication-dispense)
 & [Report]( http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/reimbursement-report/get-reimbursement-report)

**Comment by danakonovalenko** [comment]
Can't check as Reimbursement Report doesn't show Dispenses, even if Medication Request status = COMPLETED.
```
curl -X GET \
  'https://dev.ehealth.world/api/reimbursement_report?date_from_request=2017-01-01&date_to_request=2017-10-30&page_size=30' \
  -H 'authorization: Bearer YmFsVTJoTHQ5ODRkY3dIMUJtemZ5Zz09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 11ad0c74-daee-b9ad-63de-6cd01418af0c'
```

**Comment by danakonovalenko** [comment]
In reports dispense_details also must be renamed to details:
<img width="745" alt="screen shot 2017-10-30 at 3 27 54 pm" src="https://user-images.githubusercontent.com/31403196/32173254-04b36e1a-bd87-11e7-98b2-39ff08fd7dfc.png">
