### ISSUE TITLE
Capitation Report Changes

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1302]
**As for now** we receive a report which shows only legal entities with declarations, however if the legal entity doesn't have any declaration even if it's in red lists the report won't show it. 
In requirements:
```
звіт включає в себе всі заклади, де були зареєстровані декларації та всі заклади, 
що залишились в червоних списках за виключенням тих, що перетнулися з зеленими списками. 
```
**To do:** change the report according to requirements.

**Comment by danakonovalenko** [comment]
@Troush There is an error while trying to make capitation report
[capitation_report_error.txt](https://github.com/edenlabllc/ehealth.api/files/1418481/capitation_report_error.txt)

**Comment by PavelVesnin** [comment]
@danakonovalenko fixed
