### ISSUE TITLE
can't view employee and le details

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1306]
While reviewing a declaration at admin poral
https://admin.ehealth-ukraine.org/declarations/92f879a1-d719-4542-a912-106230c21be6/

Try to click on "Go to Organization"  - empty blue screen is displayed
Try to click on "Go to Employee" - nothing happens

**Comment by lymychp** [comment]
@pzhuk it has happened only for legal_entities and employees without optional blocks of data.
fixed on demo.
please check

**Comment by svetavedmed** [comment]
fixed on demo
