### ISSUE TITLE
eHealth portal - wrong region location on map

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1310]
1. Go on ehealth portal
2. Choose any region on map --> click for details
Expected result: chosen region is shown in google maps
Current result: Kyiv region is shown on map for all regions

**Comment by lymychp** [comment]
[proposal draft](https://docs.google.com/document/d/1Sn2t-2Sdp4MFS9-L-Sa7qIYIxVxq-YzhltxssIP9hQ0/edit?ts=59ede8a5#heading=h.l3qbvpbfipg)

**Comment by ivchenkodima** [comment]
https://github.com/edenlabllc/nhs.portal.web/pull/33

**Comment by lymychp** [comment]
deployed to prod
