### ISSUE TITLE
[Declaration request] Replace Gandalf call with hardcoded logic

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1311]
As a NHS admin
I want the default auth method to be calculated in the declaration creation process without integration with Gandalf
So that eHealth system is not dependent on the gndf.io availability.

Replace Gandalf call with hardcoded logic during create declaration request

Determine current authentication method according to:

1. Existing **MPI_ID**:
    * return current authentication method = previous authentication method
2. New **MPI_ID**:
    * requested authentication method = _OFFLINE_ - return current authentication method = _OFFLINE_
    * requested authentication method = _OTP_ - return current authentication method = _NA_

**Comment by lymychp** [comment]
deployed to prod
