### ISSUE TITLE
auth page returns all dictionaries in js element

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1326]
Open https://auth.ehealth.world/sign-in/

We could see that all dictionaries returned in the page code
It makes page heavy, and also it's unclear why it's needed?
`
  window.__REDUX_STATE__ = '%7B%22pages%22%3A%7B%22AcceptPage%22%3A%7B%22scope%22%3A%5B%5D%7D%7D%2C%22blocks%22%3A%7B%22Aside%22%3A%7B%22active%22%3Afalse%7D%7D%2C%22session%22%3A%7B%22token%22%3A%22TXdJSHd0RTVYcHU1bGlCM0RqYlBCUT09%22%7D%2C%22data%22%3A%7B%22clients%22%3A%7B%7D%2C%22user%22%3Anull%2C%22userRoles%22%3Anull%2C%22requests%22%3A%7B%7D%2C%22dictionaries%22%3A%7B%22EMPLOYEE_TYPE%22%3A%7B%22values%22%3A%7B%22OWNER%22%3A%22%u043A%u0435%u0440%u0456%u0432%u043D%u0438%u043A%20%u0437%u0430%u043A%u043B%u0430%u0434%u0443%20%u041E%u0417%22%2C%22HR%22%3A%22%u0432%u0456%u0434%u0434%u0456%u043B%20%u043A%u0430%u0434%u0440%u0456%u0432%22%2C%22DOCTOR%22%3A%22%u043B%u0456%u043A%u0430%u0440%22%2C%22ADMIN%22%3A%22%u0440%u0435%u0454%u0441%u0442%u0440%u0430%u0442%u043E%u0440%22%7D%2C%22name%22%3A%22EMPLOYEE_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22OWNER_PROPERTY_TYPE%22%3A%7B%22values%22%3A%7B%22STATE%22%3A%22%u0431%u044E%u0434%u0436%u0435%u0442%u043D%u0430%20%u0444%u043E%u0440%u043C%u0430%20%u0432%u043B%u0430%u0441%u043D%u043E%u0441%u0442%u0456%22%2C%22PRIVATE%22%3A%22%u043F%u0440%u0438%u0432%u0430%u0442%u043D%u0430%20%u0444%u043E%u0440%u043C%u0430%20%u0432%u043B%u0430%u0441%u043D%u043E%u0441%u0442%u0456%22%7D%2C%22name%22%3A%22OWNER_PROPERTY_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22QUALIFICATION_TYPE%22%3A%7B%22values%22%3A%7B%22TOPIC_IMPROVEMENT%22%3A%22%u0422%u0435%u043C%u0430%u0442%u0438%u0447%u043D%u0435%20%u0443%u0434%u043E%u0441%u043A%u043E%u043D%u0430%u043B%u0435%u043D%u043D%u044F%22%2C%22STAZHUVANNYA%22%3A%22%u0421%u0442%u0430%u0436%u0443%u0432%u0430%u043D%u043D%u044F%22%2C%22SPECIALIZATION%22%3A%22%u0421%u043F%u0435%u0446%u0456%u0430%u043B%u0456%u0437%u0430%u0446%u0456%u044F%22%2C%22REATTESTATION%22%3A%22%u041F%u0435%u0440%u0435%u0434%u0430%u0442%u0435%u0441%u0442%u0430%u0446%u0456%u0439%u043D%u0438%u0439%20%u0446%u0438%u043A%u043B%22%2C%22INTERNSHIP%22%3A%22%u0406%u043D%u0442%u0435%u0440%u043D%u0430%u0442%u0443%u0440%u0430%22%2C%22INFORMATION_COURSES%22%3A%22%u041A%u0443%u0440%u0441%u0438%20%u0456%u043D%u0444%u043E%u0440%u043C%u0430%u0446%u0456%u0457%22%2C%22CLINICAL_RESIDENCY%22%3A%22%u041A%u043B%u0456%u043D%u0456%u0447%u043D%u0430%20%u043E%u0440%u0434%u0438%u043D%u0430%u0442%u0443%u0440%u0430%22%7D%2C%22name%22%3A%22QUALIFICATION_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22DIVISION_TYPE%22%3A%7B%22values%22%3A%7B%22FAP%22%3A%22%u0424%u0410%u041F%22%2C%22CLINIC%22%3A%22%u0424%u0456%u043B%u0456%u044F%20%28%u0456%u043D%u0448%u0438%u0439%20%u0432%u0456%u0434%u043E%u043A%u0440%u0435%u043C%u043B%u0435%u043D%u0438%u0439%20%u043F%u0456%u0434%u0440%u043E%u0437%u0434%u0456%u043B%29%22%2C%22AMBULANT_CLINIC%22%3A%22%u0410%u043C%u0431%u0443%u043B%u0430%u0442%u043E%u0440%u0456%u044F%22%7D%2C%22name%22%3A%22DIVISION_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22DOCUMENT_RELATIONSHIP_TYPE%22%3A%7B%22values%22%3A%7B%22DOCUMENT%22%3A%22%u0414%u043E%u043A%u0443%u043C%u0435%u043D%u0442%22%2C%22COURT_DECISION%22%3A%22%u0420%u0456%u0448%u0435%u043D%u043D%u044F%20%u0441%u0443%u0434%u0443%22%2C%22CONFIDANT_CERTIFICATE%22%3A%22%u041F%u043E%u0441%u0432%u0456%u0434%u0447%u0435%u043D%u043D%u044F%20%u043E%u043F%u0456%u043A%u0443%u043D%u0430%22%2C%22BIRTH_CERTIFICATE%22%3A%22%u0421%u0432%u0456%u0434%u043E%u0446%u0442%u0432%u043E%20%u043F%u0440%u043E%20%u043D%u0430%u0440%u043E%u0434%u0436%u0435%u043D%u043D%u044F%22%7D%2C%22name%22%3A%22DOCUMENT_RELATIONSHIP_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22DOCUMENT_TYPE%22%3A%7B%22values%22%3A%7B%22TEMPORARY_CERTIFICATE%22%3A%22%u041F%u043E%u0441%u0432%u0456%u0434%u043A%u0430%20%u043D%u0430%20%u043F%u0440%u043E%u0436%u0438%u0432%u0430%u043D%u043D%u044F%22%2C%22PASSPORT%22%3A%22%u041F%u0430%u0441%u043F%u043E%u0440%u0442%22%2C%22NATIONAL_ID%22%3A%22%u0411%u0456%u043E%u043C%u0435%u0442%u0440%u0438%u0447%u043D%u0438%u0439%20%u043F%u0430%u0441%u043F%u043E%u0440%u0442%22%2C%22BIRTH_CERTIFICATE%22%3A%22%u0421%u0432%u0456%u0434%u043E%u0446%u0442%u0432%u043E%20%u043F%u0440%u043E%20%u043D%u0430%u0440%u043E%u0434%u0436%u0435%u043D%u043D%u044F%22%7D%2C%22name%22%3A%22DOCUMENT_TYPE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22EDUCATION_DEGREE%22%3A%7B%22values%22%3A%7B%22MASTER%22%3A%22%u041C%u0430%u0433%u0456%u0441%u0442%u0440%22%2C%22JUNIOR_EXPERT%22%3A%22%u041C%u043E%u043B%u043E%u0434%u0448%u0438%u0439%20%u0441%u043F%u0435%u0446%u0456%u0430%u043B%u0456%u0441%u0442%22%2C%22EXPERT%22%3A%22%u0421%u043F%u0435%u0446%u0456%u0430%u043B%u0456%u0441%u0442%22%2C%22BACHELOR%22%3A%22%u0411%u0430%u043A%u0430%u043B%u0430%u0432%u0440%22%7D%2C%22name%22%3A%22EDUCATION_DEGREE%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22EMPLOYEE_REQUEST_STATUS%22%3A%7B%22values%22%3A%7B%22REJECTED%22%3A%22%u0412%u0456%u0434%u0445%u0438%u043B%u0435%u043D%u043E%22%2C%22NEW%22%3A%22%u041E%u0447%u0456%u043A%u0443%u0454%20%u0432%u0435%u0440%u0438%u0444%u0456%u043A%u0430%u0446%u0456%u0457%22%2C%22EXPIRED%22%3A%22%u041F%u0440%u043E%u0441%u0442%u0440%u043E%u0447%u0435%u043D%u043E%22%2C%22APPROVED%22%3A%22%u0421%u0445%u0432%u0430%u043B%u0435%u043D%u043E%22%7D%2C%22name%22%3A%22EMPLOYEE_REQUEST_STATUS%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22EMPLOYEE_STATUS%22%3A%7B%22values%22%3A%7B%22DISMISSED%22%3A%22%u0417%u0432%u0456%u043B%u044C%u043D%u0435%u043D%u0438%u0439%22%2C%22APPROVED%22%3A%22%u0410%u043A%u0442%u0438%u0432%u043D%u0438%u0439%22%7D%2C%22name%22%3A%22EMPLOYEE_STATUS%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22GENDER%22%3A%7B%22values%22%3A%7B%22MALE%22%3A%22%u0447%u043E%u043B%u043E%u0432%u0456%u0447%u0430%22%2C%22FEMALE%22%3A%22%u0436%u0456%u043D%u043E%u0447%u0430%22%7D%2C%22name%22%3A%22GENDER%22%2C%22labels%22%3A%5B%22SYSTEM%22%2C%22EXTERNAL%22%5D%2C%22is_active%22%3Atrue%7D%2C%22KVEDS%22%3A%7B%22values%22%3A%7B%2246.75%22%3A%22%u041E%u043F%u0442%u043E%u0432%u0430%20%u0442%u043E%u0440%u0433%u0456%u0432%u043B%u044F%20%u0445%u0456%u043C%u0456%u0447%u043D%u0438%u043C%u0438%20%u043F%u0440%u043E%u0434%u0443%u043A%u0442%u0430%u043C%u0438%22%2C%2246.13%22%3A%22%u0414%u0456%u044F%u043B%u044C%u043D%u0456%u0441%u0442%u044C%20%u043F%u043E%u0441%u0435%u0440%u0435%u0434%u043D%u0438%u043A%u0456%u0432%20%u0443%20%u0442%u043E%u0440%u0433%u0456%u0432%u043B%u0456%20%u0434%u0435%u0440%u0435%u0432%u0438%u043D%u043E%u044E%2C%20%u0431%u0443%u0434%u0456%u0432%u0435%u043B%u044C%u043D%u0438%u043C%u0438%20%u043C%u0430%u0442%u0435%u0440%u0456%u0430%u043B%u0430%u043C%u0438%20%u0442%u0430%20%u0441%u0430%u043D%u0456%u0442%u0430%u0440%u043D%u043E-%u0442%u0435%u0445%u043D%u0456%u0447%u043D%u0438%u043C%u0438%20%u0432%u0438%u0440%u043E%u0431%u0430%u043C%u0438%22%2C%2228.93%22%3A%22%u0412%u0438%u0440%u043E%u0431%u043D%u0438%u0446%u0442%u0432%u043E%20%u043C%u0430%u0448%u0438%u043D%20%u0456%20%u0443%u0441%u0442%u0430%u0442%u043A%u043E%u0432%u0430%u043D%u043D%u044F%20%u0434%u043B%u044F%20%u0432%u0438%u0433%u043E%u0442%u043E%u0432%u043B%u0435%u043D%u043D%u044F%20%u0445%u0430%u0440%u0447%u043E%u0432%u0438%u0445%20%u043F%u0440%u043E%u0434%u0443%u043A%u0442%u0456%u0432%20%u0456%20%u043D%u0430%u043F%u043E%u0457%u0432%2C%20%u043F%u0435%u0440%u0435%u0440%u043E%u0431%u043B%u0435%u043D%u043D%u044F%20%u0442%u044E%u0442%u044E%u043D%u0443%22%2C%2256.21%22%3A%22%u041F%u043E%u0441%u0442%u0430%u0447%u0430%u043D%u043D%u044F%20%u0433%u043E%u0442%u043E%u0432%u0438%u0445%20%u0441%u0442%u0440%u0430%u0432%20%u0434%u043B%u044F%20%u043F%u043E%u0434%u0456%u0439%22%2C%2238.31%22%3A%22%u0414%u0435%u043C%u043E%u043D%u0442%u0430%u0436%20%28%u0440%u043E%u0437%u0431%u0438%u0440%u0430%u043D%u043D%u044F%29%20%u043C%u0430%u0448%u0438%u043D%20%u0456%20%u0443%u0441%u0442%u0430%u0442%u043A%u043E%u0432%u0430%u043D%u043D%u044F%22%2C%2221.20%22%3A%22%u0412%u0438%u0440%u043E%u0431%u043D%u0438%u0446%u0442%u0432%u043E%20%u0444%u0430%u0440%u043C%u0430%u0446%u0435%u0432%u0442%u0438%u0447%u043D%u0438%u0445%20%u043F%u0440%u0435%u043F%u0430%u0440%u0430%u0442%u0456%u0432%20%u0456%20%u043C%u0430%u0442%u0435%u0440%u0456%u0430%u043B%u0456%u0432%22%2C%2282.11%22%3A%22%u041D%u0430%u0434%u0430%u043D%u043D%u044F%20%u043A%u043E%u043C%u0431%u0456%u043D%u043E%u0432%u0430%u043D%u0438%u0445%20%u043E%u0444%u0456%u0441%u043D%u0438%u0445%20%u0430%u0434%u043C%u0456%u043D%u0456%u0441%u0442%u0440%u0430%u0442%u0438%u0432%u043D%u0438%u0445%20%u043F%u043E%u0441%u043B%u0443%u0433%22%2C%2210.39%22%3A%22%u0406%u043D%u0448%u0456%20%u0432%u0438%u0434%u0438%20%u043F%u0435%u0440%u0435%u0440%u043E%u0431%u043B%u0435%u043D%u043D%u044F%20%u0442%u0430%20%u043A%u043E%u043D%u0441%u0435%u0440%u0432%u0443%u0432%u0430%u043D%u043D%u044F%20%u0444%u0440%u0443%u043A%u0442%u0456%u0432%20%u0456%20%u043E%u0432%u043E%u0447%u0456%u0432%22%2C%2235.22%22%3A%22%u0420%u043E%u0437%u043F%u043E%u0434%u0456%u043B%u0435%u043D%u043D%u044F%20%u0433%u0430%u0437%u043E%u043F%u043E%u0434%u0456%u0431%u043D%u043E%u0433%u043E%20%u043F%u0430%u043B%u0438%u0432%u0430%20%u0447%u0435%u0440%u0435%u0437%20%u043C%u0456%u0441%u0446%u0435%u0432%u0456%20%28%u043B%u043E%u043A%u0430%u043B%u044C%u043D%u0456%29%20%u0442%u0440%u0443%u0431%u043E%u043F%u0440%u043E%u0432%u043E%u0434%u0438%22%2C%2287.30%22%3A%22%u041D%u0430%u0434%u0430%u043D%u043D%u044F%20%u043F%u043E%u0441%u043B%u0443%u0433%20%u0449%u043E%u0434%u043E%20%u0434%u043E%u0433%u043B%u044F%u0434%u0443%20%u0456%u0437%20%u0437%u0430%u0431%u0435%u0437%u043F%u0435%u0447%u0435%u043D%u043D%u044F%u043C%20%u043F%u0440%u043E%u0436%u0438%u0432%u0430%u043D%u043D%u044F%20%u0434%u043B%u044F%20%u043E%u0441%u0456%u0431%20%u043F%u043E%u0445%u0438%u043B%u043E%u0433%u043E%20%u0432%u0456%u043A%u0443%20%u0442%u0430%20%u0456%u043D%u0432%u0430%u043B%u0456%u0434%u0456%u0432%22%2C%2201.15%22%3A%22%u0412%u0438%u0440%u043E%u0449%u0443%u0…`

**Comment by ivchenkodima** [comment]
deployed to dev
