### ISSUE TITLE
preprod admin portal is not showing attachments

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1365]
Environment: pre-prod

Looking at the declaration and can't see any attached scan document
https://admin.ehealth.world/declarations/0d500f15-8059-437b-abb2-acb9e46209b0

As per ops records, id of request is : '19e2e53d-f3ac-41ae-9c45-934c4eae2f25'
Docs for this requests were uploaded and available at the storage:

https://console.cloud.google.com/storage/browser/declaration-requests-preprod/19e2e53d-f3ac-41ae-9c45-934c4eae2f25/?project=ehealth-162117

Expected result: attachments should be displayed

**Comment by ivchenkodima** [comment]
@pzhuk api response for this declaration is 404. So there is no attachments.
Please checkout here:
```
curl 'https://admin.ehealth.world/api/api/declarations/0d500f15-8059-437b-abb2-acb9e46209b0/documents' -H 'pragma: no-cache' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4' -H 'authorization: Bearer T0RGM1VsR0o4S1QzQW1SeTkyUHpldz09' -H 'content-type: application/json' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: admin.ehealth.world' -H 'referer: https://admin.ehealth.world/pending-declarations/0d500f15-8059-437b-abb2-acb9e46209b0/' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' --compressed
```

**Comment by pzhuk** [comment]
but that's incorrect - I am checking opsdb for the declaration request id  and it's 19e2e53d-f3ac-41ae-9c45-934c4eae2f25
exactly for this id - documents are present in the bucket https://console.cloud.google.com/storage/browser/declaration-requests-preprod/19e2e53d-f3ac-41ae-9c45-934c4eae2f25/?project=ehealth-162117

so why there are no documents, if documents are in the bucket?

**Comment by ivchenkodima** [comment]
@lymychp this is no front trouble. We have to find the problem in api service.

**Comment by lymychp** [comment]
we should try to reproduce it on dev/demo. Preprod version is really old one.

**Comment by svetavedmed** [comment]
On Dev&Demo can't see documents as well. 
Next example is on dev - [declaration.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46ec91992f8391a89be0b04de611b2843b492d762a10e17132d0ba79be462a04575c48a9150e5844fdfada7fa7e76a73db4e17ff933c0120996048e6edc00db513bb27814e80b7bc8f4bc8e13c21ef828b5d73.txt)
Documents exist in bucket:
gs://declaration-requests-dev/ee2692a0-33d1-47e1-98f2-dd1ebe7d5411/declaration_request_confidant_person.0.PRIMARY.RELATIONSHIP.BIRTH_CERTIFICATE.jpeg
gs://declaration-requests-dev/ee2692a0-33d1-47e1-98f2-dd1ebe7d5411/declaration_request_confidant_person.1.SECONDARY.RELATIONSHIP.BIRTH_CERTIFICATE.jpeg
gs://declaration-requests-dev/ee2692a0-33d1-47e1-98f2-dd1ebe7d5411/declaration_request_person.PASSPORT.jpeg
gs://declaration-requests-dev/ee2692a0-33d1-47e1-98f2-dd1ebe7d5411/declaration_request_person.SSN.jpeg

**Comment by gmile** [comment]
I looked at API call from @ivchenkodima. It's working (I'm using a different token though):

```bash
curl 'https://admin.ehealth.world/api/api/declarations/0d500f15-8059-437b-abb2-acb9e46209b0' -H 'content-type: application/json' -H 'authorization: Bearer S0VhcEJPdTNFM2
1PYU9NY3B1TGtSdz09'
```

Response (reduced for brevity):

```
{
  "meta": {
    "url": "http://api.ehealth.world/api/declarations/0d500f15-8059-437b-abb2-acb9e46209b0",
    "type": "object",
    "request_id": "48mgib47q1u2fo0v7mib17c91douq8rn",
    "code": 200
  },
  "data": {
    "updated_at": "2017-11-28T15:15:00.035876Z",
    "status": "active",
    "start_date": "2017-10-29",
    "signed_at": "2017-10-29T21:24:06.325500Z",
    "scope": "family_doctor",
    "person": {
      "tax_id": "...",
    }
  ...
}
```

**Comment by gmile** [comment]
Front-end expects `person.documents` to be present on a response:

* front-end code to access the API endpoint:
  https://github.com/edenlabllc/nhs.admin.web/blob/52a8b50d0c1996ada164a352de3ffbe96f6e27dd/app/common/redux/declarations.js#L78-L94

* front-end code to render documents: 
  https://github.com/edenlabllc/nhs.admin.web/blob/52a8b50d0c1996ada164a352de3ffbe96f6e27dd/app/common/containers/blocks/DeclarationDetail/index.js#L268-L283

However, API is not rendering any documents by what seems like an intentional API design decision:

https://github.com/edenlabllc/ehealth.api/blob/c2ae3249855a3499bf27b708a673f2e52851f829/lib/ehealth/web/controllers/declarations_controller.ex#L16-L20

https://github.com/edenlabllc/ehealth.api/blob/c2ae3249855a3499bf27b708a673f2e52851f829/lib/ehealth/declarations/api.ex#L101-L106

https://github.com/edenlabllc/ehealth.api/blob/c2ae3249855a3499bf27b708a673f2e52851f829/lib/ehealth/declarations/view.ex#L40-L60

So far I see no evidence `person.documents` will ever be there.

**Comment by gmile** [comment]
To sum up:

* in the initial issue description, @pzhuk is talking about **declaration view page** – attachments are not displayed as per my https://github.com/edenlabllc/ehealth.api/issues/1365#issuecomment-352714087,
* later in https://github.com/edenlabllc/ehealth.api/issues/1365#issuecomment-342632631 @ivchenkodima responds referring to an API call that ends with `.../documents`. By following the code trail path, it looks like Dima is talking about a different page called **view pending declaration**:
   * API call: 
  https://github.com/edenlabllc/nhs.admin.web/blob/master/app/common/redux/declarations.js#L151-L167

   * rendering code https://github.com/edenlabllc/nhs.admin.web/blob/master/app/common/containers/pages/PendingDeclarationDetailPage/index.js#L80-L87

Now:

* as noted above, the front-end [code](https://github.com/edenlabllc/nhs.admin.web/blob/52a8b50d0c1996ada164a352de3ffbe96f6e27dd/app/common/containers/blocks/DeclarationDetail/index.js#L268-L283) for **declaration view page** is not correct. There are no such thing as `person.documents` when calling declaration details API call,

* `.../documents` is indeed not working, but it is not the page @pzhuk is talking about in the initial description.

**Comment by gmile** [comment]
Actionable items:

* @pzhuk can you confirm you indeed expected attachments to display on **view declaration details** page?
* @ivchenkodima can you clarify why in an attempt to reproduce the problem you called endpoint ending with `.../documents`?

**Comment by pzhuk** [comment]
confirming the same -this task is about view "declarations requiring
review" and "declarations" - both should be able to display attachements
(if they were present)

BR, Pavel V. Zhuk


2017-12-19 14:01 GMT+02:00 Eugene Pirogov <notifications@github.com>:

**Comment by lymychp** [comment]
@pzhuk "declarations" view never supposed to show attachments.
"declarations requiring review" - will check and fix it.

**Comment by pzhuk** [comment]
@lymychp - how this two views are different from each other? Can't we have
same approach for both of them?

BR, Pavel V. Zhuk


2017-12-19 16:05 GMT+02:00 lymychp <notifications@github.com>:

**Comment by lymychp** [comment]
agreed with @pzhuk to add block with the documents to the `declarations` view. It should work the same way as for the `pending review declarations`

**Comment by svetavedmed** [comment]
done on dev
