### ISSUE TITLE
ops audit_log is empty

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1370]
At the prod environment, we could see at least 7 terminated declrations in opsdb
In the same time, audit_log is empty which is wrong

Please, check if ops audit_log is available

**Comment by lymychp** [comment]
check why do we have terminated declarations in prod and why do we have `updated_at` almost the same as `inserted_at`

**Comment by pzhuk** [comment]
checked person_id for old and new declarations - are established for same employee_id
so wild guess - terminated ones looks like doctors are re-establishing declarations when they need to fix any mistake

**Comment by lymychp** [comment]
deployed to prod
