### ISSUE TITLE
Remove doctor's personal info in all MRR responses

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1376]
remove doctor's tax_id and Documents in MRR response
- Create MRR response
- MRR Sign response
- Medication request reject response
- Get MRR list
- Get MRR by ID

- [x] Update json schemas for response @svetavedmed PR#1416
- [x] Implementation @Troush

**Comment by EdwardVoloshin** [comment]
create PR #1416 for Json-schema
