### ISSUE TITLE
Remove doctor's personal info in all MR responses

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1377]
Remove doctor's Tax_id and documents in
- Get Medication requests list
- Get Medication request by id
- Get Medication Dispenses list by Medication Request ID
- Create Medication Dispense
- Process MD
- Reject MD
- Get MD list
- Get MD by id

- [x] Update json schemas for response @svetavedmed 
PR #1415 
PR #1297
- [ ] Implementation @Troush

**Comment by EdwardVoloshin** [comment]
Create PR #1415 with json-response MR for list & show object

**Comment by EdwardVoloshin** [comment]
Update PR #1297 with  json-response MD for list & show object

**Comment by svetavedmed** [comment]
response
```
"party": {
                    "second_name": "Вікторович",
                    "phones": [
                        {
                            "type": "MOBILE",
                            "number": "+380503410870"
                        }
                    ],
                    "last_name": "Вірний",
                    "id": "1816a1ff-40f3-44ea-9665-82ea375e8be0",
                    "gender": "MALE",
                    "first_name": "Олександр",
                    "birth_date": "1984-07-12"
                },
```
