### ISSUE TITLE
link to the demo map in prod

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1389]
Here the production portal is refering to a demo map
https://github.com/edenlabllc/nhs.portal.web/blame/65d910a03727671b54c2ed90c8506ef50822479c/dist/join.html#L251

This kind of things should be avoided in future

**Comment by lymychp** [comment]
@vsirius @ivchenkodima please deploy to prod asap

**Comment by ivchenkodima** [comment]
@lymychp done
