### ISSUE TITLE
Implement SemVer for Pull Requests

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#1405]
We are using next SemVer rules:
`MAJOR` version when you make release on Production
`MINOR` version when you add new functionality
`PATCH` version when you make bug fixes

At least one commit in PR MUST contain keyword for SemVer. For example:
`[patch] - fix dirty bug`
`[minor] - enable 2FA auth`
`[major] - 14 sprint release`

Steps for implementation:
- Integrate [CI utils](https://github.com/Nebo15/ci-utils/tree/elixir) as submodule
- Ensure that commit messages are validates by [script](https://github.com/Nebo15/ci-utils/blob/elixir/fetch-source-version.sh#L46-L56)

Example of travis implementation you can see in [Annon](https://github.com/edenlabllc/annon.api/blob/master/.travis.yml#L43-L72)

Repositories:
- [x] IL
- [ ] OPS
- [ ] Mithril
- [ ] UAddress
- [ ] Reports
- [ ] OTP
- [ ] MPI
- [ ] Ael
- [x] Annon

**Comment by ybod** [comment]
Forked and updated `fetch-source-version.sh` to be **case insensitive**

https://github.com/edenlabllc/ci-utils/blob/0b4549c73af94f3186c7bd610c6cf5026e40781f/fetch-source-version.sh#L16

**Comment by gmile** [comment]
After looking at this, I think this ticket is actually valid. What must be done is: make sure all repos migrate to the submodule-style CI scripts. I'll do that.

**Comment by lymychp** [comment]
too old
