### ISSUE TITLE
OTP service is down

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1407]
Prod otp full of exceptions
500 dashboard shows a lot of errors

`{"time":"2017-11-01T10:32:54.731Z","sourceLocation":{"moduleName":null,"line":null,"functionName":null,"file":null},"severity":"ERROR","metadata":{"error_logger":"format"},"logMessage":"#PID<0.10196.25> running OtpVerification.Web.Endpoint terminated\nServer: api.ehealth-ukraine.org:80 (http)\nRequest: POST /verifications/\n** (exit) an exception was raised:\n    ** (MatchError) no match of right hand side value: {:error, [status: \"canceled\", id: \"\"]}\n        (otp_verification_api) lib/otp_verification_api/verification/verifications.ex:129: OtpVerification.Verification.Verifications.initialize_attrs/1\n        (otp_verification_api) lib/otp_verification_api/verification/verifications.ex:105: OtpVerification.Verification.Verifications.initialize_verification/1\n        (otp_verification_api) lib/otp_verification_api/web/controllers/verifications_controller.ex:23: OtpVerification.Web.VerificationsController.initialize/2\n        (otp_verification_api) lib/otp_verification_api/web/controllers/verifications_controller.ex:1: OtpVerification.Web.VerificationsController.action/2\n        (otp_verification_api) lib/otp_verification_api/web/controllers/verifications_controller.ex:1: OtpVerification.Web.VerificationsController.phoenix_controller_pipeline/2\n        (otp_verification_api) lib/otp_verification_api/web/endpoint.ex:1: OtpVerification.Web.Endpoint.instrument/4\n        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1\n        (otp_verification_api) lib/otp_verification_api/web/endpoint.ex:1: OtpVerification.Web.Endpoint.plug_builder_call/2"}
`

**Comment by Troush** [comment]
Issue Report:
Lifecell started to return status `canceled` and stoped delivering sms to clients.

Changes that was made to overcome this issue:
Put demo credentials for Lifecell to production environment

**Comment by Troush** [comment]
Updated to new credentials given by @pzhuk
