### ISSUE TITLE
Collect release notes

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#1409]
Collect PATCH and MINOR release notes from Travis CI when build is successfully merged into master and create new file with collected changelog in `release_notes/` folder with name {TYPE}-{VERSION}.
Example:
```
release_notes:
-- PATCH-0.2.21
-- PATCH-0.2.22
-- MINOR-0.3.0
-- PATCH-0.3.1
```

**Comment by ybod** [comment]
There is a proposal to save release notes not in a file but as a **git tag** message

**Comment by PavelVesnin** [comment]
We need to have a simple way to collect a lot of release notes (200+ commits) for each release. Do you think git tag message can simplify this action?
Also it will be good thing collect notes by MAJOR version. For example: `release_notes/1.0.0/PATCH-1.1.0`
