### ISSUE TITLE
Search release tags without case sensitivity

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#1412]
Code is [here](https://github.com/Nebo15/ci-utils/blob/elixir/fetch-source-version.sh#L16-L18)

**Comment by ybod** [comment]
Fixed in fork: https://github.com/edenlabllc/ci-utils/blob/0b4549c73af94f3186c7bd610c6cf5026e40781f/fetch-source-version.sh#L16
