### ISSUE TITLE
printable declaration - license is not shown

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1429]
When declaration request is created, it's possible to fetch printable version of declaration, where License MOH field exist, but never shows any info

License info should be properly rendered

**Comment by pzhuk** [comment]
Як можна побачити навпроти поля "Ліцензія МОЗ"  - нічого нема

![Uploading Screenshot from 2017-11-06 15-24-40.png…]()

**Comment by pzhuk** [comment]
![screenshot from 2017-11-06 15-24-40](https://user-images.githubusercontent.com/10362976/32443260-0b01298a-c307-11e7-92b6-fe0341ff16f0.png)

**Comment by pzhuk** [comment]
data from preprod 

id: 7f9f9d9d-b3af-4635-952f-62a1ecff4c97
[decl.html.txt](https://github.com/edenlabllc/ehealth.api/files/1446476/decl.html.txt)

**Comment by danakonovalenko** [comment]
In case there are more than 1 license for legal entity (as it's an array) which one should be shown in print out version?

**Comment by danakonovalenko** [comment]
@ybod also must be fixed the row with 'nil' value
![Screen Shot 2017-11-08 at 11.54.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a3d716beb217001ad204a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fb6b7191a379ee0c2e55415d4ebc30254d58eeb9cb74fce36f34985619e8d86c0e20c76819afbe874be906ba21881cd1b7eddc4f91fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae14c56a01a3465e272376e0a.png)

**Comment by ybod** [comment]
In case of multiple license we can output all of them like: `license_num (license_date), license_num (license_date)`

**Comment by danakonovalenko** [comment]
@ybod let's show first 3 licenses in view which was proposed by you: license_num (license_date), license_num (license_date)

**Comment by ybod** [comment]
PR merged for up to 3 licenses output in printout form
