### ISSUE TITLE
Опублікувати на порталі "Навчальні та промо-матеріали"

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1430]
На порталі у секції Пояснення - Лікарям, необхідно додати новий запис “Навчальні та промо-матеріали”, що відкриває сторінку, на якій розміщені матеріали для скачування.

Матеріали мають бути оформлені як на сторінці Документи (http://portal.demo.ehealth.world/#documents)

Нижче наведено перелік документів
- Навчальний буклет "Електронна система охорона здоров'я" / файли eHealth_буклет та eHealth_буклет_обкладинка
- Пам'ятка лікарю первинної ланки / файл Памятка_лікарю
- Інформаційний плакат для пацієнтів / файл Постер_А2
- Презентація з регіональних семінарів "Управління та фінанси". 4 квартал 2017 року  eHealth_regional seminars_finance.pdf
- Презентація з регіональних семінарів "Зміни у сфері охорони здоров'я та eHealth". 4 квартал 2017 року/eHealth_regional.seminars.pdf

[eHealth_regional seminars_finance.pdf](https://github.com/edenlabllc/ehealth.api/files/1487551/eHealth_regional.seminars_finance.pdf)
[eHealth_regional seminars.pdf](https://github.com/edenlabllc/ehealth.api/files/1487552/eHealth_regional.seminars.pdf)

[eHealth_буклет.pdf](https://github.com/edenlabllc/ehealth.api/files/1446249/eHealth_.pdf)
[Памятка_лікарю.pdf](https://github.com/edenlabllc/ehealth.api/files/1446250/_.pdf)
[eHealth_буклет_обкладинка.pdf](https://github.com/edenlabllc/ehealth.api/files/1446251/eHealth_._.pdf)
[90x50_зовнішній_бік.pdf](https://github.com/edenlabllc/ehealth.api/files/1446252/90x50_._.pdf)
[90x50_внутрішній_блок.pdf](https://github.com/edenlabllc/ehealth.api/files/1446253/90x50_._.pdf)

Візитівка лікаря / файли 90х50 зовнішній бік, 90х50 внутрішній блок

**Comment by LehaMotovilov** [comment]
1. Отсутствует файл для `Інформаційний плакат для пацієнтів / файл Постер_А2`.
2. В рамках текущей архитектуры проекта сделать внешний вид как у Документов сложно и займет больше времени. 

Так как задача с высоким приоритетом - оформил как и у остальных документов в этом разделе.

<img width="619" alt="screen shot 2017-11-22 at 12 04 31" src="https://user-images.githubusercontent.com/6247404/33121421-5b828d72-cf7d-11e7-9d00-ce96df1b3d11.png">

@lymychp ping

**Comment by lymychp** [comment]
@kmakarenko please approve the above design

**Comment by kmakarenko** [comment]
Файл постеру https://drive.google.com/file/d/1HPHSV1dYXDLo-4Q75dlykNBNm1vxckmw/view?usp=sharing

Зовнішній вигляд - ок

**Comment by LehaMotovilov** [comment]
Done: http://portal.ehealth.world/clarifications/2017-11-22-educational-and-promotional-materials/

**Comment by LehaMotovilov** [comment]
Deployed to production: https://portal.ehealth-ukraine.org/clarifications/2017-11-22-educational-and-promotional-materials/
