### ISSUE TITLE
Search Legal entities in public portal

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1444]
As a Legal entity owner or any citizen of ukraine
I want to search clinics/pharmacies on the public portal
So that 
  * I can check whether my clinic has been registered in eEhealth
  * I can search for the clinic to sign the declaration 

Solution: 
1. add new chapter `Медичні заклади` - table of legal entities with the search possibilities.
  * search by: region/area/settlement/edrpou/name
  * Legal entity detail attributes: names, edrpou, residence address, phone number, email, owner name.
  * show list of divisions by LE
  * show list of employees by division -ПІБ (лікаря), посада (лікар-терапевт)

@kmakarenko please confirm

**Comment by kmakarenko** [comment]
approved. The final UI solution should be discussed with Kristina

**Comment by lymychp** [comment]
[proposed design](https://www.dropbox.com/sh/l31iagfifbfrigq/AAAtAJmNBRa2L37jVPamQUaWa?dl=0)

**Comment by svetavedmed** [comment]
[1629](https://github.com/edenlabllc/ehealth.api/issues/1629)
