### ISSUE TITLE
Reimbursement objects migration scripts

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1445]
related to #1270

**Comment by svetavedmed** [comment]
***IL***
- [ ] dictionaries - add/update records if any. IDs should be the same.
***MITHRIL***
- [ ] client_types - add/update records if any. IDs should be the same.
- [ ] roles - add/update records if any. IDs should be the same.
- [ ] clients for mithril.admin, nhs.admin, uaddresses.admin
- [ ] user_roles - for admin fronts
- [ ] tokens - generate new tokens with new scopes in case if new endpoints are released
- [ ] approvals - generate or copy MIS approvals
***UADRESSESS***
- [ ] streets - update records all records
***PRM***
- [ ] medical_service_providers - add/update records if any. IDs should be the same.
- [ ] ukr_med_registries - add/update records if any. IDs should be the same.
- [ ] global_parameters - add/update records if any. IDs should be the same
***REPORTS***
- [ ] red_msps - update records all records
- [ ] red_msps_territories - update records all records
