### ISSUE TITLE
Publish information about MEDICS MIS on portal again

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1448]
Go on portal 
Current MISES on portal: helsi, emcimed, doctor eleks, medstar
Expected MISES on portal: helsi, emcimed, doctor eleks, medstar, medics
Functions row: as for all other MISES (Реєстрація закладів, лікарів, декларацій)

**Comment by lymychp** [comment]
ticket where it has been removed #1402

**Comment by ivchenkodima** [comment]
Could you please clarify whether (Реєстрація закладів, лікарів, декларацій) must be added to all MISes except medics or include it as for now "other MISES" can be understood in many ways.

**Comment by rkostiv** [comment]
Рядок "функції" для медікс має бути як і для інших МІСів - тобто "Реєстрація закладів, лікарів, декларацій"

**Comment by lymychp** [comment]
deployed to prod
