### ISSUE TITLE
401 instead of 403 in case of expiry token

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1449]
copied from https://github.com/ehealth-ua/api-spec/issues/118
>Є побажання, якщо це можливо звичайно, повертати 401 код замість 403 при "протуханні" access token.
Визвано тим, що ми запитуємо endpoint, до якого у користувача немає доступу і отримуємо 403 - forbidden, у відповідності до специфікації oAuth, при отриманні 403 коду ми маємо зміннювати
refresh token на access token . А по факту у користувача лише немає до цього доступу і оновлювати токен не потрібно. Як інший варіант вирішення, цього питання у боді 403 передавати якийсь параметр, щоб ми могли по ньому розрізняти.

according to the oauth2.0 spec we should return 401 in case of expiry token

**Comment by PavelVesnin** [comment]
```при "протуханні" access token.```  - I think it's about scopes, not expired token, because: 
``` у користувача немає доступу```

When token is expired, you need to refresh it, so 403 response code is valid code

**Comment by PavelVesnin** [comment]
from spec
```
invalid_token
         The access token provided is expired, revoked, malformed, or
         invalid for other reasons.  The resource SHOULD respond with
         the HTTP 401 (Unauthorized) status code. 
insufficient_scope
         The request requires higher privileges than provided by the
         access token.  The resource server SHOULD respond with the HTTP
         403 (Forbidden) status code.
```
In case expired token Gateway will response with 401 code and next body:
```
{
  "meta": {
    "url": "http://dev.ehealth.world/api/innms",
    "type": "object",
    "request_id": "51g4kc6qldk3or4bbi7i3okjs3ggj0id",
    "code": 401
  },
  "error": {
    "type": "access_denied",
    "message": "Token expired or client approval was revoked."
  }
}
```
In case invalid scope Gateway will response with code 403 and next body:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/innms",
        "type": "object",
        "request_id": "h52eq0e4qcuc78lmekpgkg3q6tu9pf2e",
        "code": 403
    },
    "error": {
        "type": "access_denied",
        "message": "Your scope does not allow to access this resource. Missing allowances: innm:write"
    }
}
```
