### ISSUE TITLE
auth is broken in prod!

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1467]
auth is broken

> 13:28:53 0|server   | {"message":"page render error Cannot read property 'POSITION' of null TypeError: Cannot read property 'POSITION' of null\n    at getEntity (/opt/app/node_modules/normalizr/dist/src/index.js:106:96)\n    at /opt/app/node_modules/normalizr/dist/src/index.js:116:18\n    at EntitySchema.denormalize (/opt/app/node_modules/normalizr/dist/src/schemas/Entity.js:99:20)\n    at unvisit (/opt/app/node_modules/normalizr/dist/src/index.js:98:17)\n    at denormalize (/opt/app/node_modules/normalizr/dist/src/index.js:139:10)\n    at y (/opt/app/static/server.js:1:6043)\n    at /opt/app/static/server.js:1:15316\n    at Connect.configureFinalMapState (/opt/app/node_modules/react-redux/lib/components/connect.js:154:27)\n    at Connect.computeStateProps (/opt/app/node_modules/react-redux/lib/components/connect.js:141:23)\n    at Connect.updateStatePropsIfNeeded (/opt/app/node_modules/react-redux/lib/components/connect.js:203:35)\n","timestamp":"2017-11-10T13:28:53.365Z","type":"out","process_id":0,"app_name":"server"}

**Comment by lymychp** [comment]
@pzhuk please provide any data for the investigation: request_id, user login, etc.

**Comment by pzhuk** [comment]
failing specificically for this invite
https://auth.ehealth-ukraine.org/invite?invite=0981eb5c-e9fe-4481-b1e0-7e5ac4a4034b

**Comment by danakonovalenko** [comment]
@ivchenkodima please take a look

**Comment by ivchenkodima** [comment]
@fixed
