### ISSUE TITLE
Gateway contains temp EP configs

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#1469]
```
Manage tokens on Mithril (temp)
Authorize app on Mithril (temp)
Manage users on Mithril (temp)
...
```
Some config allow to make [request](https://dev.ehealth.world/admin/users/e6edf5f6-42f0-4074-a8aa-2304e05c5651/roles) without token.

**Comment by lymychp** [comment]
# 1st priority
name                                 | TODO
-------------------------------------|-------------------------------------
/admin/apps                          | restrict
/admin/client_types                  | get
/admin/clients                       | get
/admin/roles                         | get
/admin/tokens                        | restrict
/admin/users                         | get

# 2nd priority
name                                 | TODO
-------------------------------------|-------------------------------------
/admin/users/_%                      | /oauth/users/_%
/admin/tokens/_%/verify              | /oauth/tokens/_%/verify
/admin/tokens/_%/user                | /oauth/tokens/_%/user
/admin/clients/_%/details            | /oauth/clients/_%/details
/admin/clients/_%/refresh_secret     | /oauth/clients/_%/refresh_secret
/api/credentials_recovery_requests%  | /oauth/credentials_recovery_requests%
/user/roles                          | /oauth/user/roles  
/users/%/actions/change_password     | /oauth/users/%/actions/change_password
/users/login                         | /oauth/users/login  
/oauth/apps/authorize                | ok
/oauth/tokens                        | ok
/reports/stats/division/_%           | /api/reports/stats/division/_%
/reports/stats/histogram             | /api/reports/stats/histogram
/reports/stats/regions               | /api/reports/stats/regions
/reports/log                         | /api/reports/log
/reports/stats                       | /api/reports/stats
