### ISSUE TITLE
Move Скинути метод авторизації to separate page

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1470]
#1236 

* Create Menu Item "Скинути метод авторизації" (Page)

* Show on "Скинути метод авторизації" (Page):
    * Title - Скинути метод авторизації
    * Input - "Ідентифікатор людини" - type GUID. Validate GUID
    * Button - "Скинути метод авторизації"
* on button click:
    * Show confirmation Dialog
    * Invoke WS ([spec](http://docs.uaehealthapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/persons/reset-authentication-method))). Scope - `person:reset_authentication_method`
    * Show result as Dialog

* Remove Button "Скинути метод авторизації" from "Declaration details" page

**Comment by svetavedmed** [comment]
GUID should be validated. 
 - In case GUID is not valid, input field should be framed in red with correct message
- In case GUID doesn't exist in DB the massage "Обліковий запис не знайдено" should be shown.
