### ISSUE TITLE
Investigate kong as new gateway application

### ISSUE THREAD

**Issue by Troush** [edenlabllc/ehealth.api#1474]
Can we move from annon to kong?
Which features we need from kong?
How we can implement caching with kong vs. with annon?

**Comment by AlexKovalevych** [comment]
1. Yes, i think we can. Mithril plugin required to:
- validate token (already done)
- resolve scopes (not done)
3. There is enterprise plugin for proxy caching and free plugin for cache into redis: https://github.com/wshirey/kong-plugin-response-cache . I think its possible to change plugin to use a different storage, if its needed of course.

**Comment by AlexKovalevych** [comment]
Need to test for correct response if some entity is not found (Ecto.NoResultsError raised) - should be 404 status code
