### ISSUE TITLE
Deploy to demo - Sprint 14

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1475]
- [x] define required versions of repo to the destination env.
  - [x] IL and all others - master. Previous version on demo: 0.5.141
  - [x] auth.api - **0.1.128**
- [x] apply the required versions of repo to the destination env.
  - [x] ehealth.api
  - [x] prm.api
  - [x] mpi.api
  - [x] annon
  - [x] ael_api
  ~~- [ ] digital_signature_api~~
  ~~- [ ] man_api~~
  - [x] mithril_api
  - [x] ops
  - [x] uaddresses
  - [x] otp_verification_api
  - [x] nhs.auth.web
  - [x] nhs.portal.web - TBD
  - [x] nhs.admin.web -TBD
  ~~- [ ] man.web~~
  - [x] uaddresses.web - TBD
- [ ] IL.dictionaries - add/update if any. IDs should be the same.
- [ ] PRM.global_parameters - add/update if any. IDs should be the same
- [ ] uaddresses - add/update records if any. IDs should be the same
- [ ] GW.apis - migrate config
  - [ ] GW.apis - Exclude temp dev routes
- [ ] GW.plugins
- [ ] Mithril config
  - [ ] client_types - add/update if any changes.
  - [ ] roles - add/update if any changes.
  - [ ] user_roles - for admin fronts
  - [ ] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [ ] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [ ] approvals - generate or copy MIS approvals
- [ ] man templates - add/update if any. IDs should be the same
- ~~[ ] DS - migrate certificates - no need~~

_____
**Release notes:**
* reimbursement
  * bug fixing and improvements
* fraud db replication
* Ehealth 1251 parties verifications (#1353)
* 1250 divisions verifications (#1347)
* fix LE verifications: addresees, phones(#1249)
* Ehealth 1233 Declaration Verification: arrays, addresses, phones (#1301)
* Add Refresh secret API
* В getDeclarationByID не повертаються дані по опікуну і emergency contact (#1208)
* check is user blacklisted on new employee_request creation (#1391)
* MIS authorization (#214)
* make region optional in List Of Districts By Search Params #1330
* [Declaration request] Replace Gandalf call with hardcoded logic #1311
* wrong db migration for il.declaration_requests field :printout_content #1148
* OTP SMS delivery metrics #1333
* Update "updated_at" after auto approve and auto terminate #1288
* Capitation Report Changes #1302
* [Capitation report] Exclude inactive red msps from report #1443
* В getDeclarationByID не повертаються дані по опікуну і emergency contact #1208
* Review and create db indexes #1089
* make documents a unique list on create declaration (#1411) - hotfix
* add logging to all microservices calls (#1298)
* removed danger default values from config (#1007)
* HTTP 500 responses on prod #1436
* NHS admin
  * Block/Unblock users NHS admin portal #1273
  * [Admin] Reset MPI authorization method via admin console #72
  * preprod admin portal is not showing attachments #1365
* UAddressesd
  * new pagination
* Mithrill admin
  * Block/Unblock MSPs Mithril admin portal #1276
  * new pagination
* Uaddresses admin 
  * new pagination applied
* GW
  * save logs to google stackdriver instead of db 
* auth
  * auth page returns all dictionaries in js element #1326

**Comment by gmile** [comment]
As a one-time action, Swift storage must be configured. See https://github.com/edenlabllc/ehealth.api/issues/1309#issuecomment-343883994

**Comment by lymychp** [comment]
@pzhuk please approve

**Comment by vsirius** [comment]
done
