### ISSUE TITLE
audit log for medications

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1482]
As a NHS I want all the changes which is related to medications tables to be logged in the prm.audit_log table. 
add trigger on next tables (save logs for all updates)
- [x] innms
- [x] medications
- [x] medical_programs
- [x] program_medications

**Comment by Troush** [comment]
- [ ] Review all audit logs
- [ ] Investigate postgres triggers

**Comment by ybod** [comment]
Additional audit log for: `PartyUsers: Create`, `BlackListUsers: Create, Deactivate`, `Parties: Create, Update`

_Investigate: **Divisions - do_update_divisions_mountain_group**_
