### ISSUE TITLE
deduplication issue in MPI

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1499]
Environment : Pre-prod

Data:
select * from persons where id='615ef2a2-7a98-49e3-903c-d545b32eb946' or id='3e593b0c-fa91-4935-a6d1-31ebce0f0ea3'

Both persons has all the same data except  second name and address
Current state - deduplication didn't happened, no any merge_candidate records found as well

Expected result: person records should be merged

**Comment by lymychp** [comment]
related to #1365

**Comment by pzhuk** [comment]
@kmakarenko  we need a decision here
