### ISSUE TITLE
eHealth portal (mobile version) issue 1

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1502]
go to http://portal.demo.ehealth.world/ --> головна сторінка
Перегляд сайту був через iphone 6, браузер safari
Там де документи - є дві кнопки (сині точки) для перемикання між вкладками з документами
Проблема: кнопки погано натискаються (треба масштабувати зображення)
Що очікується: збільшити кнопки для більш зручного перемикання
![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/32056656/32893286-921881d4-cae1-11e7-9e63-3b1031e81ac4.png)

**Comment by lymychp** [comment]
fixed
