### ISSUE TITLE
eHealth portal (mobile version) issue 2

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1503]
1. Go to http://portal.demo.ehealth.world/ --> Долучитися
2. Спочатку треба зайти на головну сторінку --> розділ "долучитися" --> потім знову на головну --> знову розділ "долучитися"
Проблема: сповзає кнопка "Долучитись до eHealth"
Перегляд сайту був через iphone 6, браузер safari
![image_uploaded_from_ios_1024-1](https://user-images.githubusercontent.com/32056656/32893574-b8704366-cae2-11e7-8aff-7ff3c2fe35d8.png)

**Comment by lymychp** [comment]
fixed
