### ISSUE TITLE
Reimbursement Report NHS admin (FE)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1504]
NHS admin must be able to download the file in csv format (with headers) and receive information about dispenses and requests. In order to be able to do that we need to have new page "Звіт" on NHS admin portal in paragraph "Рецепти". The page must have two fields for dates (Початкова дата/Кінцева дата) and the button Download.
[requirements](https://edenlab.atlassian.net/wiki/x/A4DTCQ)

**Comment by LehaMotovilov** [comment]
Done. You can check it here: http://admin.dev.ehealth.world/
