### ISSUE TITLE
New code style

### ISSUE THREAD

**Issue by LehaMotovilov** [edenlabllc/ehealth.api#1507]
We need to apply new code style (default [Prettier](https://prettier.io/)) to repositories:

- [x] https://github.com/edenlabllc/nhs.admin.web
- [ ] https://github.com/edenlabllc/mithril.web
- [ ] https://github.com/edenlabllc/uaddresses.web
- [ ] https://github.com/edenlabllc/nhs.auth.web
- [ ] https://github.com/edenlabllc/nhs.portal.web

**Comment by kiurchv** [comment]
New code style will be applied in the process of codebase migration to `ehealth.web` repo. Closing the issue as obsolete.
