### ISSUE TITLE
Event Manager

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1525]
As a MIS I want to monitor changes of different statuses So that should be done new DB in order to reduce database load.
[apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-event-manager)
*BE*
- [x] Create EventDB [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/179994845/Event+Manager)
- [x] Get EventDB list
- [x] Get EventDB by ID
- [x] Event Autotermination
- [x] Get new employee request [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1055374/IL.Get+Employee+Request+by+ID)
- [x] Get employee request [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/184778974/IL.+Get+new+employee+request+by+ID)

*FE*
- [x] Use new EP for New users #1565

**Comment by svetavedmed** [comment]
- [ ] #1595 Change `properties` in event_manager
- [ ] add filters
- [ ] change id i event_manager to uuid

**Comment by pzhuk** [comment]
can we have a distionary with even types?
