### ISSUE TITLE
Змінити назву "Клініки" на "Медичні заклади" в адмінці ehealth

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1527]
Адмінка ehealth на dev середовищі.
Зліва є перелік розділів.
Змінити назву "Клініки" на "Медичні заклади".

**Comment by svetavedmed** [comment]
![Screen Shot 2017-12-28 at 14.12.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fb6b7191a379eb0c2a53415b4ebe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf24de24c5dac103467f43b.png)
