### ISSUE TITLE
Make sure system ID is valid

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#1528]
In OPS we have a system user:

https://github.com/edenlabllc/ops.api/blob/master/config/config.exs#L53-L55

However it is not reflected in [configs](https://github.com/edenlabllc/ehealth.charts) anywhere, meaning the system user will be the same across all envs.

This should be made consistent.

In this task:

1. make sure each env has its own system user registered in the DB,
2. make sure a config for each env reflects a respective system user's ID.

**Comment by ybod** [comment]
https://github.com/edenlabllc/mithril.api/pull/213

**Comment by ybod** [comment]
I' not sure that moving System User ID from configuration files into Charts system variables can greatly improve security or consistency of related projects.
