### ISSUE TITLE
uaddresses settlements UI is broken on demo

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1529]
Environment: Demo

URL : http://uaddresses.demo.ehealth.world/settlements

Expected result: viewing list of settlments
Current result: nothing happens, UI stuck

**Comment by lymychp** [comment]
+pagination

**Comment by lymychp** [comment]
related to #1531

**Comment by svetavedmed** [comment]
@kiurchv fixed on dev. Change, please, on demo.

**Comment by svetavedmed** [comment]
fixed on demo
