### ISSUE TITLE
uaddresses streets view - list of areas is broken

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1530]
Environment : demo

Steps to reproduce:
1. Open streets view on uaddresses UI http://uaddresses.demo.ehealth.world/streets/
2. Expand list of regions 

Expected result: see all regions
Current result: only part of regions is available, for example city of Kyiv is not avaialble
Broken pagination use?

![screenshot from 2017-11-24 11-03-52](https://user-images.githubusercontent.com/10362976/33202983-2fe072de-d107-11e7-8457-5c555f49756f.png)

**Comment by lymychp** [comment]
related to #1531

**Comment by svetavedmed** [comment]
@kiurchv fixed on dev. Change, please, on demo.

**Comment by svetavedmed** [comment]
fixed on demo
