### ISSUE TITLE
Apply new pagination for UAddresses admin

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1531]
related to #1240 

bugs
- [x] Search districts by area does not work with pagination
- [x] Reset page on the list of new district
- [x] Page also should be reset if list of district was reset

**Comment by svetavedmed** [comment]
1. street are not displayed
![Screen Shot 2017-12-14 at 18.36.23.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a379e70c2857415d4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf44de84956ac143365f43b.png)

2. link to documents does not work
#GET / + Response 404 (text/plain)  
 The API Project you have requested could not be found.

3. Search districts by area does not work with pagination.
the first page displays district of this region, but the second and others show all district in Ukraine
![Screen Shot 2017-12-14 at 18.14.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a379e70c2a55415d49be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95bf44de84554ad1a3064f43b.png)

4. Some city names are longer then the field.
![Screen Shot 2017-12-14 at 18.09.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a379e70c2b58415f46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c33aa984ec95bf44de8445dac133764f43b.png)

**Comment by svetavedmed** [comment]
2. if I watch districts filtered with region and with pages,  and then I change the region name I stay on the same page number. With new region page should be reset.

**Comment by svetavedmed** [comment]
3. Page also should be reset if list of district was reset
Steps to reproduce
- go to districts second page
http://uaddresses.dev.ehealth.world/districts?region_id=b392aad2-988b-4452-851c-766d48fc94c6&page=2
![Screen Shot 2017-12-18 at 11.48.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fb6b7191a379ee0c2f59415a46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf342e1445dad163064f43b.png)
- try to search regions without any filters
![Screen Shot 2017-12-18 at 11.48.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fb6b7191a379ee0c2f59415e4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95bf342e04d5da6133464f43b.png)
