### ISSUE TITLE
wrong response when digital signature is not verified

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1534]
Environment : prod (and preprod)
Test has been performed on preprod too

Steps to reproduce:
1. post a request where digital signature hasn't been verified(is_valid=false)

Expected result: Response saying that digital signature is not correct 
Actual result: Response saying that json is not correct! (even though json is correct)

Will not post full request, because of live sensitive data
Please, ping me in slack in order to get full request OR check gateway logs for this request id, please:

```
{
    "meta": {
        "url": "http://api.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "8eop71k78hsl6vjdfl3gtau8neh09g81",
        "code": 400
    },
    "error": {
        "type": "request_malformed",
        "message": "Signed request data is invalid",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]
    }
}

```

**Comment by ybod** [comment]
Should be fixed with last update - already deployed on Demo/Preprod

**Comment by AlekzandrV** [comment]
Please change response type for all digital signature failures

Return `"type": "digital_signature_invalid"` instead of `"type": "request_malformed"`
