### ISSUE TITLE
mithril / mithril admin - all the client has no any type

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1537]
Environment: tested on prod and demo

steps to reproduce

1. open mithril admin UI
2. go to client list and open any client (MSP or MIS for instance)
3. field client type is always empty

expected result: proper client type is displayed for a 
![screenshot from 2017-11-24 19-17-21](https://user-images.githubusercontent.com/10362976/33219644-1e611e42-d14c-11e7-803a-34213c5457c8.png)
client

**Comment by PavelVesnin** [comment]
@ivchenkodima you should call 
```/admin/clients/{client_id}/details``` instead of 
```/admin/clients/{client_id}```, 
than you will get in response field `client_type_name`

**Comment by svetavedmed** [comment]
fixed on demo
