### ISSUE TITLE
Реєстрація лікарів без ІПН

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1544]
Якщо лікар не має ІПН, то має існувати можливість позначити, що він не має ІПН (галочка), тоді замість ІПН вводиться серія та номер паспорту.

Такі лікарі отримують ЕЦП, очікується, що замість номеру ІПН, у них внесено серію і номер паспорту.

**Comment by danakonovalenko** [comment]
Update WS related to Employees without tax_id #1579
