### ISSUE TITLE
2FA: small fix "request factor" page

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1550]
- [x] Remove switching errors (login, pass) on "sign-in/login", "invite/login" pages
- [x] Add new attribute (2fa_enable) to call WS on Mithrill Create user page
- [x] Add hook errors on page "init /change factor"
- [x] Add RegExp  to field OTP (page "verify otp", "approve factor"
- [x] **optional wish** on-click "resend OTP" add animation effect (sending ....)
- [x] **optional wish** after click "resend OTP" disable button for 30 sec 
- [x] add hook 503 error on send OTP service
- [x] change button text `Зкинути фактор` -> `Скинути фактор` 
- [x] change question text in dialog `...зкинути фактор...` -> `..скинути фактор...`  
- [x] hide button "reset_factor" when `factor.is_active = false`

**Comment by EdwardVoloshin** [comment]
@ivchenkodima - Im add 2 subtask.

**Comment by EdwardVoloshin** [comment]
@ivchenkodima - Im add new 2 subtask.

**Comment by svetavedmed** [comment]
- [ ] no error on page http://auth.dev.ehealth.world/update-factor/
![Screen Shot 2017-12-18 at 16.25.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fb6b7191a379e90c2954415e4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95bf04be6455ca11a3460f43b.png)

**Comment by svetavedmed** [comment]
- [ ] Malformed request. Probably, you have sent corrupted JSON.
repo steps
- enter incorrect psw
- enter correct psw
![Screen Shot 2017-12-18 at 16.40.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fb6b7191a379e90c2f51415a4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf04be94f55ac113765f43b.png)

**Comment by svetavedmed** [comment]
- [ ] psw recovery error
user with psw svetavedmed+163@gmail.com exists
![Screen Shot 2017-12-18 at 17.47.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fb6b7191a379e80c2f56415f47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf04ae34c50ac123366f43b.png)
