### ISSUE TITLE
users w/o priv_settings can't log in to admin portal - error 500 (Demo)

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1553]
there are 8 users w/o priv settings on demo. And these users cant log in to admin portal.
![Screen Shot 2017-11-29 at 10.39.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fa6b7191a379ef0c2858415a46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec959ff4fe54551a414336af43b.png)
In order to perform this action you can use user with email svetavedmed+22@gmail.com
request 
```
{
   "token":{
      "grant_type":"password",
      "email":"svetavedmed+22@gmail.com",
      "password":"12345678",
      "client_id":"{{fe_client_id}}",
      "scope":"app:authorize"
   }
}
```
response
```
{"meta":{"url":"http://demo.ehealth.world/oauth/tokens","type":"object","request_id":"df94e7109bkkgs8tlfb5er740u21uq15","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```

**Comment by EdwardVoloshin** [comment]
Problem explored & fixed.
