### ISSUE TITLE
Implement Password Policy

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1556]
1. passwords should be at least 12 characters long;
2. passwords should contain both upper- and lowercase letters, numbers, and special characters;

* Also, implement password expiration period: enforce password change every 30 to 90 days. - to be decided (go/ not go)
* if password is expired - do not allow user to login untill new password is set, expiry all the refresh tokens
* do not allow to use 3 previously used passwords - save history

- [ ] #1625
- [ ] #1626

**Comment by danakonovalenko** [comment]
- [ ] Change Password #1686
- [ ] Password Policy FE #1641
