### ISSUE TITLE
Protection Against Password Brute Force Attack

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1557]
Attacked user accounts should be locked after a certain threshold of failed login attempts during a defined period of time. For example, lock the users that had 3 failed login attempts during the last 3 minutes.
unlock - automatic based on time

- core functionality. system should behave the same way even for not existing users
- unlock user via mithril admin

**Comment by AlexKovalevych** [comment]
@EdwardVoloshin please update specs according to new logic.

**Comment by danakonovalenko** [comment]
as for now the user after reaching maximum attempts is not blocked and can't be unlock via mithril admin. It's not allowed to enter the password for the next 10 min and unlock automatically based on time

**Comment by EdwardVoloshin** [comment]
Specs updated:
https://edenlab.atlassian.net/wiki/x/aAAZCQ
