### ISSUE TITLE
on-premise SWIFT set up

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1561]
As a NHS administrator
I want to not be dependent on the 3rd party file storage service
So that I can deploy eHealth system on any DC

**Comment by gmile** [comment]
Added `minio` to dev cluster:

```
kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
coy-chinchilla-minio-0     1/1       Running   0          8d
coy-chinchilla-minio-1     1/1       Running   0          8d
coy-chinchilla-minio-2     1/1       Running   1          8d
coy-chinchilla-minio-3     1/1       Running   1          8d
```

**Comment by pzhuk** [comment]
awesome!
(what are requirements to the hard drives?)

BR, Pavel V. Zhuk


2017-12-07 11:17 GMT+02:00 Eugene Pirogov <notifications@github.com>:

**Comment by gmile** [comment]
@pzhuk right now there are no specifics or particular requirements posed by Minio that must be satisfied. Regular persistent volumes provided by Google worked out of the box.

Though in future, we might do additional work to tie vendor-specific hard drives to Minio.

One good out-of-the box feature of Minio is that is has the so-called "distributed mode", in which it mirrors the data between disks automatically:
* we've provided it with four 10Gb hard drives,
* minio exposes 20Gb of actual storage, while hiding 20Gb for data mirroring.

**Comment by gmile** [comment]
FYI, more about minio:
* https://techcrunch.com/2017/09/19/minio-scores-20-million-series-a-to-build-a-neutral-object-storage-layer/
* https://minio.io
* official Google Cloud block promotes it https://medium.com/google-cloud/build-aws-s3-compatible-cloud-storage-on-gcp-with-minio-and-kubernetes-2adc0a367f98
