### ISSUE TITLE
ael adapter for new SWIFT

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1562]
blocked by #1561

**Comment by gmile** [comment]
Done in https://github.com/edenlabllc/ael.api/pull/8

**Comment by gmile** [comment]
What needs to be tested manually:

1. CORS (ability to upload files from browser),
2. Bucket-level ACL – ability to expose certain buckets publicly (e.g. a public person, having a direct link, should be able to download a report).
