### ISSUE TITLE
Deployment to prod

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1566]
related to #1524 
    
**Preparation :**
- [x] Stop traffic to a cluster 
- [x] Backup databases
- [x] Update a kubernetes cluster to 1.8.3-gke.0
- [x] Stop logical replication on reports
- [x] Delete pvc block-db (ops)

**Deployment:**
- [x] define required versions of repo to the destination env.
  * master: 
- [x] apply the required versions of repo to the destination env.
  - [x] ehealth.api
  - [x] fraud
  - [x] prm.api
  - [x] mpi.api
  - [x] annon
  - [x] ael_api
  - [x] digital_signature_api
  - [x] man_api
  - [x] mithril_api
  - [x] ops
  - [x] uaddresses
  - [x] otp_verification_api
  - [x] nhs.auth.web
  - [x] nhs.portal.web - TBD
  - [x] nhs.admin.web -TBD
  ~~- [ ] man.web~~
  - [x] uaddresses.web - TBD
- [x] IL.dictionaries - add/update if any. IDs should be the same.
- [x] PRM.global_parameters - add/update if any. IDs should be the same
- [x] uaddresses - add/update records if any. IDs should be the same
- [x] GW.apis - migrate config
  - [x] GW.apis - Exclude temp dev routes
- [x] GW.plugins
- [x] Mithril config
  - [x] client_types - add/update if any changes.
  - [x] roles - add/update if any changes.
  - [x] user_roles - for admin fronts
  - [x] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [x] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [x] approvals - generate or copy MIS approvals
- [x] man templates - add/update if any. IDs should be the same
- ~~[ ] DS - migrate certificates - no need~~
 
**Additionally steps**
- [x]  Run Import  streets@uadresses from report_public_bk_tmp_streets.csv 
- [x] Restart reports logical replication
- [x] Start fraud logical replication
- [x] Check migration
- [x] Check monitoring metrics
 

- [x] migration objects migration scripts #1445 
_____
**Release notes:**
* reimbursement
  * bug fixing and improvements
* fraud db replication
* Ehealth 1251 parties verifications (#1353)
* 1250 divisions verifications (#1347)
* fix LE verifications: addresees, phones(#1249)
* Ehealth 1233 Declaration Verification: arrays, addresses, phones (#1301)
* Add Refresh secret API
* В getDeclarationByID не повертаються дані по опікуну і emergency contact (#1208)
* check is user blacklisted on new employee_request creation (#1391)
* MIS authorization (#214)
* make region optional in List Of Districts By Search Params #1330
* [Declaration request] Replace Gandalf call with hardcoded logic #1311
* wrong db migration for il.declaration_requests field :printout_content #1148
* OTP SMS delivery metrics #1333
* Update "updated_at" after auto approve and auto terminate #1288
* Capitation Report Changes #1302
* [Capitation report] Exclude inactive red msps from report #1443
* В getDeclarationByID не повертаються дані по опікуну і emergency contact #1208
* Review and create db indexes #1089
* make documents a unique list on create declaration (#1411) - hotfix
* add logging to all microservices calls (#1298)
* removed danger default values from config (#1007)
* HTTP 500 responses on prod #1436
* NHS admin
  * Block/Unblock users NHS admin portal #1273
  * [Admin] Reset MPI authorization method via admin console #72
  * preprod admin portal is not showing attachments #1365
* UAddressesd
  * new pagination
* Mithrill admin
  * Block/Unblock MSPs Mithril admin portal #1276
  * new pagination
* Uaddresses admin 
  * new pagination applied
* GW
  * save logs to google stackdriver instead of db 
* auth
  * auth page returns all dictionaries in js element #1326 
* NHS portal
  * reimbursement stats
___
Sprint 15
* OTP SMS delivery metrics #986
* Portal mobile version #1228
* 2-factor authentication (disabled)  #1319
* Fix redirect loops issue with cloudflare #1390
* audit log for medications #1482
* mithril.admin: Modify "user-details" page #1491
* GW tuning (replace DB with elasticsearch/kibana) - https://github.com/edenlabllc/ehealth.charts/issues/29

**Comment by gmile** [comment]
- [x] create missing buckets:
  * medication-request-requests

**Comment by gmile** [comment]
I've marked all items in my comment as complete. Closing this.

**Comment by pzhuk** [comment]
good job, thanks a lot

BR, Pavel V. Zhuk


2017-12-07 12:48 GMT+02:00 Eugene Pirogov <notifications@github.com>:
