### ISSUE TITLE
 Sign Declaration (no_tax_id)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1575]
Employee without tax_id must be able to Sign Declaration. Field 'drfo' in certificate can contain either tax_id or passport number and be compared to employee tax_id

**Comment by PavelVesnin** [comment]
@danakonovalenko done

**Comment by danakonovalenko** [comment]
We need to trim drfo received in headers and compare it with tax_id in declaration.
So if we receive `drfo=АА 111111` it should match `tax_id=AA111111`. 
As for now we have an error: `"Does not match the signer drfo"`

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed
