### ISSUE TITLE
Неможливо зареєструвати пацієнта з номером будинку 1020

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1580]
при заповнені декларації не пропускає  пацієнта номер будинку 1020 . 
Відповідь
Не вірний формат номер будинку. Можливі формати: 25, 30А, 52-Б

**Comment by pzhuk** [comment]
yepp, it looks like our regex schema does't allow building with numbers larger than 3 digits
https://github.com/edenlabllc/ehealth.api/blob/015ba8c1098fc7dfd6286cee28cebb61c57e1001/specs/json_schemas/declaration_request/declaration_request_create_request.json#L68

**Comment by lymychp** [comment]
@svetavedmed we should adjust regexp validation and allow 4 digits

**Comment by svetavedmed** [comment]
fixed on dev
