### ISSUE TITLE
Update Employee request list and Employee request by id

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1583]
1. NHS admin must be able to view employees which registered without tax_id. According to this Employee Request list must be changed and additional filters should be added [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-requests-list):
- by edrpou
- by legal entity name
- by no_tax_id flag
- by employee_request_id
2. Update Get employee Request by ID [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-request-by-id)

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed

**Comment by danakonovalenko** [comment]
search by edrpou, legal_entity_name and employee_request_id doesn't work

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed
