### ISSUE TITLE
rotate sms lifecell password

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1584]
We need to rotate lifecell password
sending details to @lymychp

**Comment by gmile** [comment]
This done & deployed – https://github.com/edenlabllc/ehealth.charts/commit/ef15f0db2b86f171bcd8f77dbe6c182d828be2d2

**Comment by pzhuk** [comment]
thanks!

BR, Pavel V. Zhuk


2017-12-04 14:02 GMT+02:00 Eugene Pirogov <notifications@github.com>:
