### ISSUE TITLE
demo/dev/preprod postmark is out of credits

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1586]
Someone has triggered large amount of calls to dev postmark so we are out of credits now
All calls seems to be done to sp.virny+206@gmail.com

can you pls investigate who was doing that? tnx

**Comment by lymychp** [comment]
this is the result of the performance tests

**Comment by pzhuk** [comment]
that's not nice :(

BR, Pavel V. Zhuk


2017-12-04 23:40 GMT+02:00 lymychp <notifications@github.com>:
