### ISSUE TITLE
Restrict access to APIs for requests that uses token "name": "authorization_code"

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1593]
Restrict access to APIs for requests that uses token "name": "authorization_code"

**Comment by EdwardVoloshin** [comment]
@PavelVesnin - with token `M2RhcHEvc3BTaVdqZGZDNEk4cUlLdz09` (expired to 2017/12/28, token name = `authorization_code`) am successful call APIs. Need restrict.
test curl get legal_entity - now return 200
`curl -X GET \
  https://dev.ehealth.world/api/legal_entities \
  -H 'api-key: Z09EWXlGTkZnT05saVVZT0RBWDhudz09' \
  -H 'authorization: Bearer M2RhcHEvc3BTaVdqZGZDNEk4cUlLdz09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 1e43c228-d184-693b-b22b-c1d1ca5175ca'
`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
Tested successful manually with postman for 2 cases: 2FA enable & 2FA disable.
