### ISSUE TITLE
request logging metadata

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1597]
As a system administrator of ehealth cluster I would like to analyze gateway logs from a performance standoint
I want current logging metadata to include endpoint url (only defined one) or controller name  
So that I could build a chart on it

Currently, phoenix.path is logging full url, so in case of GET request it will look like for example: /api/declaration_requests/c5d5c9d0-0b6a-448c-bcb6-d20dd3194711

In the same time, I would like to analyze only /api/declaration_requests since it's the endpoint location name. Would that be possible in any way?

@gmile appreciate your advice here

Tnx

**Comment by gmile** [comment]
Use `phoenix.handler` to filter desired requests:

![image](https://user-images.githubusercontent.com/207112/33660299-0ebd413e-da8c-11e7-9fb3-f48143d61f88.png)
