### ISSUE TITLE
admin isn't showing blocked users

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1602]
Env: prod

How to repro: https://admin.ehealth-ukraine.org/black-list-users?id=&page=1

Expected result: 
1) list of users who are blocked
2) able to find user by id

Actual result: no any users displayed and can't find user even though it's blocked
For example: '32d01b3c-7c54-4dcb-88a6-c7e2196cd28f'

**Comment by lymychp** [comment]
u should use mithril admin for this purpose.
NHS admin portal never supposed to provide this feature.
