### ISSUE TITLE
no any error displayed on fail to assign the role

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1607]
Env: prod
Application : mithril admin UI

How to proroduce:
- Go to user management
- Click "Add role"
- Try to add role which is already present for user

Expected result:  Some error or any notification displayed (success/unsuccess)
Current result: Nothing happens, just saving

**Comment by Troush** [comment]
@Troush create BE issue to this

**Comment by Troush** [comment]
- [ ] Handle BE Errors

**Comment by svetavedmed** [comment]
1. Редагування ролі
![Screen Shot 2017-12-21 at 17.14.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f26b7191a379e80c2a55415c46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bfe4de84e56ad123466f43b.png)

![Screen Shot 2017-12-21 at 17.16.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f26b7191a379e80c2a57415d46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bfe4de84951a01a3e6bf43b.png)

**Comment by svetavedmed** [comment]
2. Створити токен
http://mithril.dev.ehealth.world/tokens/create
![Screen Shot 2017-12-21 at 17.45.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f26b7191a379e80c2f54415e46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95bfe4ce04c52a0103167f43b.png)
