### ISSUE TITLE
spacing problem when concatenating strings at nhs portal

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1615]
When working with NHS portal I noticed a lot of wrongly concatenated strings (mostly in employees review) https://admin/employees
Screenshot attached
![screenshot from 2017-12-08 15-38-42](https://user-images.githubusercontent.com/10362976/33768262-020b386c-dc2e-11e7-8869-b9b1561c8649.png)

**Comment by danakonovalenko** [comment]
still same mistake
