### ISSUE TITLE
not possible to edit MSP client in mithril admin

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1623]
Env: demo

steps to reproduce:
* open client management in mithril admin 
* find any MSP client ( for example http://mithril.demo.ehealth.world/clients/879d1c9a-1e59-46bf-8dad-75f625d32c5b)

Try to edit, for example - try to change redirect URI

expected result: possible to edit
current result: not possible to edit, because :
a) the client type is not set (even though it should be MSP!)
b) the user id is required?

**Comment by svetavedmed** [comment]
done
