### ISSUE TITLE
Add new filters to `Search Divisions`

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1627]
- [x] Add new filters to `Search Divisions`
region_name
district_name
settlement_name
edrpou - legal_entity edrpou
legal_entity_id

- [x] Change response for `Search Divisions`
add legal entity information

[Apiary](https://uaehealthapi.docs.apiary.io/#reference/internal.-portal-and-reports/divisions/search-divisions)
[specs](https://edenlab.atlassian.net/wiki/spaces/EH/pages/235667482/Search+Legal+Entities)

**Comment by PavelVesnin** [comment]
@svetavedmed deployed
