### ISSUE TITLE
Change employee update emails

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1637]
Поточна реалізація:
При створенні запису співробітника та оновлення інформації про співробітника надсилається однаковий e-mail.

Цільова реалізація:
При створенні запису співробітника та оновлення інформації про співробітника надсилаються різні листи e-mail. Текст листа на оновлення буде надано проектним офісом.

**Comment by danakonovalenko** [comment]
@kmakarenko Я правильно розумію, що посилання в листі лишається таким як і було, параметри такі ж. Змінюється лише текст. Підтверди це, будь ласка

**Comment by kmakarenko** [comment]
Так, підтверджую

**Comment by goutsalova** [comment]
Новий текст:

Вітаємо!

Ви внесли зміни до профілю лікаря закладу "________", зареєстрованого в системі eHealth.
Для підтвердження цих змін, будь ласка, перейдіть за посиланням: ______________

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, update email text

**Comment by danakonovalenko** [comment]
- Change employee update text in emails #1695

**Comment by ivchenkodima** [comment]
done `templates/7`
