### ISSUE TITLE
auth frontend is not utilizing SPEC_QUALIFICATION_TYPE

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1645]
1 register employee and get invite
2 follow the link to accept invite
3 check details

we could see "Тип кваліфікації: DEFENSE"
expected "Тип кваліфікації: Підтвердження"

![screenshot from 2017-12-15 10-53-28](https://user-images.githubusercontent.com/10362976/34034227-3e30a374-e186-11e7-8e97-97c3aa9e047d.png)

**Comment by svetavedmed** [comment]
Done on dev. Change, please, on Demo.
