### ISSUE TITLE
Mithril Error Handling

### ISSUE THREAD

**Issue by Troush** [edenlabllc/ehealth.api#1654]
All forms and pages must show BE errors

- [x]  try to create role for user that is already exists
![Screen Shot 2017-12-29 at 17.53.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2e52415d4bbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf34de34556a6163266f43b.png)

- [x] ![Screen Shot 2017-12-29 at 17.07.33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2b56415c4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95cf34de04853a7153463f43b.png)

- [x] ![Screen Shot 2017-12-29 at 17.08.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2b59415d47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf34de04852a3173e62f43b.png)

- [x] ![Screen Shot 2017-12-29 at 17.13.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2a52415a47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95cf34de0485ca4113164f43b.png)

- [x] translate to Ukr all pop-up's buttons
![Screen Shot 2017-12-29 at 18.06.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e70c2b57415f4ebe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95cf34de24852ad103760f43b.png)

**Comment by svetavedmed** [comment]
- [ ]
![Screen Shot 2017-12-29 at 16.53.12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e90c2e52415e4cbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf34de04e51a617376bf43b.png)

- [ ]
![Screen Shot 2017-12-29 at 16.57.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e90c2e56415d48be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95cf34de04e53a2143162f43b.png)

- [ ]
![Screen Shot 2017-12-29 at 16.57.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e90c2e56415b4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95cf34de04e5da51a3f67f43b.png)

- [ ]
![Screen Shot 2017-12-29 at 16.59.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e90c2e58415d4cbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf34de04e5ca3153661f43b.png)

- [ ]
![Screen Shot 2017-12-29 at 17.00.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2b51415f49be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf34de04957a6123f6af43b.png)

- [ ]
![Screen Shot 2017-12-29 at 17.01.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456fa6b7191a379e80c2b50415e4ebe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95cf34de04956ac153666f43b.png)
