### ISSUE TITLE
Scopes of HR and ADMIN are the same on prod

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1659]
Currently scopes of HR and ADMIN on prod are the same.
However they should correspond to scopes in the Dictionaries table: https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit#gid=288335354

**Comment by pzhuk** [comment]
duplicate https://github.com/edenlabllc/ehealth.api/issues/1601
