### ISSUE TITLE
Move all the DB insert/update scripts to migrations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1661]
As a PO
I want the deployment process to not require ay manual DB scripts executios
So that I wouldn't face with the data inconsistency after deployment. For example, new roles creation, existing roles scopes update, global parameters, etc.

**Comment by gmile** [comment]
Do you want to move EXISTING scripts? This would be a one-time task:

* any existing data script would have to be re-written to check:
    * if the data to be inserted already exists, then either (we need to decide this):
        * **skip** inserting new record or
        * **update** existing record with whatever is in data script,
    * if the data to be inserted does not exist yet:
        * **insert** it.
* put such script into migration.

After this one-time event, we will have a strict rule among developers to ALWAYS put any data migration (including addition of vital fixtures) during development cycle.

Does this sound good? If yes, what do you think about skipping or updating existing records?

**Comment by lymychp** [comment]
Yes, it sounds good.
If data exists, we should update.

**Comment by gmile** [comment]
First part, Mithril, landed – https://github.com/edenlabllc/mithril.api/pull/201

I've added a basic code infrastructure for listing scopes. A list of scopes can now be easily reviewed & edited since they are stored in text files.

**Comment by gmile** [comment]
I checked regarding the second part I planned, e.g. dictionaries. It is already there – https://github.com/edenlabllc/ehealth.api/pull/1281.

It looks like we can close this one. Please re-open if I missed any fixtures that we're managing manually.
