### ISSUE TITLE
migration for user:unblock scope is missed on mithril 

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1671]
Env: preprod

As a NHS admin I tried to unblock user and failed to do so because `user:unblock` was missed for my user.
So I went to user settings and added scope 

After that - I've failed to login, because my client ('eHealth Demo Mithril Admin') has no this scope allowed.
Fixed with manual database update which includes `user:unblock` scope

`update client_types set scope='app:read app:write app:delete token:read token:write token:delete user:read user:write user:delete user:unblock role:read role:write role:delete client_type:read client_type:write client_type:delete client:read client:write client:delete  medication_dispense:write medication_dispense:read' where id='073cf1a0-6766-46a6-a879-2b2f9533483f'
`
I beilive  migration for this scope is missed, which has to update all existing NHS admin users, and NHS admin clients to add this role

**Comment by svetavedmed** [comment]
According to this document https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit#gid=288335354
only Mithril Admin has scope to block and unblock users.
