### ISSUE TITLE
Errors on mithril admin portal. BE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1675]
1. 500 with no valid data
http://mithril.dev.ehealth.world/tokens/create
response
```
{"meta":{"url":"http://api-svc.mithril/admin/tokens","type":"object","request_id":"a5793e90-9348-4770-9adc-1b8b03fe5cdb#1042","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```
2. 500 error on creating client type that is already exists  
Створити тип клієнта - http://mithril.dev.ehealth.world/client_types/create
response
```
{"meta":{"url":"http://api-svc.mithril/admin/client_types","type":"object","request_id":"6d208f24-f748-48a4-b80b-62048067e493#716","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```
3. ? can not create new client
http://mithril.dev.ehealth.world/clients/create
<img width="1440" alt="screen shot 2017-12-21 at 17 42 00" src="https://user-images.githubusercontent.com/30794602/34262919-66963df2-e676-11e7-92b5-6edd53969fff.png">

**Comment by ivchenkodima** [comment]
3 case is dipplicates https://github.com/edenlabllc/ehealth.api/issues/1537
