### ISSUE TITLE
mithril  - creating a client with wrong redirect_uri doesn't display an error

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1677]
Env: preprod

How to repro:

go to the mithril admin and try to create a client without prefixing https://

Current result: nothing happens after clicking Save button
Expected result: proper error is raised

**Comment by lymychp** [comment]
@svetavedmed it should be fixed by ticket #1654

**Comment by svetavedmed** [comment]
fixed on dev

**Comment by svetavedmed** [comment]
<img width="1440" alt="screen shot 2018-01-18 at 11 59 19" src="https://user-images.githubusercontent.com/30794602/35092941-8cb92d76-fc49-11e7-888b-f5fd4b015b58.png">

**Comment by svetavedmed** [comment]
![Screen Shot 2018-02-02 at 10.11.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f16b7191a379ef0c2a50415d47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95ff34ee84c54a2153661f43b.png)

**Comment by svetavedmed** [comment]
fixed on dev
