### ISSUE TITLE
mithril - unable to create new client: access_type required

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1678]
Env: preprod

Steps to reproduce: try to add new client

Expected result: client create

Current result: client creation failure, because access_type required

`{"meta":{"url":"http://api.ehealth.world/admin/clients","type":"object","request_id":"bdh9h4krk2005bssf9bgvocgh8jqsg4f","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":null,"params":[],"description":"access_type required."}],"entry_type":"json_data_property","entry":"$.priv_settings"}]}}`

**Comment by svetavedmed** [comment]
should add settings and priv_settings to request.
[spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/59637801/MIS+authorization)
actual request
```
{"client":{
	"settings":{},
	"priv_settings":{},
	"name":"dfdfd",
	"redirect_uri":"http://api-svc.mithril",
	"user_id":"b4abddea-49d8-4c1f-ae1b-5bb18cd3fa2c",
	"client_type_id":"aa484ff5-0fdc-4236-9069-1a1782629e52"
	}
}
```

**Comment by svetavedmed** [comment]
done on preprod
