### ISSUE TITLE
mithril - token creation requires UUID but it actuall not required

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1679]
Env: preprod

Steps to reproduce: Try to create new token

Current result: UI requires to enter ID (UUID), which actually is not used after creation, because its generated by backend

Expected result: UUID entering should NOT be required

**Comment by svetavedmed** [comment]
Can reproduce on dev. ID is not necessary on back, so we need changes on front only.
- remove UUID field on create

**Comment by ivchenkodima** [comment]
deployed to dev
