### ISSUE TITLE
Malformed request during log in. Error 400

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1684]
Malformed request. Probably, you have sent corrupted JSON.
repo steps

- enter incorrect psw
<img width="1440" alt="screen shot 2017-12-22 at 16 46 58" src="https://user-images.githubusercontent.com/30794602/34302017-bdee07e4-e737-11e7-9fe7-53c007254194.png">

response ```{"meta":{"url":"http://api-svc.mithril/oauth/tokens","type":"object","request_id":"6d208f24-f748-48a4-b80b-62048067e493#1086","code":401},"error":{"type":"access_denied","message":"Identity, password combination is wrong."}}```

- enter correct psw
<img width="1440" alt="screen shot 2017-12-22 at 16 47 45" src="https://user-images.githubusercontent.com/30794602/34302043-dadb4f10-e737-11e7-8317-636384e3ecea.png">

response ```{"meta":{"url":"http://api-svc.mithril/oauth/tokens","type":"object","request_id":"6d208f24-f748-48a4-b80b-62048067e493#1105","code":400},"error":{"type":"request_malformed","message":"Malformed request. Probably, you have sent corrupted JSON.","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}```

**Comment by ivchenkodima** [comment]
curl -X POST \
  https://dev.ehealth.world/oauth/tokens \
  -H 'authorization: e4269fb2-061b-0093-3026-038684afb7ef' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 1868570f-8800-f971-2a92-2ee8547c8477' \
  -d '{
  "token": {
    "grant_type": "password",
    "email": "edward.test2Fa.eden@gmail.com",
    "password": "12345678",
    "client_id": "e2e1d2c8-9bac-43c6-adef-83239940b30a",
    "scope": "app:authorize"
  }
}'
