### ISSUE TITLE
Add new MIS on portal

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1691]
Go to: https://portal.ehealth-ukraine.org/providers.html
Add MIS МЕДЕЙР: 

**Функції в системі eHealth**
Реєстрація закладів, лікарів, декларацій

**Про МІС**
**МедЕйр** – повнофункціональна МІС розроблена українськими розробниками для лікарів.
Ми знаємо що потрібно лікарям та впевнено втілюємо їх побажання в реальність.
Особливу увагу ми приділяємо захисту інформації та відповідності національним та міжнародним стандартам.
Компанія «Ілайф» є лідером з впровадження МІС на ринку України.
МІС «МедЕйр» впроваджений в більше, ніж 1000 медичних установах, кількість користувачів перевищує 5000.

**Технічні вимоги**
Процесор: 2-3 ГГц Core i3+
ОЗУ: 2-4 Гб +
ЖД: 2-10 Гб +
ОС: MS Windows XP SP3 та вище 

ТОВ «Ілайф»
+38-044-353-01-39
contact@e-life.com.ua

Logo:
![medeir_logo](https://user-images.githubusercontent.com/32056656/34353055-ae99e71e-ea2e-11e7-964b-8fd6bd909639.png)

Link for logo: 
http://e-life.com.ua/

**Comment by svetavedmed** [comment]
![Screen Shot 2017-12-26 at 14.18.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f56b7191a379eb0c2a59415d4fbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95cf442e14a54ad1a3667f43b.png)
