### ISSUE TITLE
verifications.api specs are private

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1703]
As an eHelath TechLead
I want to check specifications  of https://github.com/edenlabllc/otp_verification.api
So that I could see full description

Currently specs are private, please share

**Comment by AlekzandrV** [comment]
Here is a direct link to public [API Specification ](https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/otp-verification)

I've also updated Readme in repo https://github.com/edenlabllc/otp_verification.api
