### ISSUE TITLE
password grant  request does not require any client authorization

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1705]
Env: dev

Looking at the test program from user authentication, it looks like a request with a login password getting send to a API layer without any client authorization. No any Authentication or API-KEY present

It means, that anyone could create a phising page for authorization
Endpoint for password grant exchange has to be restricted to auth FE only!

Example of the code from Postman

```
POST /oauth/tokens HTTP/1.1
Host: demo.ehealth.world
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: e5740f4d-6470-91e0-ac13-c159462df9f2

{
   "token":{
      "grant_type":"password",
      "email":"<<owner_email>>",
      "password":"12345678",
      "client_id":"e2e1d2c8-9bac-43c6-adef-83239940b30a",
      "scope":"app:authorize"
   }
}
```

**Comment by lymychp** [comment]
will check it

**Comment by gmile** [comment]
So I think I get it now. Ignore my previous message.

We need to rely on CSRF mechanism. Any login attempt will be required to carry a CSRF token. It cannot be obtained other than loading our own FE login page.

I'm assigning @kiurchv to this.

Myroslav, we must adjust the login flow to include the CSRF token validation:

1. upon rendering the page, we render the CSRF token in a login form, in hidden tag,
2. upon submission of the login form, we must check the CSRF token during – in the **node app**,
3. we will disable sending "password" requests directly to the API from the world (the API endpoint will become private).

**Comment by gmile** [comment]
I redacted the issue and moved the discussion to an internal place. The fix will be published as usually in open-source.

**Comment by gmile** [comment]
https://github.com/edenlabllc/ehealth.charts/issues/52
