### ISSUE TITLE
deploy all version of ACSK ceritificates published

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1706]
As per latest discussion with uacrypto vendor - we must install all versions of certificates (root/ocsp/tsp) which published by acsk, and not only single active version

Usually, each ACSK is publishing pair of ceriticates
Please, go through existing deployed certificates and ensure that all certificates are deployed

**Comment by Troush** [comment]
- [ ] Test current capabilities 
- [ ] Upload all if it works
- [ ] If not. Create task to change implementation
