### ISSUE TITLE
Add new MIS on portal

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1707]
Go to: https://portal.ehealth-ukraine.org/providers.html
Add new MIS MedCard Plus

**Функції в системі eHealth**
Реєстрація закладів, лікарів, декларацій

**Про МІС**
**MedCard Plus** - це універсальна система, основним компонентом якої є електронна медична карта пацієнта, відповідно до стандартів МОЗ України. МІС надає зручне управління медичними послугами. Особливістю МІС  є використання процесного підходу до автоматизації медичного закладу у лікувальній та адміністративній діяльності.  MedCard Plus успішно працює у 35 комунальних закладах. Ми надаємо всю необхідну допомогу щодо  впровадження та адаптації системи для Вашого закладу.

**Технічні вимоги**
Ноутбук або персональний комп'ютер офісного рівня. Має працювати браузер Google Chrome останньої версії.

(057) 760-70-87
support@mcplus.com.ua

Logo:
![logo_200](https://user-images.githubusercontent.com/32056656/34817400-81997970-f6c0-11e7-802a-8eeb9448394c.png)

Link for logo:
https://www.mcplus.com.ua/

**Comment by ivchenkodima** [comment]
deployed to preprod http://portal.ehealth.world/

**Comment by svetavedmed** [comment]
done on preprod
