### ISSUE TITLE
Change document on portal

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1708]
Go to https://portal.ehealth-ukraine.org 
Choose "documents"

**Change document name and file**

Current document: 
Проект Закону про державні фінансові гарантії надання медичних послуг та лікарських засобів 

Expected document name: 
Закон про державні фінансові гарантії надання медичних послуг та лікарських засобів
New document file: 
[u0417u0410u041au041eu041d u0423u041au0420u0410u0406u0308u041du0418.pdf](https://github.com/edenlabllc/ehealth.api/files/1621909/u0417u0410u041au041eu041d.u0423u041au0420u0410u0406u0308u041du0418.pdf)

**Comment by ivchenkodima** [comment]
deployed to preprod http://portal.ehealth.world/

**Comment by svetavedmed** [comment]
done on preprod
