### ISSUE TITLE
prepare demo for reimbursement testing

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1711]
Env: demo

As a PO techlad
I want to test MIS for Reimbursement program
So that succesful testing could be passed

Pending tasks:

* NHS portal does not allow program management, medication management etc
* Dictionary has no list of  active programs
* Single "Доступні ліки" program has to be present in the system available for the testing.  Others test once has to be cleaned

**Comment by kmakarenko** [comment]
Необхідно зареєструвати програму "Доступні ліки".
З програмою мають бути пов'язані МНН та торгівельні назви з реєстру лікарських засобів, що підлягають відшкодуванню.
Також необхідно забепечити, щоб ця конфігурація з оновленням була доступна на всіх середовищах: дев, демо, препрод та прод.

**Comment by lymychp** [comment]
@pzhuk we do have postman integration tests that create/update/deactivate programs/inmns/medications/etc. Even if we do clear everything, every test run will generate new data.

**Comment by pzhuk** [comment]
@lymychp yes, but test generates very small subset of data (i.e. single
medication per campaign)

BR, Pavel V. Zhuk


2018-01-16 9:37 GMT+02:00 lymychp <notifications@github.com>:

**Comment by lymychp** [comment]
not only medication request, but also new innms, dosage, medications. So after the 1st run we will get the same situation as it is.
