### ISSUE TITLE
Attached documents for declaration forms

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1716]
All declaration with all authentication method has to have attached scan of declaration form. All attached documents are visible on Admin portal.

On `Create declaration request`
- create a link for declaration form with type `person.DECLARATION_FORM`

On `Approve declaration request`
 - check weather there is an attachment with type person.DECLARATION_FORM with created link with this declaration request  
 in case error return 409 -  "message": "Documents person.DECLARATION_FORM is not uploaded"

On `Get declaration by ID`
 - return declaration with attached documents

**Comment by Troush** [comment]
- [ ] Optional - Check if linked declaration is declaration
