### ISSUE TITLE
Change MEDSTAR link on portal

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1717]
Go to https://portal.ehealth-ukraine.org/providers.html
Click on MEDSTAR logo

Current link: http://medstar.ua/uk/
Expected link: http://medstar.ua

**Comment by pzhuk** [comment]
also, hreflang="ua" must be added

BR, Pavel V. Zhuk


2018-01-15 13:21 GMT+02:00 rkostiv <notifications@github.com>:

**Comment by ivchenkodima** [comment]
deployed to preprod http://portal.ehealth.world/

**Comment by svetavedmed** [comment]
done on preprod
