### ISSUE TITLE
Change MIS MedCard position on portal

### ISSUE THREAD

**Issue by rkostiv** [edenlabllc/ehealth.api#1720]
Go to http://portal.ehealth.world/providers.html

Current position of MedCard: right side
Expected position of MedCard: center

**Comment by svetavedmed** [comment]
![Screen Shot 2018-01-19 at 09.43.33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455fa6b7191a378e60c2f52415c4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95ef54fe64557a1123f63f43b.png)
