### ISSUE TITLE
Declaration Digital Signature

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1724]
As for now only Doctor can sign declaration with a Patient. 
Admin also must be allowed to sign declaration.
- [ ] update specification (add scopes for Admin)
- [ ] implement
- [ ] improve test scenarios

**Comment by pzhuk** [comment]
why do we need Admin and HR to sign declarations?

**Comment by danakonovalenko** [comment]
@pzhuk HR was incorrect input. Only Admin will have additional scope.

**Comment by danakonovalenko** [comment]
Sing declaration by any employee in legal_entity #1718
