### ISSUE TITLE
Auto termination declarations

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1730]
In case of a patient death or if a doctor was sentenced declarations must be terminated automatically:
- [x] find out how the files will be downloaded
- [x] spec the process and update erd [confluence](https://edenlab.atlassian.net/wiki/x/ioCBF)
- [x] set up automatically data storing
- [x] set up a job to terminate declarations based on stored data

**Comment by Troush** [comment]
- [ ] Read CSV. INN | Reason | 
- [ ] Insert to intermediate table with declaration date, info about how loaded and when

**Comment by Troush** [comment]
- [ ] Insert log table about files

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed on dev

**Comment by danakonovalenko** [comment]
@PavelVesnin 
- [ ] register_id  is null in register_entries
- [ ] status='PROCESSING' in tables registers and registers_entries (mpi doesn't response)
- [ ] updated_by null and updated_at is not null

**Comment by PavelVesnin** [comment]
@danakonovalenko fixed and deployed
