### ISSUE TITLE
Declaration Request Cabinet

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1734]
After authorization a person must be able to:
- view current active declaration and declarations history ***Get Declaration Status/Details by patient #1920***
- make new declaration request ***Create declaration request online #1909***
- check declarations history ***Get declarations list by patient #1919***
- terminate declaration ***Terminate Declaration via Cabinet #1925***

- [x] design and spec the process of making declaration request from cabinet
- [ ] implement
- [ ] improve test scenarios

**Comment by danakonovalenko** [comment]
Request:
```
curl -X POST \
  https://dev.ehealth.world/api/cabinet/declaration_requests \
  -H 'authorization: Bearer SFB3SDNhZlBuZFJhNlZkcmZrUjU0UT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 8ff92cb4-d049-f745-ec57-f03bf5ca8255' \
  -d '{
  "person_id": "0895e21b-06e1-4a3c-8f23-daabf86adf7f",
  "employee_id": "376bc05d-4686-4ef3-94c9-23094c735e5b",
  "division_id": "4461d9c0-0111-4c11-98ba-3db14129c072"
}'
```
Response
```
{"meta":{"url":"http://api-svc.il/api/cabinet/declaration_requests","type":"object","request_id":"41ebe20a-4282-4b5b-960d-3bca273d5cd2#426","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```

**Comment by lymychp** [comment]
@AlekzandrV please retest

**Comment by lymychp** [comment]
@AlekzandrV any results?
