### ISSUE TITLE
Support multiple versions of API at the same time

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1744]
As a NHS
I want to be able to support old version of API and the latest one at the same time
So that I can provide possibility for easy migration for MISes

**Comment by gmile** [comment]
The discussion happened in slack. Main points:

* we will use "umbrella app" approach,
* umbrella app will contain two apps: v1 and v2,
* v1 and v2 both will have distinct routers/webservers, each listening on a port of its own.

Requirements to keep in mind:

* at the time of deploy, both v1 and v2 must use same underlying DB.
