### ISSUE TITLE
Fix data corruption conflict

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1771]
As a result of the incident with the Postgres WAL-files corruption on prod env, two records has been inserted to the replication DB but are missing in the ops-db.

Solution: manually copy records with IDs ('10c1e637-1542-4dea-aa3c-7b196d7ad88c','9d26e18f-eec8-4022-9310-6b490e7803a9') to the ops-db from replication db.

**Comment by vsirius** [comment]
Error when inserted record: 
```sql> INSERT INTO public.declarations (id, employee_id, person_id, start_date, end_date, status, signed_at, created_by, updated_by, is_active, scope, division_id, legal_entity_id, inserted_at, updated_at, declaration_request_id, seed) VALUES ('9d26e18f-eec8-4022-9310-6b490e7803a9', '5c2b5529-a789-4ae6-947f-6fe774afdc61', '94e923c8-0c14-4583-a367-eb2165180925', '2018-01-30', '2021-01-30', 'active', '2018-01-30 14:49:04.327208', '030ca1a6-b4e7-49a2-b655-c7f78aeb40e6', '030ca1a6-b4e7-49a2-b655-c7f78aeb40e6', 'true', 'family_doctor', '4c4cf162-df85-47b8-a3c2-b9247d3b37b4', '030ca1a6-b4e7-49a2-b655-c7f78aeb40e6', '2018-01-30 14:49:04.344277', '2018-01-30 14:49:04.344291', 'efcb8cb5-a277-407b-8fa4-45af2a3e360d', '\x9970c86762212151cb0c609e9f96004ca2365d21cd602ec5cf0c421360868293c54d452b48f8793d0c428704b4b1bd9314cd3b7f822ddeac1a883b81df3c18cb') ```

``` [2018-02-02 15:59:56] [23505] ERROR: duplicate key value violates unique constraint "declarations_person_id_index"
[2018-02-02 15:59:56] Detail: Key (person_id)=(94e923c8-0c14-4583-a367-eb2165180925) already exists.```
