### ISSUE TITLE
Fix declaration request autotermination mechanism on PROD

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1773]
Fix declaration request autotermination mechanism on PROD

Env params:
**declaration_request_expiration** = 7
**declaration_request_term_unit** = DAYS

There are **19663** declaration requests in IL.DB older than 7 days

**Comment by lymychp** [comment]
pre-prod should be fixed/tested first

**Comment by svetavedmed** [comment]
was changed according to #1867
