### ISSUE TITLE
Sign declaration Request issue

### ISSUE THREAD

**Issue by Joyker** [edenlabllc/ehealth.api#1778]
According to [Sign declaration request](https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/sign-declaration-request) 

> Signed content MUST consists of JSON object with Declaration Request data and printout template. Object that need to be signed is returned by Get Declaration request by ID response, JSON.Path: $.data. The only field that can and must be changed is JSON.Path: $.data.patient_signed. It should be changed to true

After changing patient_signed to true, preproduction server still returns error : 

> Patient must sign declaration  form

source json payload: [request.txt](https://github.com/edenlabllc/ehealth.api/files/1689372/request.txt)
signed json payload: [signed_request.txt](https://github.com/edenlabllc/ehealth.api/files/1689373/signed_request.txt)
error: [error.txt](https://github.com/edenlabllc/ehealth.api/files/1689381/error.txt)

**Comment by svetavedmed** [comment]
To sing declaration you should send and sing only data, without the word "data".
So, not 
```
 {"data": {`content`
    }
}
```
but only `content`.
The error massage we will change.
