### ISSUE TITLE
501 при запиті на оновлення даних по співробітнику Demo

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1779]
original task - https://github.com/ehealth-ua/api-spec/issues/224

works on dev.
Should be fixed on demo.

**Comment by ybod** [comment]
Demo now have the same IL version as Preprod

**Comment by ybod** [comment]
This issue on `Demo` was related to [Man](https://github.com/edenlabllc/man.api) service configuration and now must be resolved

**Comment by svetavedmed** [comment]
fixed on demo
