### ISSUE TITLE
Search LE by settlement_id problem 

### ISSUE THREAD

**Issue by Joyker** [edenlabllc/ehealth.api#1781]
As a MIS i wont to search  Legal Entities by settlement_id with [Get Legal Entities](https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entities) method. 
Parameter settlement_id causes "Internal server error."

> https://api.ehealth.world/api/legal_entities?settlement_id=07f4730e-d764-45f9-8fe1-9a3ea59839d3&status=ACTIVE

Fails, meantime for example

> https://api.ehealth.world/api/legal_entities?status=active

Works fine.

Enviroment : preproduction.

**Comment by PavelVesnin** [comment]
@svetavedmed deployed on Dev

**Comment by Joyker** [comment]
I have tested it on demo server, works fine
