### ISSUE TITLE
`Districts by Region` and `Settlements by district` returns 404 error

### ISSUE THREAD

**Issue by lionsoft** [edenlabllc/ehealth.api#1784]
Methods `Districts by Region` and `Settlements by district`  of the API UAaresses returns 404 error on `DemoApi`

Request: `GET http://demo.ehealth.world/api/uaddresses/regions/45311788-3735-4ccf-884c-409c089f3a45/districts`
Response: `{"meta":{"url":"http://api-svc.uaddresses/regions/45311788-3735-4ccf-884c-409c089f3a45/districts","type":"object","request_id":"f81b493d-d5a9-4da9-942a-a4a136221062#8098","code":404},"error":{"type":"not_found"}}`

But the region with this `id` is present:
Request: `GET http://demo.ehealth.world/api/uaddresses/regions?koatuu=1200000000`
Response: `{"paging":{"total_pages":1,"total_entries":1,"page_size":10,"page_number":1},"meta":{"url":"http://api-svc.uaddresses/regions","type":"list","request_id":"e89715c9-d2ef-467a-b09a-419ca3888902#10486","code":200},"data":[{"name":"ДНІПРОПЕТРОВСЬКА","koatuu":"1200000000","id":"45311788-3735-4ccf-884c-409c089f3a45"}]}`

**Comment by Joyker** [comment]
Correct URL should look like:
> http://demo.ehealth.world/api/uaddresses/details/region/45311788-3735-4ccf-884c-409c089f3a45/districts

The same problem with searching settlements by districts

Correct should be :

> http://demo.ehealth.world/api/uaddresses/details/district/district_id/settlements

I was persuaded that the specification would be corrected

**Comment by lionsoft** [comment]
OK. That's good.
