### ISSUE TITLE
Оптимізувати пошук по населенному пункту на карті

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#1786]
*1. Шукати співпадіння тільки починаючи з початку назви населеного пункту, а не в будь-якій частині назви*
Приклад поточної реалізації:
При введені “Київ” пошук запропонує як варіанти, які починаються з цього набору літер (“Київське“, “Києвець“, “Київ“), так і варіанти, які мають цей набір літер в середині (“Новокиєвка“, “Вертокиєвка“)
Приклад пропонованої реалізації:
При введені “Київ” пошук запропонує лише ті варіанти, які починаються з цього набору літер (“Київське“, “Києвець“, “Київ“)
*2. Впорядковувати назви по рівню співпадіння з введеним (тобто спочатку коротші)*
Приклад поточної реалізації:
При введені “Київ” список назв по довжині впорядкований хаотично
Приклад пропонованої реалізації:
При введені “Київ” список буде відсортовано по тому, скільки літер співпадає з введеним. 
Тобто першим покаже м. Київ, бо воно має 4 з 4 співпавших символів
Наступним Києвець, бо 4 з 7 літер
Наступним Київське, бо 4 з 8 літер
...
*3. Можливість скролити список вниз, поступово вивантажуючи по 10 назв*
Приклад поточної реалізації:
При введені “Київ” система вивантажує список з 10 назв, скролити не можна.
Приклад пропонованої реалізації:
При введені “Київ” система вивантажує список з 10 назв, проте можна проскролити. При досягані дніща, система буде додавати ще по 10 назв. Ітерації можна проводити, поки варіанти в списку нє яссякнут

**Comment by lymychp** [comment]
deployed to pre-prod
#1775
