### ISSUE TITLE
Add new api for Search addresses

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1794]
Search Districts 
- List Of Districts By Search Params
 http://ehealth.edenlabllc.com/api/uaddresses/districts 
- Districts by Region
http://ehealth.edenlabllc.com/api/uaddresses/regions/290f1ee-6c54-4b01-90e6-d701748f0851/districts
- Settlements by district
http://ehealth.edenlabllc.com/api/uaddresses/districts/290f1ee-6c54-4b01-90e6-d701748f0851/settlements

till April both api should work

**Comment by PavelVesnin** [comment]
@svetavedmed deployed
