### ISSUE TITLE
Invalid validation when MSP registration

### ISSUE THREAD

**Issue by lionsoft** [edenlabllc/ehealth.api#1800]
I want to register my new  MSP on the `DemoApi`.
After sending signed base64-encoded content I get the validation errors:

`$.edrpou: string does not match pattern "^[0-9]{8,10}$" [^[0-9]{8,10}$]` for value `02007265`

`$.owner.tax_id: string does not match pattern "^([0-9]{9,10}|[А-ЯЁЇIЄҐ]{2}\\d{6})$" [^([0-9]{9,10}|[А-ЯЁЇIЄҐ]{2}\d{6})$]` for value `2050303289`

`$.phones.[0].number: string does not match pattern "^\\+38[0-9]{10}$" [^\+38[0-9]{10}$]` for value `+380562313052`

source data:

unsigned: https://startehealthatlast.slack.com/files/U9040KDFV/F94KYBM17/_onko.json

signed: https://startehealthatlast.slack.com/files/U9040KDFV/F968CAG15/_onko.json.p7s.base64

**Comment by svetavedmed** [comment]
The problem is with symbol that is not shown. On the screenshot you can see a space in all these fields. That symbol that is not shown did not pass the validation
![image](https://user-images.githubusercontent.com/30794602/36029772-402ba234-0dad-11e8-8886-1b387c16c478.png)
