### ISSUE TITLE
new temporary endpoint getEmployeeID_by_employeerequest_ID

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1807]
As a MIS
I want to have possibility to get employee_id having employee_request_id using MIS token
So that I can restore availability of my services after `/employee_requests/` has been restricted

@AlekzandrV FYI

**Comment by danakonovalenko** [comment]
WS speced [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-id-by-employee-request-id)
