### ISSUE TITLE
Add simple health-check endpoints

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#1900]
Add a simple GET health-check endpoint to IL. It should respond with `200` status, and static body containing `Ok`.

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.api/commit/8c2bcf6e7e8819ff8541923f3ea52dcbab953bbb

**Comment by gmile** [comment]
I guess now we should add this health check endpoint to charts

**Comment by gmile** [comment]
cc @vsirius
