### ISSUE TITLE
Denovo Target Hardware landscape design

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1901]
To design landscape for preprod/prod environments: how many Nodes/Pods, it's distribution, configs, limits, etc.
update eHealth specs document
- [ ] 1.3.4.  Persistence
- [ ] 1.3.5      Logging
- [ ] 1.3.10   Scalability
- [ ] 1.4  Deployment, Environments, Configurations

**Comment by gmile** [comment]
I'm going to cover all of this in a diagram, filled with details. The landscape will be more representative.

**Comment by gmile** [comment]
The image (designed in [draw.io](https://draw.io)):
![untitled diagram](https://user-images.githubusercontent.com/207112/39687153-ac45a84a-51d5-11e8-80aa-d41e9d17dd67.png)


The source code: [landscape_design.xml.zip](https://github.com/edenlabllc/ehealth.api/files/1978624/landscape_design.xml.zip)
