### ISSUE TITLE
Disaster recovery preparation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1908]
As a NHS
I want to have a detailed action plan what to do in case if the main DC (on-premise one) is down and cannot be restored during reasonable period of time (days)
So that I can provide continuity of the ehealth service.

Requirements:
* no data lose
* SLA - 8 hours to switch after the decision has been taken.

**Comment by lymychp** [comment]
[DR plan](https://github.com/edenlabllc/ehealth.charts/blob/a78ff405e36a732e3965a6c74d1fe6b43e4b245b/docs/denovo_migration.md)

**Comment by gmile** [comment]
Corrected link to point to latest DR plan – [here](https://github.com/edenlabllc/ehealth.charts/blob/migration-denovo-docs/docs/denovo_migration.md).
