### ISSUE TITLE
Get person details

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1917]
As a patient
I want see my personal information in cabinet
So that I keep it always actual

- [x] Get person details [spec](https://edenlab.atlassian.net/wiki/x/XAIoGg)

**Comment by svetavedmed** [comment]
add, please, id to response

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.api/pull/2096

**Comment by svetavedmed** [comment]
- [ ] it should be forbidden to get person information with 2fa_access_token, only with access_token
ex on dev: token.value=YTJCc1RXQmVKOTlYb2Rna2Y2WkFIQT09, token.name=2fa_access_token

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.charts/pull/86

**Comment by svetavedmed** [comment]
- [ ] necessary scopes 'person:read'

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.charts/commit/27f95bad2f40c1cb52e00dd286c5ddda0fbc1c4a
