### ISSUE TITLE
get personal info

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1918]
As a cabinet user 
I want to see greetings in cabinet
So that I see system understands who logged in to the cabinet

- [x] get personal info [spec](https://edenlab.atlassian.net/wiki/x/L4AoGg)

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.api/pull/1923

**Comment by svetavedmed** [comment]
rename, please, `mpi_id` to `id` in response

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.api/pull/2096
