### ISSUE TITLE
Missing capitation reports

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#1938]
On production, we don't have any capitation report in the bucket. We should take a look to understand why this is the case.

Are capitation reports not generating due some bug, or due to CRON misconfiguration?

**Comment by gmile** [comment]
Fixed in https://github.com/edenlabllc/ehealth.charts/commit/2832445fbd6f76e29363ea826df3a225c9df7891

**Comment by gmile** [comment]
Let's wait till Monday (1st of April) to verify.

**Comment by lymychp** [comment]
not actual anymore
