### ISSUE TITLE
Improve coverage at mpi.api

### ISSUE THREAD

**Issue by Troush** [edenlabllc/ehealth.api#1968]
We need to improve test coverage for `mpi.api` microservice.

Now it is covered at 72%

Also, target to use `ExMachina` for struct fabrics.
Also, target to use `Mox` for mocking remote http calls.

Definition of done: code coverage at 90%, fabrics with `ExMachina`, and `Mox`

**Comment by progsmile** [comment]
Done
https://github.com/edenlabllc/mpi.api/pull/75
