### ISSUE TITLE
Create Client (Mithril Admin portal)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1979]
As mithril admin I must be able to create new client. In order to do that I need to choose from dropdown list user(email). 
As for now it's impossible to do cause we filter by wrong field (***name*** instead of ***email***). Also after unsuccessful try the drop down return empty array for all next searches.
Those must be fixed

**Comment by svetavedmed** [comment]
login to mithril admin doesn't work
