### ISSUE TITLE
refresh token fo MIS

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1993]
- [ ] add description about refreshing tokens for MISes

**Comment by lymychp** [comment]
done

>1) протягом останніх  днів було декілька випадків прострочення МІС токенів доступу  до системи ehealth. У зв’язку з чим вважаю за необхідне повідомити, що під час реєстрації МІСів повинні бути видані логін/пароль, mis_client_id, secret, access_token, refresh_token. 
>2) Рекомендується хоча б раз в місцяь перевипускати `access_token`. 
>3) Це можна зробити двома способами:
3.1) з використанням [`refresh_token`](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/oauth/use-refresh-token-for-access-token-extension)
3.2) Пройшовши стандартний oauth2.0 flow з використанням [login/password/mis_client_id](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer)
>4) Пароль МІС користувача треба змінювати як мінімум раз в 90 днів. Прострочений пароль призведе до автоматичної деактивації усіх токенів.
>5) Якщо в когось немає даних з п.1 - прошу зареєструвати тікет з темою "Завершення реєстрації МІС [назва Вашого МІС]" і вказати яких саме даних Ви не отримали
