### ISSUE TITLE
Declaration request doctor speciality validation

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2042]
Change validation for doctor's speciality on [Create Declaration request](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/create-declaration-request).
Take `person.birth_date` and doctor's `employees.speciality.speciality` check:
```
If patients full year<18 then employee speciality must be in ('PEDIATRICIAN', 'FAMILY_DOCTOR'),
if patients full year>=18 then employee speciality must be in ('THERAPIST', 'FAMILY_DOCTOR')
```
In case of error return 422 error ('Doctor speciality doesn't match patient's age').

**Comment by magiccookie** [comment]
Just want to make sure if one should check both `employee.speciality.speciality` and `employee.specialities[i].speciality` ?

**Comment by danakonovalenko** [comment]
only speciality_officio must be check and speciality_officio is employees.speciality.speciality

**Comment by magiccookie** [comment]
This functional was already present.
#2654 Will change the error message to "Doctor speciality doesn't match patient's age"
