### ISSUE TITLE
Set Kong rate limits

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#2048]
Rate limiting need to be set per endpoint, not globally

**Comment by lymychp** [comment]
Proposed limits to start with:

API | period | limit
---------|---------|-----
GET declaration_requests | minute |  2000
GET declaration_request by id | minute | 2000
POST declaration_request | minute | 1000
POST otp-verification | minute | 1000

**Comment by lymychp** [comment]
@AlexKovalevych i think we should consider rate limiting per user/not per IP
Currently there is a huge diff between number of requests from centralized BE clients and distributed ones.

**Comment by lymychp** [comment]
on-hold. will return to this ticket after #2223

**Comment by lymychp** [comment]
rate limits by user_id has been deployed to prod
