### ISSUE TITLE
employee with division from another LE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2055]
As owner 
I want to create employee only in division from my LE
So as there would not be problems in the future

**Comment by lymychp** [comment]
`client_id == select legal_entity_id from divisions where id = payload.division_id`

**Comment by danakonovalenko** [comment]
@AlexKovalevych Return 422 Error $division ('Division is not within current legal entity')

**Comment by svetavedmed** [comment]
"message": "Division is not within current legal entity"
