### ISSUE TITLE
make Kibana stable again

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2066]
- [ ] all the logs from allmicroservices should be transferred to ES with zero loose possibility
- [x] configurations/visualizations/dashboards should be backed up with the clear restore process
- [x] ensure that service has enough resources to work stable
- [x] exclude sql logs

**Comment by lymychp** [comment]
configurations/visualizations/dashboards can be exported manually after creation.

**Comment by gmile** [comment]
can or cannot?

**Comment by lymychp** [comment]
can :) i've done it already
