### ISSUE TITLE
Auto remove emails from the hard-bounce list

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2073]
Running this:
```
gcloud logging read 'insertId="13yp4z7g273o4f5"' --format json --project ehealth-production | jq '.[].jsonPayload'
```

Reveals error:

```
There was a problem sending the email through the Postmark API.\nHere is the response:\n\"{\\\"ErrorCode\\\":406,\\\"Message\\\":\\\"You tried to send to a recipient that has been marked as inactive.\\\\nFound inactive addresses: d_nina06@ukr.net.\\\\nInactive recipients are ones that have generated a hard bounce or a spam complaint. \\\"}\"\n\nHere are the params we sent:
...
"Вітаємо! Вас запрошують приєднатись до системи eHealth, в рамках впровадження в Україні електронної системи охорони здоров’я.\\\"
```

So the person never got their invitation email, but the POST request returned 200 indicating everything was successful. Soon users may begin to complain about not getting invitation emails.

Maybe it's worth keeping an up-to-date list of all inactive emails (it can be obtained via postmark API call https://postmarkapp.com/developer/api/bounce-api#bounces), and return 400 error during employee registration, if an email is present in the list of inactive?

**Comment by AlexKovalevych** [comment]
Need to check postmark response body even if response is 200, in case user is inactive, just send it again and never mind the body anymore.

**Comment by progsmile** [comment]
Waiting for more emails from production to verify code works properly

**Comment by lymychp** [comment]
delivered to prod
