### ISSUE TITLE
Investigate 429 and slow reponses

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2084]
- [x] sometimes our clients are receiving 429 response code.
[- (36).txt](https://github.com/edenlabllc/ehealth.api/files/1876518/-.36.txt)
[- (38).txt](https://github.com/edenlabllc/ehealth.api/files/1876519/-.38.txt)
![image](https://user-images.githubusercontent.com/5257001/38318443-01063d98-3838-11e8-8992-1265efba4d81.png)

- [x] some requests are processing longer than 10 seconds 
examples will be send in PM

**Comment by AlexKovalevych** [comment]
According to logs sometimes client hit the server more than 50 times per second (the logs i found had 61 rps) from the same ip. No surprise it's possible to reach 100 rps and start getting 429 response from the cloudflare.
E.g. client hit the same endpoint 25 times per minute to get the same declaration_request:

![screen shot 2018-04-05 at 12 34 03](https://user-images.githubusercontent.com/577231/38360579-3baf0f2e-38d3-11e8-8923-01c9ad2e836d.png)
