### ISSUE TITLE
Catch intermittent errors while interacting with microservices

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2104]
Sometimes we have intermittent errors that look like this (request_id: 23ad82e5-8b87-4535-9e99-53c57b7dd8d0#79492):

```
** (HTTPoison.Error) :closed
    (ehealth) lib/ehealth/api/ops.ex:6: EHealth.API.OPS."request! (overridable 1)"/5
    (ehealth) lib/ehealth/api/ops.ex:9: EHealth.API.OPS.request!/5
    (ehealth) lib/ehealth/web/views/declaration_request_view.ex:34: EHealth.Web.DeclarationRequestView.render/2
    (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
    (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2
    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2
    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4
```

In order to improve user experience, instead of rendering 500, let's catch these errors.

Plan:

* change HTTPoison calls `post!`, `get!`, `put!` etc. to respective counterparts, `post`, `get`, `put`etc.
* every time a connection is :closed, write to log so we can still keep track of these cases.

Further work may include making retries.

**Comment by AlexKovalevych** [comment]
https://github.com/bitwalker/libcluster with Kubernetes strategy (probably requires pods config tuning)
