### ISSUE TITLE
Digital sign anomaly investigation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2126]
DigitalSign service response time has been dramatically increased:
![image](https://user-images.githubusercontent.com/5257001/38558692-9761db94-3cd9-11e8-8f64-ef379ff67354.png)

At the same time DS pod CPU usage has been increased, but RAM usage was dropped down.
![image](https://user-images.githubusercontent.com/5257001/38558540-20c85abc-3cd9-11e8-9d16-cf9a578ce5e5.png)

**Comment by gmile** [comment]
@ybod any thoughts? A wild guess: garbage collection in Erlang?

**Comment by ybod** [comment]
I've made some modifications of `DigitalSignature.api` service, we need to test new version on pre-prod/demo environments.

**Comment by gmile** [comment]
Going to deploy digital signature with this fix https://github.com/edenlabllc/digital_signature.api/pull/22 (https://github.com/edenlabllc/digital_signature.api/pull/23 and https://github.com/edenlabllc/digital_signature.api/pull/24 will come in too, they should be harmless)

**Comment by gmile** [comment]
@ybod pushed to demo/preprod envs, https://github.com/edenlabllc/ehealth.charts/commit/be10f98c27c69921a1f95a177434cfc583d28ae5.

**Comment by gmile** [comment]
@svetavedmed can we please test digital verification on preprod or demo?

**Comment by lymychp** [comment]
delivered to prod, will continue monitoring

**Comment by gmile** [comment]
Unfortunately this caused a spike in 400 errors on prod, see https://github.com/ehealth-ua/api-spec/issues/318. I've reverted for now, see https://github.com/edenlabllc/ehealth.charts/commit/f1c382925b3e712f5252501de4828e04b93467a0.

**Comment by lymychp** [comment]
today at aroud 15:26 we had problem again
![image](https://user-images.githubusercontent.com/5257001/38624474-d1829ce6-3db0-11e8-8772-b7209f583000.png)

**Comment by ybod** [comment]
I've tested this service with all request that resulted in 40x errors on `Prod` and cannot reproduce the issue... I've made some adjustments to the service and docker container. New version already deployed on `Demo`.
