### ISSUE TITLE
Database load balancing

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2130]
We have a DB streaming replica. It's a 100% realtime hot standby. We can utilize it, and use balance out all DB reads on it.

Let's use [`pgpool II`](http://www.pgpool.net/mediawiki/index.php/Main_Page). For short overview see – https://gist.github.com/afair/3803895.

The plan:

1. pick a microservice,
2. create a container with `pgpool II`,
3. set up master and slave DBs on `pgpool II`,
4. test the container by running queries against it:
    * see if it logs stuff,
    * verify load balancing is working.
5. if everything is OK, switch the microservice to use pgpool host / port as DB entrypoint.

**Comment by lymychp** [comment]
not actual anymore. We do use replicas as read-only datasource
