### ISSUE TITLE
Identify clients

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2139]
Right now we drop api-key and token from logs, therefor we cannot identify which MIS did the request. This hurts forensics, when we need to establish who exactly sent a request.

It'd be a great to come up with a way to distinguish clients without compromising security. One such way could be to provide a special mark in the `Agent` header.

This will not give up any sensitive information about client's request.

**Comment by lymychp** [comment]
@gmile we should also add endpoint name to the gateway log record

**Comment by gmile** [comment]
@lymychp regarding what was discussed during the standup: we do not always have client IDs. Client ID only seen while obtaining access token.

**Comment by gmile** [comment]
> we should also add endpoint name to the gateway log record

@lymychp I'll see what we can do about this

**Comment by gmile** [comment]
@AlexKovalevych can we tag an incoming request with a requested API's name? And then log the tag.

**Comment by gmile** [comment]
@lymychp regarding `Agent`. Can we please ask all our MISes to fill an `Agent` with their MIS name? I already see that all requests from helsi, for instances, are marked with good `Agent` value which can be relied upon.

**Comment by AlexKovalevych** [comment]
It's possible to log `x-consumer-id` and `x-client-id` headers if we return them to the client (we currently don't do that as i can see)

**Comment by gmile** [comment]
Current plan is: Alex is going to try and add logging to mithril plugin. I will re-build and deploy new kong container.

**Comment by gmile** [comment]
Done in all environments now. See latest change in this endeavour – https://github.com/edenlabllc/ehealth.charts/commit/ae12d22b47179fc1d38551e6d500a50b6384dd9d, verified on kibana.
