### ISSUE TITLE
Digital signature verification improvements

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2146]
Right now it's possible that DigitalSignature service misbehaves:
* it's stuck due to lack of memory resources,
* it's stuck during OCSP server negotiation,
* it's stuck because it can.

Instead of firing 50x errors, we should handle such cases gracefully to achieve better UX. It'd be great to render a proper error to user, such as: "The DigitalVerification service is temporary unavailable" or There was a problem verifying the digital signature "There was a problem verifying the digital signature" or "Online Sertificate Status Server took too long to respond. Please, try again."

At the same time we should make sure we keep close eye on digital-verification wellness.

Tasks:

- [x] fix DigitalSignature to render a proper error in case it is taking too long to talk to OCSP server,
- [x] fix DigitalSignature (api) to render a proper error in a case of GenServer response timeout,
- [ ] fix IL to render a proper error to user in case DigitalSignature responds with 500,
- [ ] on kubernetes level, make sure a sane liveness probe is being ran to verify that digital-verification is alive and well. Ideally such liveness probe would send a dummy pre-defined content for verification, every 5 seconds or so,
- [ ] on monitoring level, make sure we receive a notification every time digital-signature restarts due to failed liveness probe.

**Comment by gmile** [comment]
@lymychp please triage the issue

**Comment by ybod** [comment]
No DigitalSignature lib has 3sec socket timeout on OCSP verification and returns correct error: "OCPS verification failed"

**Comment by gmile** [comment]
@ybod can we alter the message to make it more precise? "OCSP" is too generic. Maybe: "OCSP service did not reply within 3 seconds" or "Waiting for OCSP response timed out"?

**Comment by lymychp** [comment]
done
