### ISSUE TITLE
Capitation report

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#215]
As an administrator, I should be able to generate a capitation report that used by NHS as a cause for the payments to the MSP.

- [ ] csv-generation process + index + api
- [ ] Admin FE #246

The requirements for the report are described in [spec](https://edenlab.atlassian.net/wiki/display/EH/Capitation+and+reporting)

Acceptance criteria:
- capitation report in the csv-format that is described in the specification should be available via NHS admin UI

**Comment by mmiliaieva** [comment]
#219 
#218 
#217 
#216

**Comment by kmakarenko** [comment]
Approved

**Comment by TarasenkoA** [comment]
How I can test this reports? 
Provide please url for push request.

**Comment by TarasenkoA** [comment]
Waiting for deploy.

**Comment by AlekzandrV** [comment]
Error during execute capitation report
[capitation_report_log.txt](https://github.com/edenlabllc/ehealth.api/files/1227323/capitation_report_log.txt)

**Comment by Troush** [comment]
@AlekzandrV error related to https://github.com/edenlabllc/ehealth.api/issues/853
When #853 will be fixed this will be solved.

**Comment by AlekzandrV** [comment]
Capitation report tested
