### ISSUE TITLE
Billing process

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#216]
Once per months  (parameter) at 00:00 declarations state and released info should be saved in form of Capitation report.

Info should be provided:
- [ ] Age Group
- [ ] Compensation Group - TBD
- [ ] Mountain Group

Billing table contain:
- id
- billing date
- declaration id
- MSP id
- red MSP id
- mountain group (calculate by address in declaration)
- age group (choose one of the groupe 0-5 років, 6-17 років, 18-39 років, 40-64 років, 65 років і старші)

The table contains only the first declaration of the patient, that has red_msp_id

Add connection between red_list table and billing table in specs

**Comment by TarasenkoA** [comment]
How I can test this reports? 
Provide please url for push request.

**Comment by TarasenkoA** [comment]
Waiting for deploy.

**Comment by TarasenkoA** [comment]
ok
