### ISSUE TITLE
Fix case with non-existing date

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2162]
Sometimes we get a non-existing date:
```
** (ArgumentError) cannot parse "1942-02-29" as date, reason: :invalid_date
    (elixir) lib/calendar/date.ex:276: Date.from_iso8601!/2
    (ehealth) lib/ehealth/declaration_requests/api/creator.ex:82: EHealth.DeclarationRequests.API.Creator.validate_person/1
    (ehealth) lib/ehealth/declaration_requests/declaration_requests.ex:140: EHealth.DeclarationRequests.create_offline/2
    (ehealth)
```

Ideally this is fixed on json-schema level. We're using ([1](https://github.com/edenlabllc/ehealth.api/blob/master/apps/ehealth/lib/ehealth/validators/json_schema.ex#L6)) jvalid ([2](https://hexdocs.pm/jvalid/JValid.html)) package.

Relevant request IDs:

* c72ad96b-c085-430e-a506-bb77c451ff09#51431
* db99429a-50da-43c9-a368-b8e50da42c09#225432
* 0b40d1b6-6b7b-4b24-95b0-e304a201a4eb#261922

**Comment by svetavedmed** [comment]
- [ ] medication dispense
