### ISSUE TITLE
Create contracts

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#2176]

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2177

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2190

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2196

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2211

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2212

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2257

**Comment by danakonovalenko** [comment]
- [ ]  add verification if contract_number was sent in contract request than start_date and end_date is not allowed to be sent in request.
Find contract by contract_number in status='VERIFIED' and save start_date/end_date from this contract to contract_request

**Comment by danakonovalenko** [comment]
- [ ]  change the structure how external_contractors is saved to db (without `\`):
`{\"contract\": {\"number\": \"1234567\", \"issued_at\": \"2018-01-01\"`

**Comment by IrinaRevutska** [comment]
@AlexKovalevych ,please, fix contract creation according to [specification](https://edenlab.atlassian.net/wiki/spaces/EH/pages/524288412/Sign+Contract+Request+by+Legal+Entity+Owner)
- [ ] New record`s status should be 'VERIFIED'
- [ ] For each division from array contract_divisions create a new row in **PRM.contract_divisions**
- [ ] For each employee from array create a new row in **PRM.contract_employees**
