### ISSUE TITLE
Red Lists

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#218]
During declaration creation Red List MSP should be defined - once for each patient
Exact match is using for search
- [ ] Create RedLists DB #509 
- [ ] Provide Red Lists #291

**Comment by gmile** [comment]
@Troush @lymychp I've overheard once we don't do red lists anymore, do we? I'm probably missing something though (just wanted to make sure we don't keep an open ticket for something we're not going to work on)

**Comment by lymychp** [comment]
no, we still are going to deliver this functionality, but we won't import the data until get it from the customer with the proper quality

**Comment by lymychp** [comment]
[red lists objects added to erd](https://github.com/Nebo15/report.api/pull/15)

**Comment by AlekzandrV** [comment]
Red lists tested
