### ISSUE TITLE
create contract request

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#2180]
As legal entity OWNER I want to be able to create contract request according to [specification](https://edenlab.atlassian.net/wiki/x/dwA7Hw)

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2176

**Comment by AlexKovalevych** [comment]
https://uaehealthapi.docs.apiary.io/reference/dummy.-create-legal-entity/contracts/create-contract-request

**Comment by danakonovalenko** [comment]
Json schema to validate request - [contract_request_request.txt](https://github.com/edenlabllc/ehealth.api/files/1924037/contract_request_request.txt)

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, fix bugs according to the [test cases](https://edenlab.atlassian.net/wiki/x/H4BfI)

**Comment by danakonovalenko** [comment]
- [ ]  add verification if contract_number was sent in contract request than start_date, end_date and  contractor_legal_entity_id  are not allowed to be sent in request.
Find contract by contract_number in status='VERIFIED' and save start_date/end_date/contractor_legal_entity_id from this contract to contract_request

**Comment by IrinaRevutska** [comment]
As a solution to the previous problem:

In case contract request contains parameter '$.contract_number':
1. find the contract that matches transmitted '$contract_number':
1.1 if there is no contract with specified contract number, return 422 error  ('Contract with such contract number does not exist')
1.2 if contract is in 'Terminated' status, return 409 error  ('Can not update terminated contract')
2 .set parent_contract_id value as contract.id

**Comment by danakonovalenko** [comment]
there is no parent_contract_id in response. @AlexKovalevych please, add it to response

**Comment by IrinaRevutska** [comment]
- [ ] @AlexKovalevych , please make contractor_employee_divisions  required for both cases - create contract and update contract flow, according to [specification](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/pubic.-create-contract-request) (see "Generic contract_request object scheme to be signed" section)
(JSON schema)[https://github.com/edenlabllc/ehealth.api/blob/master/apps/ehealth/specs/json_schemas/contract_request/contract_request_create.json]  to validate request
