### ISSUE TITLE
Elixir.EHealth.Web.PersonController#search_persons Error 500 

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2185]
Error from logs: 
```
    "phoenix": {
      "request_id": "281f962b-00d1-4bf3-aa61-9685c4026152#64664",
      "message": "No function clause matching in EHealth.Web.FallbackController.call/2: {:error, \"\"}",
      "log_type": "error"
    },
```

**Comment by PavelVesnin** [comment]
Empty response from /person. I can't identify reason of the empty body from logs.
For this case I've created a [fix](https://github.com/edenlabllc/ehealth.api/pull/2172), that already on Prod. 
Let's see if this helps

**Comment by PavelVesnin** [comment]
@lymychp 2 days without this exception. Fixed
