### ISSUE TITLE
Set up redirect

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2192]
`https://ehealth-ukraine.org/` should be redirected to `https://portal.ehealth-ukraine.org/`

**Comment by gmile** [comment]
Done.

**Comment by gmile** [comment]
Also, the following redirects were set up (see https://github.com/edenlabllc/ehealth.charts/commit/9d204528f17ec6b32d9fcf6a5c45287e858c42b9):

* https://portal.ehealth-ukraine.org/ -> https://portal.ehealth.gov.ua/
* http(s)://ehealth-ukraine.org/ -> https://ehealth.gov.ua/
* http(s)://www.ehealth-ukraine.org/ -> https://ehealth.gov.ua/

Also, https://ehealth.gov.ua is now hosted in our cluster, see .https://github.com/edenlabllc/ehealth.charts/commit/728e73b1e798091aa7d9217dee8597f92a07dea1
