### ISSUE TITLE
Shut down elixir services gracefully

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2193]
It's possible to make elixir services to shutdown more gracefully, see "[Graceful shutdown on Kubernetes with signals & Erlang OTP 20](https://medium.com/@ellispritchard/graceful-shutdown-on-kubernetes-with-signals-erlang-otp-20-a22325e8ae98)".

According to the post, there's a 30 seconds gap between Kubernetes asking pod to shutdown, till actual shutdown:

> Kubernetes first sends a SIGTERM signal to your main process, then calls the optional preStop hook; it then waits for up to 30 seconds for your pod to exit, and if it’s still running after that, sends it a SIGKILL.

Example from the post:

```
11:47:09.538 [info] method=POST path="/xxx" type=Sent status=403 duration=253
***K8STrafficDrain: SIGTERM received. Draining and then stopping in 20000 ms
11:47:11.444 [info] method=GET path="/xxx/xxx-svc"
11:47:11.538 [info] method=GET path="/xxx/xxx-svc" type=Sent status=200 duration=94345
***K8STrafficDrain: Stopping due to earlier SIGTERM
```

> Kubernetes sent us a SIGTERM and then sent us another HTTP request: if we’d have started shut-down immediately, this request would have failed.

Let's try and investigate if its applicable to our services, and if it is – implement this.

**Comment by dhlebnikov1** [comment]
after investigating  gracefully shutdown of the pods, after receiving SIGTERM kubernetes remove pod ip from endpoint and new request dose not go to those pods, and after new pod creation and passing livness/readness probes it add new ip address of the new pod to endpoint
