### ISSUE TITLE
Simplify digital-signature by removing database

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2207]
It's possible to read certificates from a dedicate folder instead of reading a bunch of bytes from a database. Let's do that.

Dropping the DB in favor of folder-managed certs will have the following benefits:

1. we will drop a bunch of heavy dependencies, such as ecto, postgrex, db_connection, etc.
2. at runtime we will not have a DB pool and DB workers,
3. consolidate both library and API code in a single place,
4. the app code become much simpler,
5. from the ops standpoint of view, we will be able to drop support for a digital-signature db pod, and remove its DB configs entirely.

**Comment by ybod** [comment]
Library does not provide any functionality that will allow us to built a chain of valid certificates for the given signed content. Thus we will need to resolve complex task of checking every certificate from the dedicated folder and validating it against signed content until we will find correct chain or every certificate will fail.
