### ISSUE TITLE
Suspended Contracts

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2225]
Based on fields which were changed in Update Legal Entity request Contract status `is_suspended` must be changed to true (it's false by default).
- [ ] update legal entity [spec](https://edenlab.atlassian.net/wiki/x/SvkQ) or Update Legal Entity status or Deactivate Legal Entity [spec](https://edenlab.atlassian.net/wiki/x/-m8n)
```
- name
- addresses (any field in array)
- status
```
- [ ] update owner [spec](https://edenlab.atlassian.net/wiki/x/VBYU)
```
- first_name
- last_name
- second_name
- employee_type
- status
```

**Comment by danakonovalenko** [comment]
Updating employee or owner contract still has is_suspended=false

**Comment by danakonovalenko** [comment]
@PavelVesnin remind you, that update employee or owner still doesn't change is_suspended flag

**Comment by lymychp** [comment]
@AlekzandrV please test it

**Comment by lymychp** [comment]
@AlekzandrV any results?

**Comment by IrinaRevutska** [comment]
Got 500 when try to update existing legal entity with active contracts
Response:
```
{"meta":{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"e9520d7b-eaed-4698-a50b-580e3b4895e4#18914","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```
CURL:
```
curl -X PUT \
  https://api.dev.asclepius.com.ua/api/legal_entities \
  -H 'Authorization: Bearer azg1MFNUWVIrekVnK200ejFoL2RuZz09' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 44af7245-1ece-498b-8667-2cb0246bbb82' \
  -H 'edrpou: 3160405193' \
  -d '{
  "signed_legal_entity_request": "ew0KICAidHlwZSI6ICJNU1AiLA0KICAic2hvcnRfbmFtZSI6ICJJcmVuIENsaW5pYyIsDQogICJzZWN1cml0eSI6IHsNCiAgICAicmVkaXJlY3RfdXJpIjogImh0dHA6Ly9leGFtcGxlMi5jb20iDQogIH0sDQogICJwdWJsaWNfb2ZmZXIiOiB7DQogICAgImNvbnNlbnRfdGV4dCI6ICJDb25zZW50IHRleHQiLA0KICAgICJjb25zZW50IjogdHJ1ZQ0KICB9LA0KICAicHVibGljX25hbWUiOiAiSXJlbiBDbGluaWMiLA0KICAicGhvbmVzIjogWw0KICAgIHsNCiAgICAgICJ0eXBlIjogIk1PQklMRSIsDQogICAgICAibnVtYmVyIjogIiszODA2MzI2MTkwNDAiDQogICAgfQ0KICBdLA0KICAib3duZXJfcHJvcGVydHlfdHlwZSI6ICJTVEFURSIsDQogICJvd25lciI6IHsNCiAgICAidGF4X2lkIjogIjI5ODgxMjA5NTMiLA0KICAgICJzZWNvbmRfbmFtZSI6ICLQntC80LXQu9GP0L3QvtCy0LjRhyIsDQogICAgInBvc2l0aW9uIjogIlAxIiwNCiAgICAicGhvbmVzIjogWw0KICAgICAgew0KICAgICAgICAidHlwZSI6ICJNT0JJTEUiLA0KICAgICAgICAibnVtYmVyIjogIiszODA2MzI2MTkwNDAiDQogICAgICB9DQogICAgXSwNCiAgICAibGFzdF9uYW1lIjogItCb0LjQvNC40YciLA0KICAgICJnZW5kZXIiOiAiRkVNQUxFIiwNCiAgICAiZmlyc3RfbmFtZSI6ICLQn9C10YLRgNC+IiwNCiAgICAiZW1haWwiOiAiaXJlbi5yZXZ1dHNrYSs3QGdtYWlsLmNvbSIsDQogICAgImRvY3VtZW50cyI6IFsNCiAgICAgIHsNCiAgICAgICAgInR5cGUiOiAiUEFTU1BPUlQiLA0KICAgICAgICAibnVtYmVyIjogIjEyMDUxOCINCiAgICAgIH0NCiAgICBdLA0KICAgICJiaXJ0aF9wbGFjZSI6ICLQktGW0L3QvdC40YbRjywg0KPQutGA0LDRl9C90LAiLA0KICAgICJiaXJ0aF9kYXRlIjogIjE5ODUtMDYtMTYiDQogIH0sDQogICJuYW1lIjogItCa0LvRltC90ZbQutCwINCb0LjQvNC40Ycg0JzQtdC00ZbQutCw0LsiLA0KICAibWVkaWNhbF9zZXJ2aWNlX3Byb3ZpZGVyIjogew0KICAgICJsaWNlbnNlcyI6IFsNCiAgICAgIHsNCiAgICAgICAgIndoYXRfbGljZW5zZWQiOiAi0YDQtdCw0LvRltC30LDRhtGW0Y8g0L3QsNGA0LrQvtGC0LjRh9C90LjRhSDQt9Cw0YHQvtCx0ZbQsiIsDQogICAgICAgICJvcmRlcl9ubyI6ICLQmi0xMjMiLA0KICAgICAgICAibGljZW5zZV9udW1iZXIiOiAiZmQxMjM0NDMiLA0KICAgICAgICAiaXNzdWVkX2RhdGUiOiAiMTk5MS0wOC0xOSIsDQogICAgICAgICJpc3N1ZWRfYnkiOiAi0JrQstCw0LvRltGE0ZbQutCw0YbQudC90LAg0LrQvtC80ZbRgdGW0Y8iLA0KICAgICAgICAiZXhwaXJ5X2RhdGUiOiAiMTk5MS0wOC0xOSIsDQogICAgICAgICJhY3RpdmVfZnJvbV9kYXRlIjogIjE5OTEtMDgtMTkiDQogICAgICB9DQogICAgXSwNCiAgICAiYWNjcmVkaXRhdGlvbiI6IHsNCiAgICAgICJvcmRlcl9ubyI6ICJmZDEyMzQ0MyIsDQogICAgICAib3JkZXJfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICJpc3N1ZWRfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICJleHBpcnlfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICJjYXRlZ29yeSI6ICJGSVJTVCINCiAgICB9DQogIH0sDQogICJsZWdhbF9mb3JtIjogIjE0MCIsDQogICJrdmVkcyI6IFsNCiAgICAiODYuMTAiLA0KICAgICI4MS4yMSIsDQogICAgIjQ3LjczIg0KICBdLA0KICAiZW1haWwiOiAibHlteWNocCsxQGdtYWlsLmNvbSIsDQogICJlZHJwb3UiOiAiMzE2MDQwNTE5MyIsDQogICJhZGRyZXNzZXMiOiBbDQogICAgew0KICAgICAgInppcCI6ICIwMjA5MCIsDQogICAgICAidHlwZSI6ICJSRUdJU1RSQVRJT04iLA0KICAgICAgInN0cmVldF90eXBlIjogIlNUUkVFVCIsDQogICAgICAic3RyZWV0IjogItCy0YPQuy4g0J3RltC20LjQvdGB0YzQutCwIiwNCiAgICAgICJzZXR0bGVtZW50X3R5cGUiOiAiQ0lUWSIsDQogICAgICAic2V0dGxlbWVudF9pZCI6ICJmYjVlNmYwNy0wYzJkLTRjNWMtOGJjNS1mMGI4NmJiOTQ0OTQiLA0KICAgICAgInNldHRsZW1lbnQiOiAi0KfQo9CT0KPQh9CSIiwNCiAgICAgICJjb3VudHJ5IjogIlVBIiwNCiAgICAgICJidWlsZGluZyI6ICIxNSIsDQogICAgICAiYXJlYSI6ICLQpdCQ0KDQmtCG0JLQodCs0JrQkCIsDQogICAgICAiYXBhcnRtZW50IjogIjIzIg0KICAgIH0NCiAgXQ0KfQ==",
  "signed_content_encoding": "base64"
}'
```

Log:
```
Request: PUT /api/legal_entities
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {"Expected suspended contracts amount are 7. Given 0", [nil, nil, nil, nil, nil, nil, nil]}}
        (ehealth) lib/ehealth/legal_entities/legal_entities.ex:172: anonymous fn/3 in EHealth.LegalEntities.transaction_update_with_ops_contract/2
        (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
        (ehealth) lib/ehealth/legal_entities/legal_entities.ex:235: EHealth.LegalEntities.create/2
        (ehealth) lib/ehealth/web/controllers/legal_entity_controller.ex:15: EHealth.Web.LegalEntityController.create_or_update/2
        (ehealth) lib/ehealth/web/controllers/legal_entity_controller.ex:1: EHealth.Web.LegalEntityController.action/2
```

**Comment by danakonovalenko** [comment]
As it was written above contract must be suspended in case contractor_owner_id was updated:
```
- first_name
- last_name
- second_name
- employee_type
- status
```
So, in case previous contract_owner_id was deactivated (via dismiss employee or via update legal_entity) contract must be in status is_suspended = true.

**Comment by marinakr** [comment]
Logic for employee_type and status (on approve employee) was added, but in tests contracts with verified status marked in db as suspended
If issue will occur again, can some examples of http requests be added?

**Comment by marinakr** [comment]
@AlekzandrV 
On each update legal entity new employee_request for owner is created, and it does not matter was owner changed or not. So, first of all, on approve employee request we do not have enough information does it new owner or not. Also there is no reason to create new employee request if owner info was not changed

**Comment by marinakr** [comment]
@danakonovalenko @AlekzandrV   ```api/employees/id/actions/deactivate```  -  does deactivation of employee should suspend contracts of employee only is employee_type 'owner' or for any employee_type?

**Comment by marinakr** [comment]
method PATCH should be used
----
curl -X PATCH   https://api.dev.asclepius.com.ua/api/employees/96364cf8-0837-489b-9702-2fce2a1a538d/actions/deactivate   -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09'   -H 'authorization: Bearer Tk1GK0pBQUo2U0tSUWtRQ1NtTUMrdz09'   -H 'cache-control: no-cache'   -H 'content-type: application/json'   -H 'postman-token: 6b7a18e8-2ad6-991f-d497-badf7935352c'
{"meta":{"url":"http://api-svc.il/api/employees/96364cf8-0837-489b-9702-2fce2a1a538d/actions/deactivate","type":"object","request_id":"cfd85ed3-9c8f-4685-bde8-b3dba929cf83#35963","code":200},"data":{"status":"DISMISSED","start_date":"2018-03-02","position":"P2","party":{"working_experience":null,"tax_id":"2871425582","second_name":"Вікторович","phones":[{"type":"MOBILE","number":"+380503410870"}],"no_tax_id":false,"last_name":"Вірний","id":"1e42cf62-f363-4172-85c2-a261c9542554","gender":"MALE","first_name":"Олександр","documents":[{"type":"PASSPORT","number":"120518"}],"declaration_limit":null,"declaration_count":null,"birth_date":"1991-10-03","about_myself":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"Лимич Медікал","public_name":"Лимич Медікал","owner_property_type":"STATE","name":"Клініка Лимич Медікал","mis_verified":"NOT_VERIFIED","legal_form":"140","id":"41ebae5e-c269-491f-9f78-05bfdae5e397","edrpou":"3001048467"},"id":"96364cf8-0837-489b-9702-2fce2a1a538d","end_date":"2018-07-10","employee_type":"ADMIN","division":{"type":"CLINIC","status":"ACTIVE","name":"Бориспільське відділення Клініки Борис","mountain_group":false,"legal_entity_id":"41ebae5e-c269-491f-9f78-05bfdae5e397","id":"b6af6cfd-dabe-4188-861f-05dbd8fb8591"}}}edenlabs-MacBook-Pro:ehealth edenlab$
