### ISSUE TITLE
token creation duration anomaly investigation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2236]
```
 "phoenix": {
      "status": 201,
      "request_id": "5053a582-c397-4379-a00b-3531b63cc8e3#43366",
      "path": "/oauth/tokens",
      "method": "POST",
      "log_type": "http",
      "handler": "Elixir.Mithril.OAuth.TokenController#create",
      "duration": 9416.955,
      "date_time": "2018-04-26T02:55:09Z",
      "api_version": "*/*"
    },
```
![image](https://user-images.githubusercontent.com/5257001/39290226-993b8be4-4937-11e8-8a1c-8b8ba156bc0f.png)

**Comment by PavelVesnin** [comment]
Token creation tested on local machine with 5 000 000 rows and has no troubles with performance.
Inserting new tokens costs about 20 milliseconds.
Duration anomaly causes because of I/O troubles on Denovo infrastructure
