### ISSUE TITLE
Rotate kibana credentials once a month

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2240]
Let's rotate <s>credentials</s> password for **logs.ehealth-ukraine.org** at least once a month. During rotation, @lymychp, @vsirius and @gmile should receive a new password via a secure channel (telegram, for instance).

This should be automated via a cronjob in k8s cluster.

**Comment by lymychp** [comment]
@gmile did you mean "rotate passwords"?

**Comment by lymychp** [comment]
kibana is not accessible from internet, not actual anymore
