### ISSUE TITLE
E-Health Configuration

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#225]
As NHS admin i want to configure E-Health parameters via NHS Admin portal.

@DPaschenko please add parameters here

**Comment by DPashchenko** [comment]
Add global_parameters:
* otp_expiration_term
* google_token_expiration_term
* declaration_request_expiration_term

**Comment by lymychp** [comment]
```
curl -X GET \
  http://dev.ehealth.world/prm/api/global_parameters \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 6acd886e-9cc6-a4ba-0725-1fd4094e1128'
```
