### ISSUE TITLE
Move addresses to separate table

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#2255]
In order to optimize stats selects
Move addresses from division to separate table

**Comment by svetavedmed** [comment]
some division's addresses are not added to division_addresses. 
Ex. at the moment there are 4 divisions, which addresses do not represented in division_addresses
```
division_id
091c9efa-37fd-44c9-a7d1-a5249ae7ff26
439456c7-67a2-4d8d-bf6a-ea135cfd68e6
998b224b-6ae8-443e-8f54-8bde72817174
aab1911e-4a3f-48d9-9b18-8125510eafb7
```
