### ISSUE TITLE
Check il.declaration_requests indexes

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2258]
It appears that the duration of GET /declaration_requests with the `employee_id` and `status` parameters is much longer than usual.

additional indexes might be required.
example:
```
  "phoenix": {
      "status": 200,
      "request_id": "4a8163b8-8a1c-45fc-922b-60f528d6b941#22214",
      "path": "/api/declaration_requests",
      "method": "GET",
      "log_type": "http",
      "handler": "Elixir.EHealth.Web.DeclarationRequestController#index",
      "duration": 5699.582,
      "date_time": "2018-05-03T08:51:12Z",
      "api_version": "N/A"
    },
```

**Comment by gmile** [comment]
No need to add index for the query in question. For this particular `request_id` the query is fast. It is query **queue time** that was slow. 
![image](https://user-images.githubusercontent.com/207112/39582781-5a75256c-4ef7-11e8-80ad-5c8c30573e97.png).

"queue time" means ([1](https://github.com/elixir-ecto/ecto/blob/3ca07b97c2046a73f426297b4425dfa27141d94a/lib/ecto/log_entry.ex#L13), [2](https://github.com/elixir-ecto/ecto/blob/68715062d75ef2b374a063f50a073b5154bc4bd3/lib/ecto/adapters/sql.ex#L659), [3](https://github.com/elixir-ecto/db_connection/blob/53271f7d2636bafca3966bbee44d0ecf70d10064/lib/db_connection/log_entry.ex#L16), [4](https://github.com/elixir-ecto/db_connection/blob/53271f7d2636bafca3966bbee44d0ecf70d10064/lib/db_connection/log_entry.ex#L16)) how quickly it was possible to checkout the connection from the pool.

Looks like at the time of the query all 150 connections from the pool were busy serving other SQL queries.

To fix this:

* we may consider increasing the number of ecto connections (**quickest solution**),
* dig more into why we do not have available connection for more than 5 seconds (**slowest solution**).

I'd suggest we go with quicker solution for now, but keep the tab open and investigate why we have slow queries overall.

---

Currently all DBs that IL API have access have 2048 connections max.
<details>
<summary>Details</summary>

* il:
```
kubectl exec db-0 --namespace il --context denovo-prod --stdin=true --tty=true -- psql --dbname il --username db -c "select name, setting from pg_settings where n
ame = 'max_connections';"
      name       | setting
-----------------+---------
 max_connections | 2048
```

* prm:

```
kubectl exec db-0 --namespace prm --context denovo-prod --stdin=true --tty=true -- psql --dbname prm --username db -c "select name, setting from pg_settings where
 name = 'max_connections';"
      name       | setting
-----------------+---------
 max_connections | 2048
(1 row)
```

* fraud:

```
kubectl exec db-0 --namespace fraud --context denovo-prod --stdin=true --tty=true -- psql --dbname fraud --username db -c "select name, setting from pg_settings w
here name = 'max_connections';"
      name       | setting
-----------------+---------
 max_connections | 2048
(1 row)
```

* event_manager:

```
kubectl exec db-0 --namespace em --context denovo-prod --stdin=true --tty=true -- psql --dbname event_manager --username db -c "select name, setting from pg_s
ettings where name = 'max_connections';"
      name       | setting
-----------------+---------
 max_connections | 2048
(1 row)
```
</details>

Allowing for more connection is not trivial, and will require DB restart.

However in ecto we have this:

```
il: 150 workers
prm: 50 workers
fraud: 50 workers
event_manager: 50 workers
```

So we have room for improvement on Ecto side.

**Comment by lymychp** [comment]
Ok, let’s increase the pool size

**Comment by vsirius** [comment]
fixed
