### ISSUE TITLE
Describe E-Health infra and architecture

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#230]
According to recent meeting with project ream
Format to be provided by Pavel

**Comment by pzhuk** [comment]
guys, can you pls continue working on the Architecture document as it exist now?
https://docs.google.com/document/d/1-BkFVRwrdRJoYf-sx8Rpry0c8wJGkpw6_2wnZGG0bsw/edit?usp=sharing

There are multiple unasnwered questions there, and overall this doc doesn't look super rich from information standpoint.

We shall provide some more requests on what is required to start security review, but overall - let's have this doc updated with all architecture details

**Comment by lymychp** [comment]
agreed to contribute to this document
https://docs.google.com/document/d/1oS1FiDJwOMBkR4wLbO51qcS8mO0LaBdXl7TQhk71OWM/edit#

**Comment by lymychp** [comment]
done
