### ISSUE TITLE
Approve NHS portal design

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#232]

**Comment by IrynaShevch** [comment]
работаем с Дианой, пока финальньій вариант не готов

**Comment by lymychp** [comment]
[Resources](https://www.dropbox.com/sh/z4dh7ba9csx3ke3/AAB15AangtmAp2yUEqZTjWasa?dl=0)
[png](https://www.dropbox.com/sh/itrru677dj8zmyq/AABr9YOKkperg1ePUiYZnja3a?dl=0)

@IrynaShevch please approve
