### ISSUE TITLE
add to declaration/id response

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2343]
Add field to get declaration by id in Cabinet, according to [Design](https://www.dropbox.com/s/tnrqd19nkqae44t/Declaration.pdf?dl=0) 
  https://api.dev.asclepius.com.ua/api/cabinet/declarations/{id}
- data.person.gender

**Comment by magiccookie** [comment]
my next task

add
- data.person.birth_country
