### ISSUE TITLE
Get Declaration Requests list via Cabinet

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2358]
Patients in cabinet should be able to see not only declaration, but declaration requests as well.
In order to do that the service Get declaration request list must be done
- [ ] implement according to [specification](https://edenlab.atlassian.net/wiki/x/toAnIg) / [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-patient-cabinet/cabinet/get-declaration-request-list-via-cabinet)

**Comment by svetavedmed** [comment]
get declaration request does not return data
ex. person_id='a80d85da-1a60-4979-9e56-99472140eebf'
declaration_requests: 86ab23ff-ec70-428e-a838-694a855488f5
fb769e28-4239-4351-8115-068e1a5a5c5a

request
```
curl -X GET \
  https://api.dev.asclepius.com.ua/api/cabinet/declaration_requests \
  -H 'Authorization: Bearer ODIrYWZjTlNlOXZDTVA5THpXUGROQT09' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 58ca9363-704f-4850-98fc-e87a349f318b'
```
response
```
{
    "paging": {
        "total_pages": 1,
        "total_entries": 0,
        "page_size": 50,
        "page_number": 1
    },
    "meta": {
        "url": "http://api-svc.il/api/cabinet/declaration_requests",
        "type": "list",
        "request_id": "31134980-d1eb-4626-8b3c-95a884b7db1e#11162",
        "code": 200
    },
    "data": []
}
```
