### ISSUE TITLE
Move /reports/stats/divisions endpoint under api prefix

### ISSUE THREAD

**Issue by kiurchv** [edenlabllc/ehealth.api#2424]
In order to unify endpoints used by the patient account frontend `/reports/stats/divisions` endpoint should be moved under `/api` prefix

- [x] duplicate `/reports/stats/divisions` endpoint as `/api/reports/stats/divisions`
- [ ] change `/reports/stats/divisions` endpoint to `/api/reports/stats/divisions` on the portal frontend
- [ ] remove `/reports/stats/divisions` endpoint

requires #1469

**Comment by AlekzandrV** [comment]
requires #1469
