### ISSUE TITLE
Не пропускает по валидации Content при declaration sign (via OTP)

### ISSUE THREAD

**Issue by vakafonic** [edenlabllc/ehealth.api#2428]
В запросе прикреплены ответы на запросы
1) Declaration Create
2) Declaration Approve
3) Declaration sign request (json, before base64 encode)
4) Declaration sign request (json, after base64 encode)
5) Declaration sign response

Получаю ошибку "Signed content does not match the previously created content", хотя контент идентичен.

[declaration_approve.txt](https://github.com/edenlabllc/ehealth.api/files/2090436/declaration_approve.txt)
[declaration_create.txt](https://github.com/edenlabllc/ehealth.api/files/2090437/declaration_create.txt)
[sign_request_not_encoded.txt](https://github.com/edenlabllc/ehealth.api/files/2090438/sign_request_not_encoded.txt)
[sign_response.txt](https://github.com/edenlabllc/ehealth.api/files/2090439/sign_response.txt)
[sign_request_encoded.txt](https://github.com/edenlabllc/ehealth.api/files/2090440/sign_request_encoded.txt)

**Comment by lymychp** [comment]
@vakafonic further please register your tickets in the proper [repo](https://github.com/ehealth-ua/api-spec/issues)

**Comment by vakafonic** [comment]
@svetavedmed  препрод

**Comment by svetavedmed** [comment]
Спасибо. Повторить данную ошибку не могу. На препрод все равноет корректно. Судя по вашим файлам, они у вас действительно не совпадают, при подписании не хватает данных, гнапример channel отсутствует.

**Comment by lymychp** [comment]
no feedback provided
