### ISSUE TITLE
reimbursement FE bugs

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2433]
- [ ] "Повернутися до списку" from inmms does  not work
1. goto inmms - ex. https://admin.dev.asclepius.com.ua/innms/bb4e8c4a-29e1-47e4-b7b6-db56e200ce73
2. ty to go back "Повернутися до списку"
3. redirecting to medications instead of inmms

- [ ] no possibility to reset filter on innm-dosages

- [ ] page format on innm_dosages
![Screen Shot 2018-06-12 at 12.33.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f16b7191a379ed0c2852415c49be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca50f142e74c57a71a356af43b.png)

- [ ] "Повернутися до списку" from medications root list w/o filter
ex. goto https://admin.dev.asclepius.com.ua/medications/339af0ee-664d-4fc6-be61-15daa3d55067 -> "Повернутися до списку"

**Comment by ephor** [comment]
fixed in #2373
