### ISSUE TITLE
occasional 500 on get innms through FE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2469]
curl 'https://admin.dev.asclepius.com.ua/api/api/innms' -H 'pragma: no-cache' -H 'cookie: lang=uk; meta=df01bc24-7b54-4cb0-8418-7ed90f5ac3db; authorization=eTE0bGJhemJXSDZXZFFpSXlHUnNJQT09' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36' -H 'content-type: application/json' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: admin.dev.asclepius.com.ua' -H 'referer: https://admin.dev.asclepius.com.ua/employees?page=1&party_id=079c4978-e830-4a7c-8051-e0d8ceceed46' --compressed

**Comment by lymychp** [comment]
not relevant anymore
