### ISSUE TITLE
Get capitation reports list

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#2474]
Implement API according to [spec](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/capitation-reports/get-capitation-reports) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/592904201/Get+Capitation+Reports)

**Comment by IrinaRevutska** [comment]
@magiccookie , please, add route to kong-dev

**Comment by IrinaRevutska** [comment]
Got 501 error:
```
{
    "meta": {
        "url": "http://api-svc.il/api/capitation_report_details",
        "type": "object",
        "request_id": "cfd85ed3-9c8f-4685-bde8-b3dba929cf83#26731",
        "code": 501
    },
    "error": {
        "type": "internal_error"
    }
}
```
```
curl -X GET \
  'https://api.dev.asclepius.com.ua/api/capitation_report_details?page=2&page_size=50' \
  -H 'Authorization: Bearer eEtwQUkwOGhJbCthaHg5ZXIwMGZoZz09' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 54474af4-37f5-4abc-b30b-6fcbe340ba09' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09'
```

**Comment by IrinaRevutska** [comment]
@magiccookie , please order reports by inserted at field desc, so that the first page will contain the latest reports
