### ISSUE TITLE
web hooks notifications to MIS

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#248]
As a MIS 
I want to get web hook calls about the async processes completion
so that I can get ID of the created entity
- [ ] design solution #279

- [ ] employee_request
- [ ] declaration request

**Comment by kmakarenko** [comment]
@pzhuk Please add a list of use cases when web hooks should be sent

**Comment by pzhuk** [comment]
Capitation:

* employee_request - status change (employee_id towards all MIS?)
* declaration - status change (declaration_id towards all MIS?)
* employee - status change (employee_id towards all MIS?)

Reimbursement:

* medication dispense (all MIS again?)

I really think we should organize it via some kind of endpoint which emulates subscription-based queue of different event types

**Comment by pzhuk** [comment]
Events to be handled:

* declaration status change
* medication request status change

Each status change should publish event to a corresponding eventlog table

* Additional endpoint should be added for fetching events. 
* Endpoint should support offset filtering (i.e. give me events happened after specific timestamp) filtering 
* Endpoint should support filtering by object id
* Endpoint should support filtering by event type OR different eventpoints could be provided for different even types

Event tables cleanup should be configurable and support cleanup by 2 types of events
* event age (i.e. delete events older than <event_max_age>)
* event count (delete old events, if amount of events in the eventlog is large than <event_max_amount>

**Comment by svetavedmed** [comment]
Event manager was done. It works on all environments.
