### ISSUE TITLE
Verification of uploaded documents

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2483]
Figure out how to avoid errors:
[Test cases](https://edenlab.atlassian.net/wiki/spaces/EH/pages/589070350/Upload+Documents+tests)

**Comment by lymychp** [comment]
proposed solution:
add logic to the approve contract endpoint: change policy for the specific bucket with the uploaded documents to `download`
```
mc policy download contract_requests/000025b4-9875-4a4c-b874-c72df7aaa5cb/

**Comment by lymychp** [comment]
we should also add policy to the buckets with media data:
minimum file size: 10 KBytes
maximum file size: 4 MBytes

**Comment by marinakr** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTpolicy.html

**Comment by lymychp** [comment]
another option:
* when new signed url are generated, add `_upload` prefix to the file name
* add logic to POST `/api/contract_requests/id`:
  * copy files with the name without suffix to the same folder
  * delete all the files with the upload prefix

PS:
all the contract related files should have `.pdf` extension.
