### ISSUE TITLE
Add to Get Contract Request Details respond    list of documents links

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2502]
Add to response of *"Get Contract Request Details" WS* object "Urgent" according to [specification](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523731044/Get+Contract+Request+Details) and [apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/public.-get-contract-request-details) , so that WS could respond with links to the documents. 

[Test cases](https://edenlab.atlassian.net/wiki/spaces/EH/pages/591495178/Get+Contract+Request+Details+tests)

**Comment by IrinaRevutska** [comment]
@marinakr , please, fix contract_request_id in the links :
- [ ] contract_request_id in the link should be the same as contract_request id in the request ({{host}}/api/contract_requests/**{{contract_request_id}}**)

**Comment by IrinaRevutska** [comment]
@marinakr , please, add folders to the links like this :{{host}}/api/contract_requests/{{contract_request_id}}/*media* for pdf files
{{host}}/api/contract_requests/{{contract_request_id}}/*signed_content* for signed_content

**Comment by lymychp** [comment]
@AlexKovalevych please support

**Comment by AlekzandrV** [comment]
Tested
