### ISSUE TITLE
Provide NHS portal content

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#254]
https://nhs.ehealth-ukraine.org/

### Блока Статистика
- нужно понимание какие графики нужны на сайте. И какие данные там будут отобржаться. У нас в дизайне есть пример только одного графика по количеству деклараций в разрезе областей

Обо всех остальных графиков нужны пожелания и данные

### Блок Пояснення
- нужны статьи

### Документы
- нужны документы

### Контакты
- нужны адреса, контактные телефоны и email для связи

**Comment by IrynaShevch** [comment]
блок статистика, документі, пояснення - направила на Диану, работаем
также работаем над инфографикой "як це працює"
контакти кидаю диане в слак

**Comment by SmartBBC** [comment]
Контент знаходиться за посиланням:
https://www.dropbox.com/sh/6pag34ydoao5qv7/AABMlf4TFgrSdtmDPMWadsefa?dl=0
Надалі, якщо щось буде оновлюватися або додаватися, то потраплятиме сюди ж

**Comment by lymychp** [comment]
@IrynaShevch please approve
