### ISSUE TITLE
add array element to error msg

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2540]
In case there are 10 or more employees in contractor_employee_divisions it is difficult to find not active one
{
"meta": {
"url": "http://api-svc.il/api/contract_requests/9d8bfda5-5bff-490d-9f33-9cfc9acabdf7",
"type": "object",
"request_id": "1fc6a41d-17bf-44d5-8b6d-b520c575c5ee#17983",
"code": 422
},
"error": {
"type": "validation_failed",
"message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
"invalid": [
{
"rules": [
{
"rule": "invalid",
"params": [],
"description": "Employee must be active DOCTOR"
}
],
"entry_type": "json_data_property",
"entry": "$.contractor_employee_divisions.employee_id"
}
]
}

**Comment by danakonovalenko** [comment]
@svetavedmed I tested this case and this will return the error of the first invalid legal entity occurrence, not the list of errors (same as in task #2497). If it's ok then both those tasks can be closed

**Comment by danakonovalenko** [comment]
in case we have 3 contractor_employee_divisions elements and next situation
``
[0]: employee.status='DISMISSED' & divisions.status='active'
[1]: employee.status='APPROVED' & divisions.status='closed'
[2]: employee.status='DISMISSED' & divisions.status='closed'
```
the 422 error is next
```
{
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Employee must be active DOCTOR"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.contractor_employee_divisions[0].employee_id"
            },
            {
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Employee must be active DOCTOR"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.contractor_employee_divisions[2].employee_id"
            }
```
there is no error as for division for [1].
However, if all of them APPROVED then the error is next:
```
{
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Division is not active"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.contractor_divisions[1]"
            }
```
only for [1], not for [1] and [2]

**Comment by danakonovalenko** [comment]
it was decided to show first type of mistakes, not the whole list
