### ISSUE TITLE
Refactor ops and IL cron jobs

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2542]
Currently update all mechanism is using for declarations autotermination and autoapprove,. It is not efficient with the existing volumes.,

Use genstage with small batches by 10 or 100 instead of update all.
- [x] ops.declaration auto-termination
- [x] ops.declaration auto-approve
- [x] ehealth.api.declaration_request auto-termination.

**Comment by lymychp** [comment]
related to https://github.com/ehealth-ua/api-spec/issues/479

**Comment by marinakr** [comment]
For now looks like problem in search declarations for terminate, so reduce batches from 1000 to 500 and change select + indexes
