### ISSUE TITLE
Contract Termination

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2548]
As for now for MSP it's possible to have multiples contracts within same dates.
When one contract have been already signed and another contracts in the process of signing as we terminate only pending contract requests, not contracts.
There are 2 solutions:
1. add logic to Contract Request sign by msp
```
 Find there is no contracts 
for same contractor_legal_entity_id
within same period [start_date, end_date]
status = VERIFIED
id_form
In case there is such contract change its' status to 'TERMINATE' and fetch 
all records in contract_employees by contract_id and end_date is null
set for those records end_date=$contract_request.start_date
```
2. add same logic to Create Contract Request and show the error `There is an active contract. Contract number must be sent in request`

**Comment by danakonovalenko** [comment]
It was decided to stay with second decision.
So, for endpoint Create contract Request must be added verification whether exists VERIFIED contract within same days as in contract request. In case there is such contract and contract_number wasn't sent in json show 422 error  `Active contract is found. Contract number must be sent in request`
@AlexKovalevych please, assign somebody to this task

**Comment by AlekzandrV** [comment]
Conditions:
There are no other active `contracts` created by this legal_entity_id in this period:
```
not exists (
...
where contract.contractor_legal_entity_id = contract_request.contractor_legal_entity_id
and contract.status in ('VERIFIED')
and contract_request.start_date < contract.end_date
and contract_request.end_date > contract.start_date
)
```
