### ISSUE TITLE
declaration request termination logic change

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2561]
1. As a eHealth user
I want the declaration requests to become expired only if it hasn't been signed in time
So that I wouldn't get declaration linked with the expired declaration request

At the same time
As a NHS admin
I want the `data` field to be erased  after the `declaration_request_expiration` period passed without the status changes
So that there will no personal data in the IL database 

2. All the existing declaration_requests.status == `expired` should be migrated to the status values that was before `expired`.

related to #2542 , it is recommended to implement it together.

**Comment by marinakr** [comment]
implement return statuses with postgresql foreign data wrapper

**Comment by marinakr** [comment]
Important!
