### ISSUE TITLE
Capitation report performance testing

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2581]
Test capitation report creation on big set of data.

**Comment by lymychp** [comment]
@imax-iva please add the test results

**Comment by imax-iva** [comment]
Testing results on dev

Input
Contracts: 65
Contract employees: 166
Declarations: 20,519
Declarations status history: 30,883
Persons: 660,501
Divisions: 1,265
Legal entities: 218

Output
Status: OK
Report details: 20
Total declaration count: 507,501
Process time: less 1 hour

**Comment by imax-iva** [comment]
Testing results on pre-prod

Input
Contracts: 1,312
Contract employees: 291,522
Declarations: 16,010,226
Declarations status history: 16,653,818
Persons: 15,694,250
Divisions: 10,539
Legal entities: 1,354

Output
Status: OK
Report details: 13,120
Total declaration count: 15,609,794
Process time: about 1.5 days
