### ISSUE TITLE
nhs_signed_date is empty

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2586]
After signing contract by NHS Admin nhs_signed_at is empty
ex. contract_request id = 18b27785-dbe5-4e54-b3ca-3b8d2faaaa24
status = NHS_SIGNED

on `curl -X PATCH \
  https://api.dev.asclepius.com.ua/api/contract_requests/18b27785-dbe5-4e54-b3ca-3b8d2faaaa24/actions/sign_nhs \` set nhs_signed_date=now()

**Comment by magiccookie** [comment]
same for msp?
