### ISSUE TITLE
Get Сontract employees by contract_id

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2594]
[apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-get-contract-employees)
[confluense](https://edenlab.atlassian.net/wiki/x/JgC1Hw)

**Comment by svetavedmed** [comment]
show end_date and start date as a date only 
` "start_date": "2018-06-20T00:00:00.000000",`

**Comment by danakonovalenko** [comment]
`end_date` in response is always null even for deactivated employees

**Comment by imax-iva** [comment]
"Is_active" search parameter is true by default. So you can see activated only (is_active = true or by default) or deactivated only employees (is_active = false), not all of them.

**Comment by AlekzandrV** [comment]
It was my proposal
