### ISSUE TITLE
Contract Request List response improvement

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2597]
We need to enrich response for Contract Request list and to show not only id in response.
- [ ] change response according to [spec](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contract-request/public.-get-contract-requests-list)
- [ ] is it possible to add edrpou to filter? in case it is, please add edrpou to filter filelds

**Comment by AlekzandrV** [comment]
Just for information. This change will impact MIS implementation. We should somehow mitigate effects

**Comment by danakonovalenko** [comment]
will be changed only for NHS route
