### ISSUE TITLE
Get employees in contract 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2599]
HR must be able to get employees which belongs to contract.
In order to do that WS must be implemented 
- [ ] [confluence](https://edenlab.atlassian.net/wiki/x/JgC1Hw) / [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contracts/public.-get-contract-employees)
- [ ] implement
- [ ] test

**Comment by lymychp** [comment]
duplicates #2594
