### ISSUE TITLE
Declaration requests for patients with age<14

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2623]
In case patient age<14 confidant_person should be mandatory in declaration request  

If person age < 14 check existence of confidant_person
 - in case error return 422 - msg "Confidant person is mandatory for children"

**Comment by danakonovalenko** [comment]
@svetavedmed patient age<14 still can make declaration request without confidant person in case this patient has DS and tax_id.
For combined method (when person and declaration are in one request) tested and done

**Comment by svetavedmed** [comment]
on POST http://ehealth.edenlabllc.com/api/cabinet/declaration_requests
check persons age. 
If person age < 14 check existence of confidant_person
 - in case error return 422 - msg "Confidant person is mandatory for children"
