### ISSUE TITLE
Change Get Medication Request Response

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2627]
Response in Get Medication Request by ID in apiary and as for now are different. Change response to the one as in [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-reimbursement/medication-request/get-medication-request-by-id).

**Comment by magiccookie** [comment]
Please, update apiary response example and note which field should be updated.

#2631 will add employee.division block as it was denoted in https://github.com/edenlabllc/ehealth.api/issues/2484#issuecomment-400854118

**Comment by danakonovalenko** [comment]
I compared response from apiary to actual response and highlighted difference.
@AlekzandrV please review and advice whether we should adjust apiary or fix actual response (keep in mind that there is the same situation with medication dispense)
https://docs.google.com/document/d/1k90iXPLV2rpH3HgxolrQBeoHO-rV_1h6tyjTH4p5Z98/edit?usp=sharing
