### ISSUE TITLE
Suspended contract improvement  

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2628]
to suspend contract we need to check not only for employee_id=contractor_owner_id, but for every employee_id take party_id and check whether every employee_id <> contractor_owner_id
- [x] spec
- [x] implement 
- [ ] test

**Comment by magiccookie** [comment]
which endpoint?

**Comment by danakonovalenko** [comment]
Endpoints:
api/employee_requests/{{employee_request_id_to_approve}}/approve
api/employees/{{id}}/actions/deactivate

**Comment by svetavedmed** [comment]
employee.id=77bf24a3-5542-46d1-b4cb-1c3a8682e35f is a contract owner in contract.id=7f028a96-530c-4096-9914-f122b237b55c
I have changed name of party.id='079c4978-e830-4a7c-8051-e0d8ceceed46' via "employee_id": "57adaf96-7afa-483e-b4a4-42d6a50ebb87"
but contract is still "is_suspended": false

**Comment by svetavedmed** [comment]
I created a new employee with party.id='079c4978-e830-4a7c-8051-e0d8ceceed46', but nothing was changed, nevertheless contract.id=63197ba9-7e52-44f3-8a7a-9ee8cd4ce733 changed is_suspended=false to true
While it should not, only if party was changed, contract should be with is_suspended=true
