### ISSUE TITLE
Authorization error on PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2649]
Some registered users of auth.ehealth-ukraine.org couldn't enter to portal.

When you try to authorize nothing happens 
When you try to change the password after entering the email, it writes that such user with this email does not exist.

Examples: https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

**Comment by lymychp** [comment]
по обидвох користувачах `salamahasf@ukr.net` та `groun-azpsm@ukr.net`:  успішно ініціював процес відновлення паролю на вказаний емейл.
![image](https://user-images.githubusercontent.com/5257001/42625354-35dfc454-85d0-11e8-9bfb-c3443b3bbac2.png)
![image](https://user-images.githubusercontent.com/5257001/42625316-20900fc8-85d0-11e8-9399-61bf61bd3bad.png)

Можливо, запити взагалі не доходять до ЦК. Наприклад, відбиваються на рівні провайдера або cloudflare по причині вірусів, застарілої версії софта, аномальної активності з хоста або IP клієнта. 
Перевірте, будь ласка, якщо проблема не в цьому, прошу надати лог респонсу на credential_recovery_request з консолі браузера.

**Comment by lymychp** [comment]
no feedback provided
