### ISSUE TITLE
Authorization error on DEMO in IE

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2652]
As a user of IE after request on demo environment:

https://auth.demo.asclepius.com.ua/sign-in?client_id=ed46ea49-ff14-42e7-8b2f-c2019b4f60c5&redirect_uri=http:%2f%2fe-life.com.ua%2f&scope=client:read+legal_entity:read+employee_request:read+employee_request:write+employee_request:approve+employee_request:reject+employee:read+employee:write+employee:details+employee:deactivate+division:write+division:read+division:details+division:activate+division:deactivate+declaration_request:write+declaration_request:approve+declaration_request:reject+declaration_request:read+declaration:read+otp:read+otp:write+person:read+contract_request:create&email=syrogozy%2bdemoNemyr1%40gmail.com

in Internet Explorer-і ( even v.11), 
we get an error: 
Объект не поддерживает свойство или метод "entries"

In prod and preprod env there is no such error.

**Comment by lymychp** [comment]
fixed on demo.
please check

**Comment by lymychp** [comment]
@andriy-ilin FYI

**Comment by AlekzandrV** [comment]
@kiurchv @andriy-ilin guys, do we have any updates on issue?

**Comment by lymychp** [comment]
released to demo @ehealthua-tech please check

**Comment by ehealthua-tech** [comment]
work fine! thank you!
