### ISSUE TITLE
Error 422 after scope extention for "Керівник закладу ОЗ" on PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2658]
Error 422 after scope extention for "Керівник закладу ОЗ" on PROD

Steps to Reproduce 
1) scopes update by owner.
2) The requested scopes match the list for owner
(https://edenlab.atlassian.net/wiki/spaces/EH/pages/2004415/Scopes+model)
3)  request url - http://api-svc.mithril/oauth/apps/authorize

Actual result
  error message - "User requested scope that is not allowed by role based access policies."
Expected result
  scope extension and token update
additional info #2
https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

**Comment by lymychp** [comment]
try to reproduce using list of scopes from the [roles endpoint](https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/roles/list-roles)

**Comment by lymychp** [comment]
any updates? does it work?

**Comment by ehealthua-tech** [comment]
reproduce using list of scopes from the roles endpoint:
{ “scope”: “client:read declaration:read declaration_request:approve declaration_request:read declaration_request:reject declaration_request:write division:activate division:deactivate division:details division:read division:write employee:deactivate employee:details employee:read employee:write employee_request:approve employee_request:read employee_request:reject employee_request:write legal_entity:read otp:read otp:write person:read reimbursement_report:read secret:refresh capitation_report:read contract_request:create contract_request:read contract_request:terminate contract_request:approve contract_request:sign contract:read contract:write”, “name”: “OWNER”, “id”: “a677e2b7-13c3-4361-982f-73f92f3c0aa4" }
,

**Comment by lymychp** [comment]
user with the email provide is doesn't have owner role.
Please use the proper login.
