### ISSUE TITLE
GET ../api/contract_requests/id does not return legalEntity

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2659]
DEMO env.

after create contract request with external contractor,  the answer is returned successfully "legal_entity_id": "0f5b69ab-3e7d-4339-8e6d-3b8f7ac75b5c", 
But  Get Contract Request Details with the same request it is returned an empty object legalEntity:
"legal_entity": {}

[createContrReq.txt](https://github.com/edenlabllc/ehealth.api/files/2190454/createContrReq.txt)
[getContrReq.txt](https://github.com/edenlabllc/ehealth.api/files/2190455/getContrReq.txt)

**Comment by ehealthua-tech** [comment]
the same story with contractor_payment_details.mfo.

It is also empty

**Comment by danakonovalenko** [comment]
contractar_legal_entity in task description and in attached documents are different legal entities.
Get contract details GET  https://api.demo.asclepius.com.ua/api/contract_requests/04a86b10-0f21-418d-a4ec-8697f498de25 returns next response:
```
"contractor_legal_entity": {
            "name": "Трамвай-8-джейсон2-мин33333",
            "id": "7f26e6d4-408f-49ff-b5be-eae8a8e8fc69",
            "edrpou": "3067005717",
            "addresses": [
```
```
"contractor_payment_details": {
            "payer_account": "32009102701026",
            "bank_name": "Банк номер 1",
            "MFO": "351005"
        }
```
There is an empty legal entity in external_contractors
```
[
            {
                "legal_entity": {},
                "divisions": [
                    {
                        "name": "Туец",
                        "medical_service": "PHC_SERVICES",
                        "id": "758bac76-cd21-4d49-8f63-fd65de0c60c5"
                    }
                ]
```
which is related to task #2680 and will be fixed with next release

**Comment by lymychp** [comment]
fixed on demo

**Comment by ehealthua-tech** [comment]
На демо все работает, только осталась такая же проблема с contractor_payment_details.mfo

**Comment by danakonovalenko** [comment]
Можете пояснити детальніше в чому проблема. На виклик 
```
GET \
https://api.demo.asclepius.com.ua/api/contract_requests/04a86b10-0f21-418d-a4ec-8697f498de25 
```

отримую настпуний респонс 

```
"contractor_payment_details": {
            "payer_account": "32009102701026",
            "bank_name": "Банк номер 1",
            "MFO": "351005"
        },
```
