### ISSUE TITLE
Error 500 Internal server error after declaration signing PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2673]
After declaration signing user gets at error 500 Internal server error.

{
    "meta": {
        "url": "http://api-svc.il/api/declaration_requests/2aca86da-9212-417b-9944-fd36e2a39363/actions/sign", 
        "code": 500, 
        "type": "object", 
        "request_id": "96f3d8f4-5b64-42b8-9635-3e7196769368#153295"
    }, 
    "error": {
        "errors": {
            "detail": "Internal server error"
        }
    }
}

Please see files: request.json, request_body.json, response.json here:
https://drive.google.com/drive/u/0/folders/1C_wkXMdDHKOrswHI1ZE4VjanR2YotFsN

**Comment by ehealthua-tech** [comment]
the same problem from other user:

{"meta":

{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"4a9af8e3-f56f-4566-9124-45c4fdfcef63#102410","code":500}
,"error":{"errors":{"detail":"Internal server error"}},"code":500}

**Comment by lymychp** [comment]
this kind of issues might happen 13.07.2018  only between 12:55-13:10. Was related to the index rebuilding.
