### ISSUE TITLE
change error msg

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2688]
change error msg on 
- sign_nhs with wrong date, msg ("Start date must be greater than create date")
- sign_nhs with closed LE, msg ("Legal entity must be Active")
- sign_nhs with inactive OWNER ("Contractor owner must be an active OWNER or ADMIN and within current legal entity in contract request")

**Comment by danakonovalenko** [comment]
tested
- `Start date must be greater than current date`
- `Legal entity is not active`
- `Contractor owner must be active within current legal entity in contract request`
