### ISSUE TITLE
add employee from another LE to contract

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2690]
it should be forbidden to add employees from another LE to contract
check if $employee.legal_entity_id = tokens.client_id
in case error return 422 (Employee should be active Doctor within current legal_entity_id )

**Comment by danakonovalenko** [comment]
I added employee (id='67043283-586f-4ffd-8f3e-3b439db8419f') with `legal_entity_id = 'c8aadb87-ecb9-41ca-9ad4-ffdfe1dd89c9'` to contract with `contractor_legal_entity_id='41ebae5e-c269-491f-9f78-05bfdae5e397'`.
contract_request_id='de906505-0d90-469c-be7a-71b033354d18'

**Comment by svetavedmed** [comment]
error with contract_request moved to #2765
