### ISSUE TITLE
Scope does not allow to UpdateContractEmployees

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2697]
As an owner I want to update contract employe but after UpdateContractEmployee get 403 Forbidden (message=Your scope does not allow to access this resource. Missing allowances: contract:write)
Health24, token use as owner

details log:
https://drive.google.com/drive/u/0/folders/1rp7w5qHCvGrBFfe_9qztjY_43kqOTvBm

As a result I want to update contract employee

**Comment by lymychp** [comment]
Реквест відправляється не по специфікації.
Має бути 
```
{
  "signed_content":  "",
  "signed_content_encoding": "base64"
}
```

А в прикладі 
```
{
"signed_legal_entity_request":"",
"signed_content_encoding":"base64"
}

**Comment by lymychp** [comment]
не факт, що проблема в цьому, але як мінімум варто повторити по документації

**Comment by AlekzandrV** [comment]
Виправлено на ДЕМО. Прошу перевірити
