### ISSUE TITLE
ADMIN doesn't have a scope person:read

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2698]
As an ADMIN I could sign a declaration but
I want to see them.
So, please add to ADMIN scope person:read

**Comment by AlekzandrV** [comment]
ADMIN role already has scope `person:read`

Checked on:
* DEV
* DEMO
* PROD

**Comment by AlekzandrV** [comment]
Is this problem still valid?
If so, provide more details please

**Comment by ehealthua-tech** [comment]
Закрываю тике, спасибо
