### ISSUE TITLE
Set up new endpoint for apps in Patient cabinet

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.api#2699]
As any eHealth user
I want to be able to view/manage/delete approvals(tokens) that are linked with my account
So that I can manage access to my personal data.

We have [approvals data model](https://mithrilapi.docs.apiary.io/#reference/0/approvals/get-approvals) in mithril, but we need set up new endpoint on GW: GET, DELETE /api/mithril/apps

**Comment by marinakr** [comment]
@ephor  @AlekzandrV @danakonovalenko @svetavedmed @IrinaRevutska  
what users with what access can request approvals of user_id and client_ids?

**Comment by marinakr** [comment]
@AlekzandrV  do we have scopes like approvals:delete, approvals:get:id, approvals:get?
Do we need any cors for this endpoints?

**Comment by marinakr** [comment]
@AlekzandrV  we have trouble in logic: first of all, users have access to delete approvals, but should delete tokens
Users should not have access to delete approvals
And should use another logic to delete token

**Comment by AlekzandrV** [comment]
@marinakr 

### Filter response by user_id

Example
```
  curl 'https://api.dev.asclepius.com.ua/api/admin/apps?page=1&page_size=10' \
  -H 'content-type: application/json' \
  -H 'cookie: meta=d66da3de-5b28-4440-9499-fe2d23ff2201; authorization=ZXZBRmpreitKelY0M3BqLy8wUXR4dz09' --compressed
```

This request must return only one record

### Delete also all tokens for current user_id and client_id
Client_id in tokens table can be found here (details ->> 'client_id')

```
SELECT *
FROM tokens
WHERE (details ->> 'client_id')::uuid = 'e38f2528-0bd5-4aa8-bb22-adb1558e5758'
AND user_id = 'd66da3de-5b28-4440-9499-fe2d23ff2201';
```

There is no approval for this user and client but tokens still exists

**Comment by marinakr** [comment]
```
user_app_path  DELETE  /admin/users/:user_id/apps                                        Mithril.Web.AppController :delete_by_user
                       app_path  GET     /admin/apps                                                       Mithril.Web.AppController :index
                       app_path  GET     /admin/apps/:id                                                   Mithril.Web.AppController :show
                       app_path  POST    /admin/apps                                                       Mithril.Web.AppController :create
                       app_path  PATCH   /admin/apps/:id                                                   Mithril.Web.AppController :update
                                 PUT     /admin/apps/:id                                                   Mithril.Web.AppController :update
                       app_path  DELETE  /admin/apps/:id                                                   Mithril.Web.AppController :delete
```

**Comment by svetavedmed** [comment]
For Mithril Admin we use:
- GET     /admin/apps 
- GET     /admin/apps/:id
- POST    /admin/apps
- PATCH   /admin/apps/:id
- DELETE  /admin/apps/:id
