### ISSUE TITLE
Impossible to registrate legal_entity with test key DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2707]
As a MIS (Доктор Елекс) I coudn't registrate legal_entity with test key

See logs 5 item in file: https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

<error><code>422</code><description>UnprocessableEntity</description><body>{
"meta":

{ "url": "http://api-svc.il/api/legal_entities", "type": "object", "request_id": "fc95e686-572c-4fb0-bba4-e70f79a0f681#38311", "code": 422 }
,
"error": {
"type": "validation_failed",
"message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
"invalid": [
{
"rules": [

{ "rule": "invalid", "params": [ ], "description": "invalid tax_id value" }
],
"entry_type": "json_data_property",
"entry": "$.owner.tax_id"
}
]
}
}</body></error>

**Comment by lymychp** [comment]
Test key should be used only to sign contract request from the NHS side. Use your own keys to create new contract requests. And ensure that owner’s tax-id match with the drfi from the DS
