### ISSUE TITLE
501 Internal error after Get Contract Request Printout Content DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2711]
При виклику GET запиту 
https://api.demo.asclepius.com.ua/api/contract_requests/df8ee83a-9c93-4ed7-9e78-0f362fc1d068/printout_content, 

отримуємо наступну помилку: 

{ 
    "meta": { 
        "url": "http://api-svc.il/api/contract_requests/df8ee83a-9c93-4ed7-9e78-0f362fc1d068/printout_content", 
        "type": "object", 
        "request_id": "b2cf0ad1-9b47-4d60-9603-577d4167130e#40221", 
        "code": 501 
    }, 
    "error": { 
        "type": "internal_error" 
    } 
} 

В зв'язку з чим не можемо закінчити проходження сценарію підпису договору. 
Сьогодні вдень сценарій був успішно пройдений. 

Expected results:
Отримати відповідь з заповненим атрибутом "printout_content"

**Comment by lymychp** [comment]
should work now. Please let me know in case if it is not.
