### ISSUE TITLE
Incorrect status of contract_request to modify it

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2712]
MIS: MEDSTAR
Steps to reproduce:
Согласно документации https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/public.-terminate-contract-request-by-msp: 
This WS is designed to terminate contract request by contractor. Contract request can't be in status='SIGNED' 
Есть контракты в статусе "SIGNED". При попытке прекратить их действие получаю ошибку: Incorrect status of contract_request to modify it

error:
{
"meta":

{ "url": "http://api-svc.il/api/contract_requests/c51c8f12-7f46-4836-9d19-a1a27e07ed13/actions/terminate/", "code": 422, "type": "object", "request_id": "150641d4-fe37-43ac-ac45-27d75a65dc11#40941" }
, 
"error": {
"message": "Incorrect status of contract_request to modify it", 
"type": "request_malformed", 
"invalid": [
{
"rules": [

{ "rule": "json" }
], 
"entry_type": "request"
}
]
}
}

Expected results:
прекращение действия контракта

**Comment by lymychp** [comment]
Ви ж в тікеті зсилаєтесь на документацію, де вказано, що реквести в статусі ‚signed’ не можна відміняти. Тому і отримуєте коректну відповідь
