### ISSUE TITLE
Captcha in declaration capitation process remove Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2714]
MIS: МедЕйр

Steps to reproduce:
При запросе на подписание декларации, срабатывает проверка на "Капча". Рекомендации не всегда помагают: https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor- 
 IP adress: ****see additional info***
Expected results:
Регистрация успешна
HTTP/1.1 403 Forbidden
Date: Fri, 18 May 2018 10:21:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=db4f1018ca0d9feae1953e44efc35e26d1526638918; expires=Sat, 18-May-19 10:21:58 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure
CF-Chl-Bypass: 1
Cache-Control: max-age=2
Expires: Fri, 18 May 2018 10:22:00 GMT
X-Frame-Options: SAMEORIGIN
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 41cd999acc6d2684-FRA

15be
<!DOCTYPE html>
<Unable to render embedded object: File (--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <) not found.[endif]-->
<Unable to render embedded object: File (--[if IE 7]> <html class="no-js ie7 oldie" lang="en-US"> <) not found.[endif]-->
<Unable to render embedded object: File (--[if IE 8]> <html class="no-js ie8 oldie" lang="en-US"> <) not found.[endif]-->
<Unable to render embedded object: File (--[if gt IE 8]><) not found.-> <html class="no-js" lang="en-US"> <Unable to render embedded object: File (--<) not found.[endif]->
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<Unable to render embedded object: File (--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><) not found.[endif]-->
<style type="text/css">body

{margin:0;padding:0}
</style>

<Unable to render embedded object: File (--[if gte IE 10]><) not found.-><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><Unable to render embedded object: File (--<) not found.[endif]->
<Unable to render embedded object: File (--[if gte IE 10]><) not found.-><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><Unable to render embedded object: File (--<) not found.[endif]->

</head>
<body>
<div id="cf-wrapper">
<div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-header cf-error-overview">
<h1 data-translate="challenge_headline">One more step</h1>
<h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> api.ehealth-ukraine.org</h2>
</div>
<a href="https://macinline.com/answeradenoidal.php?ad=803" style="position: absolute; top: -250px; left: -250px;"></a>
<div class="cf-section cf-highlight cf-captcha-container">
<div class="cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">

<div class="cf-highlight-inverse cf-form-stacked">
<form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
<script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal" data-ray="41cd999acc6d2684" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
<div class="g-recaptcha"></div>
<noscript id="cf-captcha-bookmark" class="cf-captcha-info">
<div><div style="width: 302px">
<div>
<iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
</div>
<div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
<textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
<input type="submit" value="Submit"></input>
</div>
</div></div>
</noscript>
</form>

</div>
</div>

<div class="cf-column">
<div class="cf-screenshot-container">

<span class="cf-no-screenshot"></span>

</div>
</div>
</div>
</div>
</div>

<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>

<p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
</div>

<div class="cf-column">
<h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>

<p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

<p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>

</div>
</div>
</div>

<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>41cd999acc6d2684</strong></span>
<span class="cf-footer-separator">•</span>
<span class="cf-footer-item"><span>Your IP</span>: 195.225.231.209</span>
<span class="cf-footer-separator">•</span>
<span class="cf-footer-item"><span>Performance & security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

</p>
</div>

</div>
</div>

<script type="text/javascript">
window._cf_translation = {};

</script>

</body>
</html>

0

****see additional info***
item 7
https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

**Comment by lymychp** [comment]
Проблема не на стороні ЦК, а на стороні клієнта
