### ISSUE TITLE
GET CONTRACT EMPLOYEES with parameter page_size DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2732]
Steps to reproduce:

/contracts/contract_id/employees?page_size=100 
Коли передаєш параметр page_size, приходить 500 помилика + в документації сказано, що 
page_size - Default: 1000, але в paging приходить page_size: 50.

Expected results:
200

Error:
{
"meta":

{ "url": "http://api-svc.il/api/contracts/4ff63453-8488-4241-b256-dad54c46a638/employees", "type": "object", "request_id": "00ea7ef4-7ef1-4f7a-9ddb-e909b7867a8d#43829", "code": 500 }
,
"error": {
"errors":

{ "detail": "Internal server error" }
},
"code": 500
}

s-110

**Comment by danakonovalenko** [comment]
related to Get contracts employees page size #2736

**Comment by lymychp** [comment]
fixed on demo. Також виправили помилку в документації. Max page_size = 500. Default = 50.
