### ISSUE TITLE
creating duplicates contractor_employee_divisions  when update employee, contracts, DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2733]
дубли contractor_employee_divisions при обновлении сотрудника по контракту

Steps to reproduce:
url: 
/contracts/6f769899-8857-4d97-b503-22d4c189b787/employees/actions/update/ 
{ 
    "signed_content": 
**additional info ***

Expected results:
обновление а не добавление дубля сотрудника

Error:
при запросе /contracts/6f769899-8857-4d97-b503-22d4c189b787/
получаю:
{
"urgent": {
"documents": [
{ "url": "https://storage.googleapis.com/contract-requests-dev/54db57c9-f7aa-42e0-ab36-1fc6572eb316/signed_content/signed_content?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1531925288&Signature=TV1yk6xo%2BrspSGTzS6xT9R%2FqJMkDaRjYvYH4eYc9OaPt2fvN%2FTEJL6zRmwwt5jvfaNnNPBX0ldZ9fypB8lYETR8OYaB4vHPNc%2Fl3V%2BTgVQsqKM1wkmGc%2B6BJ%2FC44VT7%2BkaN7hquhCJ%2FGrjtSoLgDKe879NYygkFEBIG75AmQJDeJmCkFsFA8YbFnzCyNX2RvcshBIecUwirzYaFajODKrS7S575x4KWoYa9USyXjird4InbEs8d65SO6rZq6%2BKMSD7tCneq9kvg6Ip2VdPxtpaEszXZ8D5N4JuLHbI9vsCRZsCwjeOg%2Bdo0CbKc12ps3Ox%2BSr1ezBpsjZilyj3qP%2FA%3D%3D", "type": "SIGNED_CONTENT" }
, 
{ "url": "https://storage.googleapis.com/contract-requests-dev/54db57c9-f7aa-42e0-ab36-1fc6572eb316/media/contract_request_additional_document.pdf?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1531925288&Signature=e5EmEgx8yTR7lotth87INLvo6rhExy1sF0JBEaxPmuHBOKO9G4bmsC9Y8CbsjMSrCVGlTS7cyNQPXaTad6v4C2fSrotwqm2EBdRcloXMdY77GmBo4Qc0dhDWbgZYlbvr06BHPpEMPVrNfUzNIFVp%2FgmPyuMGVMy0pwBD4Zt%2FKc3R%2B3neBDI079SXFzyohKsRnQyvYNX3qlrm4NaybxALbFRweZ0EgSB7nlmH%2Bvs3%2FdMBt3rO74FmHP%2FTJQvC4BQ6z5d3H9%2FwiumQtEChutzuhPE5sNvWQAOkaL8hTeA%2Bs0RZHqyXPFlOsjbZyl8FEm3sowxOE8SLFbfsAOpLINHncg%3D%3D", "type": "CONTRACT_REQUEST_ADDITIONAL_DOCUMENT" }
,

****additional information****
, 
"nhs_contract_price": 50000.0, 
"contractor_base": "на підставі закону про Медичне обслуговування населення", 
"issue_city": "Київ", 
"contractor_owner": {
"party":

{ "first_name": "Врач", "last_name": "Главний", "second_name": "Новий" }
, 
"id": "9a2028eb-2651-4b9b-98bf-7109ee08d0f7"
}, 
"nhs_payment_method": "FORWARD"
}
}

****additional information**** = item 9
https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

s-109

**Comment by danakonovalenko** [comment]
related to Get Contract Details #2737
