### ISSUE TITLE
do not find declarations for their requests, although they were successfully signed, PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2734]
MIS: Поліклініка без черг.

Лікар успішно підписав декларації, був статус active (зі слів лікаря). Пізніше декларація перестала відображатися. Намагалися знайти декларації по їх запитам, але безуспішно. Прохання дати відповідь чому декларації могли зникнути. Чи можна їх поновити? 

employee_id : ****additional info ***
declaration_request_id: ****additional info ***

****additional info *** = item 10 
https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

**Comment by lymychp** [comment]
з усього списку наданих declaration_requests тільки один був створений в системі і той вже в статусі expired - `c4dd6aa9-facf-4f37-9323-d73a9fc15295`
Перевірте по логах МІСу чи були передані в ЦК дані запити. Якщо так - прошу надати логи.
