### ISSUE TITLE
update contract error 409 request_conflict DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2735]
При обновлении существующего контракта через CreateContractRequest с указанием contract_number возникает ошибка

****additional info *** item 11
https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

Ожидаемый результат: обновление контракта

s-111

**Comment by danakonovalenko** [comment]
з таким id вже є contract request від 2018-07-13. Потрібно знову ініціювати запит на контракт, завантажити документи та з новим id передати існуючий contract_number.

**Comment by lymychp** [comment]
duplicates https://github.com/ehealth-ua/api-spec/issues/545
