### ISSUE TITLE
Error with 'Sign Contract Request by NHS'

### ISSUE THREAD

**Issue by olegit4med** [edenlabllc/ehealth.api#2749]
While making request to "Private. Sign Contract Request by NHS" same error occurs 'document must be signed by 1 signer but contains 0 signatures'. 
This error doesn't appear with older p7s files.

**Comment by ehealthua-tech** [comment]
You have to leave your tickets here according template: 
https://e-health-ua.atlassian.net/servicedesk/customer/portal/3
There is no technical support from developers.

Thank you for patience
