### ISSUE TITLE
Problems with declaration limits when sign PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2750]
**Steps to reproduce:**
Користувач не можу підписувати декларації 
Висвітлюється помилка, що перевищено ліміт декларацій, хоча їх лише 1429, а у користувача повна ставка. 

**Запит** 
https://api.ehealth-ukraine.org/api/declaration_requests/321bb0b9-4a3c-4e5b-9ec9-649cdf75b630/actions/approve 

employee_id: 830dcad8-7cee-4ade-ac02-818bbee243ab 

Кількість декларацій: 
 "paging": { 
        "total_pages": 29, 
        "total_entries": 1429, 
        "page_size": 50, 
        "page_number": 1 
    } 

**Expected results:**
Підписання нової декларації

**Error**
<error><code>422</code><description>UnprocessableEntity</description><body>{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/321bb0b9-4a3c-4e5b-9ec9-649cdf75b630/actions/approve", "type": "object", "request_id": "ac00cf0f-d24d-44b1-a7c9-25a8cbc86beb#112921", "code": 422 }
,
"error": {
"type": "request_malformed",
"message": "This doctor reaches his limit and could not sign more declarations",
"invalid": [
{
"rules": [

{ "rule": "json" }
],
"entry_type": "request"
}
]
}
}</body></error>

**Comment by AlekzandrV** [comment]
У данного человека зарегистрирован еще один сотрудник в другом подразделении у которого тоже есть декларации. Их сумма достигает лимита
