### ISSUE TITLE
NHS Admin Crash

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#2755]
## Steps to reproduce:

1. Go to Declaration
2. Reload this page

<img width="1440" alt="screen shot 2018-07-19 at 20 59 08" src="https://user-images.githubusercontent.com/12275915/42961295-173c67d8-8b97-11e8-9c2e-17fad150b277.png">

**Comment by andriy-ilin** [comment]
Bug on old PaginationComponent and will be fixed after migration admin repo to web repo

**Comment by lymychp** [comment]
it is still crashing on preprod
