### ISSUE TITLE
Error when request Private. Sign Contract Request by NHS use DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2760]
Steps to reproduce:
Здійснити запит http://api.demo.asclepius.com.ua/api/contract_requests/6d47c95e-0f5c-4e1a-ace3-959c705a49d8/actions/sign_nhs 
з body у прикріпленому файлі. 
Виникає помилка "document must be signed by 1 signer but contains 0 signatures". 
З файлами підписаними раніше ця помилка не виникає.
Expected results:
Успішно виконана операція чи якась інша помилка.

Error:
{
"meta":

{ "url": "http://api-svc.il/api/contract_requests/6d47c95e-0f5c-4e1a-ace3-959c705a49d8/actions/sign_nhs", "type": "object", "request_id": "fc95e686-572c-4fb0-bba4-e70f79a0f681#44069", "code": 400 }
,
"error": {
"type": "request_malformed",
"message": "document must be signed by 1 signer but contains 0 signatures",
"invalid": [
{
"rules": [

{ "rule": "json" }
],
"entry_type": "request"
}
]
}
}
additional info
https://drive.google.com/drive/u/0/folders/1TfhiSmlb-SL6Nruf_J3O7JTU0z6M9io6

**Comment by AlekzandrV** [comment]
Документ переданный в пейлоаде не проходит верификацию даже тут 
https://czo.gov.ua/verify

Похоже что подписанный документ на валидный p7s объект

**Comment by AlekzandrV** [comment]
Если проблема имеет место быть - пусть присылает то что подписывает, а также то что после подписания получается
