### ISSUE TITLE
Error get printout after update contract PREPROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2761]
Steps to reproduce:
Ошибка получения printout при обновлении договора
Expected results:
Код 200 и получение printout

Описание ошибки:
D, 2018-07-20T09:15:20.084053 #30159 DEBUG – : [httplog] Connecting: api-preprod.ehealth-ukraine.org:443D, 2018-07-20T09:15:20.193002 #30159 DEBUG – : [httplog] Sending: GET http://api-preprod.ehealth-ukraine.org:443/api/contract_requests/e8bc7d1a-7cce-4b52-b06e-fb8504cde9f0/printout_contentD, 2018-07-20T09:15:20.193145 #30159 DEBUG – : [httplog] Header: content-type: application/jsonD, 2018-07-20T09:15:20.193178 #30159 DEBUG – : [httplog] Header: authorization: Bearer cE5KbGJ6OFpmNy92a0hvd25zeFlzUT09D, 2018-07-20T09:15:20.193196 #30159 DEBUG – : [httplog] Header: api-key: 7a07feaf4c37ef135f85D, 2018-07-20T09:15:20.193211 #30159 DEBUG – : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3D, 2018-07-20T09:15:20.193226 #30159 DEBUG – : [httplog] Header: accept: */*D, 2018-07-20T09:15:20.193272 #30159 DEBUG – : [httplog] Header: user-agent: RubyD, 2018-07-20T09:15:20.193287 #30159 DEBUG – : [httplog] Header: x-newrelic-id: VQ8CVVdVABAFVVFbBAIOXw==D, 2018-07-20T09:15:20.193300 #30159 DEBUG – : [httplog] Header: x-newrelic-transaction: PxRTVAcHAVEFAlZQBgNVUwACFB8EBw8RVU4aBg1ZUAtRUF9WA1ABAFFSBENKQQxSUlZQVw9VFTs=D, 2018-07-20T09:15:20.193314 #30159 DEBUG – : [httplog] Header: connection: closeD, 2018-07-20T09:15:20.193343 #30159 DEBUG – : [httplog] Data: D, 2018-07-20T09:15:20.433506 #30159 DEBUG – : [httplog] Status: 501D, 2018-07-20T09:15:20.433871 #30159 DEBUG – : [httplog] Header: date: Fri, 20 Jul 2018 06:15:20 GMTD, 2018-07-20T09:15:20.434197 #30159 DEBUG – : [httplog] Header: content-type: application/json; charset=utf-8D, 2018-07-20T09:15:20.434616 #30159 DEBUG – : [httplog] Header: content-length: 229D, 2018-07-20T09:15:20.434765 #30159 DEBUG – : [httplog] Header: connection: closeD, 2018-07-20T09:15:20.435038 #30159 DEBUG – : [httplog] Header: set-cookie: __cfduid=dc8039e65d5a8fe9562a9e3346daa7e971532067320; expires=Sat, 20-Jul-19 06:15:20 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; SecureD, 2018-07-20T09:15:20.435140 #30159 DEBUG – : [httplog] Header: cache-control: max-age=0, private, must-revalidateD, 2018-07-20T09:15:20.435188 #30159 DEBUG – : [httplog] Header: vary: Accept-EncodingD, 2018-07-20T09:15:20.435229 #30159 DEBUG – : [httplog] Header: via: kong/0.12.1D, 2018-07-20T09:15:20.435269 #30159 DEBUG – : [httplog] Header: x-content-type-options: nosniffD, 2018-07-20T09:15:20.435308 #30159 DEBUG – : [httplog] Header: x-download-options: noopenD, 2018-07-20T09:15:20.435345 #30159 DEBUG – : [httplog] Header: x-frame-options: SAMEORIGIND, 2018-07-20T09:15:20.435428 #30159 DEBUG – : [httplog] Header: x-kong-proxy-latency: 43D, 2018-07-20T09:15:20.435535 #30159 DEBUG – : [httplog] Header: x-kong-upstream-latency: 80D, 2018-07-20T09:15:20.435579 #30159 DEBUG – : [httplog] Header: x-permitted-cross-domain-policies: noneD, 2018-07-20T09:15:20.435617 #30159 DEBUG – : [httplog] Header: x-request-id: a9e35080-3bba-416a-8ddb-0b608b1d671d#995D, 2018-07-20T09:15:20.435656 #30159 DEBUG – : [httplog] Header: x-xss-protection: 1; mode=blockD, 2018-07-20T09:15:20.435692 #30159 DEBUG – : [httplog] Header: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"D, 2018-07-20T09:15:20.435729 #30159 DEBUG – : [httplog] Header: server: cloudflareD, 2018-07-20T09:15:20.435765 #30159 DEBUG – : [httplog] Header: cf-ray: 43d34af02db19071-DMED, 2018-07-20T09:15:20.435888 #30159 DEBUG – : [httplog] Response:{"meta":

{"url":"http://api-svc.il/api/contract_requests/e8bc7d1a-7cce-4b52-b06e-fb8504cde9f0/printout_content","type":"object","request_id":"a9e35080-3bba-416a-8ddb-0b608b1d671d#995","code":501}
,"error":

{"type":"internal_error"}
}

**Comment by lymychp** [comment]
fixed on preprod
