### ISSUE TITLE
wrong url when initializate a contract_request DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2771]
Ініціалізую новий contract_request, при завантаженні документів отримую наступну помилку 

https://storage.googleapis.com/contract-requests-dev/50943853-76e7-4e51-a0f9-4ca785b3091a/media/upload_contract_request_statute.pdf?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1532090103&Signature=fqkDgykJ%2F9jbbb2wd6yX246DL3nNccZ9RGz54zLjqD%2Bhw4AymQOGbdiKNDNoOr6NjzZSnSPdllZr%2FihC6AUOzvaszQZP%2BjttTSRd0nbF9153qimdTiXih18S7qLwcM4sill0pJiFbM8qdf33gg167TawgHcdEId%2BJKXIQcAw0YuI0fC4tuPTXGGIGkM9%2FlFep8qTiidWS813%2BDRfX5byBOGZgnnZG0t1kTh6752QSBaxHCL8Qw0yZODznILPTi6Wyi5IsQu7whps5v1huqrT%2F%2F2yUY2SjT8nFIg92HVZ6Zdfql3l%2FlQ0ZBVANxUMldnpronjOxQatYWtjLCHpk8V0Q%3D%3D

Expected results:
Успішне завантаження

Error description:
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method

**Comment by AlekzandrV** [comment]
Какой Content-type и формат документа, который загружается?

Должен быть: `application/pdf`

**Comment by ehealthua-tech** [comment]
Помогло. Неправильно указывали формат
