### ISSUE TITLE
2 active owner on legal entity

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2772]
GET /api/employees/aa8eb944-6d4a-4c97-a446-3f1c75009384 возвращает сотрудника со статусом APPROVED и GET /api/employees/356697cf-9c03-4018-8786-75e73021cf8f со статусом APPROVED, id legalEntity один и тот же.

Помимо того, что по бизнес логике это недопустимо, возникает следующая проблема:

GetEmployeeList возвращает только последнего. Как получить в списке первого? Если бы у них отличались статусы, можно было бы добавить статус в фильтр, а так без вариантов.

Первый овнер нужен для отображения его ФИО в контрактах.
https://drive.google.com/drive/u/0/folders/1aPYZm6Ci9uLYQhOzMovETDWpmiFvOO0U

**Comment by AlekzandrV** [comment]
Сервис GetEmployeeList возвращает не последнего, а активного сотрудника с типом OWNER. Неактивный сотрудник не может выступать подписантом в договоре. Валидация это не пропустит

**Comment by ehealthua-tech** [comment]
почему тогда у сотрудника GET /api/employees/aa8eb944-6d4a-4c97-a446-3f1c75009384 статус APPROVED, если он неактивный?

**Comment by danakonovalenko** [comment]
Для  працівника типу OWNER статус не змінюється, змінюється is_active з true на false.
employee_id='aa8eb944-6d4a-4c97-a446-3f1c75009384' деактивований і має is_active=false
