### ISSUE TITLE
Error after request "Private. Sign Contract Request by NHS"

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2780]
Steps to reproduce:
1. Отримати інформацію по запиту на контракт: 
get https://api.demo.asclepius.com.ua/api/contract_requests/d19da925-2110-4414-a161-1d26106a609f 

2. Отримати текст договору: 
get https://api.demo.asclepius.com.ua/api/contract_requests/d19da925-2110-4414-a161-1d26106a609f/printout_content 

3. Скопіювати текст договору в "printout_content" 

4. Підписати json на сайті ca.informjust.ua 

5. Конвертувати p7s файл в base64. 

6. Виконати patch запит (body у вкладеному файлі): 
http://api.demo.asclepius.com.ua/api/contract_requests/d19da925-2110-4414-a161-1d26106a609f/actions/sign_nhs 
Expected results:
Контракт підписано
Описание
{
"meta":

{ "url": "http://api-svc.il/api/contract_requests/d19da925-2110-4414-a161-1d26106a609f/actions/sign_nhs", "type": "object", "request_id": "b2cf0ad1-9b47-4d60-9603-577d4167130e#55271", "code": 422 }
,
"error": {
"type": "request_malformed",
"message": "Signed content does not match the previously created content",
"invalid": [
{
"rules": [

{ "rule": "json" }
],
"entry_type": "request"
}
]
}
}
***additional info***: https://drive.google.com/drive/u/0/folders/1wdzNPoAK7vCjwMd-wRFdfI0l6pe33BXf

-127

**Comment by lymychp** [comment]
З документації:
>Object that need to be signed is returned by Get Contract request by ID, urgent, type='signed_content'. In response will be receive a link to download a file in pkcs7 format (signed by NHS side). This data must be signed.

Пункти 2. та 3. не треба виконувати.

**Comment by danakonovalenko** [comment]
Пункти підписання правильні, @lymychp документацію поправила
Проблема полягає в тому, що з моменту апруву було оновлено contractor_legal_entity_id. 
Договір затверджувався (2018-07-20 11:32:59.964859) для
```
"contractor_legal_entity": {
    "addresses": [
      {
        "apartment": "0",
        "area": "АВТОНОМНА РЕСПУБЛІКА КРИМ",
        "building": "23",
        "country": "UA",
        "region": "БАХЧИСАРАЙСЬКИЙ",
        "settlement": "ПОШТОВЕ",
        "settlement_id": "fc33b9dd-f3d4-4b07-a1cf-857f723b11d7",
        "settlement_type": "TOWNSHIP",
        "street": "леніна",
        "street_type": "BOULEVARD",
        "type": "REGISTRATION",
        "zip": "10472"
      }
    ],
    "edrpou": "41295364",
    "id": "64f63d11-2d1c-4fc2-bd69-3dc83b6eb4f9",
    "name": "Державна обласна клініка імені Тюленя"
  }
```
на момент підписання  мед заклад оновили (2018-07-20 12:32:09.520144)  до
```
"contractor_legal_entity": {
    "addresses": [
      {
        "apartment": "0",
        "area": "МИКОЛАЇВСЬКА",
        "building": "1",
        "country": "UA",
        "settlement": "МИКОЛАЇВ",
        "settlement_id": "1da99ee1-ffa1-4417-b0ce-5d67b9cf42bf",
        "settlement_type": "CITY",
        "street": "Ватутіна",
        "street_type": "STREET",
        "type": "REGISTRATION",
        "zip": "54050"
      }
    ],
    "edrpou": "41295364",
    "id": "64f63d11-2d1c-4fc2-bd69-3dc83b6eb4f9",
    "name": "Меделінський міський наркологічний центр"
  }
```
тому такий договір не може бути підписаним, його необхідно термінувати, вказавши причину і мед заклад має ініціювати новий договір з актуальними даними
