### ISSUE TITLE
Couldn't register employee who doesn't have tax ID PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2781]
Steps to reproduce:
Не можуть зареєструвати лікаря, який з певних причин відмовився від ІПН. 
У поле ІПН вони ввели номер паспорту. 
Поле "no_tax_id": true. 
**additional info: 

Expected results:
Успішно зареєстрований працівник

Описание
<error><code>422</code><description>UnprocessableEntity</description><body>{
"meta":

{ "url": "http://api-svc.il/api/employee_requests", "type": "object", "request_id": "d0162792-2efc-41a3-8a03-69d3b6fa7c1e#49456", "code": 422 }
,
"error": {
"type": "validation_failed",
"message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
"invalid": [
{
"rules": [
{
"rule": "format",
"params": [
"^([0-9]

{9,10}|[А-ЯЁЇIЄҐ]{2}
d{6})$"
],
"description": "string does not match pattern \"^([0-9]{9,10}
|[А-ЯЁЇIЄҐ]

{2}
\\\\d

{6}
)$\""
}
],
"entry_type": "json_data_property",
"entry": "$.employee_request.party.tax_id"
}
]
}
}</body></error>

-125

**Comment by lymychp** [comment]
якщо у лікаря немає ІПН, треба просто передати відповідний признак, Не треба в поле ІПН прописувати номер паспорту

**Comment by ehealthua-tech** [comment]
Согласно API:

tax_id: 3126509816 (string, required) - if no_tax_id=true then passport number, otherwise tax_id

**Comment by lymychp** [comment]
соррі, переплутав з declaration_request.
Перевірте, що номер паспорту точно вписується в "pattern": "^([0-9]{9,10}|[А-ЯЁЇIЄҐ]{2}\\d{6})$"

**Comment by ehealthua-tech** [comment]
Перепроверили, сейчас все ок. Спасибо!
