### ISSUE TITLE
Impossible to sign a contract from NHS side on the last step DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2790]
Steps to reproduce:
Стягую контент із вказаного у contract_request посилання (файлик content). Накладаю свій підпис 
(файлик ContractToSign(10).p7s) і отримую наступну помилку.
Expected results:
Підписаний контракт

Описание
<error><code>422</code><description>UnprocessableEntity</description><body>{
"meta":

{ "url": "http://api-svc.il/api/contract_requests/60cad765-d591-463f-ab20-6b6ba073c577/actions/sign_msp", "type": "object", "request_id": "783dfcf0-c0a1-46f2-80c8-5b90efbb9b1e#1802", "code": 422 }
,
"error": {
"type": "request_malformed",
"message": "Malformed encoded content. Probably, you have encoded corrupted JSON. Error: %Jason.DecodeError

{data: <<48, 239, 191, 189, 1, 31, 239, 191, 189, 6, 9, 42, 239, 191, 189, 72, 239, 191, 189, 239, 191, 189, 13, 1, 7, 2, 239, 191, 189, 239, 191, 189, 1, 31, 239, 191, 189, 48, 239, 191, 189, 1, 31, 239, 191, 189, 2, 1, 1, ...>>, position: 1, token: nil}
",
"invalid": [
{
"rules": [
{
"rule": "json",
"params":

{ "content": "<<48, 239, 191, 189, 1, 31, 239, 191, 189, 6, 9, 42, 239, 191, 189, 72, 239, 191, 189, 239, 191, 189, 13, 1, 7, 2, 239, 191, 189, 239, 191, 189, 1, 31, 239, 191, 189, 48, 239, 191, 189, 1, 31, 239, 191, 189, 2, 1, 1, 49, ...>>" }
}
],
"entry_type": "content"
}
]
}
}</body></error>

additional info:
https://drive.google.com/drive/u/0/folders/1XeZUj03NKPR13QA6CUf0Oije77Ta3oNm

**Comment by AlekzandrV** [comment]
Судя по всему проблема с либой через которую подписывают уже ранее подписанный контент

Можно попросить этой же либой извлечь ими же подписанный контент? И добавить сюда в задачу. Есть подозрение что проблема в этом, так как мы получает не JSON, а base64 строку внутри подписанного контента

**Comment by ehealthua-tech** [comment]
Все ок, нашли ошибку самостоятельно. Спасибо!
