### ISSUE TITLE
Error: "Invalid User, User not found" after employee email address change PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2796]
Steps to reproduce:
Відбулась зміна email адреси, після чого лікар почав отримувати дану помилку 
employee_id: 7cdedd3f-da6a-4978-8a15-b68832cbdac2
Expected results:
Успішна авторизація
Error:
Invalid User, User not found
email адреси лікаря - item 13 https://docs.google.com/spreadsheets/d/1jZyK1mWHtxyfxGoWy04oWQyLcUETgvn1hPm0lGqePNI/edit#gid=0

-120

**Comment by AlekzandrV** [comment]
We have user in mithril without roles but related employee request is APPROVED. So the user must have such role

user_id: `e62c144a-1071-4cf6-ad6c-0282d40679b6`
lis of user roles: No roles

Employee requests with new email

id | status | inserted_at
--|--------|------------
2ba74d45-5a71-4238-bf39-f0cf411bde22 |	APPROVED |	2018-07-19 17:46:00.054665
b5c4d056-f8bc-49c2-aa85-c19a55cdf445 |	APPROVED |	2018-07-19 18:08:24.110017
0f980d93-c155-49c3-81d4-8ce604c83636 |	APPROVED |	2018-07-24 12:42:51.386031

**Comment by marinakr** [comment]
Updated code was not in prod

**Comment by AlekzandrV** [comment]
Fixed
