### ISSUE TITLE
Error 500 when declaration is signed PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2797]
As a MIS MEDSTAR

After request in request.json get response
https://drive.google.com/drive/u/0/folders/1C_wkXMdDHKOrswHI1ZE4VjanR2YotFsN

Ошибки возникают периодически:
**13.07.18**
{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/32ed880e-bd44-46d8-b4f7-031c0214ba17/actions/sign", "code": 500, "type": "object", "request_id": "b7e2daf6-0d86-49ab-998b-e6bcf05b0c1b#9052" }
, 
"error": {
"errors":

{ "detail": "Internal server error" }
}
}

**16.07.18:**

``` json
{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/e9b892c1-a608-46bc-b2cb-f5108e85e9b7/actions/sign", "code": 500, "type": "object", "request_id": "03cf2d35-58f2-499f-a561-1946b8f5520e#39836" }
, 
"error": {
"errors":

{ "detail": "Internal server error" }
}
}
```
**20:11:29 23.07.2018 RequestID: b7e2daf6-0d86-49ab-998b-e6bcf05b0c1b#9052**
{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/32ed880e-bd44-46d8-b4f7-031c0214ba17/actions/sign", "code": 500, "type": "object", "request_id": "b7e2daf6-0d86-49ab-998b-e6bcf05b0c1b#9052" }
, 
"error": {
"errors":

{ "detail": "Internal server error" }
}
}

-81

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2104
