### ISSUE TITLE
Phone number in authentication_method_current, not equal patient phone number PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2798]
Надсилаємо DeclarationRequest [файл PureDeclReg.json] та у відповіді [файл PureDeclRegResp.json] отримуємо номер телефону у authentication_method_current, який не дорівнює номеру телефону пацієнта.
Очікуваний результат: Він повинен дорівнювати номеру телефона

Файли: https://drive.google.com/drive/u/0/folders/1xPkuGQdkEtoESXARJXU9gwBDfmxM8KP_

-138

**Comment by AlekzandrV** [comment]
Если человек уже есть в системе (ранее оформлял декларацию) и у него установлен метод аутентификации - то система будет использовать предыдущий метод аутентификации, для подтверждения новой декларации

В данном случае это как раз та ситуация. Есть декларация в системе с этим человеком где как раз указан номер телефона который вы получаете. Оформлена 2018-07-02

**Comment by ehealthua-tech** [comment]
Спасибо, закрываем
