### ISSUE TITLE
Request failed GetEmployeeIDbyEmployeeRequestID due to scope event:read

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2803]
На проде  озникла  ситуация - когда пользователь мигрировал данные из другой МИС, при вызове метода GetEmployeeIDbyEmployeeRequestID миграция не прошла т.к. оказалось что на этот метод нет необходимого permission'a: event:read. 

В списке скоупов в конфлюенсе указанный пермишн вообще отсутствует. 
При этом запрос GetEmployeeIDbyEmployeeRequestID от owner всегда проходил успешно. 

Проверьте, пожалуйста, и если это необходимо приведите в соответствие документацию по скоупам с бизнес-логикой прода.

**Comment by lymychp** [comment]
Прошу надати логи

**Comment by ehealthua-tech** [comment]
Токен пользователя - конфеденциальная информация. Без него не получится предоставить лог http-запроса.
Подскажите, что в данном случае можеть быть полезным из логов?

**Comment by lymychp** [comment]
можна видалити токени з логу і надати email користувача

**Comment by ehealthua-tech** [comment]
Ehealth.MozApi.EmployeeMozApi	GetEmployeeIdByEmplyeeReqId	{"id":"f9c1086e-026f-41fe-9db3-7074f3d8e5af","token":""}	2018-07-25 07:06:14	Chrome / 67.0 / WinNT	"System.Exception: {"type":"forbidden","message":"Your scope does not allow to access this resource. Missing allowances: event:read","invalid":null}

**Comment by lymychp** [comment]
@ehealthua-tech  "id":"f9c1086e-026f-41fe-9db3-7074f3d8e5af - такого request_id в логах немає
І формат неправильний. Має бути {GUID#1234}. Наприклад, `74d6c175-e69e-4346-9231-afb4d001c501#2720`. Дайте, будь ласка, логи з request_id, отриманим від ЦК або логін користувача, з токеном якого виконується запит.
