### ISSUE TITLE
WS Submit Visit Package basic

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2809]
Implement web service Submit Visit Package according to [apiary](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/visit-data-package/submit-visit-package) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/608272488/Submit+Visit+Data+Package)

_limited validation logic_

- [ ] Implement package with Episode, Visit, Encounter, Condition
- [ ] Add Observations to the Package
- [ ] Add Allergy intolerances and Immunizations to the Package
## Open questions
- [x] Redesign package according to flat structure

**Comment by AlexKovalevych** [comment]
Some points to work on:

1. Auth
2. Audit log
3. Persons topic handling (publish on MPI, consume at medical events)
4. Employee patients cache in Redis (init at OPS, use at medical events)

**Comment by lymychp** [comment]
WIP on #2930
