### ISSUE TITLE
Error when signed declaration PROD by doctors sign (private case) PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2840]
КЗ ***, лікар **** з 18.07.2018 не може підписати декларацію своїм ключем ЕЦП, помилка: 422 Does not match the signer drfo. ІПН лікаря вказаний вірно, лікаря оновили в eHealth, eHealth token діючий. Скрін з помилкою та лог додаю у вкладенні.

https://drive.google.com/drive/u/0/folders/1UhnJGdpUtmBtAqVLD1lcUW-flpRu9I8A

**Comment by svetavedmed** [comment]
Добрый день. Дело в том, что данный врач заведен в систему с tax_id=паспортные данные. А ЭЦП у нее сейчас с ИНН. Нужно перезавести персону, т.к. обновлять ИНН запрещено

**Comment by ehealthua-tech** [comment]
Добрый день. До 17.07.2018 врач с данным ЭЦП с ИНН успешно подписывала декларации. Врач заведен в систему с ИНН. Каким образом до 17.07.2018 подписание проходило успешно?

**Comment by svetavedmed** [comment]
у данного врача есть два employee и ни у одного из них нет ни одной декларации. Вы уверены, что именно этот врач подписывал декларации. Можно, пожлауйста, пример ид деклараций, подписанных данным врачом?
