### ISSUE TITLE
Declaration in pending_verification status even after release PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2852]
Будь-ласка, перегляньте яка може бути помилка навіть після релізу:
декларацій зі статусом pending_verification і з створеною датою більше місяця, 

ось логи:

employee_id: f97898ed-5ca6-424f-8b9b-ce3c5e8ff962
Є близько 10 декларацій, які очікують підтвердження і в них start_date: 2018-06-19

"id": "cf43ad57-eb2c-4054-9e9a-cd3ef5ae900e",
"id": "3b6d536f-33b4-422d-9e8e-37544e423f31",
"id": "d37e61f3-79e2-43e6-bb3b-9c102be1f662",
"id": "b85fd129-9e32-44c0-8a4b-dab86e506424",
"id": "aa44c06c-970e-40f8-892e-8d9907646ca0"

-134

**Comment by danakonovalenko** [comment]
всі наведені в прикладі декларації в статусі active (оновилися 2018-07-30 17:01:29.514430)
