### ISSUE TITLE
EventManager field entity_id does not correspond to any single entity PreProd (j164)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2855]
Середовище:
PreProd

Steps to reproduce:
1. Выбираю все события системы получаю список из 700+ елементов 
2. По полю entity_id произвожу выборку GetById EmployeeRequest Contract etc и в каждом случает получаю ответ '{"type":"not_found","message":null,"invalid":null}'
**Expected results:**
Ожидаю получить актуальные айдишники сущностей!

{"type":"not_found","message":null,"invalid":null}
'

-164

**Comment by svetavedmed** [comment]
Добрый день. Из запроса не совсем поняла, что именно вы хотите найти, каких сущностей. Event list можно фильтровать по event_type, entity_type, date..
более подробно тут: https://uaehealthapi.docs.apiary.io/#reference/public.-event-manager/get-events-list/get-events-list

**Comment by AlekzandrV** [comment]
Дайте, пожалуйста, примеры запросов/ответов

**Comment by ehealthua-tech** [comment]
МИС получает список событий в системе, в ответ отдает  800 событий, выбирается любой, например один из списка:
{
"properties": {
"status":

{ "new_value": "DISMISSED" }
},
"id": "eff9f811-6a38-461f-a3e8-23bfb32f13b4",
"event_type": "StatusChangeEvent",
"event_time": "2018-06-26T07:02:37.231430",
"entity_type": "Employee",
"entity_id": "2b429385-fefa-4141-ba6e-efbb5aad72cf",
"changed_by": "867f2f54-fb33-4dd1-baa0-8e21bf794cf9"
}

следующий этап хотим получить этого сотрудника по запросу

get = > api/employees/

{employee_id}

где {employee_id}
="entity_id" 
"entity_id" беру из списка событий
в ответ получаем 404,

вчера проверили, все таки есть некоторые сущности из списка но их очень мало из 800 порядка 40

**Comment by svetavedmed** [comment]
данный employee есть. Можно полный лог - request/response?
