### ISSUE TITLE
No letter about password reset Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2856]
Не приходит письма о восстановлении пароля. 

Смотрели в postmark 
30.07.2018 письма не отсылалось
Подробности здесь: (email указан в названии файла)
https://drive.google.com/drive/u/0/folders/1sO5wvjcez5Q6iSCP1Jg6WXnllIu-0cBA

**Comment by svetavedmed** [comment]
письмо на восстановление пароля отправила. В логах, к сожалению, по времени найти данные не могу, нужно бы request_id для этого
