### ISSUE TITLE
Electronic signature without tax id PROD (j131, j201)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2857]
Actual result 
 {"meta":{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"d649c6b8-66bb-400e-8692-eddbb8432139#1246","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"required","params":[],"description":"can't be blank"}],"entry_type":"json_data_property","entry":"$.edrpou"}]}}

Описание
Доброго дня, що робити у наступному випадку, коли ФОП намагається зареєструвати legal_entity, проте не може цього зробити, так як по новим стандартах ЕЦП для фізичних осіб не містить ЄДРПОУ, відповідно отримуємо наступну помилку при реєстрації?

Тут приклад:  https://drive.google.com/drive/u/0/folders/1xaYACy0wCVIzYNotyke0xRQvD7w_AMVE

**Comment by svetavedmed** [comment]
Добрый день. ЭЦП физ.лица и ФОП сейчас ничем не отличаются друг от друга. Если мы разрешим создавать legal_entity по подписи с drfo только, тогда любой человек, у которого есть ЭЦП, сможет создать legal_entity. Нормально ли это?

**Comment by ehealthua-tech** [comment]
У человека (ФОП) должна быть лицензия на совершение медицинской деятельности, без нее НСЗУ не сможет заключить контракт. И, даже если физ.лицо подаст заявку, то она будет отклонена, поскольку у него не будет лицензии. Лицензия проверяется перед подписанием договора от НСЗУ.

**Comment by ehealthua-tech** [comment]
Ще одне звернення від МІСів:
https://drive.google.com/drive/u/0/folders/12GqtQSnpmTyUK62XceOc-54PTKGpyaKF

**Comment by svetavedmed** [comment]
Change validation of tax_id on create/update legal_entity
[confluence](https://edenlab.atlassian.net/wiki/x/SvkQ)

1. Check that EDRPOU in Certificate details exists and not empty
 - Check that EDRPOU in Certificate details is valid according to ^[0-9]{8,10}$
 - Check that EDRPOU in Certificate details is equal to EDRPOU in Legal Entity payload
    - In case validation fails - generate 422 error
2. If EDRPOU in Certificate details is empty check that DRFO exists and not empty
 - Check that DRFO in Certificate details is valid according to ^([0-9]{9,10}|[А-ЯЁЇIЄҐ]{2}\\d{6})$
 - Check that DRFO in Certificate details is equal to EDRPOU in Legal Entity payload with Latin to Cyrillic mapping
    - Convert DRFO and EDRPOU in Legal Entity to uppercase 
    - Compare DRFO and EDRPOU in Legal Entity as Cyrillic letters
    - Convert DRFO to Cyrillic and compare as Cyrillic letters 
 - In case validation fails - generate 422 error
3. In case EDRPOU and DRFO is empty return error 422, msg "EDRPOU and DRFO is empty in digital sign"
