### ISSUE TITLE
Request error on contracts when contract is active PreProd

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2858]
Середовище:
PreProd

Expected results:
{"meta":{"url":"http://api-svc.il/api/contract_requests/cc7bd79c-2fc0-49d7-ad90-88a1a429af0f","type":"object","request_id":"1a9f15c6-da1e-4dde-85bd-be956370f473#6487","code":422},"error":{"type":"request_malformed","message":"Active contract is found. Contract number must be sent in request","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

Описание
Понятно из сообщения, что надо редактировать существующий договор. Но не понятно как его искать. По статусу, по типу контракта?
Это должно быть тут: https://edenlab.atlassian.net/wiki/spaces/EH/pages/523960439/Create+Contract+Request
Но нету.

Напишите - какой алгоритм создания запроса на договор. Именно в разрезе проверки на существование верифицированного договора.

**Comment by svetavedmed** [comment]
Для обновления контракта, вам в запросе нужно указать номер контракта и не указывать даты действия контракта. Искать, у какого именно контракта конфликт с вашим, нужно по датам. Если даты пересекаются, создать новый контракт вы не можете.

**Comment by svetavedmed** [comment]
также поправили описание
