### ISSUE TITLE
Unknown number for patient verification (OTP) Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2859]
Доброго дня! 
Ми фіксуємо до 5 дзвінків на день з проблемою щодо відправлення смс на інший номер телефону (authentication_method_current відрізняється від authentification_methods). 
Десь половина лікарів/пацієнтів стверджують що вони не впізнають цей номер або ж взагалі реєструються вперше. Ми транслюємо інформацію про те, що крок за НСЗУ в створенні тех.підтримки і наданні можливості зміни номера верифікації.

Наразі вибрали один приклад, коли пацієнт стверджує, що реєструється вперше взагалі і впевнений в цьому.

Необходимо проверить номер: 
{"urgent":{"authentication_method_current":{"type":"OTP","number":"+38093*****23"}}

Дополнительная информация:

https://drive.google.com/drive/u/0/folders/1S_BEYcQBYvGyt7WTmu5gHVkJ55yIiUNE

**Comment by AlekzandrV** [comment]
Данные о данном пациенте попали в систему с декларацией заключенной 2018-07-06 в следующем подразделении со следующим сотрудником

legal_entity_id |	legal_entity_name |	division_id |	division_name |	employee_id
--|--|--|--|--
76de29dd-c120-4328-9e7e-c3e3c40a8297 |	КОМУНАЛЬНЕ НЕКОМЕРЦІЙНЕ ПІДПРИЄМСТВО "ЧЕРНІГІВСЬКА МІСЬКА ЛІКАРНЯ №2" ЧЕРНІГІВСЬКОЇ МІСЬКОЇ РАДИ |	0bd5975a-a974-446d-9a1d-acdfe06b8121 |	Відділення первинної медичної допомоги поліклініки комунального некомерційного підприємства "Чернігівська міська лікарня №2" Чернігівської міської ради |	a58eb458-4ab2-4ab8-9dc3-2a630e8c70f8
