### ISSUE TITLE
The information provided by NHS does not correspond to the data in eHealth PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2860]
Інформація надана НСЗУ не відповідає даним на ЦК.
Прохання перевірити наступний вопрос на стороні ЦК.
Кочубеївський ЦПМСД. 

Згідно API: https://api.ehealth-ukraine.org/api/employees?status=APPROVED 

"total_entries": 4, із них 3 "employee_type": "DOCTOR" 

Інформація конкретно не співпадає по 
employee_id: 53012655-8dad-4af1-a3a9-170d177b9d25 НСЗУ надає дані що цей співробіник працює в division_id: 07861fb8-9679-4b35-848b-e614f6059d3b 

API повертає: що employee_id: 53012655-8dad-4af1-a3a9-170d177b9d25 
працює в division_id: fb742336-a8f0-409b-872e-fe19bbf2998a 

Також необхідно перевірити чи в цього лікаря (employee_id: 53012655-8dad-4af1-a3a9-170d177b9d25) є активні декларації в division_id: 07861fb8-9679-4b35-848b-e614f6059d3b

Дополнительная информация:
https://drive.google.com/drive/u/0/folders/1rrR8LRAXpjOZCaAYSbbudhGIJAD91f7E

**Comment by AlekzandrV** [comment]
У данного врача есть декларации в двух подразделениях:

division_id | declarations
-----------|------------
fb742336-a8f0-409b-872e-fe19bbf2998a	| 621
07861fb8-9679-4b35-848b-e614f6059d3b |	3

В ЦК врач закреплен за подразделением `fb742336-a8f0-409b-872e-fe19bbf2998a`

Думаю, нужно отдельно выяснять - что за информация предоставлена от НСЗУ. Пока нет деталей в чем именно не соответствие - комментировать сложно
