### ISSUE TITLE
Caching information about the active doctor's patinets to the Redis  - Prototype

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2868]
[Medical events auth](https://edenlab.atlassian.net/wiki/spaces/EH/pages/613646349/Access+to+patient+medical+data#Accesstopatientmedicaldata-Searchfordeclarationsusingtoken)
In order to decrease load on ops/prm/mithril it sounds reasonable to pre-cache some permanently used info.

------------
https://edenlab.atlassian.net/wiki/spaces/EH/pages/613646349/Access+to+patient+medical+data#Accesstopatientmedicaldata-Searchfordeclarationsusinguser_idandclient_id

https://edenlab.atlassian.net/wiki/spaces/EH/pages/613646349/Access+to+patient+medical+data#Accesstopatientmedicaldata-Searchfordeclarationsusingparty_idandclient_id

**Comment by progsmile** [comment]
@svetavedmed I'm working with the task right now, accidentally closed?

**Comment by svetavedmed** [comment]
accidentally closed task
