### ISSUE TITLE
422 error when contract print DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2872]
Cреда: Demo
Steps to reproduce:
эндпоинт - Public. Get Contract Request Printout Content 
(/contract_requests/fe29d930-3832-464b-b252-5c6c72ba3362/printout_content/) 
в описании указано, что данный эндпоинт доступен при статусах запроса: APPROVED, PENDING_NHS_SIGN, NHS_SIGNED, SIGNED. 
При попытке получить печатный контракт со статусом запроса APPROVED получаю 422 - "Incorrect status of contract_request to generate printout form"

Expected results:
отсутствие ошибки. 

Описание
запрос - "/contract_requests/fe29d930-3832-464b-b252-5c6c72ba3362/printout_content/"
ответ - 
{
"meta":

{ "url": "http://api-svc.il/api/contract_requests/fe29d930-3832-464b-b252-5c6c72ba3362/printout_content/", "code": 409, "type": "object", "request_id": "783dfcf0-c0a1-46f2-80c8-5b90efbb9b1e#42686" }
, 
"error":

{ "message": "Incorrect status of contract_request to generate printout form", "type": "request_conflict" }
}

https://drive.google.com/drive/u/0/folders/1iIe8lgy9N6x9nxPiiZ08fhuZkE2qSmcG

**Comment by svetavedmed** [comment]
Добрый день.
Только в статусе "PENDING_NHS_SIGN" можно получить печатную форму по url: "http://api-svc.il/api/contract_requests/fe29d930-3832-464b-b252-5c6c72ba3362/printout_content 
В статусах NHS_SIGNED', 'SIGNED' можно получить печатную форму из подписанного контента по /api/contract_requests/id
https://edenlab.atlassian.net/wiki/x/AQCYIg
