### ISSUE TITLE
Redirect url changes for client_ID PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2875]
MIS:
MEDSTAR
Середовище:
Prod

Описание
Прошу изменить redirect_url для client_id: 987330f9-f6df-4d27-a96c-73230f99cc1c c адреса /oauth/redirect/ на адрес /e-health/oauth/redirect/

Expected results:
client_id: 987330f9-f6df-4d27-a96c-73230f99cc1c 
old redirect_url: .../oauth/redirect/ 
new redirect_url: .../e-health/oauth/redirect/

**Comment by lymychp** [comment]
@ehealthua-tech  if we just change it, wouldn't it immediately impact on MIS?
Should we agree on some specific time to change?

**Comment by lymychp** [comment]
done
