### ISSUE TITLE
Wrong Employee PROD (j175)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2876]
Середовище:
Prod

Steps to reproduce:
В списку https://api.ehealth-ukraine.org/api/employees присутній лікар якого стверджують, що не реєстрували, employee_id: e2c07b70-426f-492f-b12e-bc6ecf259df3, в нього в деталях показує - 

"declaration_limit": 2000, 
"declaration_count": 623 

якщо викликати: 
https://api.ehealth-ukraine.org/api/declarations?status=active&employee_id=e2c07b70-426f-492f-b12e-bc6ecf259df3 
список пустий 

legal_entity - "id": "d50e188b-28fb-41ef-8fec-38d1ce38abbe" 

більше того по запиту - https://api.ehealth-ukraine.org/api/declarations?status=active 

повертає, що в цьому мед закладі всього 527 декларацій 
"paging": { 
        "total_pages": 11, 
        "total_entries": 527, 
        "page_size": 50, 
        "page_number": 1 
    }, 
    "meta": { 
        "url": "http://api-svc.il/api/declarations", 
        "type": "list", 
        "request_id": "f0d0860e-3525-4a5b-8f85-ef8015919f9e#280263", 
        "code": 200 
    } 

Expected results:
правильний список лікарів

-175

**Comment by ehealthua-tech** [comment]
Щодо кількості декларацій зрозуміло.

Проблема в тому, що у нашій базі лікаря *** не існує. При спробі зареєструвати такого користувача представником закладу на скриньку **** видається повідомлення, що він вже зареєстрований у системі (ми зробили запит до API, лікар *** зареєстрований у ЦК на скриньку ****) .

Що робити щоб можна було зареєструвати лікаря?

Повний текст: https://drive.google.com/drive/u/0/folders/1TBQu3LIc0BjMcqxjz6NTdkQhu5LACpzR

**Comment by svetavedmed** [comment]
у данного врача три employee, один из которых не в вашей больнице. А также три юзера. Декларации возвращаются согласно контекста, просьба прислать сам реквест curl.
На данный момент этот employee деактивирован.
Также для одного employee может  быть несколько юзеров, а у одного юзера несколько ролей.
