### ISSUE TITLE
Deleted declaration_request PROD (jira_id_75)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2878]
Наскільки відомо,  для затверджених декларацій, declaration_request будуть зберігатися?

Але є проблема. Декларації, які були затверджені і для яких були видалені declaration_request далі залишаються без declaration_request. Я так розумію, що ці дані втрачені.
Чи є можливість їх відновити? 
Зокрема нас цікавлять declaration_request по установі з ід - "a4b601ca-85dc-48f7-b9af-f521c64c314f"
Дані декларації були імпортовані з ЦК у нашу систему, проте у сутності declaration відсутня інформація по адресах пацієнта, в той час як у declaration_request є. Користувачеві з даної установи необхідні дані адреси.

Ось приклад curl (метод get) : https://api.ehealth-ukraine.org/api/declarations/e64ac755-fb40-44ba-bb3d-ac000d6d52f9
Декларація посилається на declaration_request з id "1397e29b-441a-4da5-a230-aeabd07540fd"

Проте запит 
https://api.ehealth-ukraine.org/api/declaration_requests/1397e29b-441a-4da5-a230-aeabd07540fd
вертає помилку

{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/1397e29b-441a-4da5-a230-aeabd07540fd", "type": "object", "request_id": "a65854d1-a247-4790-a278-129e57b3c33c#86159", "code": 404 }
,
"error":

{ "type": "not_found" }
}
Список декларацій: 
https://drive.google.com/drive/u/0/folders/1PzORqwLrppS5FZrDka0B2-Xs7KU6E9kF

Expected result: відновити втрачені declaration_request

**Comment by svetavedmed** [comment]
Добрый день. 
Персональные данные удаляются в declaration_request через семь дней.
Данные по адресам пациента есть в системе. Однако на данный момент они не возвращаются при Get declaration Deatails.
Для обогащения данными деталей декларации нужно создать change request, который будет оценен отдельно. Также данный change request затронет имплементации МИС, т.к. он требует изменения данных по Get declaration Deatails
