### ISSUE TITLE
Media storage and compression algorithms for signed content

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2883]
Investigate how could we compresse signed content for Medical Events and what media storage should we use for this purpose

**Comment by AlexKovalevych** [comment]
We should probably use CP1251 encoding to reduce signed content size

**Comment by lymychp** [comment]
acceptance criteria:
- [ ] ensure that chosen file storage will support the planned volumes

**Comment by IrinaRevutska** [comment]
@lymychp 
Original signed content size for the full package was 43 kb
The package consisted of:
encounter
5 conditions
10 observations
2 immunizations
3 allergy intolerances

Signed_conten size after compression - 9 kb

in case an average patient has 5 encounters per year there will be needed 45kb/patient

So, is it enough?

**Comment by lymychp** [comment]
@IrinaRevutska  it is more than enough)
