### ISSUE TITLE
Sending SMS to wrong number when declaration signed PROD (jira 178)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2887]
Звернувся клієнт із наступною проблемою. При підтверджені декларації пацієнта, sms-повідомлення пішло на невідомий номер. При цьому на телефон пацієнта sms-повідомлення не прийшло. 

Клієнт стверджує що деклараії раніше не подавав, і на даний момент подав заяву до поліції відносно того, що медичний клієнт типу поширює її персональні дані. Ми отримали офіційний лист від медичного закладу ,маємо надавати відповідь. 

Детально: https://drive.google.com/drive/u/0/folders/1nnpgNwpDPJYJTxIJ1gJDIN0J43e6Ibgh

**Comment by AlekzandrV** [comment]
Декларация с этим пациентом была заключена 2018-06-07 на отделении `d751cacc-0c66-4ba5-9505-70a552a4b224` клиники `a6aa7c39-e37f-4018-b355-08699ae4ca9c` с врачом `482a0e8a-2fa6-4570-abac-1a99bcec636d`
