### ISSUE TITLE
certificate expiration "*.demo.asclepius.com.ua" (and 2 more)

### ISSUE THREAD

**Issue by vsirius** [edenlabllc/ehealth.api#2888]
`Your certificate (or certificates) for the names listed below will expire in 10 days (on 16 Aug 18 08:23 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.
We recommend renewing certificates automatically when they have a third of their
total lifetime left. For Let's Encrypt's current 90-day certificates, that means
renewing 30 days before expiration. See
https://letsencrypt.org/docs/integration-guide/ for details.
*.demo.asclepius.com.ua
*.dev.asclepius.com.ua
*.preprod.asclepius.com.ua
For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.
If you are receiving this email in error, unsubscribe at http://mandrillapp.com/track/unsub.php?u=30850198&id=50cdfbcda34b492fb858144227302a55.Cu23qusT99kojjveisXjxZW1TW8%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Diamexile%2540gmail.com
Regards,
The Let's Encrypt Team `

10-days left before certificate expiration :

[*.demo.asclepius.com.ua](url)
[*.dev.asclepius.com.ua](url)
[*.preprod.asclepius.com.ua](url)

**Comment by dhlebnikov1** [comment]
New certificates are installed and valid until November 4, 2018
