### ISSUE TITLE
NHS tokens for demo without scope contract:terminate DEMO (jira 180)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2892]
На одном из техколов обещали добавить скоуп для тестирования.
Expected results:
необходима возможность имитации прекращения действия контракта со стороны НСЗУ, например для проверки ивентов по контрактам
Описание
{
"meta":

{ "url": "http://api.demo.asclepius.com.ua:8000/api/contracts/937fb423-7ffe-48f1-ae02-4870903e982d/actions/terminate/", "code": 403, "type": "object", "request_id": "783dfcf0-c0a1-46f2-80c8-5b90efbb9b1e#62899" }
, 
"error":

{ "message": "Your scope does not allow to access this resource. Missing allowances: contract:terminate", "type": "forbidden" }
}

**Comment by svetavedmed** [comment]
fix for DEMO
