### ISSUE TITLE
Error to get a scope for Owner PROD (jira-181)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2893]
Сотрудник с "id": "92a1f205-62e3-4041-86ce-40aa1ab30b08" пытается получить следующий набор scope 
'employee_request:read', 'employee_request:write', 'employee_request:approve', 'employee_request:reject', 'employee:read', 'employee:write', 'employee:details', 'employee:deactivate' 

employee_type: OWNER 

После авторизации на сайте ehealth получаем ошибку "User requested scope that is not allowed by role based access policies". 
request_id: 
"5a6ad297-204e-4016-8b41-2728b679202c#181338" 

Expected results:
Получение необходимых scope происходит без ошибки

employee_id: "92a1f205-62e3-4041-86ce-40aa1ab30b08"
request_id:
"5a6ad297-204e-4016-8b41-2728b679202c#181338"

https://drive.google.com/drive/u/0/folders/1aCf57LIyIxkILXBj1lBT9EXOFhqejOFX

**Comment by lymychp** [comment]
duplicates https://github.com/edenlabllc/ehealth.api/issues/2658
