### ISSUE TITLE
Remove redirect_uri from legal entity attributes

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2902]
В связи с расширением функциональности системы и её возможностей, предлагается убрать параметр redirect_uri из аттрибутов ЗОЗа.

Предлагаемые изменения следует разбить на 2 этапа:
1) расширение функциональности МИСов по redirect uri
2) удаление аттрибута redirect uri из легал энтити

Первый шаг предусматривает функциональность:
- МИС через API может редактировать свой список redirect uri. Это будет “белый список“. Редактирование этого списка должно подвергаться аудиту (логироваться). 
- при авторизации, МИС будет передавать в форму авторизации return url
- если return url не входит в список, заявленный МИСом, авторизация не работает.
- форма авторизации после успешной процедуры, должна переводить пользователя в return url, а не в redirect uri в Legal Entity.
- если не указан return url, форма переводит пользователя по redirect uri из LegalEntity

Второй шаг (когда все МИСы будут готовы к функциональности):
- авторизационная форма не работает без ReturnURL
- удаляется поле redirectURI из legal entity и его апи.

**Comment by svetavedmed** [comment]
done for demo
