### ISSUE TITLE
Keys request for emcimed

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2903]
Просимо надати нижчеперелічені дані:
• логін/пароль
• mis_client_id
• secret
окремо для прода, пре-прода та демо
на e-mail, вказаний у заяві

https://drive.google.com/drive/u/0/folders/1CEdxc5iDTB87y07LAb20wRLQsd6MW6Vq

**Comment by lymychp** [comment]
credentials вислано на вказаний емейл
Прошу підтвердити отримання та закрити тікет
