### ISSUE TITLE
Active declaration is absent PROD (jira-188)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2904]
Декларація #0000-6942-АА78 була складена в травні місяці.
Але нещодавно вона зникла. 
Лікар передзвонив до пацієнта, та пацієнт запевнив лікаря, що не переукладав декларацію з іншим лікарем.
legal_entity_id = 2005fdbd-5b7f-4511-bc43-9da560d94ff4
Будь ласка, можете назвати причину, чому зникла декларація?

https://drive.google.com/drive/u/0/folders/1wbqM5A2PLKFt-JbOLtMjdteF-9Z--uU9

**Comment by lymychp** [comment]
Запит на декларацію був створений `2018-05-20 13:41:56.709743`, але так і не був підписаний. 
Тому з часом перейшов статус `expired`.
МІС перевіряв в своїх логах, що даний запит був підписаний та отримав успішну відповідь від ЦК про підписання? Якщо так, прошу надати логи.
