### ISSUE TITLE
Сapitation_report:read  for client_id PREPROD and DEMO

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2905]
Добавьте пожалуйста scope - capitation_report:read для client_id: 68325CEB-84FA-4217-A544-40FC38837911 (демо/препрод).

Нужен для работы с отчетами по капитации

**Comment by lymychp** [comment]
@svetavedmed please check and add if it is missing and only if it SHOULDN'T

**Comment by svetavedmed** [comment]
Добрый день. client_id: 68325CEB-84FA-4217-A544-40FC38837911 - это клиент МИСа. Данный скоуп может быть только у ADMIN, OWNER, NHS ADMIN
На препрод скоупы были верные, на демо поправила. Уточните, пожалуйстаю, нужно ли еще что-то?
