### ISSUE TITLE
Impossible to upload tax id PROD 

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2906]
При аутентифікації через документи присутнє посилання для завантаження лише паспорту. При цьому посилання для ІПН відсутнє.
Чому відсутнє поля для завантаження ІПН?

"urgent": { 
    "documents": [ 
      { 
        "url": "https://storage-01.ehealth-ukraine.org/declaration-requests/a4/b6/44/85/34/a4df459a-b6ed-4422-859c-34d79cc2da2f/declaration_request_person.PASSPORT.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QBUj69Ukz9CqGN%2F20180807%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180807T122502Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=adb7e91f40ff96421f9065d44b1d9b652662634a6259c105dde91400e26ceab6", 
        "type": "person.PASSPORT" 
      } 
    ], 
    "authentication_method_current": { 
      "type": "OFFLINE" 
    }

**Comment by svetavedmed** [comment]
Добрый день. Т.к. в нашей стране не у всех людей есть ИНН, следовательно его не всегда нужно подгружать. Если в реквесте нет tax_id - линк не формируется. Перепроверьте пожалуйста реквест. Спасибо.
