### ISSUE TITLE
Authorisation MIS error PROD (jira 194)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2908]
При запросе на авторизацию МИС МедЕйр (получение AccessToken) получаем ошибку: 
The redirection URI provided does not match a pre-registered value. 

На данный момент нет возможности делать update Legal_Entity 

Expected results:
Response: AccessToken
Описание
Запрос делали с redirect_uri:

1. redirect_uri":"https://portalauth.e-life.com.ua

2. redirect_uri":"http://e-life.com.ua"

Оба ридерект ури не проходят

https://drive.google.com/drive/u/0/folders/1Nj18Q7qIqCZc6Gg33awKdOvXemAkPZGw

**Comment by lymychp** [comment]
redirect_uri не було змінено. Зараз змінили на `https://portalauth.e-life.com.ua/`
Повинно працювати.
