### ISSUE TITLE
All declarations of an employee are terminated PROD (j195)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2917]
Середовище:
Prod
MIS:
Helsi

Повідомте, будь ласка, причину зміни статусу декларацій за співробітником 
0f5f3097-d4f5-499d-beea-4af6ab22aa20

Error:
Всі декларації співробітника 
employee_id 0f5f3097-d4f5-499d-beea-4af6ab22aa20 
перейшли в статус terminated. 
Дата зміни статусу 08.08.2018.

**Comment by lymychp** [comment]
```
  "phoenix": {
      "status": 500,
      "request_id": "0260dde6-f6ab-4183-8f9e-85d95af67e40#119539",
      "path": "/api/employees/0f5f3097-d4f5-499d-beea-4af6ab22aa20/actions/deactivate",
      "method": "PATCH",
      "log_type": "http",
      "handler": "Elixir.EHealth.Web.EmployeeController#deactivate",
      "duration": 15352.889,
      "date_time": "2018-08-08T06:49:01Z",
      "api_version": "N/A"
    },
    "@timestamp": "2018-08-08T06:49:01.959101624+00:00",
    "tag": "phoenix.app"
  },
```
declaration termination events are sent to the events service even if the termination was not successful.

**Comment by lymychp** [comment]
@ehealthua-tech `2018-08-08T06:49:01.959Z` був виклик методу PATCH `/api/employees/0f5f3097-d4f5-499d-beea-4af6ab22aa20/actions/deactivate` з використанням токену користувача та api-key MIS Helsi.
У відповідь було відправлено `500` від ЦК.
Даний запит не був опрацьований, співробітника не було деактивовано, декларації не були відмінені. Але по причині помилки, в events були записані події про деактивацію декларацій. 
Це некоректна поведінка системи. Причина помилки локалізована і буде виправлена з наступним релізом.
У співробітника `0f5f3097-d4f5-499d-beea-4af6ab22aa20` 848 активних декларацій.

**Comment by ehealthua-tech** [comment]
Спасибо! Имеется ввиду релиз, который планируется на 16 августа?
