### ISSUE TITLE
No automatic status declaration changing due to patient age (j200, j203)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2919]
КНП «ЦПМСД №3 Дніпровського району м. Києва»
Пацієнтам виповнилося 18 років. Декларації, які були укладені з лікарем-педіатром не змінили статус з "діюча" на "термін дії скінчився". В які строки відбувається зміна статусів декларації?

https://drive.google.com/drive/u/0/folders/1MuHCOrkRkJzDTUXGBGtDUdpHmLnpJCex

**Comment by ehealthua-tech** [comment]
Ще одне звернення:

MIS:
MEDSTAR
Середовище:
Prod

Декларация не изменила статус c 'active' на 'closed' при достижении ребёнком возраста в 18 лет. 
Специальность врача: Педиатр. 
declaration end_date: 2018-08-07 
текущий статус: 'active'
https://drive.google.com/drive/u/0/folders/1wCKYH7rRDdJqbCWGn5FAKbzYJF9bvBW7


Expected results:
корректный статус декларации

**Comment by AlekzandrV** [comment]
Взято в работу, ищем решение

**Comment by AlekzandrV** [comment]
@AlexKovalevych  На текущий момент в системе имеется 5651 декларация с датой окончания меньше сегодняшней в статусе "активна", которые подпадают под условие закрытия по достижении срока завершения

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2843

**Comment by marinakr** [comment]
@AlekzandrV  can not  reproduce this issue

**Comment by AlekzandrV** [comment]
Will be fixed with #2843
