### ISSUE TITLE
When editing employees in the contract printtout_content is not updated DEMO (j202)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2920]
MIS:
Доктор Елекс
Середовище:
Demo

Після додавання чи вилучення працівників з контракту, printout_content та contractor_employee_divisions у contract_request не оновлюються.

Приклад контракт з contract_id = "ba272fdb-1010-4730-b04a-0c6246b2db59",
contract_request_id = "b90c75b5-9903-42b1-acc6-d709b34aca2a".

Додаю скріни із даними з контракту та з друкованою версією
https://drive.google.com/drive/u/0/folders/1dYPsPDw_h-mgTfDFHpuKI3d5IyUrNGW5

**Comment by AlekzandrV** [comment]
При получении печатной формы по контракт реквесту - в респонсе возвращается печатная форма, которая была подписана обеими сторонами.
При изменении сотрудников привязанных к контракту в одностороннем порядке - печатная форма всего контракта не меняется. Это корректное поведение системы
