### ISSUE TITLE
"declaration_count" is over 2000  and equal 2427 (j206)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2921]
MIS:
Поліклініка без черг
Середовище:
Prod

У врача "declaration_count" равен 2427, 
См. запрос №1. 
При поиске самих деклараций, находим всего 4 декларации: "total_entries": 4, 
См. запрос №2
Expected results:
Количество деклараций совпадает и не превышает 2000

https://drive.google.com/drive/u/0/folders/1J9nvvnp2hmos3pnVd30Ra9BXoB_MTw4F

**Comment by svetavedmed** [comment]
Добрый день. После внедорения контрактов все лимиты переносятся на уровень контрактов. Ограничений на создание декларация уже не будет, но оплата будет производится только за декларации указанные в контрактах для данного сотрудника. Также будут убраны declaration_count и declaration_limit - все эти решения были временными до создания контрактов.
Потому закрываю данную задачку, в связи с изменением логики работы.

**Comment by lymychp** [comment]
відповідь надано через slack

**Comment by ehealthua-tech** [comment]
1) Зміна логіки роботи відбулась, але що буде, коли ці 427 декларацій підтвердяться? 
2) У даного лікаря в даному конкретному випадку зараз  2427 активних декларацій?

**Comment by lymychp** [comment]
так і залишиться
