### ISSUE TITLE
Declarations disappear (j207)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2922]
MIS:
ЕМСІМЕД
Середовище:
Prod

Доктор повідомив, що в нього масово зникають декларації.
Після надання роз'яснень, щодо відмінності між зникненням декларацій та зникненням заяв на декларацію, клієнт все одно, попросив перевірити 2 декларації:
0000-5АКК-1971
0000-Х940-755Т

Будь-ласка найдайте результат історї змін цих документів?

**Comment by AlekzandrV** [comment]
А можно помимо номера попросить ID этих объектов? И employee_id сотрудника за кем были эти декларации?

**Comment by lymychp** [comment]
обидва запити не були підписані і були переведені в статус `expired`.
