### ISSUE TITLE
Error 424 when declaration registered

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2923]
Steps to reproduce:
Користувач не може внести декларацію в систему. Масово.

Expected results:
Відновлення коректної роботи.
Описание
"uri" : "https://api.ehealth-ukraine.org/api/declaration_requests/d3422717-f74b-4d81-963d-6e95e7d9f2c4/actions/sign"

"body" : {
"meta" :

{ "url" : "http://api-svc.il/api/declaration_requests/d3422717-f74b-4d81-963d-6e95e7d9f2c4/actions/sign", "type" : "object", "request_id" : "4ba63193-d74c-402c-bb2f-2cf0c297368f#183445", "code" : 422 }
,
"error" : {
"type" : "validation_failed",
"message" : "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
"invalid" : [ 
{
"rules" : [

{ "rule" : null, "params" : [], "description" : "424: The method could not be performed on the resource because the requested action depended on another action and that action failed." }
],
"entry_type" : "json_data_property",
"entry" : "$.signed_declaration_request"

**Comment by ehealthua-tech** [comment]
MIS:
nHealth
Середовище:
Prod
Steps to reproduce:
У разных пользователей стала часто появляться ошибка 422 при отправке подписанной декларации. Проблему заметили сегодня утром.
Expected results:
Корректное создание декларации.
Описание
{"meta":

{"url":"http://api-svc.il/api/declaration_requests/7f967862-29eb-4d53-8681-c20adab16129/actions/sign","type":"object","request_id":"f47c3e73-0dcf-4fb6-9a59-7580983d1c58#30025","code":422}
,"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[

{"rule":null,"params":[],"description":"424: The method could not be performed on the resource because the requested action depended on another action and that action failed."}
],"entry_type":"json_data_property","entry":"$.signed_declaration_request"}]}}

**Comment by AlekzandrV** [comment]
Проблема была связана с неработоспособностью (медленной работой) онлайн сервиса проверки сертификата ДФС
