### ISSUE TITLE
Declaration sign ($.last_name) PROD (j192)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2924]
MIS:
Доктор Елекс
Середовище:
Prod
Steps to reproduce:
Відтворюється дана помилка при підписанні декларації
Expected results:
Підписана декларація

Error
{
"meta":

{ "url": "http://api-svc.il/api/declaration_requests/ba1e7e82-5652-4e27-8914-de6f93240d26/actions/sign", "type": "object", "request_id": "f305def2-02e4-428e-ba17-0a99c0e70a0f#10133", "code": 422 }
,
"error": {
"meta":

{ "url": "http://api-svc.il/persons", "type": "object", "request_id": "f305def2-02e4-428e-ba17-0a99c0e70a0f#10133", "code": 422 }
,
"error": {
"type": "validation_failed",
"message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
"invalid": [
{
"rules": [

{ "rule": null, "params": [ ], "description": "has already been taken" }
],
"entry_type": "json_data_property",
"entry": "$.last_name"
}
]
}
}
}

1) Підписаний контент декларації, який відправляється прикріпив у файлі

2) Декларацію підтвердили, проте при запиті на https://api.ehealth-ukraine.org/api/declaration_requests/
{ID_HERE}
/actions/sign отримуємо описану помилку.

https://drive.google.com/drive/u/0/folders/16CVDCDD0UsudoY9jhffm3oyv0qC3eXX4

**Comment by svetavedmed** [comment]
this problem will be solved in #2641 after internal person search changes

**Comment by lymychp** [comment]
not actual anymore
