### ISSUE TITLE
OCSP certificate verificaton failed (j210)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2925]
MIS:
Доктор Елекс
Середовище:
Prod
Steps to reproduce:
Почали спостерігати більшу активність помилки перевірки сертифікату на підписанні декларації, чи можна це вирішити так, як багато запитів по цьому питанню на контакт центр?
Expected results:
Signed declaration
Описание
{"meta":

{"url":"http://api-svc.il/api/declaration_requests/c97f3067-1b40-463a-95be-dc2cd01cc1e0/actions/sign","type":"object","request_id":"6e0cd067-17a6-48c7-8fef-340557cdf24a#140106","code":400}
,"error":{"type":"request_malformed","message":"OCSP certificate verificaton failed","invalid":[{"rules":[

{"rule":"json"}
],"entry_type":"request"}]}}

**Comment by AlekzandrV** [comment]
Проблема была связана с неработоспособностью (медленной работой) онлайн сервиса проверки сертификата ДФС
