### ISSUE TITLE
Medical_events audit_log service

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2929]
As a Security officer  
I want whenever any entity is created or updated, information about this event to be recorded:
Request_id, who, when, resource_that_has_been_changed, resource_id, change_set/new_state (optional)
So that I can easily do the investigation and answer the questions: 
* why the particular record is like it is, 
* who and when has changed it ,
* what were the changes

**Comment by IrinaRevutska** [comment]
@PavelVesnin , please, implement logic to handle insert case separate from update

**Comment by PavelVesnin** [comment]
@IrinaRevutska no problem
