### ISSUE TITLE
WS Submit Encounter Package advanced

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2930]
web service Submit Encounter Package according to [apiary](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/submit-encounter-package) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/608272488/Submit+Visit+Data+Package)

- [x] Implement package with  Visit, Encounter, Condition

**Comment by IrinaRevutska** [comment]
- [ ] $.encounter.diagnoses[\*].condition.identifier.value could be one of $.conditions[*].id
- [ ] $.encounter.division.identifier.value must meet the  requirement PRM.division.status = "ACTIVE"

**Comment by IrinaRevutska** [comment]
- [ ] Bug: Getting "Episode is not active" when the episode actually belongs to the other patient (and it is active)
- [ ] Please, add "asserted_date" field to condition (according to JSON schema and confluence)
