### ISSUE TITLE
PROD Update inserted_by and updated_by for persons

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#2931]
Update `inserted_by` and `updated_by` persons attributes with real user_id instead of `default`

How to determine this values:

* **inserted_by** - find the first record in ops.declarations ordered by inserted_at ASC and filtered by '<ops.declarations.person_id>' = '<mpi.person.id>' 

* **updated_by** - find the last record ops.declarations ordered ordered by inserted_at DESC  and filtered by '<ops.declarations.person_id>' = '<mpi.person.id>' 

#2926

**Comment by marinakr** [comment]
https://github.com/edenlabllc/ehealth.charts/pull/119

**Comment by marinakr** [comment]
ERROR:  null value in column "inserted_by" violates not-null constraint
DETAIL:  Failing row contains (8c29bde8-80d2-4e44-baff-783ddbed962c, Олександра, Звєркова, Олександрівна, 2005-09-19, Україна, FEMALE, null, null, null, null, t, [{"zip": "08310", "area": "КИЇВСЬКА", "type": "RESIDENCE..., null, null, 2018-03-29 11:54:30.914945, 2018-03-29 11:54:30.914959, default, {"phones": [{"type": "MOBILE", "number": "+380503520290"}], "las..., [], [{"type": "OTP", "phone_number": "+380503520290"}], Ротовская, active, Київ, t, t, null, f, null).

**Comment by marinakr** [comment]
@AlekzandrV  we have persons that do not have dedicated record in declarations!

**Comment by marinakr** [comment]
updated without 1160  persons

**Comment by lymychp** [comment]
@AlekzandrV please close ticket
