### ISSUE TITLE
Release 8.5.1 to prod

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2941]
# deployment preparation checklist
- [x]  prepare [release notes](https://github.com/ehealth-ua/api-spec/pull/552) 
- [x]  prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specific release
- [x]  prepare all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.)
- [x]  create PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec

- [x]  define required versions of repo to the destination env. @AlekzandrV please check
```
*mpi* to *2.1.0*, *ehealth* to *8.5.1*, *ops* to *2.2.1*, *report* to *2.3.1*
```
- [x]  apply the required versions of repo to the destination env.
  - [x]  ehealth.api
  - [x]  mpi.api
  - [x]  ops
  - [x]  reports.api
~- [ ]  IL.dictionaries - add/update if any. IDs should be the same. @svetavedmed @AlekzandrV should we add something manually?~
~- [ ]  PRM.global_parameters - add/update if any. IDs should be the same. @svetavedmed @AlekzandrV should we add something manually?~
~- [ ] uaddresses - add/update records if any. IDs should be the same~
- [x]  GW.apis - migrate config
~- [ ] GW.apis - Exclude temp dev routes~
~- [ ] GW.plugins~
~- [ ]  Mithril config @svetavedmed @AlekzandrV should we add something manually?~
  ~- [ ]  client_types - add/update if any changes.~
  ~- [ ]  roles - add/update if any changes.~
  ~- [ ] tokens - generate new tokens with new scopes or  in case if new endpoints are released~
  ~- [ ] approvals - generate or copy MIS approvals~
~- [ ]  man templates - will be updated via migration @svetavedmed @AlekzandrV should we add something manually?~
~- [ ] DS - migrate certificates if any~
~- [ ]  create all new buckets in minio~
- [x]  run the magic replication script

# post-release check-list
- [x]  cluster metrics
- [x]  service metrics
- [x] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [x]  login/sanity check of NHS admin
~- [ ] login/sanity check of UAddresses admin~
- [x]  manual sanity check of new deployed features (should be taken from the Release Notes)
- [x]  check backups
- [x]  check logs in kibana
- [x]  check graphana monitoring metrics
- [x]  check reports and fraud DB replication status
  - [x]  overall replication status
  - [x]  every table status
  - [x]  parties.declaration_count
- [x]  check dictionaries
- [x]  check scopes
- [x]  check division stats

**Comment by AlexKovalevych** [comment]
ops: 2.2.1
