### ISSUE TITLE
New capitation report test run

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2946]
Run capitation report on the prod volumes with the DS check on.

**Comment by imax-iva** [comment]
Testing results on pre-prod (without DS check procedure)

Input
Contracts: 1,312
Contract employees: 291,522
Declarations: 16,010,226
Declarations status history: 16,653,818
Persons: 15,694,250
Divisions: 10,539
Legal entities: 1,354

Output
Status: OK
Report details: 13,120
Total declaration count: 15,609,794
Process time: about 1.5 days
