### ISSUE TITLE
Get async Job processing details endpoint

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2957]
Service to get details of the async job 
[spec](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/get-async-job-processing-details)

child of #2930

**Comment by PavelVesnin** [comment]
response for pending status:
```
data: {
  eta: _,
  status: pending,
  links: []
}
```
response for processed status:
```
{
  eta: _,
  status: processed,
  links: [
      {
        "entity": "visit",
        "href": "/visits/90a9e15b-b71b-4caf-8f2e-ff247e8a5600"
      },
      {
        "entity": "encounter",
        "href": "/encounters/90a9e15b-b71b-4caf-8f2e-ff247e8a5600"
      }
  ]
}
```
response for invalid validation
```
{
  eta: _,
  status: processed,
  status_code: 422,
  errors: [...]
}
```

**Comment by IrinaRevutska** [comment]
@PavelVesnin status code 200 when it is actually an error. Example `FWyFtaShW9XfemRcAqv7Lw`

**Comment by IrinaRevutska** [comment]
@PavelVesnin , please, do not set status_code until status is not terminated, otherwise, I get 500 when status == 0
