### ISSUE TITLE
Not possible to update access token through oauth2.0 flow (j237)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2960]
MIS:
Облік медичних кадрів України та пацієнтів
Середовище:
Prod
Steps to reproduce:
https://auth.ehealth-ukraine.org/sign-in?client_id=client_id&redirect_uri=https%3A%2F%2Fehealth.infomed.ck.ua%2Fconnect%2Fehealth%2Fcheck&scope=legal_entity%3Aread+legal_entity%3Awrite+legal_entity%3Amis_verify+role%3Aread+user%3Arequest_factor+user%3Aapprove_factor+event%3Aread&email=email 
Вводим пароль, на следующей странице жмем ПРИЙНЯТИ ТА ПРОДОВЖИТИ. 
Видим белый экран. 

Скопы взяты отсюда - https://api.ehealth-ukraine.org/admin/roles - для MIS USER
Expected results:
Перенаправление.
Описание
{
"meta":

{ "url": "http://api-svc.mithril/oauth/apps/authorize", "type": "object", "request_id": "0eaf00de-7446-4dbb-8ae6-ab6dce633c4c#497492", "code": 422 }
,
"error": {
"type": "request_malformed",
"message": "Scope is not allowed by client type.",
"invalid": [
{
"rules": [

{ "rule": "json" }
],
"entry_type": "request"
}
]
}
}

**Comment by ehealthua-tech** [comment]
Второе обращение (j236): 

MIS:
Helsi
Середовище:
Prod
Steps to reproduce:
1. Перейти на сторінко логіну (https://auth.ehealth-ukraine.org/sign-in) для авторизації 
2. Ввести логін-пароль 
3. Клікнути "Увійти"
Expected results:
Успішна авторизація та редіректо до інтерфейсу МІС
Описание
Запит зависає у статусі Pending
А згодом падає у 524 помилку

**Comment by AlekzandrV** [comment]
Проблема описанная в теле задачи - исправлена. Прошу проверить
