### ISSUE TITLE
One declaration is not inside eHealth  PROD (j226)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2961]
была зарегестрирована декларация (фото прилагаю), распечатана, но в Эмсимед ее не могут найти в eHealth
Посмотрите, пожалуйста, есть ли эта декларация в системе? 
Если нет, то по каким причинам ее нет в системе на данный момент 

https://drive.google.com/drive/u/0/folders/1EF0pkQx1ilJfrOFOG6JfsMuqdBeE8tPK

**Comment by svetavedmed** [comment]
данной декларации в системе нет. Был сделан только declaration_request, но не был подписан. Поэтому распечатать печатную форму возможность была, а вот деклаоации нет.
