### ISSUE TITLE
Delete contacts on Portal

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2962]
1) Необходимо "закомментировать" раздел "Контакти" с верхнего меню портала https://portal.ehealth.gov.ua/

2) Также закомментировать ссылку на Twitter
http://prntscr.com/kl62cu

3) Закомментировать блок "ЗВОРОТНІЙ ЗВ’ЯЗОК" внизу страницы: 
http://prntscr.com/kl635x

**Comment by lymychp** [comment]
done
