### ISSUE TITLE
500 error after request https://api.ehealth-ukraine.org/api/divisions?ids= PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2968]
500 ошибка при запросе: https://api.ehealth-ukraine.org/api/divisions?ids=2fc6be12-84f0-4e36-acec-7a52d182b7e3

MIS:
МедЕйр
Середовище:
Prod
Steps to reproduce:
При запросе на получение division by id, получаем ошибку (данный метод описан в API, ранее работал): 
{"meta":{"url":"http://api-svc.il/api/divisions","type":"object","request_id":"2426acfd-7529-40f7-bdc2-3e38aa8607b1#139325","code":500},"error":{"errors":{"detail":"Internal server error"}}}

Expected results:
Получение инфо по division_id

Описание ошибки:

HTTP/1.1 500 Internal Server Error
Date: Mon, 20 Aug 2018 12:04:10 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 190
Connection: keep-alive
Set-Cookie: __cfduid=d03c6eda227c58ac6d85054e8d2760c781534766650; expires=Tue, 20-Aug-19 12:04:10 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure
Cache-Control: max-age=0, private, must-revalidate
Vary: Accept-Encoding
Via: kong/0.13.1
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Kong-Proxy-Latency: 8
X-Kong-Upstream-Latency: 11
X-Permitted-Cross-Domain-Policies: none
X-Ratelimit-Limit-Minute: 20
X-Ratelimit-Remaining-Minute: 19
X-Request-Id: 2426acfd-7529-40f7-bdc2-3e38aa8607b1#139325
X-Xss-Protection: 1; mode=block
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 44d4b88ddb648b76-KBP

{"meta":

{"url":"http://api-svc.il/api/divisions","type":"object","request_id":"2426acfd-7529-40f7-bdc2-3e38aa8607b1#139325","code":500}
,"error":{"errors":

{"detail":"Internal server error"}
}}

**Comment by svetavedmed** [comment]
do not show error 500 in case filter does not exist

**Comment by svetavedmed** [comment]
filter by id does not work
request
```
curl -X GET \
  'https://api.dev.asclepius.com.ua/api/divisions?id=a99dc8ae-9047-4f9c-b956-2d588fb7469a' \
  -H 'Authorization: Bearer cUcycEFhalhPYTd5Q0UwMG56a0JCQT09' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: af7ebfc2-03ba-427b-b34d-fe69b1ea2fd9' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09'
```
response
```
    "paging": {
        "total_pages": 9,
        "total_entries": 438,
        "page_size": 50,
        "page_number": 1
    }
...
```

**Comment by lymychp** [comment]
Why do we have parameter `id`?
This one should work:
```
curl -X GET \
  'https://api.dev.asclepius.com.ua/api/divisions/a99dc8ae-9047-4f9c-b956-2d588fb7469a' \
```

**Comment by marinakr** [comment]
ids

**Comment by svetavedmed** [comment]
done for dev
