### ISSUE TITLE
Error $ data - invalid_age PROD (j228)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2969]
$ data - invalid_age : лікарі із сертификатом сімейного лікаря не можуть заключити декларацію із 17-річними.

MIS:
MedCard Plus
Середовище:
Prod
Steps to reproduce:
Попередня умова: 
Лікарі лікарні працюють на посаді терапевта, але мають 2 сертифіката: терапевта та сімейного лікаря (у системі) 

Кроки: 
1) Створюють декларацію на пацієнта 08.02.2001 року народження 
2) При відправлені декларації на реєстрацію вртається помилка $ data - invalid_age 
https://drive.google.com/drive/u/0/folders/1Ym3qPa_sPNrG_OJnm4ybnqo2hwmkouOY

Expected results:
До серпня місяця ці лікарі успішно підписували декларації із 17-ти річними, бо мають сертифікат сімейного лікаря.

**Comment by svetavedmed** [comment]
Добрый день. 
Попрошу вас написать больше данных по запросу: ид врача, ид пациента, логи запроса.
Также могли бы пожалуйста пояснить что именно вы подразумеваете под "сертификатом сімейного лікаря"?
Это массовая ошибка или наблюдается у одного лишь врача?
Спасибо большое.

**Comment by ehealthua-tech** [comment]
Ошибка массовая. 
ранее было так - врач со СПЕЦИАЛЬНОСТЬ семейная медицина может заключать декларации со всеми возрастами. У врачей этой поликлиники 2 специальности- 2 сертификата: терапия и семейная медицина. Должность у них - терапевт, почти у всех. Они терапевты в том числе и по договору. Теперь вопрос: если логика центрального компонента в этом аспекте поменялась, где об этом можно почитать и что теперь делать этим врачам?
Лог добавлен в txt файле: 
https://drive.google.com/drive/u/0/folders/1Ym3qPa_sPNrG_OJnm4ybnqo2hwmkouOY

**Comment by svetavedmed** [comment]
Добрый день. Логика не менялась. Если у врача две специальности, значит у врача есть два employee. У каждого employee есть speciality_officio, согласно которой врач именно с этой специальностью может или нет заключать декларацию именно с этим поциентом. 
В данном случае у врача только одна специальность - THERAPIST, а поциенту еще нет 18-ти лет, следовательно декларация между ними заключена быть не может.
