### ISSUE TITLE
500 error, after get division PREPROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2970]
MIS:
Облік медичних кадрів України та пацієнтів

Середовище:
PreProd

Steps to reproduce:
https://api-preprod.ehealth-ukraine.org/api/divisions?ids=98fd7a47-828d-4a9d-bb74-4f1e93baa76a 

Подразделение с таким id есть.
Expected results:
Подразделение с таким id, или пустой список если такого id нет.

Описание
{"meta":

{"url":"http://api-svc.il/api/divisions","type":"object","request_id":"31828a74-3ac8-4504-a578-ea5463fb412b#689","code":500}
,"error":{"errors":

{"detail":"Internal server error"}
}}

**Comment by svetavedmed** [comment]
get division by ids does not work. Only filter by ID. Specification changed. Error number will be changed with #2968 as tasks are duplicated.
