### ISSUE TITLE
422 error when enter  PROD (j213, j

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2971]
MIS:
Helsi
Середовище:
Prod

Під час логіну отримуємо 422 помилку користувач 0f5f3097-d4f5-499d-beea-4af6ab22aa20 

Перед цим спостерігалися проблеми із деактивованими деклараціями
https://github.com/edenlabllc/ehealth.api/issues/2917

Опис помилки:
{"meta":

{"url":"http://api-svc.mithril/oauth/apps/authorize","type":"object","request_id":"3b5fa0b0-3c9b-4a7d-9d79-2612a1475e33#7689","code":422}
,"error":{"type":"request_malformed","message":"User requested scope that is not allowed by role based access policies.","invalid":[{"rules":[

{"rule":"json"}
],"entry_type":"request"}]}

Нажаль проблема зберігається зараз і на мою думку ні як не пов'язана із сервісом підписання.
Під час логіну співробітник 0f5f3097-d4f5-499d-beea-4af6ab22aa20 отримує білий екран та помилку. 
В лікаря попердньо були проблеми із некоректною поведінкою системою, внаслідок чого розірвалися декларації. https://github.com/edenlabllc/ehealth.api/issues/2917.

 Зараз декларації активні проте лікар не має доступу до свого кабінету.

https://auth.ehealth-ukraine.org/accept?client_id=f4bd6e1f-06f4-40df-af1e-6f4eb1224cb9&email=kai09021959%40gmail.com&redirect_uri=https%3A%2F%2Freform.helsi.me%2Fuser%2Fauth&request_type=code&scope=declaration%3Aread+declaration_request%3Aapprove+declaration_request%3Aread+declaration_request%3Asign+declaration_request%3Awrite+division%3Aread+employee%3Aread+employee_request%3Aapprove+employee_request%3Areject+legal_entity%3Aread+otp%3Aread+otp%3Awrite+person%3Aread+employee_request%3Aread

Повертається {"meta":

{"url":"http://api-svc.mithril/oauth/apps/authorize","type":"object","request_id":"e08b007b-2195-42e5-8f06-3d4226dd389f#59554","code":422}
,"error":{"type":"request_malformed","message":"User requested scope that is not allowed by role based access policies.","invalid":[{"rules":[

{"rule":"json"}
],"entry_type":"request"}]}}

https://drive.google.com/drive/u/0/folders/1Oaq4mQF9KFZllgYT1KzEmDHjnfofH1WR

**Comment by svetavedmed** [comment]
Ошибка связана с предыдущей ошабкой в задаче  #2917. При деактивации доктора были задеты роли пользователя. Ошибку для данного доктора исправили.
