### ISSUE TITLE
Info about patient is not matched data PROD (j221)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2972]
Дані пацієнта в запиті на створення декларації та самій декларації не співпадають
data->person->last_name різниться

MIS:
Askep.net
Середовище:
Prod

Деталі:
https://drive.google.com/drive/u/0/folders/1AQ4rSgk2DORbS8u6R_fSfKFTQKkoP6Yj

**Comment by svetavedmed** [comment]
У данных персон отличается фамилия, но ИНН и дата рождения совпадают, а также совпадают имя и отчество. Поиск персон происходит по ИНН+дата рождения, потому то персона и была найдена. Из всего этого следует, что по всей вероятности дама просто сменила фамилию.
