### ISSUE TITLE
Statistics about employee PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2977]
Для оценки и проработки вопросов связанных с лимитами, просим выгрузить информацию о
1) количество party с одним employee с указанием специализации
2) количество party, у которых больше одного employees  (с возможным указанием количества employee)
3) количество party, у которых больше одного employees и больше одной специализации (с возможным указанием количества employee и специализаций)
4) количество party, у которых больше одного employees в больше чем одном division с разными специализациями

Просьба предоставить информацию в технический канал слек

**Comment by AlekzandrV** [comment]
@ehealthua-tech  Добрый день.
Речь полагаю идет только о докторах (сотрудниках с типом employee_type = 'DOCTOR')?

**Comment by AlekzandrV** [comment]
--------------------
#### 1. количество party с одним employee с указанием специализации

Специализация | Статус | Количество
--------------|--------|-----------
FAMILY_DOCTOR | APPROVED | 12099
FAMILY_DOCTOR | DISMISSED | 388
PEDIATRICIAN | APPROVED | 3683
PEDIATRICIAN | DISMISSED | 110
THERAPIST | APPROVED | 2789
THERAPIST | DISMISSED | 134

--------------------
#### 2. количество party, у которых больше одного employees (с возможным указанием количества employee)

Количество employee на party | Количество party с таким кол-вом employee
-- | --
2 | 1538
3 | 240
4 | 43
5 | 17
6 | 4
7 | 1
12 | 1

--------------------
#### 3. количество party, у которых больше одного employees и больше одной специализации (с возможным указанием количества employee и специализаций)

Количество специализаций | Количество party с таким кол-вом спец
-- | --
2 | 91
3 | 1

--------------------
#### 4. количество party, у которых больше одного employees в больше чем одном division с разными специализациями

| Количество |
| - |
| 46 |
