### ISSUE TITLE
[Mithril] List of roles and clients is not reloaded

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2985]
env: demo
**Repro Steps:**
1. login to [mithril](https://mithril.demo.asclepius.com.ua/sign-in)
2. got to [users](https://mithril.demo.asclepius.com.ua/users)
3. choose any user
4. click "створити роль для користувача" [link](https://mithril.demo.asclepius.com.ua/users/{ID}/roles/create)

**Actual result**
list of roles and list of clients doesn't show all the records. Client `eHealth NHS Admin` is missing
![image](https://user-images.githubusercontent.com/5257001/44647280-48938600-a9e6-11e8-9517-f9283dd0c65c.png)

**Expected result**
All the clients should be presented in the list. For example, Client `eHealth NHS Admin`.

**Comment by ephor** [comment]
Cannot reproduce
