### ISSUE TITLE
Validity of Declaration Preservation in case of legal entity reorganization

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2990]
**Збереження чинності декларації у випадку реорганізації (об’єднання, поглинання, зміна форми власності) надавача ПМД**

Передумовою збереження декларації після реорганізації (зміна організаційно-правової форми медичного закладу (перетворення), об’єднання кількох медзакладів (злиття), або приєднання одного закладу до іншого) є те, що обраний пацієнтом лікар продовжує надавати послуги пацієнту у тому самому місці у новому НМП. 
Цей процес не враховує реорганізацію через поділ медичного закладу. 
Процесс виконується з боку НСЗУ з ініціативи медзакладу. В залежності від виду реорганізації один або декілька мед закладів, після створення правонаступника,  автоматично переходять у стан “деактивовано в зв’язку з реорганізацією”. 
З моменту зміни стану  при розрахунках активні декларації  враховуються на закладі-правонаступнику. Декларації, пов’язані із закладом “деактивованого у зв’язку із реорганізацією”, можуть бути тільки терміновані. 
  
**Опис**

Уповноважений працівник ЗОЗ створює новий медичний заклад.
Уповноважений працівник НСЗУ встановлює зв'язок правонаступності юридичних осіб.
Уповноважений працівник НСЗУ вносить інформацію щодо причини встановлення  правонаступності.
Уповноважений працівник НСЗУ накладає ЕЦП на операцію реорганізації медзакладів.
E-Health зберігає підписаний контент.

**E-Health звіряє, що:**
в нового медзакладу є права правонаступності стосовно поточного медзакладу
лікар, що обслуговує декларацію залишився без змін (працює у закладі - правонаступнику)
місце надання послуг пацієнту не змінилося
декларації в статусі=Active.
Якщо одна з вимог п.6. не виконується - декларація термінується.
Статус мед закладів, які підлягають реорганізації змінюється на “деактивований з причини реорганізації”.
Створення нових декларацій на медзакладах, що знаходяться в статусі “деактивований з причини реорганізації”  заборонено.
Активні декларації, що належали до початку реорганізації до медзакладу, який набув статусу “деактивований з причини реорганізації” -  не змінюють свій статус і мають можливість бути терміновані звичайними шляхами.
Декларації медзакладу, який набув статусу “деактивований з причини реорганізації”, які знаходяться в статусі pending_verification активуються на мед закладі, який їх надіслав.
Якщо у закладі - правонаступнику змінюється місце надання послуг лікарем, обраним пацієнтом у декларації, тоді декларації, що належать до медзакладу, який набув статусу “деактивований з причини реорганізації” термінуються.
При формуванні капітаційного звіту активні декларації підраховуються по медичному закладу - правонаступнику, враховуючи активні декларації медзакладів, які набули статусу “деактивований з причини реорганізації”.
Капітаційний звіт по медзакладам, які набули статусу “деактивований з причини реорганізації” не формується.
Дії працівника НСЗУ щодо зміни статусу медзаклада зберігаються в журналі 
Ствердження
Рішення про те, які медичні заклади є правонаступником приймає НСЗУ.
Всі дані про пацієнта не змінюються

**Переваги** 
Всі Декларації незалежно від методу автентифікації зберігаються без змін.
Лікарю не потрібно підписувати декларації поштучно ЕЦП
eHealth не потрібно повідомляти пацієнта про зміни в юридичному стані медзаклада 
Інформація про медичні заклади та їх деклараціях залишається без змін, додається лише інформація щодо правонаступництва.

**Недоліки**
Відсутній алгоритм  розділення медичного закладу та виділення його частини.
Активні декларації можуть зберігатись на активованих підприємствах, якщо у нього є  правонаступник. Це ускладнює механізми підрахунку декларацій та формування звітів

**Comment by lymychp** [comment]
implemented by edenlabllc/ehealth.api#3557
