### ISSUE TITLE
Declaration dublicate PROD (j239) 

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2994]
Декларація 5470beb0-1134-4948-99f3-49b0098eeee2 була заключена 2017-10-24 та не має номеру, тільки declaration_id.

2018-08-02 відбулася спроба перезаключення даної декларації, що закінчилась створенням дублікату (declaration_id: 08ef1bac-35dd-437a-b5d4-9052b70e1394 , declaration_number: 0000-4E6E-4641).

Не зрозуміло чому так сталось, адже обидві декларації мають однакові дані про персону, тому декларація повинна була перезаключитися (а попередня декларація на цього пацієнта: 5470beb0-1134-4948-99f3-49b0098eeee2 — мала розірватися). 

Просимо допомогти у вирішенні проблеми.

**Comment by svetavedmed** [comment]
Добрый день.
Задублировалась персона из-за того, что ранее уже было заведены в системе две персоны - одни с ИНН, другая без. Поэтому при поиске персоны без ИНН было найдены обе, и т.к. не ясно какую именно обновлять, была создана новая. 
Для избежания подоных ошибок в будущем - алгоритм поиска и обновления персон будет изменен по задаче #2641, а также разрабатывается алгоритм дедубликации персон.
Сейчас предыдущую декларацию можна разорвать через админку НСЗУ.
