### ISSUE TITLE
GET Divisions: not return division addresses PREPROD, PROD (j240, j253)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2995]
GET Divisions 
Баг актуалний як на проді, так і на предпроді. 
Відповідь нижче із предпроду

{
"paging":

{ "total_pages": 2, "total_entries": 73, "page_size": 50, "page_number": 2 }
,
"meta":

{ "url": "http://api-svc.il/api/divisions", "type": "list", "request_id": "a5e1102d-b8e9-4eb9-8c13-c31cbe1f71a5#16414", "code": 200 }
,
"data": [
{
"working_hours": null,
"type": "AMBULANT_CLINIC",
"status": "ACTIVE",
"phones": [

{ "type": "LAND_LINE", "number": "+380441111111" }
],
"name": "Амбулаторія загальної практинки №5 Філія2 КНЦ ЦПМСД №1 м.Обухів",
"mountain_group": false,
"location":

{ "longitude": 30.648468, "latitude": 50.12458 }
,
"legal_entity_id": "9d9bcdcb-e572-495c-8bdb-ce07a2ea9675",
"id": "4ddb3e69-c0bd-4a89-9e08-195046ff0dcb",
"external_id": null,
"email": "a.yakovenko@helsi.biz.ua",
"addresses": []
},
]
}

Expected results:
Мають повертатися адреси, що були вказані при створенні/редагуванні підрозділу.

**Comment by ehealthua-tech** [comment]
https://drive.google.com/drive/u/0/folders/1IbqAOJ6TUZLqBKIZC23lAKTcfly3kzT9

**Comment by ehealthua-tech** [comment]
У додаток до цього , друковані форми декларацій формуються частково заповненими без вказання місця надання медичної допомоги (поля 3.5.1 - 3.5.5) у звяз'ку із втратою адрес підрозділів.

**Comment by lymychp** [comment]
Fixed
