### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH Prod (j242)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2996]
MIS:
Доктор Елекс
Середовище:
Prod

Error:
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Описание
При спробі змінити пароль нічого не відбувається.
У логах помилка: "net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

![image 4](https://user-images.githubusercontent.com/40864195/44705901-9bce0d00-aaa8-11e8-8700-20421d2f3633.png)

**Comment by lymychp** [comment]
1. Try Clearing the SSL State On Your Computer
Another thing to try is clearing the SSL state in Chrome. Just like clearing your browser’s cache this can sometimes help if things get out of sync. To clear the SSL state in Chrome on Windows, follow these steps:
Click the Google Chrome – Settings icon (Settings) icon, and then click Settings.
Click Show advanced settings.
Under Network, click Change proxy settings. The Internet Properties dialog box appears.
Click the Content tab.
Click “Clear SSL state”, and then click OK.
Restart Chrome.

2. Use a New Operating System
Older operating systems fall out of date with newer technologies such as TLS 1.3 and the latest cipher suites as browsers stop supporting them. Specific components in the latest SSL certs will simply stop working. Google Chrome, in fact, pulled the plug on Windows XP back in 2015. We always recommend upgrading to newer operating systems if possible, such as Windows 10 or the latest version of Mac OS X.
