### ISSUE TITLE
EmployeeRequest processes PROD (j243)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2997]
MIS:
ЕМСІМЕД
Середовище:
Prod
Описание
Доброго дня!
Просимо надати роз’яснення логіки роботи ЦК у такому випадку

створили EmployeeRequest
і-мейл не прийшов, що характерно для @ukr.net, @bigmir, @i.ua
недочекавшись (чекали півдня), створили ще один EmployeeRequest
і-мейл прийшов ОДИН РАЗ, але не зрозуміло, у відповідь на який саме запит
користувач пройшов по посиланнях, підтвердив зміни
питання:
1) що станеться, якщо і-мейл був на перший запит?
2) що станеться, якщо і-мейл був на другий запит?
3) чи скасовуються автоматично "старі" запити у разі надходження "більш нових" ?
4) чи оброблюються якимось чином усі наявні запити у разі підтвердження змін за останнім запитом?

**Comment by svetavedmed** [comment]
Добрый день. 
Будет создан employee на тот employee_request по которому был отправлен email. Сделать два разных сотрудника на один email не удастся. Сам employee_request живет только 29 дней, следовательно один employee_request перейдет в статус EXPIRED через 29 дней и создать employee по нему уже будет невозможно. Старые employee_request не удаляются при создании новых, но они экпайрятся через 29 дней. Запросы на сотрудников обрабатываются при создании на них employee - прописывается employee_id, статус сменяется на "APPROVED", данные об этом employee_request уходят в event_manager.
