### ISSUE TITLE
deleted division_addresses on prod and preprod

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3018]
on update division we can delete division addresses for division.

query - DELETE FROM "division_addresses" WHERE "id" = $1

examples for preprod: 
date - August 7th 2018, 16:48:27.273
request_id - 90410b63-5b95-44ae-9928-40fee32b31d4#27999

date - August 1st 2018, 16:19:24.880
request_id - 1f99f824-4cf7-467d-80fb-b06eadf25706#17539

**Comment by marinakr** [comment]
actions:
DivisionController
activate
deactivate

**Comment by marinakr** [comment]
Step to reproduce: 
1) Insert into database division with 10 addresses
2) Activate division
3) Count addresses for division: 10
3) Insert into db new address for division
4)Count addresses for division: 11
5) Activate division again
4)Count addresses for division: 10
EXPECTED: 11

**Comment by marinakr** [comment]
Write migration
