### ISSUE TITLE
Use declaration auth module on GETs

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3030]

**Comment by IrinaRevutska** [comment]
- [x] get episodes by id
- [ x] get episodes by search_params
- [ ] get encounters by id
- [ ] get encounters by search_params
- [ ] get conditions by id
- [ ] get conditions by search_params
- [ ] get observations by id
- [ ] get observations  by search_params
- [ ] get allergy_intolerances by id
- [ ] get allergy_intolerances by search_params
- [ ] get immunizations by id
- [ ] get immunizations by search_params

**Comment by lymychp** [comment]
auth will be tested with all the future endpoints
