### ISSUE TITLE
Create Observations, AIs, Immunizations via Composite

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3032]
Add 
- [x] conditions
- [x] observations, 
- [x] allergy_intolerances, 
- [x] immunizations 
to the composite according to [apiary](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/submit-encounter-package) and [confluence](https://edenlab.atlassian.net/wiki/spaces/EH/pages/608272488/Submit+Encounter+Data+Package#SubmitEncounterDataPackage-ValidateObservations)

**Comment by IrinaRevutska** [comment]
- [ ] I get 409 "Visit with such id already exists" when IDs of to different CONDITIONS matches. 
*Despite the error, objects are created*
- [ ] There is no "onset" validation. Should be "$.conditions[*].onset_date <= current_date"

**Comment by IrinaRevutska** [comment]
@AlexKovalevych , what is that about:
```
 "errors": {
            "invalid": [
                {
                    "entry": "$.allergy_intolerances.[0].source",
                    "entry_type": "json_data_property",
                    "rules": [
                        {
                            "description": "must be present",
                            "params": [],
                            "rule": "required"
                        }
                    ]
                }
            ],
```
I have this part in the allergy_intolerance:
```
"primary_source": true,
      "asserter": {
        "identifier": {
          "type": {
            "coding": [
              {
                "system": "eHealth/resources",
                "code": "employee"
              }
            ]
          },
          "value": "d50efcc2-6fb1-4f7d-afc5-08a2c3e152ce"
        }
      },

```

**Comment by IrinaRevutska** [comment]
- [ ] entry": "$.observations.[0].value_sampled_data.data", "description": "type mismatch. Expected Number but got String", - **should be string**
- [ ] "description": "schema does not allow additional properties",
                            "params": {
                                "lower_limit": -3300,
                                "upper_limit": 3300
                            },  - **they are not additionl**

**Comment by IrinaRevutska** [comment]
@BatrakM, please, check why job is still in status pending 
 "id": "5bab4335f5c3b40001aa4ae3"

**Comment by IrinaRevutska** [comment]
@progsmile, fix this, please:
- [ ] do not create evidences on conditions, if they(evidences) weren`t submitted

**Comment by progsmile** [comment]
Regarding failed job - we should check logs immediately after fail (our logging is not configured now), so will try again

**Comment by progsmile** [comment]
In case of allergy_intolerances.source: should be "Report origin" or "asserter", right?
