### ISSUE TITLE
Search for a Person NHS admin v2

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3035]
As NHS admin I want to be able to search for a person using next possible filter parameters:

---
phone_number
birth_date

---
tax_id
passport_number

---
at least one of field in each block must be required

and sort by birth_date, tax_id, national_id

We need to implement WS according to [spec](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/persons.graphql)

**Comment by lymychp** [comment]
@warehousman @danakonovalenko please review list of combinations

**Comment by danakonovalenko** [comment]
[test cases](https://edenlab.atlassian.net/wiki/x/WIArKg)
- [ ] street_type and zip should be optional
- [ ] there is no declarations connection yet
