### ISSUE TITLE
Get Person Details NHS admin v2

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3036]
As NHS admin I want to view person details, so we need to implement service according to  [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/persons.graphql) / [features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/person_details.feature)

**Comment by lymychp** [comment]
documents should be a parameter of declaration, not person
