### ISSUE TITLE
Get Declaration List/Details nhs admin v2

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3038]
As nhs admin I want to be able to view list of patients declaration knowing either 
```
- person_id
- declaration_number
```
So, we need to implement services 

- [x] Get declarations list [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/declarations.graphql)/ [feature for list](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature) 
- [x] Get declaration by id  [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/declarations.graphql)/ [feature for details](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature)

**Comment by danakonovalenko** [comment]
I can't receive declaration attached documents as I receive an error 
```
<Error>
<Code>ExpiredToken</Code>
<Message>The provided token has expired.</Message>
<Details>
Request signature expired at: 2019-01-22T14:29:54+00:00
</Details>
</Error>
```
@progsmile please, help me to understand why we have such issue

**Comment by progsmile** [comment]
Please create new issue for that

**Comment by danakonovalenko** [comment]
So, I checked whether that is related to data issue. And seems that there is other problem. I created few new declarations and downloaded valid documents and still receive same error. e.g. declaration_id='66d5524c-a52c-4690-a7ac-f3a632b2213c'
