### ISSUE TITLE
check the balance of ЕМСІМЕД legal entities PROD (j244)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3041]
MIS:
ЕМСІМЕД

Есть необходимость "сверить балланс" по докторам и OWNERам
Сделайте, пожалуйста, выгрузку по ЗОЗам ЕМСІМЕД вот такой структуры:
LegalEntityID;
LegalEntityEDRPOU;
LegalEntityName;
LegalEntityUpdatedAt;
DivisionID;
DivisionName;
DivisionUpdatedAt;
EmployeeID;
EmployeeType;
EmployeePosition;
EmployeeStatus;
EmployeeUpdatedAt;
PartyID;
PartyFIO;
PartyEMail

Просьба не выкладывать файл в открытый доступ, а передать каналом Slack

**Comment by svetavedmed** [comment]
Добрый день. Данную статистику можно посмотреть через BI

**Comment by ehealthua-tech** [comment]
На данный момент ehealth, к сожалению, не имеет возможности это сделать

**Comment by lymychp** [comment]
я так розумію, вже не актуально? можна закрити?

**Comment by ehealthua-tech** [comment]
я думаю, що можна. якщо будуть ще питати, відкриємо нову. Дякую.
