### ISSUE TITLE
IL slow queries

### ISSUE THREAD

**Issue by marinakr** [edenlabllc/ehealth.api#3042]
1. "SELECT count('*') FROM (SELECT d0.\"id\" AS \"id\", d0.\"data\" AS \"data\", d0.\"status\" AS \"status\", d0.\"authentication_method_current\" AS \"authentication_method_current\", d0.\"documents\" AS \"documents\", d0.\"printout_content\" AS \"printout_content\", d0.\"inserted_by\" AS \"inserted_by\", d0.\"updated_by\" AS \"updated_by\", d0.\"declaration_id\" AS \"declaration_id\", d0.\"mpi_id\" AS \"mpi_id\", d0.\"overlimit\" AS \"overlimit\", d0.\"channel\" AS \"channel\", d0.\"declaration_number\" AS \"declaration_number\", d0.\"inserted_at\" AS \"inserted_at\", d0.\"updated_at\" AS \"updated_at\" FROM \"declaration_requests\" AS d0 WHERE (d0.\"data\"->'legal_entity'->>'id' = $1) AND (d0.\"status\" = ANY($2))) AS s0"
Check  query plan
ALL statuses

2. "SELECT count(d0.\"inserted_at\"), to_char(d0.\"inserted_at\", 'YYYY-MM-DD') FROM \"declarations\" AS d0 WHERE (d0.\"inserted_at\"::date >= $1) AND (d0.\"inserted_at\"::date <= $2) GROUP BY to_char(d0.\"inserted_at\", 'YYYY-MM-DD')"
Do not apply any functions to columns used in 'WHERE' clause if no index with this function exists

**Comment by lymychp** [comment]
@vsirius @dhlebnikov1 one more migration that should be planned and maybe executed before release
