### ISSUE TITLE
User authorize problem, PROD, #J255

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3054]
Проблема получения скоупов после входа пользователя в систему.
Описание флоу здесь https://drive.google.com/drive/u/1/folders/1ODmbgFJ6pjXpMJhE0sNITBM06IenNLkL?ogsrc=32

**Comment by lymychp** [comment]
судячи по скріншоту і тексту помилки, користувач логіниться по лінку https://auth.ehealth-ukraine.org/sign-in
Тобто не передані параметри `client_id`, `scope`, `redirect_uri`
