### ISSUE TITLE
New declaration form design changes before release 8.6 on Prod 

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3055]
Згідно шаблону нової декларації зробити наступні зміни форми декларації, яка розташована на препроді:
1) збільшити поле "Підпис пацієнта" як в шаблоні
http://prntscr.com/kp58a4
2) збільшити відступ між блоками:
http://prntscr.com/kp58a4
щоб декларація була розтянута на лист А4
3) перенести п.2.4. вниз:
http://prntscr.com/kp598w
4) розміри шрифтів необхідно ще раз переглянути згідно шаблону.

5) У п.2.1 написано "Прізвище, ім’я, по-батькові", виводить, "ім’я, по-батькові, прізвище"

6) Необхідно додати в шаблон "dummy" п.4.6 Бажаний спосіб зв'язку, процес заповнення якого буде реалізовано в api 2

Форма декларації повинна бути максимально схожа з шаблоном, оскільки від нас чекають максимальну схожіть і розподілення полів на паперовому носії повинно бути таким же як і на шаблоні.

**Comment by ehealthua-tech** [comment]
Please, see updated comments by 5 and 6 points.

**Comment by svetavedmed** [comment]
done on demo and preprod
