### ISSUE TITLE
Employee's id duplication when record is edited, PROD, #J246

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3059]
Добрый день.
От пользователей (FE) пришел запрос.
Доброго дня!
У результаті редагування даних, які, на нашу думку, в жодному разі не можуть відноситись до ідентифікуючих, по лікарям на ЦК утворились дублі Employee (див. вкладення)
Клієнт про помилку повідомив не вчасно і лікарі встигли уклати декларації на дублі.
Як усунути дублювання Employee без скасування декларацій?.
Необходимо выполнить, следующее: 

- определить, есть ли ошибка со стороны FE
- если да, то указать проблемные/ошибочные запросы
- если нет, то указать другую причину дублирования.

Примеры дубликатов в формате json: https://drive.google.com/drive/u/1/folders/16GI7LiDPr2lkPhINd9Vh5Tdw6Cr89arz

**Comment by lymychp** [comment]
@ehealthua-tech з опису і з даних по лінку не зрозуміло в чому проблема.
Прошу реєструвати тікети в форматі:
* Repro steps:
* Actual result:
* Expected result:

дякую

**Comment by ehealthua-tech** [comment]
Відносно проблеми дублювання записів.
_Repro steps_: запит щодо доадткової нформації направлено до замовника
_Current result_: за посиланням в цьому тікеті. Також буде додано інформацію після отримання відповіді клієнту.
_Expected result_: 1. В подальшому (після виправлення помилки) при редагуванні не створюється новий запис, але фіксуються зміни, які виконує користувач.
2. Саме виправлення помилки:
* визначити дату пошуку = дата, коли виникла помилка;
* отримати всі записи лікарів та їх пацієнтів за той час;
* визначити ознаки, за якими ідентифікується дублікат;
* отримати список задубльованих записів (тобто відповідаючих критерію (має, як вказано вище, такі ознаки));
* визначити первинний запис, до якого будуть пов'язані надалі пацієнти та інші об'єкти, які створює лікар в процесі роботи;
* виконати скріпти для зміни зв'язків;
* записати лог виконання скріптів
* видалити задубльовані ідентифікатори.

**Comment by lymychp** [comment]
ждем repro steps для розуміння чи є взагалі проблема.
