### ISSUE TITLE
Division search (website), PROD, #J247

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3061]
Доброго дня, зареєстровано три відділення ("legal_entity_id": "18791c31-3281-4e5a-9ea5-2eef9a6fe18e"):

1) "id": "b4985f5a-a2e4-4a52-b65f-59c8a7a90549","Амбулаторія загальної практики сімейної медицини № 1"
2) "id": "80904c4a-80e9-4680-9101-3c8d87bad1ba", "Амбулаторія загальної практики сімейної медицини № 2"
3) "id": "ac50fb91-36dc-449c-9205-61365e725dc5", "Амбулаторія загальної практики сімейної медицини № 3"

по запиту через API вони є, поточний статус "ACTIVE" і вказані координати, проте при пошуку на сайті https://portal.ehealth.gov.ua/divisions.html#/ їх не видно, як через ЄДРПОУ закладу так і по ід.

такий запит нічого не повертає хоча division guid зареєстрований
https://portal.ehealth.gov.ua/divisions.html#/b4985f5a-a2e4-4a52-b65f-59c8a7a90549
Скриншот здесь

**Comment by lymychp** [comment]
судячи з усього тікет уже прострочений. Перед створенням тікетів рекомендую переконатись, що проблема відтворюється
![image](https://user-images.githubusercontent.com/5257001/45012974-202d0c80-b022-11e8-8872-d723ef63c670.png)
![image](https://user-images.githubusercontent.com/5257001/45012996-33d87300-b022-11e8-8a99-26a07df9d955.png)
![image](https://user-images.githubusercontent.com/5257001/45013004-3d61db00-b022-11e8-8f98-f6b8352f6b3d.png)
