### ISSUE TITLE
Doctor's id exists in DB. Problem: the record is not visible in the list by request. PROD, #J249

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3062]
По запросу от FE. 
За запитом у списку немає лікаря, але за запитом по одному запису вона визначена зі статусом ACTIVE.
Повний опис та приклади відсутніх записів у списку, в той час коли вони є в БД, тут https://drive.google.com/drive/u/1/folders/1hwrm2g-R8PjaCGR7XdpGZ_jMyWNPBwoy

**Comment by lymychp** [comment]
немає доступу до папки по лінку

**Comment by ehealthua-tech** [comment]
Доброе утро, коллеги. Доступ к папке открыт.

**Comment by svetavedmed** [comment]
Можно еще курл реквеста и весь респонс, пожалуйста? по двум вариантам - когда есть нужный employee и когда нет.
