### ISSUE TITLE
Using the same email address to create defferent employee accounts, PROD, #J270

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3069]
Добрый день. Пользователь ошибся при заведении аккаунта employee (доктора).
Суть ошибки (запрос от пользователя с данными аккаунта доктора тут https://drive.google.com/drive/u/1/folders/14dQvTVax1ySkD9HO_0yx5YYmGftnIKlo?ogsrc=32):
_Repro steps_
Добрый день,
Вопрос следующий.
Зарегистрировали в додатке предприятие на главрача,
Но этот врач еще и симейный доктор (тоесть у него 2 должности)
Проблема следующая. При регистрации указали и в первом и во втором случае один и тот же емейл. В итоге при входе в систему, теперь доктор заходит только как симейний доктор (как главрач пропал).
Можно ли решить данный вопрос, что бы остался аккаунт и главврача и симейного доктора.
_Expected result_
Наличие двух разных аккаунтов - главврача и семейного врача.
Необходимо определить сколько записей, связанных с указанным в тикете, электронным адресом есть в БД.  Также, пожскажите, какие будут рекомендации, чтобы получить Expected result. 
Если в документации есть описание проверки уникальности при заведении employee? пожалуйста, подскажите, где можно данную информацию изучить.

**Comment by lymychp** [comment]
у вказаного в тікеті користувача є дві ролі: `doctor`, `owner`.
Відповідно він може отримати скоупи обидвох використовуючи один email.
Логіка дедублікації parties описана [тут](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1316436/IL.Approve+Reject+employee+request)
