### ISSUE TITLE
Password managing emails (restore, reset) are not received, PROD, #J269, #J272, #J274, #276

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3070]
При скиданні та відновленні паролю користувач не отримує листів на свою адресу електронної пошти. Повна інформація тут https://drive.google.com/drive/u/1/folders/1AwRKrjs0did4tROHjd2iRpZ-kn58ZsiP?ogsrc=32.
Також э проблема з надсиланням листыв пыдтвердження створення employee.

**Comment by svetavedmed** [comment]
по email отписалась в файлике. Также email на видео и в файлике не разнятся.

**Comment by ehealthua-tech** [comment]
В файл на моем диске добавила еще один адрес, на который не приходит ответ от Вашего сервера. Проверьте, пожалуйста, данный емейл (выделила другим цветом).

**Comment by svetavedmed** [comment]
ответила в документе. Для данного адреса не было ни одного письма
