### ISSUE TITLE
Authorization problem  PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3080]
MIS:
Helsi
Середовище:
Prod
Steps to reproduce:
1. Пререйти на сторінку auth.ehealth-ukraine.org 
2. Ввести коректні логін та пароль 
3. Натиснути "Увійти"
Expected results:
Успішна авторизація
Описание
Повідомлення "Логін чи пароль не вірні".
У частині випадків допомагає очистка кешу.
У частині випадків допомагає зміна браузеру.

Один і той же користувач може увійти через одін барузер/прилад та не може із іншого браузера/ прилада.

**Comment by ehealthua-tech** [comment]
https://drive.google.com/drive/u/0/folders/1vBNizx50nbSA8lsdnvl1rPgD0XPwUAJx

На даний момент зафіксували 5 випадків з однаковою помилкою (додаю скріни). Пробували:

натиснути на клавіатурі Ctrl+F5;
очистити хеш/куки;
оновити браузер до останньої версії;
скористтися іншим браузером;
спробувати пройти авторизацію з іншого комп'ютера;
Помилка залишалася та сама.
Після натискання "Забули пароль" і зміни логіну+паролю на одному з акаунтів авторизація пройшла успішна.

Є припущення, що пароль застарів, але чому вертає що "невірний логін/пароль"? 
Що робити з подальшими випадками?

**Comment by lymychp** [comment]
В усіх користувачів пароль не прострочений.
Для вирішення проблеми - Ввести правильний пароль.
Якщо забули пароль, пройти процедуру скидання паролю.
![image](https://user-images.githubusercontent.com/5257001/45282912-08073280-b4e5-11e8-9577-a57a7960b0da.png)
