### ISSUE TITLE
Changes to new print declaration form PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3084]
1.
Зараз колір назви полів: #525659 (rgb: 82, 86, 89) - сірий 
А колір значення полів: #201600 (rgb: 32, 22, 0 ) - майже-чорний 
Пропонуємо колір назв полів зробити темніше, бо на друці виглядає погано 
(принтер щоб зробити сірим робить зернистим) -  колір назв полів, зробити таким саме, як і значення полів.
Оскільки сірий колір погано друкується на старих прінтерах.

2. 
Текст, що відображається білим по чорному (Пункти 1,2,3,4,5,6) у краще зробити жирним - при друці на принтері (особливо низькоякісному) не жирний текст може бути нечитабельним на чорному фоні

3. Підзаголовки (тобто пункти 1.7, 1.8, 1.11 та інші) використовують шрифт менший ніж їх підпункти (1.7.1, 1.8.1, та інші). Слід зробити кегль шрифта підзаголовка таким самим та залишити його жирним

![Uploading Декларація.jpg…]()

**Comment by svetavedmed** [comment]
done for prod
