### ISSUE TITLE
department' id filter does not work, PreProd, #J279

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3085]
Не работает фильтр по id подразделений. При запросе по id подразделения в ответе возвращаются все подразделения.
https://api-preprod.ehealth-ukraine.org/api/divisions?id=98fd7a47-828d-4a9d-bb74-4f1e93baa76a.
Запрос-ответ здесь https://drive.google.com/drive/u/1/folders/1XCiR__zlfieIpJgVO_4FG0bHsqDNkPRa?ogsrc=32

**Comment by ehealthua-tech** [comment]
Коллеги, добрый день. Есть какая-нибудь информация по этой задаче?

**Comment by svetavedmed** [comment]
done with #2968
