### ISSUE TITLE
Get User details by id  PROD (j285)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3087]
Після оновлення (https://github.com/ehealth-ua/api-spec/pull/558) 

запит по отриманні деталей юзера вимагає токен:
https://api.ehealth-ukraine.org/admin/users/{USER_ID} 

раніше його не потрібно було вказувати, питання наступне - яким чином можна отримати деталі юзера після його авторизації і отримання access_token через (Exchange grant token) ? 

Expected results:
Get user details

{
"meta": {
"url": "http://api.ehealth-ukraine.org:8000/admin/users/

{USER_ID}
",
"code": 401,
"request_id": "3489c213-0048-40d7-8187-9f7a0d421744#135175",
"type": "object"
},
"error":

{ "message": "Authorization header is not set or doesn't contain Bearer token", "type": "access_denied" }
}

https://drive.google.com/drive/u/0/folders/1yRSCjGalKE4oIsn-ckuwXnl_jIqY8Nde

**Comment by lymychp** [comment]
даний ендпойнт не призначений для використання через MIS API

**Comment by ehealthua-tech** [comment]
Питання з коменту вище: яким чином можна отримати деталі юзера після його авторизації і отримання access_token через (Exchange grant token)?

**Comment by lymychp** [comment]
такої можливості немає і не передбачалось.
