### ISSUE TITLE
Authorization fail after new release implemented, PROD, #J283

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3099]
После установки новой версии многие пользователи столкнулись с проблемой, которая дл пользователя выглядит, как невозможность авторизации в системе (на FE), на самом же деле является проблемой того, что не очищен кеш по предыдущим обращениям к auth.ehealth-ukrane.org. Т.е. пользователь видит сообщение, что у него неверный логин/пароль. В действительности возникает конфликт между уже обновленным центральным компонентом и кешированной версией uth.ehealth-ukrane.org. Из списка реализованных Вами задач я вижу, что предусмотрено много случае очистки устаревших токенов через заданные периоды времени. Можно ли принудительно очищать кеш/токены при заливке новой версии? Сколько такая задача требует времени? Что для этого необходимо с нашей стороны?

**Comment by lymychp** [comment]
проблема користувачів в неочищеному кеші браузера. На нашій стороні кеш очищений

**Comment by ehealthua-tech** [comment]
Спасибо
