### ISSUE TITLE
Search for patient by id and his declaration is failed, PROD, #J292

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3102]
Добрый день. Возникает проблема при поиске пациента. Детали здесь https://drive.google.com/drive/u/1/folders/12rzJ3Vr8DK9Oj98gPG9l20PvAV4eavOZ?ogsrc=32.  
Смотрела по запросам API - возникает подозрение в корректности формирования запроса. Но, к сожалению, нет возможности проверить детально - доступа к ни к одной из инстанций пока нет. Также можно подозревать некорректный ввод данных пациента. Проверьте, пожалуйста.

**Comment by svetavedmed** [comment]
персона есть в базе, не находится т.к. в базе записана иначе - с пробелами. 
Декларации возвращаются по контексту - legal_entity  и employee. Кто запрашивает данные в запросе не видно.

**Comment by ehealthua-tech** [comment]
Добрый день еще раз. По формированию данных запроса:
Запрос https://api.ehealth-ukraine.org/api/persons/03a67963-c5bd-49c2-b495-f9460a4e173c/declarations
делался овнером ID aa70e9d9-dced-471e-8e3a-51a809c60c87
legal_entity ID 7e910798-7dfb-4561-ac96-aa610c6c5794
Также есть вопрос по валидации: по поводу пробелов - как они попали в базу если фамилии валидируются eHealth на отсутствие таковых?

**Comment by svetavedmed** [comment]
Можете ли повторить ошибку? По всем данным догктор должен был увидеть декларацию.
по валидации - есть тикет #3119 для исправления.
