### ISSUE TITLE
Search by FIO for declaration (NHS problem) is failed, PROD

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3106]
Проверьте, пожалуйста. была ли декларация на это фио с другим телефоном. Декларация здесь https://drive.google.com/drive/u/1/folders/1-RoKLPJf_svOGCeE9tOvAPru7wOEZfOQ?ogsrc=32.  Пациент обратился напрямую в НСЗУ, там не смогли решить вопрос. Заранее спасибо за помощь.

**Comment by svetavedmed** [comment]
С такими ИНН и датой рождением уже есть персона в системе. Декларация для данной персоны была заключена 2018-05-23, тогда же и была создана персона, Декларация была заключена в отделении "Великоцепцевицька амбулаторія загальної практики-сімейної медицини", ид отделения=b8cbc89f-1d40-4ed3-a39e-f6aa50e9d05e, Больницы "Комунальне некомерційне підприємство "Володимирецький районний центр первинної медико-санітарної допомоги"" , ид больницы = a62db51c-31a7-4eff-9ee0-7d58315d4e81. Ид врача, заключившего декларация, a4b56d70-c34e-4cbe-b095-8541893eac1c
