### ISSUE TITLE
Declaration status PENDING_VERIFICATION is not changed more then 30 days, PROD, #J298

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3108]
Доброго дня!
Наведені нижче декларації перебувають у статусі (PENDING_VERIFICATION) "очікують пітвердження" більше 30 днів.

declaration_request_id:
cd72144a-8cd3-435d-aba0-075f6d41718e,
dc11ea0c-dca1-4b11-a54c-ab36a2f2594d,
f33b8d34-f5ba-43de-a7e8-b8fbbefdbebf,
0d7e14a0-c1c0-40db-9781-ccbd9bf3a7ea

declaration_id відповідно:
bd29d2df-57e0-43fe-920c-cd84f778ad82,
7377ec1c-9c35-4ea0-a4a4-bb6668e14e30,
ba7d02e0-656a-489b-9ea4-9230ffe02f20,
7a1d91ac-c887-416c-a8bd-a306f8e616d0

**Comment by svetavedmed** [comment]
все єти декларации в статусе "active", сменили статус 2018-09-08
