### ISSUE TITLE
Get children legal entity by MSP

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3114]
MSP must be able to get list of children legal entities. According to this we need to have new WS base on [logic](https://edenlab.atlassian.net/wiki/x/UoDuJQ) and [spec](
https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/legal-entities/get-legators-legal-entities)

- [x] implement
- [ ] test

**Comment by marinakr** [comment]
https://edenlab.atlassian.net/wiki/spaces/EH/pages/635273505/LE+Reorganization+API

**Comment by danakonovalenko** [comment]
tested
