### ISSUE TITLE
New refresh token for client_id, PreProd, #J303

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3118]
Для МИС необходим обновленный токен для client_id: "68325CEB-84FA-4217-A544-40FC38837911" для препрода. 
Также просьба проверить и, если есть необходимость, актуализировать данные в файле https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit

**Comment by svetavedmed** [comment]
done
