### ISSUE TITLE
save persons to DB w/o spaces

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3119]
1. trim leading and trailing spaces while save person's first_name, last_name and second_name to DB (json_schema)
2. create migration for those fields

**Comment by lymychp** [comment]
we should also not allow or trim double spaces

**Comment by svetavedmed** [comment]
Person is saved to DB w/o double spaces, but search works with all spaces in first, last and second name. 
So, in case there is a person in BD, and new declaration is made for the same person but with extra spaces , it would not be found and person in mpi would be duplicated.
