### ISSUE TITLE
Declaration request failed when scan is download, #J311, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3127]
Помилка при завантаженні скан копій документів при створенні декларації. 
Дані в файлі тут https://drive.google.com/drive/u/0/folders/1wq7PLzQyqEUFw1zEy0Tdk3FSP2_uRPXp?ogsrc=32. Чи потрібна ще інформація від МІС?

**Comment by svetavedmed** [comment]
Да, пожалуйста, респонс, реквест полностью. На препрод воспроизводится?

**Comment by ehealthua-tech** [comment]
Добрый день. Пока проблема не повторяется, можно закрыть этот тикет. Спасибо.
