### ISSUE TITLE
Prolongate contract for merged legal entities

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3129]
Add possibility for NHS admin to update contract end date for merged legal entities

- [x] [logic](https://edenlab.atlassian.net/wiki/x/c4APK) / [apiary](
https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contracts/private.-prolongate-contract)
- [x] implement
- [x] test

**Comment by danakonovalenko** [comment]
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/contracts/1a5865b0-3775-415e-a2a2-c3eee24df7e0/actions/update",
        "code": 403,
        "request_id": "69b11f4b-e493-4c30-9369-f517c6d1eed9#10886",
        "type": "object"
    },
    "error": {
        "message": "ACL: No matching rule was found for path /api/contracts",
        "type": "forbidden"
    }
}
```

**Comment by danakonovalenko** [comment]
please, 
- [ ] change error message from `Incorrect status of parent contract` to `Incorrect contract status to modify it`
- [ ] add verification 
```
Check contractor_legal_entity status = 'active'
in case of error return 422 error 'Legal entity is not active'
```

**Comment by marinakr** [comment]
@danakonovalenko When ehealth return error "Client is not active" on check client legal entity is active  this error code is 403 (forbidden) 
It make sense always return 403 code if legal entity is not active

**Comment by marinakr** [comment]
409 conflict

**Comment by danakonovalenko** [comment]
there is no error in case legal entity is not active
