### ISSUE TITLE
change sing-up and update person in cabinet - add unzr

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3133]
add unzr to Cabinet api:
- [sign-up](https://uaehealthapi.docs.apiary.io/#reference/internal.-cabinet/cabinet/patient-registration)
- [get person detail](https://uaehealthapi.docs.apiary.io/#reference/public.-patient-cabinet/cabinet/get-person-details)
- [update person](https://uaehealthapi.docs.apiary.io/#reference/public.-patient-cabinet/cabinet/update-mpi)
- change json schema

**Comment by svetavedmed** [comment]
- [ ] for GET /api/cabinet/persons/details return expiration_date for documents if exists

**Comment by marinakr** [comment]
Please re-check does MPI database contains expiration_date of document for this  person
