### ISSUE TITLE
Declaration printing error. Doctor's postion is incorrect in the document, Prod, #J275

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3137]
Доброго дня. Опис проблеми з боку користувача
Лікар Сілецький Олександр Олександрович (ід - a2d015f0-a9cb-4401-bfba-32f610d2add4), посада р11 (Лікар-терапевт дільничний), при друці декларацій даного лікаря у пункті 2.4 посада лікаря-спеціаліста вкащано "Терапевт", а не "Лікар-терапевт дільничний".
Для прикладу можна розглянути декларацію з ід - 4f133379-e608-4702-9f1e-864024345423 (declaration_request_id - 6e251f48-9d9e-4470-adae-002986467852)
В розділі даних про лікаря вказано код посади р11, а в розділі контент в пункті 2.4 - "Терапевт"

Деталізація - repro steps тут https://drive.google.com/drive/u/0/folders/1XRUqIYw0MW3JMXep9IcizDJP57u1pyyd?ogsrc=32
Також ам відображено результат, який користувач вважає некоректним.

**Comment by svetavedmed** [comment]
посада - это информационное поле, которое указывает не на специальность врача, а на позицию в больнице. В п. 2.4 "посада лікаря-спеціаліста" указывается именно специальность врача, т.е. Педиатр, Терапевт или Семейный врач
