### ISSUE TITLE
Address of legal_entity is incorrect when deaclaration is printed, PROD, #J321

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3142]
Кроки для відтворення:
1. Реєструєте заклад з вказаною вище адресою.
2. Реєструєте лікарів, підписуєте декларації.
3. Роздруковуєте будь-яку декларацію, отримуєте в полі про заклад невідому інформацію про квартиру, яка не була вказана при реєстрації 
Details here https://drive.google.com/drive/u/0/folders/1Z70s32FqzYVGj4WoT9wsFVfBO_N1pdGK?ogsrc=32

**Comment by svetavedmed** [comment]
в декларации печатается адрес division, а не legal_entity
