### ISSUE TITLE
Maximum attempts exceed, 403, Prod, #J250

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3144]
Добрый день. Проверьте, пожалуйста, в чем причина отказа. 
Также мы запрашивали информацию по лимитам попыток обращения к ЦБД от пользователей МИС и самих МИС. Мы предполагаем, что причиной подобных (см. ниже) отказов может быть превышение этих лимитов.
request:
https://mirra-bershad.newmedicine.com.ua/api/app/ApproveDeclaration?ehealthId=dfffb14c-ebc0-4b0f-822d-23159b919f61&sms=7478
response:
{"message":"success","responce":{"meta":
{"url":"http://api-svc.il/api/declaration_requests/dfffb14c-ebc0-4b0f-822d-23159b919f61/actions/approve","type":"object","request_id":"b2c0e9f6-f0bf-414c-9971-13c38c0f0160#97135","code":403}
,"error":
{"type":"forbidden","message":"Maximum attempts exceed"}

}}

**Comment by lymychp** [comment]
[rate limits](https://docs.google.com/spreadsheets/d/1iNd_0oj-wBx5NJVI-3_YQEe42kBITavyyFbAu9n1cvA/edit#gid=360071771)
