### ISSUE TITLE
Content of the declaration is not placed correctly (for some patients), #J317, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3148]
У некоторых пациентов вид декларации отличается от остальных и размещается некорректно на листе. Вся информация - ид-ры деклараций и примеры -  тут https://drive.google.com/drive/u/0/folders/1HosafleEEDHtVdOMeKYpthJcoM49z4Dm?ogsrc=32

**Comment by lymychp** [comment]
що саме відрізняється?

**Comment by ehealthua-tech** [comment]
Спасибо
