### ISSUE TITLE
Error in PreProd, code = 501, Preprod, #J326

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3151]
Steps to reproduce:
1. При отправке подписанного declaratiom_request получаем 501 ошибку
2. При подгрузке документов получаем 503 ошибку 
Подробности здесь https://drive.google.com/drive/u/0/folders/1wv05pv_ALHJCHBP4nxjWYjcRHLF5u_C-?ogsrc=32

**Comment by svetavedmed** [comment]
fixed on preprod
