### ISSUE TITLE
No data in the documents block in the method Search for person, PROD, #J325 

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3153]
МИС утверждает, что блок документов не приходит в ответе на запрос Search for person. Описание метода в документации https://uaehealthapi.docs.apiary.io/#reference/internal.-master-patients-index/search-for-a-person противоречит его работе в том месте, где говорится о том, что придут исключительно те параметры, которые указаны в запросе. Т.е. в параметрах запрос отсутствует параметр 'document', следовательно запросить документ нельзя.Тем не менее массив докуметов должен приходить в ответе согласно описания метода. Результат - массив документов не приходит. См. подробнее здесь https://drive.google.com/drive/u/0/folders/1nS9pCQhc5H7ndT7rzRXCwLOz1TzW-v2-?ogsrc=32

**Comment by svetavedmed** [comment]
в документации пример на internal search-for-a-person. В [public search-for-a-person](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/persons/search-for-a-person) есть параметр birth_certificate, следовательно его можно передавать в запросе и тогда ответ придет с блоком документов. Другие документы передавать нельзя, т.к. по ним не осуществляется поиск персоны.
например,
request 
```
curl -X GET \
  'https://api-preprod.ehealth-ukraine.org/api/persons?last_name=%D0%90%D0%BB%D1%8C%D0%BE%D1%85%D1%96%D0%BD&first_name=%D0%94%D0%B0%D0%B2%D0%B8%D0%B4&birth_date=2015-07-13&birth_certificate=%D0%86%20-%20%D0%9A%D0%93204034' \
  -H 'Authorization: Bearer QzVYbnZrV2xrVnU4dk1DdEo4ZmgwZz09' \
  -H 'Postman-Token: e6cde250-1116-45b2-919d-fb5659744637' \
  -H 'api-key: d036273f779b1741dcf0' \
  -H 'cache-control: no-cache'
```
response
```
{
    "meta": {
        "url": "http://api-svc.il/api/persons",
        "type": "list",
        "request_id": "36607cbd-fa12-4f76-8a65-42b83d171523#96515",
        "code": 200
    },
    "data": [
        {
            "second_name": "Олегович",
            "merged_ids": [],
            "last_name": "Альохін",
            "id": "4e0e76b6-1f61-46a0-9bba-fd86650a4450",
            "first_name": "Давид",
            "documents": [
                {
                    "type": "BIRTH_CERTIFICATE",
                    "number": "І - КГ204034",
                    "issued_by": null,
                    "expiration_date": null
                }
            ],
            "birth_settlement": "Цюрупи (Голованівський, Кіровоградська область)",
            "birth_date": "2015-07-13",
            "birth_country": "Україна"
        }
    ]
}
```

**Comment by ehealthua-tech** [comment]
спасибо
