### ISSUE TITLE
Create Declaration Request - addresses block, PreProd, #J330

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3154]
Згідно документації та вказаного там прикладу https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/create-declaration-request блок адрес може складатися тільки з одного об’єкту, що має тип Residence.
Але при спробі відправити запит з одним об’єктом з типом Residence отримуємо помилку(вказану нижче).
Поясніть, будь ласка, де є невідповідність та надайте актуальну інформацію щодо правил формування цього запиту.

{"meta":{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"056b574d-1ee5-4d0b-9bd2-77925fb4779d#152023","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"length","params":{"min":2},"description":"expected a minimum of 2 items but got 1"}],"entry_type":"json_data_property","entry":"$.declaration_request.person.addresses"}]}}

**Comment by svetavedmed** [comment]
на данный момент для персоны необходимо вносить два адреса. Согласно требований для новой принформы декларации в скором времени можно будет вносить лишь один тип адреса. Актуальную валидацию для любых запрсов всегда можно посмотреть в json схемах.
