### ISSUE TITLE
StatusCode: 501 in registration MSP process PreProd, DEMO (j331)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3156]
MIS:
Helsi
Середовище:
PreProd
Steps to reproduce:
Процес рерєстрації МСП

Expected results:
200
Описание
Отримаємо StatusCode: 501 in registration MSP process PreProd, DEMO

"Date" : [ 
"Thu, 20 Sep 2018 09:04:34 GMT"
],

"request_id" : "4cbc82d7-cbbf-47dd-855e-652b0a755064",
"request" : {
"method" : "PUT",
"uri" : "https://api-preprod.ehealth-ukraine.org/api/legal_entities",
"formParams" :

{ "signed_legal_entity_request" : "MII....gUto", "signed_content_encoding" : "base64" }
,
"response" : {
"status" : "error",
"message" : "Not Implemented",
"statusCode" : 501,

"body" : {
"meta" :

{ "url" : "http://api-svc.il/api/legal_entities", "type" : "object", "request_id" : "c0612da5-8be9-40d0-aac4-8960d42feb0c#96003", "code" : 501 }
,
"error" :

{ "type" : "internal_error" }
}

**Comment by ehealthua-tech** [comment]
Коллеги, добрый день. Проблема не решилась. Пожалуйста, исправьте.

**Comment by ehealthua-tech** [comment]
Да, ошибка не исчезла:
Помилка однакова як для демо так і препроду. Лог для препроду.
[2018-09-20 14:04:02 GMT]
{
"meta":
{ "url":"http://api-svc.il/apilegal_entities", "type":"object", "request_id":"54d89899-1238-4925-a747-1859a441c9ea#235145", "code":501 }

,
"error":
{ "type":"internal_error" }

}

Сегодня они проверили с другим ключом:
 Редактировать Удалить

Помилка залишається, щойно ще раз перевірили на препрод
{"meta":
{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"45cf09eb-e54d-48da-85ac-501c73fb7fd5#151185","code":501}

,"error":{"type":"internal_error"}}

через 1-2 години спробуємо ще на данних реального лікувального закладу, який ще не реєструвався на демо та препроді, напишу результати.


Перевірили заклад с ключем Привату на препрод, відповідь знову 501

{"meta":
{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"bc2643d6-92c3-412b-9d2a-e507496de623#117214","code":501}

,"error":
{"type":"internal_error"}

}

**Comment by svetavedmed** [comment]
все же сам запрос можно увидеть? cyrl? судя по всему он не верный...

**Comment by ehealthua-tech** [comment]
Здесь все данные по задаче https://drive.google.com/drive/u/1/folders/1do4zgZPgEKkSANtXt7j8lB6_TeKMO2at?ogsrc=32

**Comment by svetavedmed** [comment]
Даже тестовые данные должны быть более менее приближенные к реальным.
Например, данные из запроса
"name":";8=8:0 @>3@5A"
"short_name":"@>3@5AA <54",
"area":"."

**Comment by ehealthua-tech** [comment]
спасибо, уточню

**Comment by ehealthua-tech** [comment]
Задачу можно закрыть, МИС нашли ошибку
