### ISSUE TITLE
Manage client configuration for Mithril admin

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3166]
AS Mithril Admin I want to see any client connections without a context So that I can manage them
[apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/deprecated-client-secret)

Add Connections block that should show list of [client's connections](https://mithrilapi.docs.apiary.io/#reference/mithril.-cruds/clients/get-client-connections)
connected with edenlabllc/ehealth.api#2998

**Comment by lymychp** [comment]
works fine on dev
