### ISSUE TITLE
Scope receiving problem, #J353, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3179]
Steps to reproduce:
    Наведені нижче кроки виконані виключно для депонстрації помилкової ситуації
    1) виконати стандартний oAuth flow для користувача doc.banas@gmail.com
    2) дійти до кроку отримання скоупів на ролюю DOCTOR (час на відео починаючи з 01:35) та отримати пустий JSON-об’єкт data
    3) дійти до кроку https://api.ehealth-ukraine.org/oauth/apps/authorize та, оскільки скоупи на кроці 2 не було отримано, - отримати помилку message: "User requested scope that is not allowed by role based access policies."
    type: "request_malformed"
    за словами клієнта, інші лікарі цього ЗОЗ помилок під час авторизації не отримують
    Expected results:
    позитивне проходження oAuth flow цим користувачем
Описание
відповідь на запит GET https://api.ehealth-ukraine.org/user/roles?client_id=963fb34c-8dd3-4a27-8105-6ca5de15ac33 містить пустий JSON-об’єкт data
см. https://drive.google.com/drive/u/1/folders/1qLzooDPDrb4oLsT7YQ4QBOpZWZW0qFzJ?ogsrc=32

Проблема спостерігається тільки у цього МІС та у цього лікаря

**Comment by svetavedmed** [comment]
у доктора с данным email нет роли в данной клинике. У него две роли - DOCTOR и OWNER, но в другой клинике. Поэтому он и не может получить скоупа для доступа в клинику, в которой он не зарегистрирован.
