### ISSUE TITLE
contribution guide v.1

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3181]
- branches description and it's purpose. How to use
- how to use tags
- steps to propose PR
- PR review rules
- steps to propose hot-fix
- Release process (demo/preprod/prod)

**Comment by kiurchv** [comment]
There are some examples of well done contributing guides:

https://github.com/babel/babel/blob/master/CONTRIBUTING.md
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md
https://github.com/angular/angular/blob/master/CONTRIBUTING.md
https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md
https://reactjs.org/docs/how-to-contribute.html
https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md
https://github.com/moby/moby/blob/master/CONTRIBUTING.md
