### ISSUE TITLE
The role MIS USER is not able to receive its scopes, PreProd, #J355

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3184]
Steps to reproduce:
GET https://api-preprod.ehealth-ukraine.org/admin/roles
Для ролі MIS USER у скоупах містяться скоупи: user:request_factor user:approve_factor
Із цими скоупами неможливо виконати процедуру логіну від користувача МІС.
Expected results:
Скоупи відповідають документації та досзволяють пройти Oauth Flow
Детальніше маємо наступне:

GET https://api-preprod.ehealth-ukraine.org/admin/roles

Response Body:
....
3: scope:"legal_entity:read legal_entity:write legal_entity:mis_verify role:read user:request_factor user:approve_factor event:read"
name:"MIS USER"
id:"56134459-f73e-45a5-af79-e16f3db7151f"
....

При спробі логіну із даними скоупами:
POST https://api-preprod.ehealth-ukraine.org/oauth/apps/authorize

Request Headers:
content-type:"application/json"
api-key:"d036273f779b1741dcf0"
authorization:"Bearer Z2VMSHcyK1ppakorUUxJdmRTL3dRQT09"
cache-control:"no-cache"
postman-token:"6212b19a-0e6f-45d8-8adb-609b86c4a649"
user-agent:"PostmanRuntime/7.3.0"
accept:"/"
host:"api-preprod.ehealth-ukraine.org"
cookie:"__cfduid=d793d0eccd15c42ea6746e77dc14d01711532015998"
accept-encoding:"gzip, deflate"
content-length:267

Request Body:
app:
client_id:"68325CEB-84FA-4217-A544-40FC38837911"
redirect_uri:"http://example.com/redirect"
scope:"legal_entity:read legal_entity:write legal_entity:mis_verify role:read user:request_factor user:approve_factor event:read"

Response Body:
meta:
url:"http://api-svc.mithril/oauth/apps/authorize"
type:"object"
request_id:"c0612da5-8be9-40d0-aac4-8960d42feb0c#112951"
code:422
error:
type:"request_malformed"
message:"Scope is not allowed by client type."

На даний момент виконали запит повторно:
Щойно перепровірив. GET https://api-preprod.ehealth-ukraine.org/admin/roles все ще повертає невірні скоупи.
Response Headers:
date:"Fri, 28 Sep 2018 09:12:35 GMT"
Response Body:
3:
scope:"legal_entity:read legal_entity:write legal_entity:mis_verify role:read user:request_factor user:approve_factor event:read"
name:"MIS USER"
id:"56134459-f73e-45a5-af79-e16f3db7151f"

**Comment by ehealthua-tech** [comment]
Добавляю присланные ими данные и доп. описания

Процедура логіну виконувалась від наданого тестового користувача МІС:
client_id: 68325CEB-84FA-4217-A544-40FC38837911
access_token:12d8156e3c1ee26c09c2 c490c936651a0f6badeb426721076437
client_secret: cf8ddbe190a54e153bf9
redirect_uri = http://example.com/redirect
user login = mis_94436a495c@email.com
user psw = 12345678
Також зауважу, що якщо видалити із запиту скоупи user:request_factor user:approve_factor то логін проходить успішно.

ЕМСИМед также добавляет, что столкнулся на препрод с этой ошибкой:

У нас така саме помилка на ПРЕ-ПРОДі під час проходження oAuth від імені "MIS USER"

client_id = '08f21410-7b5f-4771-a648-f40bde95b650'
client_secret/mis_api_key = 'f40d3bb7b183f40e9edd'
user login = 'test_user@mail.com'
user password = 'Pnm4RGwr73T6DC(]jjqo'
access_token = '0d5573e57dd6bf554cc7'
refresh_token = 'bee5d69c2761d2449a15'

client_id: fa41716f-de5c-45fb-ac86-9ae6962f5e54
access_token: 256e839faf5ac39d17b8a768aa5ea268
client_secret: 7e3d7caee0bb522a5079
redirect_uri = http://example.com/redirect
user login = mis_f57185ec77@email.com
user psw = 12345678

на test_user@mail.com - помилка невідповідності redirect_uri

01.10.2018 10:37:27
Protocol error
Function name: internalAppAuthorize;
Request URL: https://api-preprod.ehealth-ukraine.org/oauth/apps/authorize;
Request headers: Authorization: Bearer UU00OUprTEJXNDF0QnpUb0RLMXpyQT09 ## Api-key: 7e3d7caee0bb522a5079 ## Content-Type: application/json ## Accept: */* ## Cache-Control: no-cache ## Pragma: no-cache;
Response code: 422;
Response text: HTTP/1.1 422 Unprocessable Entity;
Response: {"meta":{"url":"http://api-svc.mithril/oauth/apps/authorize","type":"object","request_id":"bc2643d6-92c3-412b-9d2a-e507496de623#129578","code":422},"error":{"type":"request_malformed","message":"Scope is not allowed by client type.","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

**Comment by svetavedmed** [comment]
ошибка не воспроизводится. Под логином user login = mis_94436a495c@email.com на демо залогинится могу. Запрашиваю след. скоупы "scope": "legal_entity:read legal_entity:write legal_entity:mis_verify role:read event:read employee_request:read". Токен получаю.

Для юзера редирект ури отправила в личку.
