### ISSUE TITLE
write to log hard bounced emails

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3186]
As for now hard bounced emails are not represented in logs. In case email was hard bounced it should be saved to logs.

**Comment by progsmile** [comment]
emails can be found in kibana by queries

bounced emails: `"[PostmarkClient]: Attempting to activate"`
activated emails: `"PostmarkClient Email" "was activated"`

**Comment by lymychp** [comment]
checked on prod logs
