### ISSUE TITLE
Error 400 in Prod instance when user tries to sign in a declaration, Prod, #J374

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3189]
При отправке подписанного контента декларации получаем ошибку 400: matching TSP certificate not found.
См. здесь https://drive.google.com/drive/u/1/folders/1r9TzhkUxroC_7YPcL8eKw8-iiG-TQHUK?ogsrc=32

**Comment by svetavedmed** [comment]
Можете в файл добавить сам реквест? Спасибо.

**Comment by svetavedmed** [comment]
done for prod
