### ISSUE TITLE
Digital Stamp

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3193]
As NHS admin I want to be able not only to sign documents with DS, but with Digital Stamp as well. 
For that we need to implement service which allow to sign documents with Digital Stamp and check its' validity

**Comment by lymychp** [comment]
only if it is possible

**Comment by danakonovalenko** [comment]
as for now when we send content with more than 1 signature we receive an error
[content_2signatures.txt](https://github.com/edenlabllc/ehealth.api/files/2538404/content_2signatures.txt)

```
{
    "meta": {
        "url": "http://api-svc.digital-signature.svc.cluster.local/digital_signatures",
        "type": "object",
        "request_id": "5386d3e9-0d55-41ba-bb61-f06ec599f5d1#17739",
        "code": 424
    },
    "error": {
        "type": "failed_dependency",
        "message": "The method could not be performed on the resource because the requested action depended on another action and that action failed."
    }
}
```

**Comment by marinakr** [comment]
troubles with index on dev
