### ISSUE TITLE
Admin authorization probs, Prod+PreProd, #J375

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3196]
На Prod та PreProd не працює авторизація уповноваженої особи (роль ADMIN)
Після натисканні кнопки Прийняти та продовжити пуста сторінка
Просимо дати коментар в чому може бути причина.
Scope передаємо згідно https://edenlab.atlassian.net/wiki/spaces/EH/pages/2004415/Scopes+model
Детальніше тут https://drive.google.com/drive/u/1/folders/1U4QMY5v-7lsCO9vUD1Rj0M98uoAUfEGn?ogsrc=32

**Comment by svetavedmed** [comment]
согласно Scopes model у admin нет скоупа "employee_request:read", вы же его передаете, потому и ошибка
