### ISSUE TITLE
DEDUPLICATION_DEPTH bug

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3199]
Candidates for deduplication must be chosen based on DEDUPLICATION_DEPTH:
```
- Read DEDUPLICATION_DEPTH parameter value. 
   If DEDUPLICATION_DEPTH = 0, analyze the whole period
- Fetch records from MPI.person created in DEDUPLICATION_DEPTH
```
As for now when DEDUPLICATION_DEPTH = 0, zero candidates will be returned.

**Comment by lymychp** [comment]
@danakonovalenko it is not actual anymore, right?

**Comment by danakonovalenko** [comment]
yes, it's not actual and can be closed
