### ISSUE TITLE
Problem with token on DEMO instance, Demo, #J386

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3201]
Доброго дня, підкажіть як отримати (де взяти) токен до демо. Беру з файлу - він невалідний, пробую авторизуватися по даних з файлу (client_id, email, etc..) - отримую "Не знайдено додаток за вказанним ідентифікатором" після входу.

На даний момент МІС використовував ці дані:

client_id: D552A01A-CD67-4C0B-B34C-921FF05E6CF6
access_token: 41e1d188453e26846c469f0388322613
client_secret: 7a07feaf4c37ef135f85
redirect_uri = http://example.com/redirect
user login = mis_dbf51fee31@email.com
user psw = 12345678

**Comment by svetavedmed** [comment]
is duplicated by #3203
