### ISSUE TITLE
Demo, Preprod tokens problem, (HRIS tests)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3203]
Необходимо обновить токены (демо, препрод). При тестировании по проекту HRIS - данные не валидны, а также сегодня поступают массовые жалобы от МИС. Информация по результатам тестирования здесь https://drive.google.com/file/d/0B5A4tisi0ko2dVhsWnA4R0tTbVdmbHd6eW5NeW1xRkpSbUhr/view?usp=sharing.
Использовались токены по ранее предоставленной ссылке: https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit.

**Comment by svetavedmed** [comment]
Для логина нужно использовать следующую ссылку
https://auth.demo.asclepius.com.ua/sign-in?client_id={{mises_client_id}}&scope={{requested_scopes}}&redirect_uri={{mis_redirect_uri}}
где client_id - ид клиента миса
скопы - скоупы для МИСа
redirect_uri - это redirect_uri для МИСа

Все данные в файлике верные. Логинится нужно через наш фронт. Далее можно использовать рефреш токен.
