### ISSUE TITLE
Teenagers' declarations were stopped incorrectly, Prod, #J368

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3204]
В період до 25 червня 2018 (дата реалізації https://github.com/edenlabllc/ehealth.api/issues/2473) декларації укладені неповнолітньою особою мають значення end_data = дата досягнення повноліття.
Така ситуація для сімейного лікаря не відповідає вимогам 503 наказу. 
Expected results:
Декларації неповнолітніх із сімейним лікарем мають бути безстроковими.

**Comment by AlekzandrV** [comment]
Можно примеры таких деклараций?

**Comment by ehealthua-tech** [comment]
Вот так я сформулировала для них запрос:

"Декларація, яка укладена
-  В період до 25 червня 2018 неповнолітньою особою мають значення end_data = дата досягнення повноліття.
 -  Що була закрита, але мала не розриватись
 -  Припинення відбулось автоматично ТА причиною розірвання стало досягнення end_data = дата досягнення повноліття."
Вот полученные от них примеры и замечания:
https://drive.google.com/drive/u/1/folders/1JCss91HSQsBJ9r9Mxq5YrbCzNEhuSCxw?ogsrc=32

**Comment by svetavedmed** [comment]
Декларации заключенные до изменений уже нельзя изменить, т.к. декларации подписываются личной электронной подписью врача. Такие декларации будут разорваны по истечению срока действия. Новые декларации с семейными врачами будут заключены бессрочно.
