### ISSUE TITLE
Insert one more type of document into the dictionary, #J369, Prod, Preprod, Demo

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3205]
У дітей народжених закордоном може не бути свідоцтва про народження, а буде Довідка про громадянство дитини з консульства України.
Для коректного укладання декларації з такими пацієнтами необхідно додати відповідний документ.
Перевірила в словниках на даний момент - такого типа документа не знайшла.

**Comment by svetavedmed** [comment]
Согласно указу [503 от 19.03.2018](http://zakon.rada.gov.ua/laws/show/z0347-18) такого документа нет среди тех, что необходимо предоставлять для подписания декларации.
список документов
- паспорт громадянина України;
- тимчасове посвідчення громадянина України;
- свідоцтво про народження (для осіб, які не досягли 14-річного віку);
- посвідка на постійне проживання в Україні;
- посвідчення біженця;
- посвідчення особи, яка потребує додаткового захисту;
