### ISSUE TITLE
[Summary] Get Allergy Intolerances (List, by ID)

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3208]
As a Authorized eHealth User
I want to see patient's allergy intolerances as a part of patient summary
So that i can provide high quality medical care for patient

Implement service according to spec ([List](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/patient-summary/get-allergy-intolerances), [by ID](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/patient-summary/get-allergy-intolerance-by-id)) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/616399174/Get+Allergy+Intolerances)

child of #3206

**Comment by IrinaRevutska** [comment]
- [ ]  should be 404 if patient does not exist but not empty array
```
GET /api/patients/5386d3e9-0d55-41ba-bb61-f06ec599f5d1/summary/immunizations HTTP/1.1
Host: https://api.dev.asclepius.com.ua
Content-Type: application/json
Authorization: Bearer K0JocVFqQklyTGFoaHF3MTlybVJ2UT09
api-key: eDBidGdHakQvWXB6M0RRZWUwM3BhUT08
cache-control: no-cache
Postman-Token: 13ea41c9-ce3f-4076-b2ed-c3c9e7461a40
```
