### ISSUE TITLE
[Summary] Get Observations (List, by ID)

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3210]
As a Authorized eHealth User
I want to see patient's observations as a part of patient summary
So that i can provide high quality medical care for patient

Implement service according to spec ([List](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/patient-summary/get-observations), [by ID](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/patient-summary/get-observation-by-id)) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/654279128/Summary+Observations)

child of #3206

**Comment by IrinaRevutska** [comment]
- [ ] No filtration on list

**Comment by IrinaRevutska** [comment]
- [ ] Why can I see any in response? Should be `16cad9b7-3237-4de2-8172-b2c2d74dc4f3`
