### ISSUE TITLE
add person change to event manager

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3214]
As legal entity employee 
I want to know if person I work with was deactivated 
So as I know if i still have permission to work with this person

- [ ] design
    - [spec](https://edenlab.atlassian.net/wiki/x/3YC6Cg)
    - [apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-event-manager)
- [ ] implementation
   - person status change
        - auto merge
- [ ]  test

**Comment by lymychp** [comment]
`entity_type` in event_manager should be `Person`, not `MergeCandidate`
