### ISSUE TITLE
Error 505 when InitOTPVerification method is called, #J400, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3222]
виклик InitOTPVerification
в декларації телефон у дитини зазначений той самий, що і в раніше укладеній декларації у його батьків 
подробиці тут https://drive.google.com/drive/u/1/folders/1KQGO6yj59uexprWg53Y2VkcW_NALvddD?ogsrc=32

**Comment by svetavedmed** [comment]
won't fix
