### ISSUE TITLE
Modifications in the dictionary uaddress, #J402, Demo, Preprod, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3223]
Steps to reproduce:
    Наразі перелік підрозділів організацій розташовані у населених пунктах, що являются гірськими згідно Постанови Кабінету Міністрів від 11 серпня 1995 р. № 647 "Про перелік населених пунктів, яким надається статус гірських".

    Згідно із довідником населених пунктів на стороні ЦК ці населені пункти не являються гірськими.
    Що впиває на формування звітів НСЗУ "Про обсяг медичних послуг, пов'язаних з первинною медичною допомогою".
    Expected results:
    1. Привести довідник населених пунктів у відповідність Постанови Кабінету Міністрів "Про перелік населених пунктів, яким надається статус гірських"

    2. Формування коректних звітів "Про обсяг медичних послуг, пов'язаних з первинною медичною допомогою"

Описание

КЗ «Путильський районний Центр первинної медико-санітарної допомоги» Код ЄДРПОУ 36754912

Підрозділи:
1. Путильська амбулаторія ЗПСМ адреса: 59100, Чернівецька область, Путильський район, селище міського типу Путила, вулиця Українська, будинок 38
2. Розтіцька амбулаторія ЗПСМ, адреса: 59111, Чернівецька область, Путильський район, село Розтоки, вулиця Головна, будинок 172
3. Яблунецька амбулаторія ЗПСМ , адреса:59126, Чернівецька область, Путильський район, село Яблуниця
4. Довгопільська амбулаторія ЗПСМ , адреса: 59120, Чернівецька область, Путильський район, село Довгопілля, вулиця Миколайчука, будинок 24
5. Селятинська амбулаторія ЗПСМ, адреса: 59131, Чернівецька область, Путильський район, село Селятин, вулиця Шкільна, будинок 3А

Постанова Кабінету Міністрів "Про перелік населених пунктів, яким надається статус гірських":
http://zakon.rada.gov.ua/laws/show/647-95-%D0%BF

-------
Від eHealth:
Відправлено запит до юридичного відділу щодо правомочнсті таких змін. Тому поки що пропнуємо вности зміни на демо та препрод. Спасибі.

**Comment by ehealthua-tech** [comment]
Отримали відповідь юристів;
"Пункт 50 Постанови Кабінету Міністрів України від 25 квітня 2018 року №411, передбачає, що Адміністратор:

1) здійснює адміністрування та технічну підтримку центральної бази даних, зокрема виконує функції, передбачені пунктом 8 цього Порядку;
пунктом   8. Порядку  Функціональні можливості електронної системи охорони здоров’я повинні забезпечувати:  12) можливість використання для внесення та систематизації інформації у центральній базі даних державних класифікаторів, номенклатур та довідників, затверджених в установленому законодавством порядку;
Наразі перелік підрозділів організацій розташовані у населених
пунктах, що являются гірськими згідно Постанови Кабінету Міністрів від
11 серпня 1995 р. № 647 "Про перелік населених пунктів, яким надається
статус гірських".  вона чинна, тому буде приведено у відповідність ЦБД ."
Будь ласка, візьміть тікет у роботу. Спасибі.

**Comment by svetavedmed** [comment]
done for demo and preprod

**Comment by svetavedmed** [comment]
done for prod according to the law
