### ISSUE TITLE
2 active declaration, 2 different id, no tax_id for 1 person, Prod, #J404

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3244]
Користувачі виявили, що існують дві активні декларації на одну особу у різних лікарів.
Тобто на одну активну особу створилися дві різні сутності person.

Наводжу лані персони тут https://drive.google.com/drive/u/1/folders/1mZoxuGL6KUfda1_yF1QBjqBq7pCHGDHP?ogsrc=32
як так сталося, що існують дві підписані, активні декларації на одну й ту саму особу в різних лікарів ?

**Comment by svetavedmed** [comment]
Дети ищутся по Дата рождения+номер сертификата о рождении. В данном случае не нашелся человек из-за разного воода номера документа свидетельства о рождении. Учитывая то, что подобный ввод часто присутствует, будут применены изменения для документов. Во-первых, будет более строгая валидация; во-вторых, поиск детей будет немного изменен.
