### ISSUE TITLE
Get legalEntityMergeJobs 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3251]
As NHS admin I want to be able to receive and filter async job by legal entity according to 
[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/legalEntityMergeJobs.graphql)  [features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/async_jobs.feature) and design

**Comment by danakonovalenko** [comment]
- [ ] please, fix errors according to [test cases](https://edenlab.atlassian.net/wiki/x/AQDFJw)

**Comment by danakonovalenko** [comment]
I still receive 500 when input not valid ID and '1970-01-01' as end_date when job status is PENDING

**Comment by PavelVesnin** [comment]
@danakonovalenko cause it's delivered on dev just now
