### ISSUE TITLE
Adopt conventional commits spec on the backend repos

### ISSUE THREAD

**Issue by kiurchv** [edenlabllc/ehealth.api#3277]
Adopting the [conventional commits](https://www.conventionalcommits.org/) spec will get us meaningful commit messages, automated versioning and change log management.

We can do this with https://github.com/zachdaniel/git_ops tool
Also consider to use https://github.com/z0al/commitlint-bot as check for PRs

**Comment by AlexKovalevych** [comment]
On ` mix git_ops.release --initial` getting

```
== Compilation error in file lib/confex_config_provider.ex ==
** (CompileError) lib/confex_config_provider.ex:22: module Mix.Releases.Config.Provider is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/confex_config_provider.ex:22: ConfexConfigProvider (module)
```

**Comment by marinakr** [comment]
Git_ops added for ds.api. Note: version_tag_prefix in current git_ops could not be empty. Change lib or use with prefix

**Comment by kiurchv** [comment]
@marinakr Its absolutely fine to have prefix in tags, majority of the open-source projects (and Elixir itself) uses it

**Comment by marinakr** [comment]
make apps umbrella

**Comment by marinakr** [comment]
[ ] man
[ ] ael
[ ] mithril
[ ] uadresses

**Comment by marinakr** [comment]
we can use own git server and check commits with hooks
allow push on github only from that server
