### ISSUE TITLE
API does not return the block of data by the request get legal entity by id, DEMO, #J358

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3282]
Steps to reproduce:
https://api.demo.asclepius.com.ua/api/legal_entities/c39710d0-82e4-462d-8dc7-247f073f814f
Expected results:
отсутствие полей
"urgent": {
        "security": {
"redirect_uri": "",
            "client_secret": "",
            "client_id": ""
}
    }
ожидалось наличие этих полей в ответе согласно  https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entity-by-id

Полностью запрос - ответ
curl -X GET \
https://api.demo.asclepius.com.ua/api/legal_entities/c39710d0-82e4-462d-8dc7-247f073f814f \
-H 'API-key: f40d3bb7b183f40e9edd' \
-H 'Authorization: Bearer TmR1WDlRRnYwdlNXc0RFMG4vNmVvUT09' \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-H 'Postman-Token: 548cc463-4a57-4291-b276-3b8b72b13bdb'

{
"urgent": {
"security": {}
},
"meta":
{ "url": "http://api-svc.il/api/legal_entities/c39710d0-82e4-462d-8dc7-247f073f814f", "type": "object", "request_id": "783dfcf0-c0a1-46f2-80c8-5b90efbb9b1e#174716", "code": 200 }

,
"data": {
"website": "www.ipag.com",
"updated_by": "7dfa0a74-f2c8-4063-b92f-691178d0af1d",
"updated_at": "2018-06-27T15:20:42.051646",
"type": "MSP",
"status": "ACTIVE",
"short_name": "ІПАГ",
"receiver_funds_code": null,
"public_name": "ІПАГ",
"phones": [
{ "type": "MOBILE", "number": "+380634811482" }

],
"owner_property_type": "STATE",
"nhs_verified": false,
"name": "Інститут педіатрії, акушерства та гінекології",
"mis_verified": "VERIFIED",
"medical_service_provider": {
"licenses": [
{ "order_no": "34689120", "license_number": "нк 6759874", "issued_date": "2018-04-02", "issued_by": "КНУА", "expiry_date": "2020-06-30", "active_from_date": "2018-04-02" }

],
"accreditation":
{ "order_no": "655473892", "order_date": "2017-05-10", "issued_date": "2008-04-02", "expiry_date": "2022-05-30", "category": "FIRST" }

},
"legal_form": "425",
"kveds": [
"86.21"
],
"is_active": true,
"inserted_by": "7dfa0a74-f2c8-4063-b92f-691178d0af1d",
"inserted_at": "2018-06-25T15:38:39.832685",
"id": "c39710d0-82e4-462d-8dc7-247f073f814f",
"email": "poshta1822@gmail.com",
"edrpou": "77778888",
"beneficiary": null,
"archive": null,
"addresses": [
{ "type": "REGISTRATION", "street_type": "STREET", "street": "Мельникова", "settlement_type": "CITY", "settlement_id": "adaa4abf-f530-461c-bcbf-a0ac210d955b", "settlement": "КИЇВ", "country": "UA", "building": "34", "area": "М.КИЇВ" }

]
}
}

**Comment by lymychp** [comment]
блок `urgent` - optional. Він повертається тільки у відповідь на `POST /legal_entities`.
У відповідь на GET ніколи не повертався і не буде з точки зору безпеки
