### ISSUE TITLE
Error 401. Access denied. Redirect url is not valid. #J433, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3301]
Користувач не може авторизуватись в системі. Проблема з  redirect url.
Запит - відповідь тут https://drive.google.com/drive/u/0/folders/1dAkQKNhP7tbN_2bGZnZpXEaMDONMEZgJ?ogsrc=32

**Comment by svetavedmed** [comment]
fixed
