### ISSUE TITLE
API returns user_id which does not exist in the legal entity, Prod, #J434

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3310]
При спробі авторизації на ЕХ, користувачеві вертається user_id, який не існує в межах установи даного користувача.
Опис проблеми тут https://drive.google.com/drive/u/1/folders/1DLmaf2XJypniNoq8HZdNrWyaRL-sf9EQ?ogsrc=32

Якщо зробити вибірку всіх employee_request в межах даної установи то жоден з employee_request не матиме отриманий user_id.

User_id вказаного користувача, на даний момент є іншим - див. за посиланням вище
Питання - чому при спробі авторизації ми отримуємо токен для користувача (user_id), якого не існує в межах даної установи?

**Comment by lymychp** [comment]
`user_id` та `employee_id` - атрибути різних об'єктів
З опису не зрозуміло в чому проблема.
Ви отримали токен. Чим він Вас не влаштовує? Які операції не проходять?

**Comment by ehealthua-tech** [comment]
Наскільки я їх зрозуміла,, то вони не задоволені тим, що користувач з такою електронною адресою має інший user_id.
Також вони вважають, що людина з таким user_id не належить до вказаного legal_entity.
Але мені також не все зрозуміло з їх запиту, тому я прошу в них більш кокретний опис проблеми.
Ваші питання додам до своїх.

**Comment by ehealthua-tech** [comment]
Проблему вирішено. Можна закрити задачу.
