### ISSUE TITLE
2 active declarations in the system, Prod, #J436

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3314]
Звернулись з ЗОЗ про те що вони мають 2 активні декларації на одного пацієнта.  id декларацій тут https://drive.google.com/drive/u/1/folders/12kz1E6hqJBf8YVAYgut6QHyuWO67lSOR?ogsrc=32

**Comment by svetavedmed** [comment]
деклараций действительно две по каждой из персон, однако одна из них в статусе "active", а вторая  "terminated". Так и должно быть. У одной персоны должна быть только одна декларация в статусе "active", но "terminated" и "closed" могут дублироваться, т.к. эти декларации недействительны уже.
