### ISSUE TITLE
Declaration signing probs, Prod, #J438

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3328]
При подписании декларации у доктора возникает проблема только с одним пациентом.
Подробнее - запрос, сообщение об ошибке - здесь https://drive.google.com/drive/u/1/folders/1fbGqtVDMq4pkljR28aP09JbdZTaD5kus?ogsrc=32

**Comment by svetavedmed** [comment]
duplicates #2924
