### ISSUE TITLE
Add dictionary type

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3354]
- [x] list
- [x] update

**Comment by danakonovalenko** [comment]
please, update schema for Dictionaries type

**Comment by danakonovalenko** [comment]
As field id was added to il.dictionaries we should use it in Update mutation.
```
input UpdateDictionaryInput {
"The ID of an object."
  id: ID!
 "Name of a dictionary."
  name: String
  "In case dictionary is used isActive = true."
  isActive: Boolean
  "Type of usage dictionary in the system"
  labels: [String]
  "Dictionary's values."
  values: JSON
}
```

**Comment by danakonovalenko** [comment]
please, fix [test cases](https://edenlab.atlassian.net/wiki/x/AQD3KQ) which return incorrect results

**Comment by progsmile** [comment]
String is already parsed with one key

**Comment by danakonovalenko** [comment]
it was decided to fix on front side https://github.com/edenlabllc/ehealth.web/issues/619
