### ISSUE TITLE
 Validations on create contract_request

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3360]
Validate contract_type according (*Validation p1*)

Validate program according (*Validation p13,14*)

Validate contract_number (*p.10.e , p10.f*)

Validate contract is unique  (*p.12, it has been modified - medical_pogram_id validation added for reimbursement contracts*)

Add medical_program_id to "Search pending contract requests"

 [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523960439/Create+Contract+Request#CreateContractRequest-Validaterequest)

**Comment by svetavedmed** [comment]
- [ ] NHS sign button does not work
- [ ] error after contract request list page return

![Screen Shot 2018-12-21 at 3.45.58 PM.png](https://zube.io/files/edenlabllc/86c1b8757089a433687586d32c7ba821-screen-shot-2018-12-21-at-3-45-58-pm.png)
