### ISSUE TITLE
Error (code 31 React) when create employee method is processed, Prod, #J446, #J448

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3375]
Кілька МІСів стверджують, що не можуть зареєструвати лікаря. Це прод. Відповідь  така: в консолі браузера користувача: "помилка #31
Invariant Violation: "Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Brules%2C%20entry_type%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "" 
 Кеш очистидли зазадлегідь. Також це зроблено перед повторенням для відтворення помилки.
Подробиці тут https://drive.google.com/drive/u/0/folders/1ZIQmZRZB6umuruxRAMk8Y4L2z0jCTQJL?ogsrc=32

**Comment by lymychp** [comment]
В тікеті описані проблеми з МІСом. Немаї інформації про те які апі і як саме не працюють. 
Нехай звертаються в службу підтримки МІС.

**Comment by ehealthua-tech** [comment]
Запросили додаткову інфрмацію у МІСа.

**Comment by lymychp** [comment]
Прошу уточнити 
1) які параметри перпдавались при редіректі на `https://auth.ehealth-ukraine.org/sign-in`
2) Який url в браузері після кроку 4?

**Comment by ehealthua-tech** [comment]
додала файл ji446_448_add.txt
