### ISSUE TITLE
2 owners for 1 clinic. Prod, #j450

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3385]
Для legal_entity c id: 8fff90c1-2d95-4357-b885-8a34b220dda8
обнаружили двух OWNER
запрос: request_15922545
и запрос: request_15922854
причем в списке сотрудников: request_ 15921185
присутствует только один owner

у employee отличается только start_date
отсутствует end_date
и одинаковый статус APPROVED

Вопрос:
- может ли быть больше одного owner в организации?
- как удалить лишнего? :)
- почему отображается только один в списке сотрудников? 
Подробности тут https://drive.google.com/drive/u/0/folders/1Az-4lfP0I0qyAcK5I3whKH0pF3ZFk0zU?ogsrc=32

**Comment by svetavedmed** [comment]
у данной lehal_entity два оунера, но только один активный. Все верно.
