### ISSUE TITLE
Insert record into dictionary LEGAL_FORM, PROD, #J300 

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3408]
Прохання поновити роботу над заадчей #3143. Пріорітет встановлюю стандартний, але прохання прискорити виконання цієї задачі.

**Comment by lymychp** [comment]
@ehealthua-tech прошу підтвердити, що юристи підтвердили необхідність виконання даної задачі

**Comment by ehealthua-tech** [comment]
Маємо таку інформацію від НСЗУ; "Найближчим часом, НСЗУ опублікує нового листа, який не буде вимагати в ОПФ вказувати КНП.".
Тікет можна закрити.
