### ISSUE TITLE
[Episode context] Get encounters list and details

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3425]
Implement web service according to spec ([list](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/episode-of-care/get-encounters-in-episode-context), [details](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/episode-of-care/get-encounter-details-in-episode-context)) and [logic](https://edenlab.atlassian.net/wiki/x/DQBfK)

child of edenlabllc/ehealth.api#3424

**Comment by IrinaRevutska** [comment]
Please, fix Data consistency validation according to the [specefication](https://edenlab.atlassian.net/wiki/spaces/EH/pages/677314573/Get+child+entities+through+episode+context#Getchildentitiesthroughepisodecontext-Validatedataconsistency) - should be 404 in case episode does not exist (both by id and list)
[Test cases ](https://edenlab.atlassian.net/wiki/spaces/EH/pages/717619425/Test+Cases+Get+child+entities+through+episode+context)
