### ISSUE TITLE
[Changes] Add episode number to episode of care

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3434]
Add episode number to episode of care

episode number - is a common identifier for all service requests related to this episode of care
This number must be unique and is generated by the client before submitting request

- [ ] Add attribute to DB ([spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/602800163/Medical+Events+Data+Model#MedicalEventsDataModel-Episodeofcare))
- [ ] Update create episode WS ([spec](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/episode-of-care/create-episode), [description](https://edenlab.atlassian.net/wiki/x/UoD2J))

child of edenlabllc/ehealth.api#2811

**Comment by IrinaRevutska** [comment]
get episode?

**Comment by AlekzandrV** [comment]
won't implemented

Revert changes in specs
