### ISSUE TITLE
[Changes] Create medication request - improve validation according to new attributes

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3476]
[Changes] Create medication request - improve validation according to new attributes

1. There can be more than one medication request with type _plan_ at the same period with the same innm
2. Apply different schemas for plan and order
3. Validate attributes:
    * prior prescription - valid medication request
    * context - valid Encounter
    * intent - dictionary
    * category - dictionary
    * dosage instructions - valid object

child of edenlabllc/ehealth.api#3474

**Comment by lymychp** [comment]
IL and ops

**Comment by lymychp** [comment]
duplicated
