### ISSUE TITLE
Offline verification

### ISSUE THREAD

**Issue by DPashchenko** [edenlabllc/ehealth.api#348]
As a NHS Admin i want to see list of declarations that needs to be verified via NHS portal.
Declaration status for verification: Pending

**Comment by DPashchenko** [comment]
Confluence: https://edenlab.atlassian.net/wiki/display/EH/Declaration+verification

**Comment by lymychp** [comment]
- [ ] NHS admin FE
- [ ] 4 BE methods

**Comment by lymychp** [comment]
blocked by #674

**Comment by gmile** [comment]
@lymychp should be unblocked now.

**Comment by lymychp** [comment]
[get declaration images endpoint](http://docs.uaehealthapi.apiary.io/#reference/internal.-il-db/get-declaration-request-images-list/get-declaration-request-images-list)
