### ISSUE TITLE
Making setting for new github acc (acc ehealthUA-support for support MISes)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3497]
Прохання налаштувати новий аккаунт для колег з ДП "Електронне здоров'я" для Служби підтримки МІС.
Колеги мають мати можливість:
- створити тікет на гітхабі
- редагувати тікет
Правила щодо встановлення mark (support, level of priority) надані працівникам Служби підтримки.
Login ehealthUA-support

**Comment by lymychp** [comment]
added as collaborator
