### ISSUE TITLE
Change regex for TEMPORARY_CERTIFICATE number validation (prod, #J444)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3514]
Старий варіант сертифікату має довжину 5 цифр в номері. На даний час в regex жостко встановлено 6 цифр в номері сертифікату. Прохання змінити regex з урахуванням такої можливості, як наявність меньше ніж 6 цифр в номері. 
Приклад документу https://drive.google.com/drive/u/0/folders/1Stveu2Nxa2nINoghMoMY9X0fL9-1l5Ae?ogsrc=32

**Comment by svetavedmed** [comment]
Согласно [постановления № 1983 ](http://zakon5.rada.gov.ua/laws/show/251-2012-%D0%BF) технического описания п.16 должно быть 6 цифр.  
```16. У верхній частині сторінок бланка посвідки та правого форзаца перфорується серія і номер посвідки, що складаються з двох літер та шести цифр.```
Прошу подтвердить изменение на 5 цифр.
Спасибо

**Comment by lymychp** [comment]
@ehealthua-tech please answer the question

**Comment by eHealth-victory** [comment]
Прохання до @ehealthUA-support - отримати від юриста відповідь щодо останнього уточнення з боку Світлани.

**Comment by nemaslov** [comment]
@jafaribnmustaf Приклад ЧР №1111 і йому подібні містять пробіл та номер. Щоб уніфікувати формат та запобігти виникнення помилок при повторному введенні, пропонуємо вводити в форматі XXY..Y, де XX - серія, Y..Y-номер у необхідній кількості цифр(4-6) який не містить пробілу та символу №.

**Comment by nemaslov** [comment]
@jafaribnmustaf Внесли виправлення. 
Буде доступно при наступному релізі.
