### ISSUE TITLE
Get Contract REST

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3522]
[confluence Contract List](https://edenlab.atlassian.net/wiki/spaces/EH/pages/529039458/Get+Contracts+List)
[apiary Contract  list](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-get-contracts-list)
- create separate routes for capitaion and reimbursement versions of a contract
- add contract_type
- add medical_program_id
- add filtration by medical_program_id

[confluence Contract details](https://edenlab.atlassian.net/wiki/spaces/EH/pages/530481202/Get+Contract+by+ID)
[apiary Contract  details](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-get-contract-details)
- create separate routes for capitaion and reimbursement versions of a contract
- add contract_type
- add medical_program_id
- add filtration by medical_program_id

[DataModel](https://edenlab.atlassian.net/wiki/spaces/EH/pages/671252546/Contract+Reimbursment+version+Data+model)

**Comment by svetavedmed** [comment]
- [ ] pharmacy owner should get only reimbursement contracts and only its own. As for now I can get too much
