### ISSUE TITLE
Authorization problems in Preprod, Preprod, #J491

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3527]
Steps to reproduce:
Другий крок авторизації
POST /oauth/apps/authorize
Expected results:
Успішна авторизація
Подробиці тут https://drive.google.com/drive/u/0/folders/1McRkK5bml9w8vlLvPuxuhF1mGldaHsb2?ogsrc=32

**Comment by svetavedmed** [comment]
fixed
