### ISSUE TITLE
Release service request API

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3540]
Implement service according to spec and logic

1. Release service request - [Apiary](https://ehealthreferralsapi.docs.apiary.io/#reference/service-requests/manage-service-requests/release-service-request), [Confluence](https://edenlab.atlassian.net/wiki/x/BQBNJw)

child of edenlabllc/ehealth.api#3491

**Comment by AlexKovalevych** [comment]
Implemented without incoming_referrals validations

**Comment by AlekzandrV** [comment]
The following validations are not implemented:
* [Check for related episodes and encounters](https://edenlab.atlassian.net/wiki/spaces/EH/pages/659357701/Release+Service+Request#ReleaseServiceRequest-Checkforrelatedepisodesandencounters)
