### ISSUE TITLE
Method GET division returns field "total_entries" that different from number division in responce, PROD, #J493

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3545]
Steps to reproduce:
для эндпоинт GET /divisions/ в total_entries отдаётся информация что есть 10 записей, а фактически всего 5 
Expected results:
Количество объектов в total_entries соответствует фактическому.

Подробиці тут: https://drive.google.com/drive/folders/1RbX1NJh56ykYFqu_hFB_IhVxbXp8Gm28?usp=sharing

**Comment by AlekzandrV** [comment]
Проблема имеет место быть, когда у подразделения больше одного адреса.

**Comment by AlekzandrV** [comment]
Tested
