### ISSUE TITLE
Contract_request return "500 Internal server error", PreProd, Demo, #J508

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3575]
Steps to reproduce: При спробі відправлення заявки на створення договору отримуємо помилку:

{"meta":
{"url":"http://api-svc.il/api/contract_requests/fb7e8e8e-d40e-4cde-a33e-a56b13d582ea","type":"object","request_id":"7164d905-8c70-42ad-90e9-9d875488eefa#100335","code":500}
,"error":{"errors":{"detail":"Internal server error"}
}}

Подробиці тут: https://drive.google.com/open?id=1JGMCux75CPttI7siFb6aFJA7rNc736BP

**Comment by lymychp** [comment]
not relevant anymore
