### ISSUE TITLE
Authorization error on PROD in IE, Prod, #J514

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3609]
При авторизації через браузер Internet Explorer 
виникає помилка сценарію з'явилась після релізу сьогодні.  
Кроки для відтворення:
1. Зробити запит на авторизацію через IE 

2. Форма авторизації не піднімається

3. З'являється помилка сценарію. 

Додаткова інформація: https://drive.google.com/open?id=1vlZUl_HTthoxfls_PqSD4r5wVc8dEi7w

**Comment by lymychp** [comment]
fixed on prod
