### ISSUE TITLE
403 error on update contracts request by NHS with new DEMO access_token, DEMO, #J518

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3610]
При спробі виконати update contracts request by NHS з новими access-token для DEMO з'являеться помилка: 
    "error": {
        "message": "Your scope does not allow to access this resource. Missing allowances: contract_request:update",
        "type": "forbidden"
    }
Подробиці: https://drive.google.com/drive/folders/15sQMbd4RT507_aZNx7VmT1fBKOdormRA?usp=sharing

**Comment by lymychp** [comment]
not actual anymore
