### ISSUE TITLE
Credentials for MIS to DEMO and PreProd

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3612]
Прошу згенерувати 60 наборів даних для МІС для авторизації на середовищах DEMO та PreProd.
Вимога до набору даних: 
1) access_token
2) Дані для проходження oAuth, а саме: 
- auth_uri
- api_uri
- client_id
- client_secret/mis_api_key
- redirect_uri
- e-mail та password для "MIS USER"

Дані прошу надіслати на l2-support@ehealth.gov.ua

**Comment by Defibrilyator** [comment]
А як (де, у кого, який порядок) отримати такий "набір даних" для доступу до DEMO-сервера звичайному розробнику?
На ehealth.gov.ua розписано як підключати вже готову МІС, але для цього її роботу з api треба перевірити на базі демо. Якось все дивно, на сайті тільки посилання на Фейсбук, ні імейлів ні телефонів.

**Comment by lymychp** [comment]
credentials has been sent to l2-support@ehealth.gov.ua
