### ISSUE TITLE
Invalid Digital Signature fault notifications

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3624]
Sometimes DS verification service sends alarms about Invalid signed content.
But it is valid.
Examples: ee4a2b60-1416-44e7-99aa-7ee008c1f7e5, 334a6f35-e696-409a-8093-21d7820ad771, fbdc2e70-16c4-4fa2-a5d3-b56600c18da6

**Comment by lymychp** [comment]
@lymychp check it

**Comment by marinakr** [comment]
makes apps umbrella
