### ISSUE TITLE
Checking phone limit number for declaration creating is not equal 10

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3628]
Поточний ліміт декларацій (пацієнтів) може бути прив'язаний до одного номеру телефону, так як було вказано, що він 10, а у самій помилці показує 5.
Опис помилки тут https://drive.google.com/drive/u/0/folders/1kb9Z7L5oSNYgTU7H7XG8h48sM7HzKNZC?ogsrc=32
connected #3255  
connected #3418

**Comment by lymychp** [comment]
Fixed
