### ISSUE TITLE
Impossible declaration signing. Tax_id error, Prod, #J470

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3633]
При виконанні запиту на підписання декларації, отримуємо помилку.
Піідробиці тут
https://drive.google.com/drive/u/0/folders/1079IJifPN6ZFUodgSDkL0Sdkne48lFQg?ogsrc=32

**Comment by lymychp** [comment]
body_error_1107.txt - декларація була підписана електронною печаткою, а не підписом. В електронній печатці відсутній параметр drfo.
Прошу надалі уважніше перевіряти коректність дій користувачів МІСа
