### ISSUE TITLE
Update Contract Employees : Does not match the signer drfo, Demo, #J536

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3635]
curl в файлі тут https://drive.google.com/drive/u/0/folders/1sXPtPDSQA1ZqYxwQmoDrTrenJYqFDJ0Z?ogsrc=32.
signed_content підписаний головним лікарем, тим самим підписом, який використовувався для створення контракту. 

Повідомлення про помилку

{"meta":
{"url":"http://api-svc.il/api/contracts/23a25c74-27a2-41c2-ad9e-d4e66466ef31/employees/actions/update","type":"object","request_id":"b006b174-42ff-4199-9a2e-88381e34392e#38073","code":422}

,"error":{"type":"request_malformed","message":"Does not match the signer drfo","invalid":[{"rules":[
{"rule":"json"}

],"entry_type":"request"}]}

Ця помилка по тестуванню. Встановлено стандартний пріорітет, але прохання - виконати з високим прірітетом.

**Comment by lymychp** [comment]
no feedback provided
