### ISSUE TITLE
Validation problem for declaration request, Prod, #J527

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3645]
Створено запит на декларацію з документом пацієнта "documents":[{"type":"BIRTH_CERTIFICATE","number":"І-ЖС039685"...

Є підозра, що проблема в тіре, але ж це реальная серія документа
Лог тут https://drive.google.com/drive/u/0/folders/1WSTp5gob68roSZPhZ7G_3J185YL-Ii_e?ogsrc=32

**Comment by lymychp** [comment]
@ehealthua-tech треба дозволити дефіси в свідоцтві про народження?

**Comment by ehealthua-tech** [comment]
так

**Comment by lymychp** [comment]
no feedback provided
