### ISSUE TITLE
Owner deactivation is_suspended bug

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3654]
contractor_owner_id has employee_type='OWNER'. When Legal entity is updated and previous owner is deactivated (is_active=false) and previous owner was contractor_owner_id, for those contracts is_suspended must be true. As for now it's false

**Comment by progsmile** [comment]
Talking to @AlekzandrV this bug should be checked in approve employee request, right?

**Comment by danakonovalenko** [comment]
tested
