### ISSUE TITLE
Contracts: 422 string does not match pattern, Demo, #J545

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3664]
Текст згоди не проходить валідацію. Подробиці тут  https://drive.google.com/drive/u/0/folders/1iGj0nOocUoK2c-WOtMU_7OKVa3Le3qVG?ogsrc=32.
Після отримання новго тексту - помилка залишилась. Опис помилки в файлах з позначкою _2

**Comment by lymychp** [comment]
Текст угоди валідується по [json-схемі](https://github.com/edenlabllc/ehealth.api/blob/develop/apps/core/specs/json_schemas/contract_request/contract_request_create.json)
