### ISSUE TITLE
Incorrect decalarations limit settings (less than 2000), Prod, #J544

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3665]
Сімейному лікарю при підписанні декларації повертає відповідь про перевищення ліміту "This doctor has 1192 declarations and could not sign more". Як таке може бути? Чи можна це виправити?

Реквест і відповідь тут https://drive.google.com/drive/u/0/folders/1K3ADW8sUtmhG1-QbreKAPT3Mhkh2TtEP?ogsrc=32

**Comment by lymychp** [comment]
вказаний в тікеті лікар зареєстрований в двох ЗОЗах.
В одному - педіатр, в іншому - сімейний лікар. 
Після останнього релізу відповідно до [правил розрахунку лімітів](https://edenlab.atlassian.net/wiki/spaces/EH/pages/983335/IL.Create+declaration+request#IL.Createdeclarationrequest-Validatedeclarationlimit) - береться мінімальний, тобто ліміт педіатра (900)
