### ISSUE TITLE
Error 500 when contract request is declined by the user, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3695]
PROD 500 error при відхиленні заявки.
More there https://drive.google.com/drive/u/0/folders/1FmD4Fxc7LfA3NtZJoT-7U_wRefb2WU38?ogsrc=32

**Comment by ehealthua-tech** [comment]
Ссылка обновлена.
Ошибка 500 отражена в логах тут admin-4-500-4

**Comment by danakonovalenko** [comment]
наразі поле `status_reason` має тип varchar(255). 
Зі сторони фронта буде виправлено в межах цієї таски https://github.com/edenlabllc/ehealth.web/issues/543

**Comment by danakonovalenko** [comment]
parent of #3703
