### ISSUE TITLE
Any actions of user are unsuccessful in admin panel, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3697]
Ошибка возникает при любом действии в интерфейсе.
Проблема наблюдается у двух пользователей.
Адреса в файле в папке adr_user.txt
Подробности тут https://drive.google.com/drive/folders/1cNXY_iMdbl5hOVMueEZsJd4ETRw-nHhI

**Comment by warehousman** [comment]
It appears that problem caused by client side browser settings
