### ISSUE TITLE
2 active declarations exist, Prod, #J442

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3701]
Опис проблеми
. Ми відкриваємо список декларацій закладу в нашій МІС, здійснюємо пошук по конкретному пацієнту та бачимо, що у цього пацієнта є дві ідентичні активні декларації. Дата народження та інші дані, які нам дозволяє перевірити eHealth, співпадають. Ідентифікаційний номер, на жаль, не маємо змоги звірити, оскільки eHealth приховала цю інформацію у давнішій декларації. Аналогічну ситуацію виявили ще з 5 пацієнтами. При потребі, наведемо дані ще й по них. Поки що надсилаємо дані по Ботич Софії.
2. Надсилаємо у прикріплених файлах.

6b9652cf-e0f0-48c4-8687-158b8f3ef31f.txt (7 kB)

34ba1586-955a-4f6c-8adb-39a1bc9c080b.txt (6 kB)
Файли тут https://drive.google.com/drive/u/0/folders/12vu216e6IFgXDF2WETj2HoGhn3cZ-EGU?ogsrc=32

**Comment by lymychp** [comment]
По даному пацієнту було оформлено дві декларації без вказання ІПН та з вказаними різними номерами свідоцтва про народження. Тому було створено два записи. Як би там не було, після запуску офлайнової процедури дедуплікації є висока ймовірність, що один з записів буде деактивовано.
