### ISSUE TITLE
Change status_reason field type for Decline contract request by NHS, Prod

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3703]
As a NHS Admin Signer  
I want to set the whole set of the reasons of reject to accept the contract request.  
So that I need to insert more than 255 symbols into status_reason field.

**Comment by lymychp** [comment]
please specify what kind of validation should be applied to this field

**Comment by ehealthua-tech** [comment]
Field type = text
Letters 	Letters A-Z, in lower or uppercase, and spaces 
Numbers 	0-9 
The size is exactly the same to miscellaneous field

**Comment by danakonovalenko** [comment]
As I saw from today example they also use tabs (\t), new lines (\n) and symbols («()\".',)

**Comment by ehealthua-tech** [comment]
I have added some info into requirements to the field status_reason.

**Comment by danakonovalenko** [comment]
- in table il.contract_requests and prm.contracts change `status_reason` from `varchar(255)` to `text`

- on Decline Contract Request, Terminate Contract  change json schema
```
 "status_reason": {
            "type": "string",
            "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[a-zA-ZА-ЯҐЇІЄа-яґїіє0-9№\\\"!\\^\\*)\\]\\[(._-].*$",
             "maxLength": 3000
        }
```
