### ISSUE TITLE
Declaration sign problems, Prod, #J516

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#3716]
При спробі підписати декларацію виникає помилка. Подробиці тут
https://drive.google.com/drive/u/1/folders/1SQhjy-5rGhW2V7F3sM9P84_F-SdDfMAL?ogsrc=32

**Comment by warehousman** [comment]
moved to tickets see #2

**Comment by warehousman** [comment]
@AlekzandrV please comment on this
