### ISSUE TITLE
Change status_reason field  BE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3739]
- [x] in tables il.contract_requests and prm.contracts change status_reason from varchar(255) to text
- [ ] on Decline Contract Request, Terminate Contract change json schema
```
 "status_reason": {
            "type": "string",
            "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[a-zA-ZА-ЯҐЇІЄа-яґїіє0-9№\\\"!\\^\\*)\\]\\[(._-].*$",
             "maxLength": 3000
        }
```

**Comment by danakonovalenko** [comment]
as for now multi line comment can't be sent. please, add support string with `\n`

**Comment by AlekzandrV** [comment]
As discussed  yesterday, remove pattern at all
@danakonovalenko please confirm this decision

**Comment by danakonovalenko** [comment]
it was agreed to remove pattern and limit max input length
tested
