### ISSUE TITLE
Error 400 "matching TSP certificate not found" when doctor tries to sign declaration, Prod, #J590

### ISSUE THREAD

**Issue by ehealthUA-support** [edenlabllc/ehealth.api#3753]
При спробі виконати ендпойнт api/declaration_requests/{id}/actions/sign використовуючи ЕЦП ПРИВАТ-БАНКУ ЦК видає помилку "matching TSP certificate not found"
Докладніше https://drive.google.com/drive/folders/19UCB3F0C7lXamb_2thmM5_xnmdBM1lme?usp=sharing

**Comment by svetavedmed** [comment]
task is re-opened in [zube](https://zube.io/edenlabllc/e-health/tickets/4). Please, create new tasks in zube. Thank you
