### ISSUE TITLE
Additional validation errors (extend error message)

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3756]
- [ ] test for Changeset validation error with full error message fields (rules, path, description)
- [ ]  test for JSON Schema validation error with full error message fields (rules, path, description)

**Comment by PavelVesnin** [comment]
[ ] test for Changeset validation error with full error message fields (rules, path, description)
[ ] test for JSON Schema validation error with full error message fields (rules, path, description)
