### ISSUE TITLE
Update documentation based on UAT

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#3775]

**Comment by warehousman** [comment]
@IrinaRevutska Please comment on Eugene remarks

**Comment by IrinaRevutska** [comment]
@Eugene-Yesakov ,
1) I added more info into https://edenlab.atlassian.net/wiki/spaces/EH/pages/659325157
2) Changed this one a little bit, but don`t want to overwhelm it with a business logic.
https://edenlab.atlassian.net/wiki/spaces/EH/pages/608272488/Submit+Encounter+Data+Package
