### ISSUE TITLE
[Design] CSRF implementation on auth

### ISSUE THREAD

**Issue by Troush** [edenlabllc/ehealth.api#3816]
Problem:
Some of "public" and anonymous endpoints in eHealth, must be accessible only by eHealth inner front-ends.

Description:
We must apply set of security actions regarding this endpoints.

Actions:

- [ ] `mithril.api` must provide endpoint that on response sets `CSRF Token`, httpOnly cookie, for auth.ehealth.web domains on different ENVs.
- [ ] `mithril.api` must check validity of CSRF Token on eachAuthentication action
- [ ]  `mithril.api` must be secured with kong plugin for CORS and allow only auth.ehealth.web Origins in request
- [ ] `auth.ehealth.web` must make first request to `mithril.api` to get CSRF token and pass this CSRF token in cookie with each request to `mithril.api`

Example of Login request:
<img width="351" alt="screen shot 2018-12-11 at 12 40 28 pm" src="https://user-images.githubusercontent.com/1163074/49795186-05191980-fd42-11e8-9cf1-a3c1626dfa95.png">

**Comment by lymychp** [comment]
has been deprecated, another solution has been chosen
