### ISSUE TITLE
Switch to kaffe and add login/password support

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#3817]
- [x] ehealth.api @imax-iva  - remove kafka_ex, update branch kafee
- [X] ops.api @BatrakM - remove kafka_ex, update branch kafee
- [X] ds.api @BatrakM - remove kafka_ex, update branch kafee
- [X] mpi.api - remove kafka_ex, update branch kafee
- [X] kaffe sasl support

Danger! brod supports only key:value pushing to kafka, so format of kafka messages will be changed
@AlexKovalevych

**Comment by marinakr** [comment]
34 listeners=SASL_PLAINTEXT://localhost:9093
 35 advertised.listeners=SASL_PLAINTEXT://localhost:9093
 36 security.inter.broker.protocol=SASL_PLAINTEXT
 37 sasl.mechanism.inter.broker.protocol=PLAIN
 38 sasl.enabled.mechanisms=PLAIN

**Comment by marinakr** [comment]
https://github.com/spreedly/kaffe/pull/81

**Comment by marinakr** [comment]
- [ ] ehealth.api @imax-iva  - remove kafka_ex, update branch kafee
- [ ] ops.api @BatrakM - remove kafka_ex, update branch kafee
- [X] kaffe sasl support
