### ISSUE TITLE
Uaddresses naming collision clean up

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3826]
As any api user
I want to use the same names for `область` and `район` for all the endpoints
So that there will no collisions and misunderstanding and data quality will be improved.

We should start using the same naming for `область` and `район`.
* `area` - `область` 
* `region` - `район`
So, we should change the uaddresses:
1. rename everywhere all endpoint names, parameter names and DB:
* `region`-->>`area` - `область` 
* `district`-->>`region` - `район`
2. Existing endpoints should be still temporary supported

**Comment by progsmile** [comment]
Waiting to be reviewed

**Comment by AlekzandrV** [comment]
Tested
