### ISSUE TITLE
move some the applications to umbrella - batch2

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3863]
In order to have possibility to scale services without scaling cron-jobs
it should be restructed to umbrella:
- [ ] mithril
- [ ] IL
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

**Comment by marinakr** [comment]
loacked by PR https://github.com/edenlabllc/ehealth.api/pull/4135
