### ISSUE TITLE
Change processing of the field 'second name' in the endpoint 'update party'

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#3892]
I 
as a Role = OWNER or Role = HR
want to change second name in the Object = party 
When
endpoint update party is required.
If update party.second name is null set party. second name as null

Example:
 "party": {
      "id": "d290f1ee",
      "first_name": "Гохар",
      "last_name": "Алі-Шах",
      "second_name": null,
      "birth_date": "1991-08-19T00:00:00.000Z",
      "gender": "MALE",
      "no_tax_id": false,
      "tax_id": "3126509816",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "АА120518",
          "issued_by": "Рокитнянським РВ ГУ МВС Київської області",
          "issued_at": "2017-02-28",
          "expiration_date": "2027-02-28"
        }
      ],

Attentin: this change must be included into next release and implemented into prod instance in January, 2019

**Comment by svetavedmed** [comment]
- [ ] error on create legal_entity.
On create LE we also create an employee request, so we also should have a possibility to reset second name for a OWNER
```
"error": {
        "invalid": [
            {
                "entry": "$.owner.second_name",
                "entry_type": "json_data_property",
                "rules": [
                    {
                        "description": "type mismatch. Expected String but got Null",
                        "params": [
                            "string"
                        ],
                        "rule": "cast"
                    }
                ]
            }
        ]
```
