### ISSUE TITLE
[Device] Update specification of Encounter package

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#3894]
including Validation rules and technological process described in confluence
Create, Get, Cancel, Patient Summary
- [x] Apiary
- [ ] Confluence
- [ ] Json Schema
- [ ] Test Scenarios

**Comment by IrinaRevutska** [comment]
https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/submit-encounter-package
https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/cancel-encounter-package-dummy
