### ISSUE TITLE
[Device] Design data model

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#3897]
- [x] Data model on Confluence
- [x] Decide on Dictionaries with examples
- [x] Validation rules, data types

**Comment by IrinaRevutska** [comment]
https://edenlab.atlassian.net/wiki/spaces/EH/pages/618987536/Medical+Events+Dictionaries
https://edenlab.atlassian.net/wiki/spaces/EH/pages/602800163/Medical+Events+MongoDB+Data+Model#MedicalEventsMongoDBDataModel-Device
