### ISSUE TITLE
Reject / Approve Declaration mutations

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3924]
Declarations in status `PENDING_VERIFICATION` can be APPROVED or REJECT.
In order to do that by NHS admin next mutation must be implemented:
- [x]  approveDeclaration(input: ApproveDeclarationInput!): ApproveDeclarationPayload
- [x]  rejectDeclaration(input: RejectDeclarationInput!): RejectDeclarationPayload

[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/index.graphql)
[confluence for reject](https://edenlab.atlassian.net/wiki/x/MpIt)
[confluence for approve](https://edenlab.atlassian.net/wiki/x/Y5At)
[features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature)

**Comment by lymychp** [comment]
blocks edenlabllc/ehealth.web#635
