### ISSUE TITLE
Terminate Declaration mutation

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3925]
Declaration in status `active` can be terminated. In order to do that we should implement mutation
```
 terminateDeclaration(
    input: TerminateDeclarationInput!
  ): TerminateDeclarationPayload
```
[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/index.graphql)
[features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature)

**Comment by lymychp** [comment]
blocks edenlabllc/ehealth.web#636

**Comment by danakonovalenko** [comment]
I can't complete happy pass as I receive an error - `Current client is not allowed to access this resource`,
however token belongs to NHS
[test cases](https://edenlab.atlassian.net/wiki/x/CgBtKg)

**Comment by danakonovalenko** [comment]
status_reason should be changed from `varchar(255)` to `text` as for now we receive 500 error
```
 "extensions": {
        "code": "BAD_REQUEST",
        "exception": "%{\"error\" => %{\"errors\" => %{\"detail\" => \"Internal server error\"}}, \"meta\" => %{\"code\" => 500, \"request_id\" => \"86aceff7-7039-41d5-b6b4-161fdb77f360#20467\", \"type\" => \"object\", \"url\" => \"http://graphql-svc.il/declarations/66d5524c-a52c-4690-a7ac-f3a632b2213c/actions/terminate\"}}"
      }
```
