### ISSUE TITLE
Assign merge candidate in order to be reviewed

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#4028]
As NHS admin reviewer of manual merge requests I want to be able to assign merge candidate to review. 

In order to do that we need to implement mutation base on [logic](https://edenlab.atlassian.net/wiki/x/sIBUKg) and spec

- [ ] implement

- [ ] test

**Comment by danakonovalenko** [comment]
please, see the comments on [test cases](https://edenlab.atlassian.net/wiki/x/AQCqKg) page

**Comment by svetavedmed** [comment]
- [ ] try to assign new merge candidate and receive an error
```
{
  "data": {
    "assignMergeCandidate": null
  },
  "errors": [
    {
      "errors": [
        {
          "$.manual_merge_candidate_id": {
            "description": "has already been taken",
            "rule": ""
          }
        }
      ],
      "extensions": {
        "code": "UNPROCESSABLE_ENTITY"
      },
      "locations": [
        {
          "column": 0,
          "line": 2
        }
      ],
      "message": "Validation error",
      "path": [
        "assignMergeCandidate"
      ]
    }
  ]
}
```
