### ISSUE TITLE
Get details of merge request

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#4036]
As NHS admin I want to see details of merge request I reviewing in order to make decision on it

We need to implement WS 

- [ ] [logic](https://edenlab.atlassian.net/wiki/x/wQBTKg) / schema
- [ ] implement 
- [ ] test

**Comment by ephor** [comment]
Blocked by edenlabllc/ehealth.api#4038

**Comment by danakonovalenko** [comment]
there is a problem with checking role, I still get merge requests list/id without required role `NHS REVIEWER` in case I have required scope

**Comment by progsmile** [comment]
I've perform this check with `client_id` field, should do with `consumer_id`?

**Comment by danakonovalenko** [comment]
that's neither about `cient_id` nor `consumer_id`. We should check user's roles within client
