### ISSUE TITLE
Storing merge candidates for manual merge process

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#4038]
Deduplication process on mpi based on config parameters min_manual_score/max_manual_score should behave differently 
- if status=NEW and score >= max_manual_score then make auto termination of declaration and person and change status to MERGED
-  if status=NEW and score in range [min_manual_score, max_manual_score) then write such pairs to dedupe DB in table manual_merge_candidates based on [erd](https://edenlab.atlassian.net/wiki/x/NoBUKg) and change status to MANUAL

**Comment by ephor** [comment]
Blocked by edenlabllc/ehealth.api#4037

**Comment by svetavedmed** [comment]
pairs are not saved in manual_merge_candidates based
