### ISSUE TITLE
500 on reject medication dispense

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4081]
```{"error":{"errors":{"detail":"Internal server error"}},"meta":{"code":500,"request_id":"d1b4ae6d-23d6-4cb5-ad7d-d10e0b521532#123360","type":"object","url":"http://api-svc.il/api/medication_dispenses/8f5819cb-da60-4302-82ce-52e3af83ca44/actions/reject"}}```

**Comment by AlexKovalevych** [comment]
@svetavedmed  which environment?

**Comment by svetavedmed** [comment]
demo
