### ISSUE TITLE
Change the list of fields of patient data that  pharmacy employees could see

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4103]
All the endpoints that return medication request view should be reviewed.

As a pharmacy employee I could see a patient data only:
- party id;
- surname;
- initials (first letter of first name and first letter of middle name);
- patient age.

According legal analysis:
https://docs.google.com/document/d/1aTgluLapOg8dmpLUja_V1tokbw0nqk7ECBQiynpmquE/edit 
and no plans to build "KSZI" on a pharmacy side, other patient data is forbidden to translate to pharmacy.

**Comment by lymychp** [comment]
is related to edenlabllc/ehealth.api#4105 
should be done together

**Comment by AlekzandrV** [comment]
Done
