### ISSUE TITLE
Add medication packages info for participants on Qualify Medication Request by ID request

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4104]
[qualify](https://uaehealthapi.docs.apiary.io/#reference/public.-reimbursement/medication-request/qualify-medication-request-by-id)
As a pharmacist on Qualify Medication Request by ID request I want to get info about packages for every participant:
- package_qty;
- package_min_qty.

**Comment by AlekzandrV** [comment]
Done
