### ISSUE TITLE
Add licence and accreditation information of MSP to a prescription

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4105]
As a pharmacy employee when I get information from a prescription I want to see licences and accreditation information of MSP where the prescription was prescribed.

So, add to all requests about prescription attributes licenses and accreditation of legal_entity
MUST: [get by id](https://uaehealthapi.docs.apiary.io/#reference/public.-reimbursement/medication-request/get-medication-request-by-id)
Responses for all other endpoints might be also updated if the same view is used.
@AlekzandrV spec should be updated for all the endpoints.

{
       "licenses": [
         {
           license_number:
           "issued_by": 
           issued_date: 
           expiry_date: 
           active_from_date: 
           "what_licensed": 
           "order_no":
         }
       ],
       "accreditation": {
         "category":
         issued_date:
         expiry_date: 
         "order_no": 
         order_date:
       }
     },

**Comment by AlekzandrV** [comment]
Done
