### ISSUE TITLE
Double check and clean up all the existing dictionaries

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4107]
The values aren't translated:
- allergy_intolerance_verification_statuses
- allergy_intolerance_clinical_statuses

eHealth/ucum/units - it's not full and isn't translated.

Please add (one) default values for vaccination_dose_statuse_reasons and vaccination_dose_statuses.

**Comment by IrinaRevutska** [comment]
- [x] Added only required values into ucum units dictionary (values that matched with observation list)
