### ISSUE TITLE
Multiple sms gateways using at the same time

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4116]
As NHS admin
I want different processes to use different sets of sms gateway configurations (only Life provider) at the same time
So that It could be managed by separate contracts and payments can be separated as well.

name of configuration that has been used should be stored in DB

Provider as parameter for each sms will be set (or used default)  in ehealth.

**Comment by marinakr** [comment]
why in DB, not config file? We will repeat man or ds certs unhealthy implementation

**Comment by marinakr** [comment]
It requires a lot of work - lib read config on init and changes should be done inside of lib

**Comment by lymychp** [comment]
@marinakr  PR link is missing

**Comment by lymychp** [comment]
@warehousman please share 2nd life account name, login and password. It will be used for tests

**Comment by marinakr** [comment]
@AlekzandrV @AlexKovalevych @warehousman ensure how to choose the way define sms provider
