### ISSUE TITLE
Approval response data in job details response

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4143]
As an Architect 
I want approvals processing results to be stored in the job details
So that [get job details](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/encounter-data-package/get-async-job-processing-details) will return approval data in response

As a result
I want the regular mongodb collection to be used for jobs instead of capped one
So that we are not restricted to the data volume that can be stored in one dcocument

**Comment by AlekzandrV** [comment]
Tested
