### ISSUE TITLE
mpi merge consumer

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4174]
There should be a kafka topic `person_merges` that contains messages like {id, master_person_id, person_id}. And consumer that processes this topic and do the same as auto-merge function:
1) deactivate declaration
2) deactivate person

**Comment by lymychp** [comment]
@PavelVesnin  FYI

**Comment by PavelVesnin** [comment]
Recently have discussion with @marinakr and decided another implementation.
- move deactivation functions into core, that can be used in MPI controller on MERGE action.
- reuse it in person deactivator for auto-merge candidates
