### ISSUE TITLE
Add info about reorganized le to fraud

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4177]
As a NHS Admin
I want information about reorganizes legal_entities (employees.status_reason, ) were added to fraud
So that I can get analytics for those legal_entities

- [ ] add reason to fraud declarations, employees #
- [ ] change le reorganization, add status_reason to deactivated employees, set it as 'auto_merge' #

**Comment by eHealth-victory** [comment]
Pls also add info about reorganized le into Report DB.

**Comment by lymychp** [comment]
@svetavedmed please ensure that [erd-diagram](https://github.com/edenlabllc/ehealth.api/blob/develop/apps/core/specs/database_schema/ehealth.erd) has been updated

**Comment by lymychp** [comment]
not actual anymore edenlabllc/ehealth.api#4498
