### ISSUE TITLE
Validate LE using EDR

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#4179]

**Comment by brizolehealth** [comment]
Задачи в рамках этого тикета
[CR-NHS-check-LE-22-12-2018.docx](https://zube.io/files/edenlabllc/b2a85a971f372dbce5612f254f083be6-cr-nhs-check-le-22-12-2018.docx)

**Comment by warehousman** [comment]
DUPLICATES edenlabllc/ehealth.api#4501
