### ISSUE TITLE
Approve dashboard - number of declarations and doctors in area context

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#418]
As NHS Portal user I should see all active declarations and doctors in the context of area
filters:
- date
- date period (limited on the site side)
dashboard parameters:
- area name
- active declarations amount on date 
- amount of created declarations for the period 
- active doctors on date
- amount of created doctors for the period

**Comment by kmakarenko** [comment]
@IrynaShevch need your approval

**Comment by lymychp** [comment]
dashboards should be as it is described in Design #232 
@IrynaShevch please confirm
