### ISSUE TITLE
Approve dashboard - number of declarations and doctors for NHS admin

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#420]
As NHS admin I should see all declarations and doctors
filters:
- date
- date period
- area
- settlement (inactive if not selected area)
- MSP
dashboard parameters:
- active declarations amount on date
- amount of created declarations and closed declarations for the period
- active doctors on date
- amount of created doctors for the period
- MSP (if selected area and settlement)

**Comment by kmakarenko** [comment]
@IrynaShevch need your approval
