### ISSUE TITLE
Search persons in Admin Panel by any document type

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4200]
As for now we search persons only be passport and unzr, but some persons do not have passport and/or unzr so we should be able to search by any document type
p.s. check if we have index by document type+number

**Comment by svetavedmed** [comment]
- [ ] order by inserted_at does not work
- [ ] on ordering by unzr erro
```
{"errors":[{"locations":[{"column":0,"line":2}],"message":"Argument \"orderBy\" has invalid value $orderBy."}]}
```

**Comment by progsmile** [comment]
I'll check with inserted_at
There is no unzr order in schema, so I'll add
https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/persons.graphql#L79-L92
