### ISSUE TITLE
Declaration Printout form

### ISSUE THREAD

**Issue by DPashchenko** [edenlabllc/ehealth.api#421]
As a Client i want to get completed declaration printout
Продумать метод заполнения печатной формы (бек-енд/фронт-енд)
[Декларація_23052017.pdf](https://github.com/Nebo15/ehealth.api/files/1070976/_23052017.pdf)
ФОРМА НЕ ФИНАЛЬНАЯ!!!!!!

**Comment by TarasenkoA** [comment]
After changes mapping (description in comment in 651 task) need to see one of current method  authentication.
