### ISSUE TITLE
Write service request status changes to event manager

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4218]
Write service request status changes to event manager

Update the following services:
1. [Cancel service request](https://ehealthreferralsapi.docs.apiary.io/#reference/service-requests/manage-service-requests-in-patient-context/cancel-service-request)
2. [Recall service request](https://ehealthreferralsapi.docs.apiary.io/#reference/service-requests/manage-service-requests-in-patient-context/recall-service-request)
3. Deprecated: [Complete service request](https://edenlab.atlassian.net/wiki/x/PwBLJw) (Kafka consumer)

**Comment by lymychp** [comment]
blocked by edenlabllc/ehealth.api#4219

**Comment by marinakr** [comment]
What event type should be stored on cancel? on recall and complete? What properties should be stored?

**Comment by lymychp** [comment]
all the events should be with the same type: `StatusChangeEvent`
we should send new value of `status` property to the event manager in similar [structure](https://uaehealthapi.docs.apiary.io/#reference/public.-event-manager/get-events-by-id/get-events-by-id) as it has been done for other events.

**Comment by IrinaRevutska** [comment]
@AlekzandrV , We also have autoexpiration process and "Process service request" web-service. They change service request status as well. Shouldn't they be included in the task?

**Comment by lymychp** [comment]
@IrinaRevutska please test it

**Comment by IrinaRevutska** [comment]
Nothing new in event manager
