### ISSUE TITLE
Async event manager processing

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4219]
Implement Kafka consumer for Event manager messages

Move clients to async flow

- [X] rename application api -> core, web -> api
- [X] update deps
  - [X] ecto 3
  - [X] phoenix
  - [X] elixir
  - [X] add git_ops
  - [X] fix ecto_trail repo
- [X] add app consumer (get events from kafka and store into db) according to existing logic
- [x] use ehealth logger
  - [X] log plug endpoin
  - [X] logger config
  - [X] telemetry to ecto queries
  - [x] phoenix error instrument

**Comment by marinakr** [comment]
generated error ``` {
  "error": {
    "type": "internal_error"
  },
  "meta": {
    "code": 500,
    "request_id": "2m4hgveso9jhqfl95k000056",
    "type": "object",
    "url": "http://localhost/api/events/3bcb6439-f6df-400a-a8c7-e357e0917"
  }
}```
logs on error on server:
```{"log":"#PID<0.1723.0> ..: localhost:80",  :phoenix_action => nil, :phoenix_controller => EventManager.FallbackController, :phoenix_endpoint => EventManager.Endpoint, :phoenix_format => \"json\", :phoenix_layout => {EventManager.LayoutView, :app}, :phoenix_pipelines => [:api], :phoenix_router => EventManager.Router, :phoenix_view => EventManager.EventView} .. }```

**Comment by marinakr** [comment]
@vsirius create topic event_manager_topic
new application will be deployed - APPS='[{"app":"event_manager_consumer","chart":"em","namespace":"em","deployment":"api","label":"event-manager-consumer"}]'

**Comment by AlekzandrV** [comment]
It seems like there are no events in EM DB since 2019-04-03 00:00:00.060766
