### ISSUE TITLE
new LE types (simple version) - api v2

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4246]
https://docs.google.com/spreadsheets/d/1oudCIboyDtmCdLtoKi3uJslx5kae3U2my9ptlwva608/edit?usp=sharing
As a MIS
I want to be able to register legal entities that combine pharmacy and primary care licenses
So that 
- [X] create new client_type = `MSP_PHARMACY` [PR](https://github.com/edenlabllc/mithril.api/pull/353) @AlekzandrV  mithril.api
- [ ] Create [PUT /legal_entities v2](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity-v2), [Confluence](https://edenlab.atlassian.net/wiki/x/9IAVKw)
  - [X] calculate kveds from licenses 
  - [X] add `type` and `kveds` to `licenses` 
  - [X] calculate LE_type from licenses_type
  - [X] merge `owner` and `pharmacy_owner` --> `owner` [PR](https://github.com/edenlabllc/mithril.api/pull/353) @AlekzandrV 
  - [X] ukr_med_registries - delete unique edrpou index, create edrpou + type unique index
  - [ ] ukr_med_registries - fill data for mixed legal entities (with types only MSP, PHATRMACY, code do split types) @AlekzandrV 
  - [x] add new dictionaries @AlekzandrV LICENSE_TYPE [added](https://github.com/edenlabllc/ehealth.api/pull/4271)
  - [X] return `not_implemented` for cases with error
  - [ ] cover tests elixir
  - [ ] cover with postman collection @AlekzandrV 
- [ ] change [PUT /legal_entities v1](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity)
  - [ ] no changes
- [ ] DB Model
  PRM
    - [ ] no changes (simple version). All new attributes will be stored in JSONB object
  Mithril
    - [ ] no changes (simple version)

**Comment by AlekzandrV** [comment]
Merge only unique values to `$.kveds`

### Example
Trying to register new LE with the following licenses
```
[
            {
                "what_licensed": "реалізація наркотичних засобів",
                "type": "MSP",
                "kveds": ["86.10", "81.21", "47.73"],
                "order_no": "К-123",
                "license_number": "fd123443",
                "issued_date": "1991-08-19",
                "issued_by": "Кваліфікацйна комісія",
                "expiry_date": "1991-08-19",
                "active_from_date": "1991-08-19"
            },
            {
                "what_licensed": "реалізація наркотичних засобів",
                "type": "PHARMACY",
                "kveds": ["47.73", "01.11"],
                "order_no": "К-123",
                "license_number": "fd123443",
                "issued_date": "1991-08-19",
                "issued_by": "Кваліфікацйна комісія",
                "expiry_date": "1991-08-19",
                "active_from_date": "1991-08-19"
            }
        ];
```

### Expected result
```
        "kveds": [
            "47.73",
            "01.11",
            "86.10",
            "81.21"
        ],
```

### Actual result
```
        "kveds": [
            "47.73",
            "01.11",
            "86.10",
            "81.21",
            "47.73"
        ],
```

**Comment by AlekzandrV** [comment]
Can't create division to MSP_PHARMACY

#### Request
```
curl -X POST \
  https://api.dev.asclepius.com.ua/api/divisions \
  -H 'Authorization: Bearer VmVMakFNUEY1Z1cxUlNIQ0NBcEI3Zz09' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: e7c27b9b-c2b1-42ba-ab34-86458aebb326' \
  -H 'api-key: ejJ1VWFqZlNUUlpmMWNIMmc0YTB1UT09' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Medication Request Division",
  "addresses": [
    {
        "type": "RESIDENCE",
        "country": "UA",
        "area": "ВОЛИНСЬКА",
        "settlement": "ЛУЦЬК",
        "settlement_type": "CITY",
        "settlement_id": "2029f5e9-0682-4ecf-b4c3-605a9ef800ca",
        "street_type": "STREET",
        "street": "Олицька",
        "building": "2",
        "apartment": "23",
        "zip": "43000"
      }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "sp.virny+51@gmail.com",
  "type": "CLINIC",
  "external_id": "3213213"
}'
```

#### Response
```
{
    "error": {
        "type": "internal_error"
    },
    "meta": {
        "code": 500,
        "request_id": "fd8712d6-ec62-4101-8025-68580ab0f845#2994",
        "type": "object",
        "url": "http://api-svc.il/api/divisions"
    }
}
```
Guess this is caused by the following validation
```
defp validate_division_type(%LegalEntity{type: legal_entity_type}, params) do
    config = Confex.fetch_env!(:core, :legal_entity_division_types)

    legal_entity_type =
      legal_entity_type
      |> String.downcase()
      |> String.to_atom()

    allowed_types = Keyword.get(config, legal_entity_type)
    type = Map.get(params, "type")

    if !type || Enum.member?(allowed_types, type) do
      :ok
    else
      Error.dump(%ValidationError{
        description: "value is not allowed in enum",
        path: "$.type",
        params: allowed_types,
        rule: "inclusion"
      })
    end
  end
```

Lets define new config param to manage allowed division types
```
config :core, :legal_entity_division_types,
  msp: {:system, "LEGAL_ENTITY_MSP_DIVISION_TYPES", ["CLINIC", "AMBULANT_CLINIC", "FAP"]},
  pharmacy: {:system, "LEGAL_ENTITY_PHARMACIST_DIVISION_TYPES", ["DRUGSTORE", "DRUGSTORE_POINT"]},
  msp_pharmacy:
    {:system, "LEGAL_ENTITY_MSP_PHARMACY_DIVISION_TYPES",
     ["CLINIC", "AMBULANT_CLINIC", "FAP", "DRUGSTORE", "DRUGSTORE_POINT"]}
```
