### ISSUE TITLE
Delete closed LE on DEMO/PREPROD

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4247]
AS a MIS
I want to erase unnecessary test data 
So that i can easily repeat test scenarios and use the same Digital Signature for tests

Run the following script daily in any period between 00:00 AM and 06:00 AM
[delete_closed_le.sql.zip](https://zube.io/files/edenlabllc/8ef96788040d12844c4d2fa2ebf5ae21-delete_closed_le-sql.zip)

**Comment by vsirius** [comment]
@liubenokvlad deploy kubernetes cronjob   and  schedule to execute the script on PRM DB daily at 00:00 AM

**Comment by liubenokvlad** [comment]
Deployed cronjob with the schedule (daily at 00:00)
