### ISSUE TITLE
changes to Capitation contract print form

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4255]
- [ ] Changes to update contract with comments - https://docs.google.com/document/d/1Mx9XbTgiD9shkEisoAMvirnyUXxW7gaU1df49eP6Z1c/edit?usp=sharing
- [ ] Changes to contract with commets - https://docs.google.com/document/d/1edVYijHdIRiOTE6EZopaiC0a6Lm7GnTKfCDy7WyYGj4/edit?usp=sharing

- [ ] to all print forms
```
UPD. 18-02-2019 прошу при обновлении форм в системе из шаблонов Договора и Договора про внесении изменений к договору исключить в Додатке 1, п.8, абзац «Сторони погодили, що умови цього договору застосовуються до відносин між ними, які виникли з 01 січня 2019 року відповідно до частини третьої статті 631 Цивільного кодексу України.»
```

ticket https://zube.io/edenlabllc/e-health/tickets/144

**Comment by svetavedmed** [comment]
actual print form
[crpf(1).txt](https://zube.io/files/edenlabllc/ea3b3a25e0ea393f5f3619d705aa1bc1-crpf1.txt)[crpf.txt](https://zube.io/files/edenlabllc/e1594358fa232d5cddf50b5c191e7b7e-crpf.txt)

**Comment by burlachenkovv** [comment]
[Contract.html](https://zube.io/files/edenlabllc/ab2169ae325fad22a1c03c01fb94bf81-contract.html)[Update Contract.html](https://zube.io/files/edenlabllc/9aa360c9b69e5b3d0c75190f5c99d741-update-contract.html)
