### ISSUE TITLE
new template for reimbursement contract and update contract

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4284]
[Договір реімбурсація_шаблон_v2.docx](https://zube.io/files/edenlabllc/2312866dbd44c9a7a2e6bb19a70c015e-dogovir-reimbursaciya_shablon_v2.docx)

current form [RCRPF.html](https://zube.io/files/edenlabllc/f99595b06ee7c89bb67ae2ea03875374-rcrpf.html)

**Comment by burlachenkovv** [comment]
[rcrpf-28-02-2019.html](https://zube.io/files/edenlabllc/e3ee47ff08d47db978d315cb4dff2ffa-rcrpf-28-02-2019.html)
