### ISSUE TITLE
Do not deactivate slave declaration if master_person does't have own

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4366]
!!!There should be noe active declaration with inactive person - to be discussed

**As** NHS
**I want** the person's declaration **NOT** to be terminated in case if `master_person` from the merge_candidate pair doesn't have it's own declaration
**So that** we won't end up with persons with no declaration after merge

PS: Logically it shouldn't be the case, but technically it's possible that we might have person records without declarations.

**Comment by marinakr** [comment]
related to https://zube.io/edenlabllc/e-health/c/5514

**Comment by lymychp** [comment]
there should be only one `master_person_id` for every `merge_person_id` in the `merged_pairs` table.

**Comment by lymychp** [comment]
[tests passed](https://edenlab.atlassian.net/wiki/spaces/EH/pages/731873367/Person+deactivation+test+cases)
