### ISSUE TITLE
Dashboards. Division details for MAP WS

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#438]
As a Portal users I want to see detaled info about division on map
WS [specs](http://docs.ehealthapi1.apiary.io/#reference/internal.-portal-and-reports/divisions/search-divisions)

**Comment by TarasenkoA** [comment]
@AlexKovalevych  In response don't present e-mail.
In spec:
```
"contacts": {
        "email": "email@example.com",
        "phones": [
          {
            "type": "MOBILE",
            "number": "+380503410870"
          }
        ]
      },
```

in response (without "contacts" block):
```
"phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
```

**Comment by TarasenkoA** [comment]
Need to check status division in db and have in response only active divisions:
divisions.status = 'ACTIVE';
divisions.is_active = true.
