### ISSUE TITLE
FraudDB Tables

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#4498]
The current content is work with patients, doctors, declarations.
It is necessary to replicate data from tables:

MPI
1.1. persons
1.2. merge_candidates
PRM
2.1. parties
2.2. employees
3.ops_db
3.1. declarations
3.2 declarations_status_hstr

new configuration of pglogical - https://github.com/edenlabllc/ehealth.charts/pull/277

**Comment by lymychp** [comment]
@OleksandrRiabets We also have additional table on MPI:
* `person_addresses`
* `person_documents`
* `merged_pairs`

Should we replicate is as well or it is not needed?

**Comment by lymychp** [comment]
Also for PRM I suggest to keep these tables:
`legal_entities`
`divisions`
`division_addresses`
There is not a big amount of data, it is public, and it might help for the investigation.

**Comment by lymychp** [comment]
Reports on dev:
MPI: `merge_candidates`, `merged_pairs` are missing

**Comment by lymychp** [comment]
@OleksandrRiabets report replica була оновлена на проді.
Можна перевіряти

**Comment by lymychp** [comment]
have you finished testing?
is this the only comment?

**Comment by lymychp** [comment]
is reports DB ok now? can we drop and recreate fraud DB?

**Comment by lymychp** [comment]
you can drop your own tables only. But actually you shouldn't create new table on Reports DB

**Comment by lymychp** [comment]
fraud DB is ready for use
