### ISSUE TITLE
Reset auth method: Part 1

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#4500]
Скинути метод аутентифікації
Необхідно знати дату коли відбудеться скидання (для комунікації з МІС і ЗОЗ)

**Comment by AlekzandrV** [comment]
По результату анализа файла - есть следующие предложения:

1. В реестре присутствуют персоны в статусе inactive. Для них метод аутентификации сбрасываться не будет
2. В реестре присутствуют персоны с методом аутентификации OFFLINE. Для них метод аутентификации сбрасываться не будет
3. В реестре присутствует текущий номер телефона пациента как телефон аутентификации. Если по факту он отличается - метод аутентификации сбрасываться не будет

**Comment by AlekzandrV** [comment]
Итого, по результату выполнения задачи получены следующие результаты:

Результат | Кол-во
------------|-------------
Метод сброшен для персоны | 459912
Записей проигнорировано по причине отличного метода аутентификации в MPI | 17304
Записей проигнорировано по причине деактивированной персоны | 17417
