### ISSUE TITLE
make "region" optional in List Of Districts By Search Params

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#454]
Here in this spec, `region` param should be used as a filter(i.e. optional parameter) instead of making in mandatory

https://github.com/Nebo15/ehealth.api/blob/1c816ad6544f8387bc80c8510641015ac4803b07/apiary.apib#L2276-L2280

This will  simplify caching of districts for MIS

**Comment by pzhuk** [comment]
cc: @warehousman  - for a backlog please?

**Comment by svetavedmed** [comment]
Apiary is updated. Region is optional on Demo and Dev
