### ISSUE TITLE
Change code validation for person with OFFLINE authenticaition

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4576]
As NHS Admin 
I want dispenses for requests for persons with authentication method type=`offline` could be done with code=0000 as well as without code
So that all pharmacies could work with PIS implementation according to the law

The next case should work

authentication_method|code|result
---|---|---
offline|null|true
offline|0000|true
offline|`any four numbers`|false
otp|0000|validate according to mr
otp|null|false
otp|`any four numbers`|validate according to mr

**Comment by AlekzandrV** [comment]
@svetavedmed  Disagree with the first record. Must be false or validation error

**Comment by AlekzandrV** [comment]
Done, Fixed
