### ISSUE TITLE
Get Activity Type

### ISSUE THREAD

**Issue by mamaelka** [edenlabllc/ehealth.api#4637]
Get Activity Types [Confluence] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/766541925/IL.Get+Activity+Types) [Apiary] (https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-activity-types)
Get Activity Type By Id [Confluence] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/767197208/IL.Get+Activity+type+by+ID) [Apiary] (https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-activity-type-by-id)

**Comment by lymychp** [comment]
not actual anymore
