### ISSUE TITLE
Get Licenses

### ISSUE THREAD

**Issue by mamaelka** [edenlabllc/ehealth.api#4638]
Get Licenses List [Confluence] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/766410855/IL.Get+Licenses) [Apiary] (https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-licenses)
Get Licenses By Id [Confluence] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/766640267/IL.Get+License+by+ID) [Apiary] (https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-license-by-id)

**Comment by lymychp** [comment]
not actual anymore
