### ISSUE TITLE
Mithril Changes

### ISSUE THREAD

**Issue by mamaelka** [edenlabllc/ehealth.api#4645]
- [ ] user story @lymychp 
Access rights for Legal Entity depend on its activity types and sometimes on their status and nhs_verified state (access rights for inactive or not nhs_verified activity_type are limited). Thus, It should be possible to set more than one client type for one Legal Entity.
* create new table
* migrate existing client_types
* approval verification changes

**Comment by lymychp** [comment]
not actual anymore
