### ISSUE TITLE
mutation for Activity Type

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4661]
- nhsVerified - could be changed by NHS Admin to true and false
- status (ACTIVE, INACTIVE) - could be changed by NHS Admin to both statuses
when status is changed to INACTIVE search contracts by contractor_legal_entity_id=$legal_entity, if contracts found set contract.is_suspended=true
- [ ] mutation @svetavedmed

**Comment by lymychp** [comment]
not actual anymore
