### ISSUE TITLE
Change the contract sample

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4670]
As NHS admin I want to change the contract sample so that it allows automatic EDR validation.  

If the counterpart is FOP, the name of the counterpart should be taken as "ФОП" + LEGAL_Entity.Name.
If the counterpart is not FOP, no changes needed.

**Comment by lymychp** [comment]
@svetavedmed please test it

**Comment by svetavedmed** [comment]
done on prepared
