### ISSUE TITLE
Pending verification > 30 days

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#4682]
10221 декларація не змінила статус pending_verification на active через 30 дні після укладення[Pending.csv](https://zube.io/files/edenlabllc/a726b5e3fddaf90720a3ad2a2e34aa1f-pending.csv)
person auth method OTP, OFFLINE

**Comment by marinakr** [comment]
Looks like this issue was fixed in commit  [583b513e310c1b094e48857fcfdc98445d917720](https://github.com/edenlabllc/ehealth.api/commit/583b513e310c1b094e48857fcfdc98445d917720)

**Comment by lymychp** [comment]
it has been released to prod already. But obviously it didn't help.

**Comment by lymychp** [comment]
released to prod
