### ISSUE TITLE
Division is null in response on Get Contracts list, PROD, #J1076

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4704]
See logs in related support ticket

**Comment by kiurchv** [comment]
Such a response is returned when one of the contractor divisions is inactive.
It seems that we can deactivate division even when there are active contracts it acting in existing

**Comment by svetavedmed** [comment]
current response is according realization. In case it should be changed service request should be created. Ticked closed as this is not a bug.
