### ISSUE TITLE
Error 500, when pharmacist tries to create medication dispence, PREPROD, #J1252

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4705]
See details in related support ticket
https://zube.io/edenlabllc/e-health/tickets/284

**Comment by AlekzandrV** [comment]
Update "search active contract" logic

Get only active ("VERIFIED") contract that is valid in current period
```
start_date <= current_date
end_date >= current_date
```

**Comment by svetavedmed** [comment]
done for preprod
