### ISSUE TITLE
Resolve problem with big dictionaries

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#4707]
There are several dictionaries in our system, that are going to be too big for the current data structure (1 single json).
For example, LOINC/body_sites contains 30 000 items.
What problems we may face:
- all the data will not fit in 1 document
- get dictionary is going to be very slow
- front-end will be forced to get dictionaries that are huge but not used

**Comment by lymychp** [comment]
add config parameter: `big_dictionaries`
and these dictionaries shouldn't be returned by default
