### ISSUE TITLE
Investigate query correctness on MPI

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4712]
there a lot of query preloads of 
`merged_pairs`, `person_phones`, `person_documents` comparing to other queries. 2000-3000 to dozens.
![image.png](https://zube.io/files/edenlabllc/283a4fac56ef80502c5902e24cd6fc2a-image.png)

**Comment by AlexKovalevych** [comment]
This happens because we do preload without join, so it does a separate queries. In order to have a single query we need to add join to each query where we do preload and not forget about pagination since it doesn't work well with joins.

**Comment by lymychp** [comment]
we still have a lot of selects on the `GET /api/persons` endpoint
```
   "path": "/api/persons?first_name=[REDACTED]",
    "code": "200",
    "request_id": "9233d254-9efb-40a3-9fed-709ae4a3b79b#1694280",
    "@timestamp": "2019-04-26T12:38:52.081064554+00:00",
    "tag": "gateway"
```

**Comment by marinakr** [comment]
just refactoring - https://github.com/edenlabllc/mpi.api/pull/330
