### ISSUE TITLE
Perform stress testing of medical events

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#4714]
@IrinaRevutska provide with JSON bodies
required loads are described [here](https://docs.google.com/spreadsheets/d/1iXq3yH2OL_Y0Xa3CCndIdSKXu_9JIYZ9aXrERhU1JYU/edit?usp=sharing)

Open questions:
1. What can we do about authorization? Requests should be generated by 30k+ different doctors 
2. How can we fill DB for 30k+ patients with proper data? Legal entities, doctors, declarations, patients, medical data...
@lymychp

**Comment by lymychp** [comment]
duplicates edenlabllc/ehealth.api#4884
