### ISSUE TITLE
it should be error if psw is expired

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4765]
if psw is expired there should be an error `"The password expired for user: #{id}"` on `authorize token`
reproducible on demo

**Comment by PavelVesnin** [comment]
PASSWORD_EXPIRATION_DAYS was set to 900 days (30 month), when password was set > 30 month ago.
After changing `password_set_at` to 2011 year, user login was reject with error `The password expired for user`
