### ISSUE TITLE
Response JSON has 2 "error" in structure , PROD, #J1229

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4772]
See details in the related ticket

------------

#### [Ticket #269: **Response JSON has 2 "error" in structure , PROD, #J1229**](https://zube.io/edenlabllc/e-health/tickets/269)

У json відповіді системи з'явився вкладений блок error в блок error.

Лог: [55588_Full.txt](https://zube.io/files/edenlabllc/42402f7ca5db215f345dc95c97177d53-55588_full.txt)

**Comment by progsmile** [comment]
Passed success pass.

**Comment by lymychp** [comment]
@svetavedmed please run regress for sign declaration_request 
+ check error response in case of `has already been taken`
