### ISSUE TITLE
Error 500 "internal_error" /api/drugs/, PREPROD, #J1276

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4773]
#### [Ticket #314: **Error 500 "internal_error" /api/drugs/, PREPROD, #J1276**](https://zube.io/edenlabllc/e-health/tickets/314)

Під час виконання пошуку за кодом АТХ отримуємо помилку HTTP/1.1 500 Internal Server Error

Логи: [EHealth.C07AB02.log](https://zube.io/files/edenlabllc/7f6a4e054a81703798659035631db8e1-ehealth-c07ab02.log)
[EHealth.C07AG02.log](https://zube.io/files/edenlabllc/53eaa401d45c73a8a36a0d8baa543c8f-ehealth-c07ag02.log)

**Comment by svetavedmed** [comment]
done for preprod
