### ISSUE TITLE
Error 500 "internal_error" on api/reimbursement_report, PROD, #J1274

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4774]
#### [Ticket #291: **Error 500 "internal_error" on api/reimbursement_report, PROD, #J1274**](https://zube.io/edenlabllc/e-health/tickets/291)

При запиті на on api/reimbursement_report отримують помилку 500 "internal_error"
Лог: [reimbursement_report.json.txt](https://zube.io/files/edenlabllc/aa93b136421b1bf2eea45cedc751b0d6-reimbursement_report-json.txt)

**Comment by marinakr** [comment]
"%ArgumentError{message: \"Postgrex can only decode dates with days between 0 and 3652424, got: 73786498\"}, [{Postgrex.Extensions.Date, :day_to_elixir, 1, [file: 'lib/postgrex/extensions/date.ex', line: 42]}, {Core.PostgresTypes, Postgrex.Extensions.Date, 6, [file: '/app/deps/postgrex/lib/postgrex/type_module.ex', line: 713]}, {Postgrex.Protocol, :rows_recv, 4, [file: 'lib/postgrex/protocol.ex', line: 2733]}, {Postgrex.Protocol, :recv_execute, 5, [file: 'lib/postgrex/protocol.ex', line: 1777]}, {Postgrex.Protocol, :bind_execute, 4, [file: 'lib/postgrex/protocol.ex', line: 1652]}, {DBConnection.Holder, :holder_apply, 4, [file: 'lib/db_connection/holder.ex', line: 270]}, {DBConnection, :run_execute, 5, [file: 'lib/db_connection.ex', line: 1195]}, {DBConnection, :run, 6, [file: 'lib/db_connection.ex', line: 1282]}]",
