### ISSUE TITLE
Object "person" is null in response on Get Declarations List, PROD/PREPROD, #J1066, #J1174

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4775]
#### [Ticket #219: **Object "person" is null in response on Get Declarations List, PROD/PREPROD, #J1066, #J1174**](https://zube.io/edenlabllc/e-health/tickets/219)

Після релізу на ПРОД 8.12
Під час виконання запиту GetDeclarationList несистемно (на перший погляд) в структурі declaration не повертається об’єкт person

case1: серверний лог
case2: результат виконання запиту [GET /api/declarations?legal_entity_id=361edd25-e37e-4cda-acad-c3ba4a75263c&status=active&page=1&page_size=100]

Логи: [getDeclarationList-case1.log](https://zube.io/files/edenlabllc/45f826659fe1d551f3023addcb8ca875-getdeclarationlist-case1.log)
[getDeclarationList-case2.json.txt](https://zube.io/files/edenlabllc/079d904ec5f6febf369c41dcc8e1adda-getdeclarationlist-case2-json.txt)

**Comment by progsmile** [comment]
Is fixed by https://github.com/edenlabllc/mpi.api/pull/294

**Comment by lymychp** [comment]
@progsmile still reproducable on prod https://zube.io/edenlabllc/e-health/tickets/219
