### ISSUE TITLE
Ticket #321: **Error 422 "type mismatch. Expected string but got null" on medication_requests/id/actions/reject when .employee.party.second_name is null, PROD, #J1316, #J1325**

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4787]
#### [Ticket #321: **Error 422 "type mismatch. Expected string but got null" on medication_requests/id/actions/reject when .employee.party.second_name is null, PROD, #J1316, #J1325**](https://zube.io/edenlabllc/e-health/tickets/321)

Після деякого дослідження маємо наступну інформацію: існує лікар у якого немає По-батькові(second_name). Він зареєстрований без нього в ЦБД. При виконанні запиту рецепту – Get Medication Request by ID, він повертає "second_name": null для блоку employee. 
При спробі відміни отримуємо помилку(у вкладенні).

Лог: [GetMedicationRequestByID_no_secondname.json.txt](https://zube.io/files/edenlabllc/93a49a3376ad29ac210dfd7e8034db5b-getmedicationrequestbyid_no_secondname-json.txt) 
Скрін:
![image_2019_04_08T06_46_47_568Z.png](https://zube.io/files/edenlabllc/08cdf405c4a139b3bf3d7e802c29c6aa-image_2019_04_08t06_46_47_568z.png)

Є таке ж звернення від іншої МІС.
Логи: [medication_reject_medication_get_info.txt](https://zube.io/files/edenlabllc/131cfc8041fdf25248d491d93cc8d183-medication_reject_medication_get_info.txt)
[medication_reject_second_name_null_error.txt](https://zube.io/files/edenlabllc/4c00ac9f2ea8c458abafa9d0687df737-medication_reject_second_name_null_error.txt)

**Comment by svetavedmed** [comment]
done for prepared
