### ISSUE TITLE
Add search param managing organization on get episode by search params

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#4797]
Add search param managing organization on get episode by search params according to [specification](https://ehealthmedicaleventsapi.docs.apiary.io/#reference/medical-events/episode-of-care/get-episodes-by-search-params)

**Comment by IrinaRevutska** [comment]
Can you please rename it to "managing_organization_id"?

**Comment by BatrakM** [comment]
Done
