### ISSUE TITLE
INTERNAL_SERVER_ERROR when searching a person

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.api#4813]
"log": "Task #PID<0.14305.0> started from #PID<0.1727.0> terminating\n** (FunctionClauseError) no function clause matching in MPI.Rpc.search_persons/3\n    (mpi) lib/mpi/rpc/rpc.ex:152: MPI.Rpc.search_persons([{:is_active, :equal, true}, {:birth_date, :equal, ~D[1989-09-30]}, {:tax_id, :equal, \"3278011533\"}], [desc: :inserted_at], {0, 11})\n    (kube_rpc) lib/server/server.ex:31: anonymous fn/5 in KubeRPC.Server.handle_call/3\n    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\nFunction: #Function<1.69230676/0 in KubeRPC.Server.handle_call/3>\n    Args: []",
  "request_id": "806e0f81-ac97-470e-988f-6391e9abf642#15162",

**Comment by kiurchv** [comment]
Unable to reproduce the issue
