### ISSUE TITLE
increase max page_size for GET /api/declarations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4815]
max page_size = 300

**Comment by lymychp** [comment]
@marinakr  max page_size parameter should be configured in charts for all the envs

**Comment by marinakr** [comment]
MAX_PAGE_SIZE - config param

**Comment by marinakr** [comment]
https://github.com/edenlabllc/ehealth.charts/pull/325

**Comment by svetavedmed** [comment]
anyway have only 100 in page_size
