### ISSUE TITLE
JSON schema validation: full path to invalid parameter

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#483]
Request with failed validation should contain full path to invalid parameter.
The issue is complicated because of refactoring [validator](https://github.com/Nebo15/nex_json_schema/blob/master/lib/ex_json_schema/validator.ex) (all `validate_aspect`) for passing additional parameter to function call. Or do it in another way, that also requires refactoring.

**Comment by AlekzandrV** [comment]
#180
