### ISSUE TITLE
update NHS employee

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4841]
in case there is an `employee_id` in request employee should be updated

according to [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1316436/IL.Approve+Reject+employee+request)
```
4. Chech employee_id in request
   - if employee_id is exist in request, Update employee.
   - if  employee_id is not exist, Create employee.
```

**Comment by kiurchv** [comment]
Closing due to employee update via employee request creation is already supported by `createEmployeeRequest` mutation
