### ISSUE TITLE
sign declaration  idempotency

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4842]
[endpoint PATCH /api/declaration_requests](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/sign-declaration-request)
[spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1108579/IL.Sign+declaration+request)
Create declaration endpoint on OPS should be idempotent:
if there is existing record in the declarations table with the same id and declaration_request_id, return ok to IL.
Same with mpi

**Comment by svetavedmed** [comment]
on trying to sing declaration request second time I get an error
```
{
    "error": {
        "message": "person is not found",
        "type": "request_conflict"
    },
    "meta": {
        "code": 409,
        "request_id": "70c07c01-e2df-46af-9d3f-3fd93620e5f7#8558",
        "type": "object",
        "url": "http://api-svc.il/api/declaration_requests/1e70e255-2ea2-430b-a4dd-60bca762c042/actions/sign"
    }
}
```
