### ISSUE TITLE
sign MRR idempotency

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4843]
[endpoint PATCH api/medication_request_requests/id/actions/sign](https://uaehealthapi.docs.apiary.io/#reference/public.-reimbursement/medication-request-requests/sign-medication-request-request)
[spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3381025/Sign+Medication+Request+Request)
Create MR endpoint on OPS should be idempotent:
if there is existing record in the medication_requests table with the same id and medication_request_request_id, return ok to IL

**Comment by marinakr** [comment]
https://github.com/edenlabllc/ops.api/pull/230

**Comment by AlekzandrV** [comment]
Don't know how to test it

Get 409 on 2nd sign
```
{
    "error": {
        "message": "Invalid status Medication request Request for sign transition!",
        "type": "request_conflict"
    },
    "meta": {
        "code": 409,
        "request_id": "8ddcfb9e-e89c-4571-a186-b0319f61de59#11074",
        "type": "object",
        "url": "http://api-svc.il/api/medication_request_requests/137d9d9b-2a52-4c9f-8f93-b40be9947df5/actions/sign"
    }
}
```

@lymychp @marinakr any ideas?

**Comment by lymychp** [comment]
@AlekzandrV it is correct behavior. 
Change status of MRR to not signed. And try to sign it again

**Comment by AlekzandrV** [comment]
Tested
