### ISSUE TITLE
Terminate Contract Request on Legal Entity Update

### ISSUE THREAD

**Issue by mamaelka** [edenlabllc/ehealth.api#4878]
- [x] Find contract requests related to current legal entity in status = NEW, APPROVED, PENDING_NHS_SIGN, NHS_SIGNED, set status = 'TERMINATED', status_reason "Legal Entity Data has changed" if Legal Entity is updated in [Create/Update Legal Entity V1] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/1112394/IL.Create+Update+Legal+Entity)
- [x] Find contract requests related to current legal entity in status = NEW, APPROVED, PENDING_NHS_SIGN, NHS_SIGNED, set status = 'TERMINATED', status_reason "Legal Entity Data has changed" if Legal Entity is updated in [Create/Update Legal Entity V2] (https://edenlab.atlassian.net/wiki/spaces/EH/pages/758939732)

**Comment by lymychp** [comment]
async via kafka
