### ISSUE TITLE
Add an event in the Event Manager to collect records for "is_suspended" changes (Contract API)

### ISSUE THREAD

**Issue by AlexKovalevych** [edenlabllc/ehealth.api#4885]
I as a MIS User want to receive records from Event Mnager if the attribute is_suspended (contract data) has been changed:
- false -.> true OR
- true -> false

So that I will be able to collect contracts that have been changed the attribute "is_suspended".

**Comment by imax-iva** [comment]
Already done.
Commit: implement suspend contracts (#4414)
