### ISSUE TITLE
GET /api/persons optimisation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4902]
we do have a lot of selects on the `GET /api/persons` endpoint
```
   "path": "/api/persons?first_name=[REDACTED]",
    "code": "200",
    "request_id": "9233d254-9efb-40a3-9fed-709ae4a3b79b#1694280",
    "@timestamp": "2019-04-26T12:38:52.081064554+00:00",
    "tag": "gateway"
```

Let's try to write manual join instead of ecto

**Comment by marinakr** [comment]
select p.*, json_agg(d),json_agg(ph) from persons p join person_documents d on d.person_id = p.id join person_phones ph on ph.person_id = p.id group by p.id limit 1;

**Comment by lymychp** [comment]
duplicates edenlabllc/ehealth.api#4712
