### ISSUE TITLE
Search legal_entity and see details

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#500]
As NHS admin I want search legal_entity and see its details
Searching parameters:
- edrpou
- legal_entity_id (нет сейчас)
- settlement (нет сейчас)
If found more than one, display all as list
Legal entity list and details contain all parameters from user story #499 

- [ ] add search parameters in WS #514

**Comment by PavelVesnin** [comment]
@mmiliaieva, @alexeybondarenko  `legal_entity_id` - it's invalid field name for `/legal_entities`. It should be named as field in database - `id`
