### ISSUE TITLE
cache all counts on get /declarations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#5009]
endpoint GET [/api/declarations](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declarations/get-declarations-list)

records count should be cached for all the query params combination, not only `legal_entity_id + status`
TTL configurable - 10 minutes

**Comment by marinakr** [comment]
https://github.com/edenlabllc/ops.api/pull/239

**Comment by lymychp** [comment]
there are no records in cache

**Comment by lymychp** [comment]
tested on dev.
