### ISSUE TITLE
There are no attached documents in the application for the contract request

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.api#5018]
#### [Ticket #422: **There are no attached documents in the application for the contract, admin panel  NHSU.**](https://zube.io/edenlabllc/e-health/tickets/422)

В административной панели НСЗУ отсутствуют прикрепленные документы, которые подаются вместе с заявкой на договор со стороны ЗОЗ.
Необходимо обеспечить отображение и доступность документов для пользователей админ панели НСЗУ.
![image.png](https://zube.io/files/edenlabllc/9c7255200bfa40ab89a0522a2fccd5d4-image.png)

At this moment field `attachedDocuments` return empty array.

**Comment by PavelVesnin** [comment]
Bug founded, fix tested on preprod and ready to deploy.

**Comment by PavelVesnin** [comment]
@Zhanna-Khomenko fix deployed on prod

**Comment by PavelVesnin** [comment]
@Zhanna-Khomenko try again please. As we see, documents are found.
