### ISSUE TITLE
Error 501 "internal_error" on /api/declaration_requests/id/actions/sign, PROD, #J1537

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#5053]
#### [Ticket #426: **Error 501 "internal_error" on /api/declaration_requests/id/actions/sign, PROD, #J1537**](https://zube.io/edenlabllc/e-health/tickets/426)

There is a number of records in logs with the `app.log` = `*{:error, :badrpc}*` messages
Should be investigated

**Comment by progsmile** [comment]
Fixed on declaration_requests sign
Ready for deploy
