### ISSUE TITLE
Create RedLists DB

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#509]
- [ ] Add RedList table in Reporting DB erd-specs
- [ ] Create RedList table, that contain:
- id 
- edrpou
- legal_entity_name
- division_name
- area
- region
- settlement_type
- settlement
- street_type
- street
- buildings
- patients_number

**Comment by lymychp** [comment]
[доопрацьований Червоний реєстр (по областях).zip](https://github.com/Nebo15/ehealth.api/files/1122272/default.zip)

**Comment by lymychp** [comment]
[red lists objects added to erd](https://github.com/Nebo15/report.api/pull/15)
