### ISSUE TITLE
Add `Create` mutation  for Services

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#5110]
Add `Create` mutation for services.
[Features in PR] (https://github.com/edenlabllc/ehealth.api/pull/5129)
[Spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/740720641/Contract-Program-Service+ERD)
[GraphQL schema (edenlabllc/ehealth.api#4938)](https://zube.io/edenlabllc/e-health/c/6346)

**Comment by PavelVesnin** [comment]
I've changed storypoint to 3 because of additional work:
 - added creation Service in DB
 - added JSON validation Schema for request (category is a value from dictionary)
 - fixed BDD feature

**Comment by novohatnya** [comment]
- [ ] code must be unique
