### ISSUE TITLE
Licenses structure for LE

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#590]
As per recent changes in licensing of LE, there are no more such paper document as license
http://www.moz.gov.ua/ua/portal/pre_20170126_a.html

Basically Legal Entity could have only order number now, and no any license number exist

Could you please analyze and suggest a solution?
Should we make licence_no optional?

cc: @warehousman

**Comment by IrynaShevch** [comment]
Зараз паралельно існують дві версії документів, що засвідчують наявність ліцензії:
- паперова ліцензія (зелененький папірець, старий формат)
- витяг з реєстру (простий а4, новий формат).

У кожному з них є інформація про # наказу (# рішення), про дату наказу. 

У зелененькій окремо також написані; серія і номер ліцензії; дата "діє з", яка співпадає із датою наказу; дата видачі ліцензії.
У а4 є тільки #наказу та дата наказу, яка зокрема показує з якого числа ліцензія діє.

**Comment by lymychp** [comment]
duplicates #647
