### ISSUE TITLE
Pagination trouble

### ISSUE THREAD

**Issue by ivchenkodima** [edenlabllc/ehealth.api#611]
We have a couple of wrong cases:

1. If we are on the start of the list, we could have both flag [ending_before, starting_after].
So I could go back using ending_before. But on this request I get empty list with no any flag.
2.  If I go down to the end of the list, I need to have ending_before flag to go back, but I hadn't. [ending_before == null]

**Comment by AlexKovalevych** [comment]
1.  This behaviour can't be changed, response from AndrewDryga:
 `The first page should have ending_before so that you can fetch newer items when they arrive.`
