### ISSUE TITLE
Single person profile in PRM

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#619]
As a NHS Admin  
I want to have only one unique Person profile in PRM and only one Party for single User_id

- [x] Fix party_users relations
- [x] Prevent duplicated profiles on Create vie Employee request, Owner request etc

**Comment by lymychp** [comment]
it has no side effects at the moment. We might look at this ticket again when implement doctor's cabinet.

**Comment by AlekzandrV** [comment]
Рішення:
При спробі створення співробітника з існуючим користувачем (email) та іншими ідентифікаційними данними (пара ІПН + Дата народження) - повертати помилку з текстом
"Email is already used by another person"

Якщо первинні дані були внесені з помилкою - то для вирішення проблеми необхідно буде завести новий email та ввести коректні дані
