### ISSUE TITLE
Make IL.declaration_request.data great again

### ISSUE THREAD

**Issue by DPashchenko** [edenlabllc/ehealth.api#626]
It is necessary to remove excess and duplicated attributes from the  IL.declaration_request.data .
It should be similar to the [Get declaration request by ID](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/get-declaration-request-by-id) response

**Comment by gmile** [comment]
Per discussion with @MBatrak 

- [ ] we need to unfold employee.party, and filter which party fields we keep
- [ ] also, we need to pull party email separately.

**Comment by MBatrak** [comment]
To retrieve party email we need to do the following steps:
  1. go to PRM.party_users and get user_id's (there can be more than one) by party_id
  2. for each user_id go to Mithril and check if that user has "DOCTOR" role. If there are still more than one 
      user we should take the one that was created last and take his email

**Comment by gmile** [comment]
This was done in #664 and #747
