### ISSUE TITLE
Improve Uaddresses filtering and paging

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#642]
**Search regions API:**
- [ ] Improve filtering:
   - name - like search, optional
   - koatuu - like search, optional
- [ ] Fix paging

**Search districts API:**
- [ ] Improve filtering:
   - region - exact match, optional
   - name - like search, optional
   - koatuu - like search, optional
- [ ] Fix paging

**Search settlements API:**
- [ ] Improve filtering:
   - region - exact match, optional
   - district - exact match, optional 
   - name - like search, optional
   - type - exact match, optional
   - mountain_group - exact match, enum ("true", "false"), optional
   - koatuu - like search, optional
- [ ] Fix paging

**Comment by MBatrak** [comment]
[ ] update apiary @AlekzandrV

**Comment by AlekzandrV** [comment]
1. Make search by region, district, name - case-insensitive
2. Support routes with *search* param in URL

**Comment by MBatrak** [comment]
Done

**Comment by lymychp** [comment]
tested,
apiary specs updated
