### ISSUE TITLE
Add seed to declaration requests

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#663]
For now return simple static value.

**Comment by AlekzandrV** [comment]
@gmile Return constant value instead of random value. And it must be something more similar to hash

**Comment by gmile** [comment]
@AlekzandrV done in https://github.com/edenlabllc/ehealth.api/commit/5159c2a1e18ab20dc30297e612a4353b1c98f2cb

**Comment by gmile** [comment]
I'm closing this. The following work is being done in https://github.com/edenlabllc/ehealth.api/issues/669
