### ISSUE TITLE
Помилка навігації між сторінками

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#686]
Relates to `https://github.com/ehealth-ua/api-spec/issues/68`

## Steps to Reproduce (Repro steps)

- [x] endpoint address
http://demo.ehealth.world/api/divisions
- [x] sequence of actions that should be taken to reproduce the behavior.
1) Виконуємо запит
 `http://demo.ehealth.world/api/divisions?ending_before=c1f5c3de-a948-46db-a091-8c682b70ede5`
2) отримуємо відповідь 
`{
    "paging": {
        "size": null,
        "limit": 15,
        "has_more": true,
        "cursors": {
            "starting_after": null,
            "ending_before": "e75132e7-cf8a-429a-a8ee-ac7c74925fed"
        }
    },
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "list",
        "request_id": "r4ofskug0i0qavlf9j6un5hpm09fqljm",
        "code": 200
    },
    "data": [
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "e75132e7-cf8a-429a-a8ee-ac7c74925fed",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "cb135cb4-6165-4f6e-a57c-b416577688c5",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "cf3804ae-ce48-41c1-88ec-f03c9395a550",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Борис",
            "mountain_group": false,
            "location": null,
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "3da4b998-751b-42fd-9934-8e5dc178f616",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "c7d1c057-1231-4eb3-bc4b-762de7aa4491",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "378b668d-29e3-4d83-add7-ffcc3cc2fc7e",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "fe1d2411-48c1-4cb3-9f90-5515880b2796",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "b2582fbf-9211-4b62-b67d-ff2c5f658a70",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "e72bf9d1-47ed-4514-9bf1-4d8650369377",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "6ababcc8-92dc-44d1-af9c-00372955bf97",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "abf978a0-5fa4-4741-9c8f-a07c7925190f",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "b3d38f8d-bcfc-4510-b33e-a9b9043d259c",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "62aaaa9a-118c-497d-844a-22afefe596d0",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "139e4476-0fa2-4296-9313-9f901a397880",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "clinic",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "location": {
                "longitude": 50.4430679,
                "latitude": 30.5001845
            },
            "legal_entity_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
            "id": "bcee5715-ff34-487e-a838-3f34fb46cdb2",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        }
    ]
}`
У відповіді paging.has_more = true
2) Берем параметр paging.cursors.ending_before і виконуємо наступний запит
`http://demo.ehealth.world/api/divisions?ending_before=e75132e7-cf8a-429a-a8ee-ac7c74925fed`

## Actual result
- [x]  `{
    "paging": {
        "size": null,
        "limit": 15,
        "has_more": false,
        "cursors": {
            "starting_after": null,
            "ending_before": null
        }
    },
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "list",
        "request_id": "idu7eredle62pq14rlfuh7gqolmlmrgc",
        "code": 200
    },
    "data": []
}`  
Результат повторюється лише у випадку коли paging.limit дорівнює кількості повернених елементів в масиві data

## Expected result
- [x] У випадку коли paging.limit дорівнює кількості елементів в масиві data - paging.has_more має дорівнювати false

**Comment by lymychp** [comment]
to decide whether we can change the pagination implementation

**Comment by lymychp** [comment]
fixed with the new pagination
