### ISSUE TITLE
Declaration forms changes

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#692]
1) Необхідно змінити текст згоди пацієнта на наступний:

Своїм підписом я, ___________________________________________, підтверджую добровільний вибір лікаря з надання первинної медичної допомоги, достовірність наданих мною даних, а також надаю згоду на обробку та використання моїх персональних даних, зокрема щодо здоров’я, що містяться в електронній системі охорони здоров’я, яка працює у дослідній експлуатації, а також на здійснення дій пов’язаних зі збиранням, реєстрацією, накопиченням, зберіганням, адаптуванням, зміною, поновленням, використанням, поширенням, розповсюдженням, реалізацією, передачею, знеособленням, знищенням будь-яких відомостей про мене для цілей охорони здоров’я, у тому числі надання первинної медичної допомоги, такому лікарю з надання первинної медичної допомоги, іншим лікарям за його направленням або лікарю, до якого звернувся пацієнт, в межах, необхідних для надання медичної допомоги та/або медичних послуг, в рамках промислової експлуатації електронної системи охорони здоров’я. Я не вимагаю здійснення повідомлення про передачу (поширення) моїх персональних даних, що включені до електронної системи охорони здоров’я, третім особам, якщо така передача (поширення) відбувається в моїх інтересах з метою реалізації вказаних вище правовідносин. Розпорядникам персональних даних є медичні інформаційні системи, підключені до електронної системи охорони здоров’я.

2) У документах, що посвідчують особу:
паспорт — паспорт громадянина України
ID-картка — паспорт у формі ID-картки,
посвідка — посвідка на тимчасове проживання/посвідка на постійне проживання іноземця,
свідоцтво — свідоцтво про народження.

3) У документах, що додатково посвідчують факт представництва мають бути наступні документи: 
свідоцтво - свідоцтво про народження
посвідчення опікуна - посвідчення опікуна або піклувальника
документ - документ, що підтверджує повноваження представника органу опіки та піклування або керівника дитячого закладу, закладу охорони здоров’я або закладу соціального захисту дітей, у якому дитина перебуває на повному державному забезпеченні, та документ, що підтверджує факт зарахування дитини до цього закладу
рішення суду.

4) у варіанті видрукованому з системи порядок Ім'я-По-батькові-Прізвище замінили на Прізвище-Ім'я-По-батькові

Актуальна форма декларації:
https://drive.google.com/file/d/0B9rXAkrOg1wQVzVrVy0xbmRtRUU/view

**Comment by lymychp** [comment]
waiting for the final declaration template from @kmakarenko

**Comment by kmakarenko** [comment]
Форма декларації, актуальну для запуску у вересні. 
Номерки у варіанті, що видруковується з системи, не обов‘язкові. Такий варіант на сторінці 4 документу: https://drive.google.com/open?id=0B9rXAkrOg1wQajVQcjdXSU9rODQ

**Comment by lymychp** [comment]
@alexeybondarenko please start work on the ticket.

**Comment by alexeybondarenko** [comment]
@lymychp, let's plan this ticket for the next week. We need to finish the admin and portal this week.
