### ISSUE TITLE
Store employee_id after employee_request approval

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#693]
As a admin
I want the employee_id to be stored in the `il.employee_request` table after employee_request approval
So that I can easier investigate issues

**Comment by lymychp** [comment]
suggest to store it in jsonb, not new column.
Currently there is no fulfilled column on dev env.

**Comment by AlexKovalevych** [comment]
there is `employee_id` in data column and as i understood, its used to update existing employee on employee_request approval, so that is different field
