### ISSUE TITLE
Password management UI

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#694]
As a eHealth user
I want be able to change or reset my password
So that i can login to eHealth system

Design and implement pages:
- [x] 1. Login form to Approve employee request - add button "Forgot password?"
[page](http://auth.dev.ehealth.world/invite?invite=f70543e7-4740-43b8-8a66-05dc1aadce42)

- [x] 2. Auth 2.0 Flow Login form - add button "Forgot password?"
[page](http://auth.dev.ehealth.world/sign-in?client_id=d9f2134a-ef07-47f1-abc4-47c772e3e3c4&redirect_uri=http%3A%2F%2Fexample.com&scope=employee%3Aread%2Cemployee%3Awrite%2Cemployee_request%3Aread%2Cemployee_request%3Awrite)

- [x] 3. "Forgot password?" page
             Form elements:
             * Email
             * Submit button

- [x] 3.1 "Forgot password?" result page:
             Show delivery status
             * Show resend email button
             * Show "Home" (?back) button

- [x] 4. Reset password page
             User goes to this page via reset password link from email
             * Show input "New password"
             * Show input "Confirm password"

- [x] 4.1 Reset password result page
             Show action result:
             * Success scenario
             * Error scenario

Services to integrate with:
1. Send Reset link
```
curl -X POST -H Content-Type:application/json http://dev.ehealth.world/api/credentials_recovery_requests -d'{"credentials_recovery_request":{"email": "sp.virny+100@gmail.com"}}'
```

2. Reset password:
```
curl -X PATCH -H Content-Type:application/json http://dev.ehealth.world/api/credentials_recovery_requests/ba951607-4df7-4b59-9a91-d40f43dcc072/actions/reset_password -d'{"user":{"password":"234567"}}'
```
Password management API #278 
Email template #650

**Comment by AlekzandrV** [comment]
Fix Error Hint for nonexistent email
Remove `or password`
![Screen Shot 2017-07-28 at 14.33.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e6058a02bec2001a6ea34d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379eb0c2852415e4ebe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec859f44fe04a57a3163565f43b.png)

**Comment by alexeybondarenko** [comment]
А зачем это править?

**Comment by alexeybondarenko** [comment]
Лучше не выдавать такую ошибку на апи. Чтобы нельзя было определить. Есть такй ящик у нас в системе или нет

**Comment by AlekzandrV** [comment]
какой best-practice по этому вопросу у других сервисов?

**Comment by AlekzandrV** [comment]
@alexeybondarenko @ivchenkodima Нужно еще хендлить вот такой случай, когда приглашение на смену пароля заэкспайрилось
Сейчас мы ничего не показываем и остаемся на той же странице
```
{
   "meta":{
      "url":"http://dev.ehealth.world/api/credentials_recovery_requests/eaebd5e6-6512-444f-b769-02e74b45f4f1/actions/reset_password",
      "type":"object",
      "request_id":"k9d47ef55bpkullspg4485b1a9357b08",
      "code":422
   },
   "error":{
      "type":"validation_failed",
      "message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
      "invalid":[
         {
            "rules":[
               {
                  "rule":"expiration",
                  "params":[

                  ],
                  "description":"is expired"
               }
            ],
            "entry_type":"json_data_property",
            "entry":"$.expires_at"
         }
      ]
   }
}
```

**Comment by AlekzandrV** [comment]
Предлагаю вести на страницу подобную этой, только с другой формулировкой
<img width="634" alt="screen shot 2017-07-28 at 16 41 58" src="https://user-images.githubusercontent.com/12275915/28719783-cd6e6d46-73b3-11e7-989e-83be4d3eff94.png">

**Comment by lymychp** [comment]
@ivchenkodima @AlekzandrV  please close this ticket

**Comment by ivchenkodima** [comment]
@AlekzandrV  Please specify what text need to be changed. And we will close this issue.
