### ISSUE TITLE
Update employee qualifications - add new fields

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#697]
У поле інформацію про сертификат спеціаліста подати поле “дійсний до”

Необхідно додати у поля “qualifications” лікаря наступні поля:

дійсний до
додаткова інформація

**Comment by lymychp** [comment]
optional/mandatory?
specialities."valid_to_date": "2017-08-05" - дійсний до?

**Comment by kmakarenko** [comment]
both optional
