### ISSUE TITLE
MSP Secret Key management Design

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#70]
- [ ] Get secret key
- [ ] Restore secret key
- [x] Renew secret key

**Comment by lymychp** [comment]
via MIS

**Comment by pzhuk** [comment]
endpoint has to be provided, separate scope has to be provided as well

BR, Pavel V. Zhuk


2017-10-04 10:46 GMT+03:00 lymychp <notifications@github.com>:

**Comment by AlekzandrV** [comment]
1. Get secret key, 2. Restore secret key - use Create or Update Legal entity API in order to get existing secret key (or generate new in case new LE)
3. Renew secret key [API](http://docs.uaehealthapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/roles/refresh-client-secret)
