### ISSUE TITLE
[Admin] Reset MPI authorization method via admin console

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#72]
As a NHS admin, MIS user  or a Doctor.
I want reset MPI  authorization method to N/A.
So that implement particular WS "Reset authentication_method"  & implementation NHS portal page for this action.

----------------
- [x] Add logging table for MPI (task #1225)
- [x] Specify WS API ([spec](https://edenlab.atlassian.net/wiki/x/2IAFAw))
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios [Tests](https://edenlab.atlassian.net/wiki/x/_YFfBQ)
- [x] Design & implement button "Reset ..." on page "Declaration detail" (task #1236)

**Comment by lymychp** [comment]
new role on the NHS admin

**Comment by EdwardVoloshin** [comment]
@PavelVesnin please add validation mpi.persons.status=ACTIVE, if invalid - return 409 error "Invalid status MPI for this action"

**Comment by PavelVesnin** [comment]
@EdwardVoloshin done

**Comment by EdwardVoloshin** [comment]
API tests passed

**Comment by EdwardVoloshin** [comment]
API & FE implementation done.
