### ISSUE TITLE
NHS Admin role mode

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#722]
1) Support - Search/read MSP, declarations, employees
2) Verifier - SUPPORT + Verify LE
3) Admin - Config and Dict
4) Manager - Dashboard, Reports

**Comment by alexeybondarenko** [comment]
@warehousman am I right understand that `manager` can only see the dashboard and the reports and no search by the declarations, msps and the employees?

**Comment by alexeybondarenko** [comment]
These endpoints are not secured by the scopes. They are public. So currently everyone can log in to the admin and see this information.

**Comment by alexeybondarenko** [comment]
I've added the user for each role:
- ab+support@nebo15.com
- ab+verifier@nebo15.com
- ab+admin@nebo15.com
- ab+manager@nebo15.com

All users have password: `12345678`

For each role, I've created a role in dev.mithrill.

- `NHS ADMIN MANAGER`
- `NHS ADMIN SUPPORT`
- `NHS ADMIN ADMIN`
- `NHS ADMIN VERIFIER`

You can easily specify scopes for each role in mithril admin.

**Comment by alexeybondarenko** [comment]
Note: dictionaries, reports, and stats are public methods. So they are shown for everyone.

**Comment by alexeybondarenko** [comment]
@warehousman, @lymychp are you want to test or change something now? Or we will adjust scopes later?

**Comment by lymychp** [comment]
I have changed the list of scopes for manager - `legal_entity:read`.
only one point - `clinics-verification` view is available even if user doesn't have scopes:
`legal_entity:nhs_verify legal_entity:deactivate` 
Buttons are disabled, so it's not an issue.
