### ISSUE TITLE
Add endpoint to return available user roles

### ISSUE THREAD

**Issue by alexeybondarenko** [edenlabllc/ehealth.api#726]
As an nhs.auth.web I want to receive available roles for specific client_id and user_Id to login user with a specific role.

In UI I want to show role name. And I need the scopes related to the role to send them in token creation.

**Comment by lymychp** [comment]
updated spec [Get User Roles](http://docs.mithrilapi.apiary.io/#reference/0/user-roles/get-user-roles)
