### ISSUE TITLE
Integration with PRM database

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.api#735]
Migrate all PRM requests from HTTP to SQL calls using `PRMRepo`.
Some endpoints has only proxy functionality, without paging or error handling logic. In this case you should replace it from PRM.

Migration plan:
1. Rewrite HTTP calls on SQL calls with same logic (by id, lists etc.)
2. Simple refactoring for new response structures in all places, where `PRM.API` module is used
3. Replace `mock_server.ex` to `ex_machina`
4. Optimize DB calls where it needs

Step by step:
1. Choose one HTTP call in `PRM.API` module and rewrite it to SQL call (create new or update module in `prm` directory).
2. Rewrite proxy functionality if [needs](https://github.com/edenlabllc/ehealth.api/blob/master/lib/ehealth/web/controllers/division_controller.ex#L15).
3. Remove endpoint from `test/support/mock_server.ex`
4. Add `ex_machina` fixture and update tests
5. Drop outdated function from `PRM.API` module

PRM modules:
- [x] legal entity
- [x] divisions
- [x] party 
- [x] party users
- [x] employee
- [x] registry

**Comment by PavelVesnin** [comment]
@gmile @Troush @AlexKovalevych welcome to discussion

**Comment by gmile** [comment]
Agree with thing said above. Only want to add one thing: let's not make huge refactoring PRs. Let's do this in baby steps, one piece at a time.

**Comment by lymychp** [comment]
and all the refactoring should happen only after release to prod.

**Comment by gmile** [comment]
@PavelVesnin added schema in https://github.com/edenlabllc/ehealth.api/pull/765. It's now possible to use any table from PRM. You only need to add a schema file for respective table, if it doesn't exist yet

**Comment by gmile** [comment]
Refactored declaration request creation to use PRM DB: https://github.com/edenlabllc/ehealth.api/pull/769

That PR introduced `legal_entity` and `medical_service_provider` schemas, now available to be used across IL.

**Comment by PavelVesnin** [comment]
Refactored UkrMedRegistries: [#775](https://github.com/edenlabllc/ehealth.api/pull/775)

**Comment by gmile** [comment]
Added ex_machina with support for multiple repos https://github.com/edenlabllc/ehealth.api/pull/774

**Comment by gmile** [comment]
Next: going to take divisions https://github.com/edenlabllc/prm.api/blob/master/lib/prm/divisions/division.ex.

**Comment by PavelVesnin** [comment]
Next: going to take a [party_users](https://github.com/edenlabllc/ehealth.api/blob/master/lib/ehealth/api/prm.ex#L111-L131)

**Comment by gmile** [comment]
Next: employees + doctors

**Comment by lymychp** [comment]
@PavelVesnin @AlexKovalevych I suppose we can close it, right?

**Comment by PavelVesnin** [comment]
yep
