### ISSUE TITLE
Create new entity (employee_type_legal_entity_type_links) in ERD

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#756]
- [x] Create **Mapping** in IL for relationse between employee_type & legal_entity_type

 - [x] Fill data into this entity: [values](https://docs.google.com/spreadsheets/d/12uHMP7yyYQ_m9o9nuhUMLRnCfl2xl3CxDVs9YyWp1tw/edit?usp=sharing)
!!! importantly:- before fill data - need complete #742 (new value at dictionary "EMPLOYEE_TYPE")

**Comment by lymychp** [comment]
it has been decided to implement on the configuration level, not DB

**Comment by EdwardVoloshin** [comment]
Done with @AlexKovalevych
