### ISSUE TITLE
Discuss & solution to change entity "employee_doctor" an "employee_add_info"

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#776]
There is a entity "employee_doctor":
```
[employee_doctors]
id | uuid | not null
education | jsonb[] | not null
qualifications | jsonb[]
specialities | jsonb[] | not null
science_degree | jsonb
employee_id | uuid | not null
inserted_at | timestamp | not null
updated_at | timestamp | not null
```
proposal change name entity & structure:
```
[employee_doctors]
id | uuid | not null
employee_id | uuid | not null
additional_info | jsonb | not null
inserted_at | timestamp | not null
updated_at | timestamp | not null
```
where additional_info сontains data structure:
- class employee (doctor, pharmacist, ...)
    - type info (education, qualifications, ....)
        - [array info]

**Comment by AlekzandrV** [comment]
Pull request https://github.com/edenlabllc/ehealth.api/pull/789

**Comment by AlexKovalevych** [comment]
@AlekzandrV @EdwardVoloshin what is the default value for `additional_info` column, since its not null and not all of the employees have employee_doctor, then we should write something to `additional_info`, i guess an empty string?

**Comment by lymychp** [comment]
aditional_info has been already implemented and tested
