### ISSUE TITLE
Update Deactivate Employee WS

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#778]
Update Deactivate Employee WS according to requirements

Requirements: [Реімбурсація - вимоги](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1054349/IL.Deactivate+Employee#IL.DeactivateEmployee-Deactivateemployee.1)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios
- [x] Development:

Add new cases into conditions for employee_type: PHARMACY_OWNER

**Comment by EdwardVoloshin** [comment]
Please review spec

**Comment by svetavedmed** [comment]
Pharmacy_owner can deactivate employees in other pharmacies. Should deactivate only employees in the same Pharmacy where pharmacy_owner is registered.
