### ISSUE TITLE
Digital signature - decode signed content without full verification

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#790]
As a eHealth System
I want to decode signed content without full validation (no Certification Authority, Revokation)
So that I can faster and easier obtain signed content

- [ ] Add new EndPoint - /degital_signatures/actions/decode
- [ ] Skip Authority validation, skip revocation list validation etc

**Comment by MBatrak** [comment]
Done. Add **"check": false** to request json if you want to skip all checks and just decode the data. Add **"check": true** or add nothing at all to go through all checks as it was initially meant to be
