### ISSUE TITLE
Declaration request - incorrect term of new declaration

### ISSUE THREAD

**Issue by TarasenkoA** [edenlabllc/ehealth.api#793]
I try to test declaration term and have next result:
"data": {
"status": "active",
"start_date": "2017-08-07",
"signed_at": "2017-08-07T12:30:31.503265Z",
"scope": "family_doctor",
"person_id": "af919404-5f4e-4a61-b147-7eae04265fd2",
"legal_entity_id": "9c81824b-bc13-4d07-bc76-b069e2a2876b",
"is_active": true,
"inserted_at": "2017-08-07T12:30:31.518649Z",
"id": "017a05e9-fb86-4aba-8771-46fe2f5c342d",
"end_date": "2017-08-08",
"employee_id": "c1269987-c4ee-4b07-ba5e-3dcfde3cbc77",
"division_id": "a7007627-cb29-4159-b813-68cd51bb3d98",
"declaration_request_id": "5e6e4664-c1a4-4597-b3de-c7d7cbe2284f"
}

Description of declaration test in task 88:
if (age < 18) {
  end_date = min(birth_date + 18y - 1d, start_date + declaration_term);
} else {
  end_date = start_date + declaration_term;
}

https://github.com/edenlabllc/ehealth.api/issues/88

So, in current case declaration end date must be - "1999-12-18"

**Comment by gmile** [comment]
@TarasenkoA **`1999-12-18`**? It's earlier than the birthday. I think you mean the `end_date` must be **`2017-12-18`**.

So yeah, somehow the currently calculated date `end_date`, **`2017-08-08 `**, is no entirely correct. I'm fix this.

**Comment by gmile** [comment]
```
select age(date '2017-08-07', date '1999-12-19'), date '1999-12-19' + interval '18 years' - interval '1 day' as "Option A", date '2017-08-07' + interval '1 year' as "Option B", date '2017-08-07' + interval '1 year' as "Option C";
           age           |      Option A       |      Option B       |      Option C
-------------------------+---------------------+---------------------+---------------------
 17 years 7 mons 19 days | 2017-12-18 00:00:00 | 2018-08-07 00:00:00 | 2018-08-07 00:00:00

```

**Comment by gmile** [comment]
@TarasenkoA so it looks like current date calculation if perfectly fine.

**Comment by gmile** [comment]
@TarasenkoA done in https://github.com/edenlabllc/ehealth.api/commit/5a130ed220f925e713d2b6dd28c9904bac1c5d5e

Basically the declaration request creation code now relies on two variables:

* declaration_term
* declaration_term_uni
