### ISSUE TITLE
Add checkbox about personal data to Legal Entity creation

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#795]
При створенні медичного закладу, МІС має надсилати “галочку” про те, що користувач надав згоду на обробку персональних даних,

**Comment by lymychp** [comment]
@kmakarenko we agreed to reject this ticket, right?

**Comment by kmakarenko** [comment]
I am still waiting for approval from legal point of view.
The task is currently postponed. I will let you know about the final decision next week.

**Comment by lymychp** [comment]
rejected by @kmakarenko
