### ISSUE TITLE
NHS admin - bugs in functionality

### ISSUE THREAD

**Issue by TarasenkoA** [edenlabllc/ehealth.api#828]
1. The "back" button does not work in section with info list
2. Section declaration - click on detail info - field “Область дії” = “family_doctor” - need to show with mapping with "SPECIALITY_TYPE" dictionary.
3. Employee section - speciality = "AWARDING" 
need to link with "SPEC_QUALIFICATION_TYPE" dictionary 
4. if NHS admin doesn't have scope to change dictionary - need to disable check-box inactive and opportunity to change info in dictionary.
5. Section Declaration under consideration - in this section need to show declaration only in status "NEW".

**Comment by ivchenkodima** [comment]
- [] 1
- [] 2
- [] 3
- [] 4
- [] 5
