### ISSUE TITLE
Deactivate Legal Entity

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#851]
As a NHS Admin
I want to deactivate Legal Entity 
So that i can manage legal entities according to legal information

- [x] Add activity to NHS Admin to deactivate Legal Entity
- [x] Integrate NHS Admin with [Deactivate API](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/deactivate-legal-entity-tbd)
- [x] Do not show "Deactivate" button for deactivated LE

**Comment by ivchenkodima** [comment]
done
