### ISSUE TITLE
Create new dictionary for reimbursement

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#855]
- [x] Create all dictionaries from list on page "reimbursement" from [file](https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit?usp=sharing)
- [x] Load values for all new dictionaries except for "medication_route_type". I will prepare values later.

PR #1354

**Comment by lymychp** [comment]
@EdwardVoloshin please add link to values

**Comment by AlekzandrV** [comment]
#1039

**Comment by EdwardVoloshin** [comment]
Create PR #1354 for dictionaries (without `SCOPES`)

**Comment by EdwardVoloshin** [comment]
PR #1354
