### ISSUE TITLE
Create mechanism generate human readable receipt Num

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#859]
Create logic/mechanism for generate `human readable receipt number` and `verification code`.

**Comment by lymychp** [comment]
[Human readable Medication request number](https://edenlab.atlassian.net/wiki/spaces/EH/pages/19923007/Human+readable+Medication+request+number)
FYI @warehousman @EdwardVoloshin @Troush @AlekzandrV
