### ISSUE TITLE
Mithril testing

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#860]
- [x] Підтвердження
  - [x] редагувати підтвердження:
    - [x] scopes should be editable
    - [x] ID shouldn't be editable
  - [x] створити нове підтвредження: change button name to `зберегти підтвердження`
  <img width="779" alt="screen shot 2017-08-15 at 1 53 05 pm" src="https://user-images.githubusercontent.com/5257001/29313152-1f452d9c-81c1-11e7-950e-90e416a8c006.png">

**Comment by ivchenkodima** [comment]
done
