### ISSUE TITLE
Password recovery bugs and improvements

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#872]
- [x] Validate password length on Reset password page
<img width="1440" alt="screen shot 2017-08-17 at 09 59 58" src="https://user-images.githubusercontent.com/12275915/29399926-d4f37d4c-8333-11e7-979e-3374bda933a5.png">

- [x] Remove button "Повернутися до входу" from all Password recovery pages

**Comment by ivchenkodima** [comment]
done

**Comment by lymychp** [comment]
tested
