### ISSUE TITLE
Incorrect printout form

### ISSUE THREAD

**Issue by TarasenkoA** [edenlabllc/ehealth.api#880]
When I try to print declaration request - I have incorrect printout form.
In db on man not full code.

**Comment by TarasenkoA** [comment]
Correct form:
[ehealth.templates-master.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595cbbd83dad79001a5f977e/125516c66e82c728ace21e0d46ed9c9f228e97a1c1fdba4eb451f1802c556a7e2817b72e62c7af6aaf50740b0a0c0abe4b4a5a4dfda8dd2af3be3f768f085dead16c5c27923c40fabbd30da313f871d51bdaebe5c01982fa3737e6898f4d3b14041d89fc5d31a09942cb5ff548f300.zip)

**Comment by PavelVesnin** [comment]
My steps to reproduce bug with invalid template content:
- Put valid template via Man UI
- Check template in db
Declaration Request printout form generated as normal.
I can't find, where is a trouble with additional prefix "293.15K (204.80K loaded)" and can't reproduce it.

**Comment by AlekzandrV** [comment]
Fixed
