### ISSUE TITLE
Static IP for lifecell

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#881]
As a lifecell service provider
I want all the requests from the service `OTP_verification` to be sent from the static IP addresses
So that Lifecell provider can add this IP to his whitelist.

[reference](https://github.com/edenlabllc/ehealth.k8s/issues/19)

**Comment by vsirius** [comment]
3 options:
1. Sent to  lifecell service provider list of all static IP  adresses from all nodes in kubernetes cluster. 
2. Add configuration in kubernetes sirvice config file   to deploy service pod  to specific  nodepool: 
example :     
  ` nodeSelector:
        cloud.google.com/gke-nodepool: persistent-workloads`
3. Add configuration in kubernetes config file   to deploy service pod  to already existing  node in claster.
example:
`kubectl label nodes <node-name> <label-key>=<label-value> `
   ` nodeSelector:
         <label-key>=<label-value>"
