### ISSUE TITLE
Cannot read property getHostNode of null

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#897]
Got "Cannot read property getHostNode of null" error in NHS Admin console during navigate through NHS Admin sections
<img width="1440" alt="screen shot 2017-08-21 at 18 21 59" src="https://user-images.githubusercontent.com/12275915/29526457-76449b82-869e-11e7-9c6a-39587bb16594.png">

**Comment by ivchenkodima** [comment]
Can't reproduce this case.
