### ISSUE TITLE
Document type nil in Declaration printout

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#914]
Show valid document type in Declaration printout instead of nil

<img width="1073" alt="screenshot at aug 23 16-47-41" src="https://user-images.githubusercontent.com/12275915/29619206-271ba2ea-8823-11e7-9ebd-a20346563516.png">

**Comment by alexeybondarenko** [comment]
Если там нет данных - то это вопрос к сервису, который использует шаблон. @AlekzandrV
