### ISSUE TITLE
Change "Find Verifications by Phone Number" Response

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#937]
Change "Find Verifications by Phone Number" Response in OTP Verification according to [spec](http://docs.uaehealthapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/otp-verification/find-verifications-by-phone-number)

## Response
```
{
  "meta": {
    "url": "http://example.com/resource",
    "type": "object",
    "code": 200,
    "request_id": "req-adasdoijasdojsda"
  },
  "data": {
    "id": "7d23bebb-1cf3-4221-bf21-18aada444756",
    "status": "NEW",
    "code_expired_at": "2017-07-10T12:20:16.300597Z",
    "active": true
  }
}
```

**Comment by Troush** [comment]
I think here we need to change spec according to current response, but not vice versa

**Comment by svetavedmed** [comment]
Have changed spec according to current response
