### ISSUE TITLE
EP: Create Substance

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#980]
Create Substance entity WS
 
- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/7569568/Create+Substance)
- [x] Implement
- [x] Deploy
- [ ] Improve test scenarios

**Comment by danakonovalenko** [comment]
While creating substance with same SCTID which is already exists it was received 500 error.

# Steps to reproduce

## Request
```
  {
    "sctid": "52574003",
    "name": "Аміодарон-",
    "name_original": "Amiodarone-"
  }
```

## Response
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/substances",
        "type": "object",
        "request_id": "1tjeauuqjmls54iv3oj9oqnsn92m914t",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by PavelVesnin** [comment]
@danakonovalenko fixed
