### ISSUE TITLE
NHS portal inner pages frontend fixes

### ISSUE THREAD

**Issue by SmartBBC** [edenlabllc/ehealth.api#984]

**Comment by SmartBBC** [comment]
Map page:
- Add "No results"  to side menu if there is no search-results
- Show details when user selects object on side menu
- Show five objects on side menu, rest is should be hidden under "show more" button

How to page:
- Wrong spacing between Done and "Join" button
Now: 20px
Should be: 50px

**Comment by ivchenkodima** [comment]
<img width="1102" alt="screen shot 2017-09-15 at 8 51 38 pm" src="https://user-images.githubusercontent.com/8415813/30496758-1836d6b2-9a59-11e7-921c-2753088d8269.png">
