### ISSUE TITLE
proper SSL Cloudflare configuration

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#985]
* All our PROD services has to have SSL certificates deployed, including API and FE services
* Load-balancers port 80 should be CLOSED for access from Internet
* Load-balancers port 443 should be OPEN only for WHITELISTED IPs of Cloudflare https://www.cloudflare.com/ips/

**Comment by pzhuk** [comment]
cc: @warehousman @lymychp

**Comment by lymychp** [comment]
@pzhuk done on prod
