### ISSUE TITLE
OTP SMS delivery metrics

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#986]
We should have a metrics for SMS delivery process

* Succesful/unsuccessful SMS submissions stats
* Undelivered SMS
* SMS delivery latency

cc: @warehousman @lymychp

**Comment by lymychp** [comment]
- [ ] integration with life report to store counters
- [ ] new metrics on datadog

**Comment by warehousman** [comment]
@kmakarenko Оценка: https://docs.google.com/spreadsheets/d/1X1gQEWQc02loG1OtNRZzzuN3NssLRoESIgpn-aRDMPQ/edit?usp=sharing
