### ISSUE TITLE
Update declaration - remove Approval phrase

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#987]
The following phrase should be removed from printed declaration form:

"ЗАТВЕРДЖЕНО

Наказ Міністерства охорони здоров’я України
від ______________________ No_____________________"

**Comment by AlekzandrV** [comment]
Таке цільове рішення?
<img width="1052" alt="screenshot at sep 14 11-33-44" src="https://user-images.githubusercontent.com/12275915/30419912-b219e522-9940-11e7-992c-051d0488a5a6.png">

**Comment by kmakarenko** [comment]
так
