### ISSUE TITLE
Portal testing histogram error

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#990]
While testing portal it was found that there is no data for histogram  Статистика "Динаміка реєстрацій декларацій" and instead we receive and error 422 Unprocessable Entity
(please see the attached file below)

## Response

<img width="1438" alt="screen shot 2017-09-06 at 10 17 30 am" src="https://user-images.githubusercontent.com/31403196/30099798-7646de44-92ef-11e7-91db-90a2b3d674ec.png">

**Comment by lymychp** [comment]
fixed
