### ISSUE TITLE
Fix reports/stats/regions API

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#991]
Fix query for `doctors_by_regions`
https://github.com/edenlabllc/report.api/blob/2af0cd2172ecf5fd3b212dcf0d46aadf79339e8d/lib/report/stats/main_stats.ex#L186-L195

**Query requirement:**
Get all employees with employee_type == 'DOCTOR' and status == 'APPROVED' and is_active == TRUE
Calc employees count 
Group result by area from division (employee.division_id == division.id and division.address.type == 'REGISTRATION')

**Comment by PavelVesnin** [comment]
https://github.com/edenlabllc/report.api/pull/33

**Comment by danakonovalenko** [comment]
1) Still the query for doctors_by_regions, declarations_by_regions and msps_by_regions must be fixed as filter for type == 'REGISTRATION' doesn't work. If the array has 2 types (Residence and Registration this division will be calculated 2 times)
2) the name of area in Response doesn't match the name of the area on the bar diagram

**Comment by PavelVesnin** [comment]
@danakonovalenko, @AlekzandrV 
1. Fixed, deployed 
2. API response is correct. Let's check front-end for this issue.
