### ISSUE TITLE
Update countries dictionary

### ISSUE THREAD

**Issue by kmakarenko** [edenlabllc/ehealth.api#993]
The dictionary should correspond to the following dictionary:
http://www.ukrstat.gov.ua/klasf/st_kls/op_ks_2016.htm

**Comment by lymychp** [comment]
uploaded from [source](http://www.profiwins.com.ua/uk/letters-and-orders/gks/4405-426.html) received from @IrynaShevch.
Applied to dev/demo/preprod.
